// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package elasticsearch

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "elasticsearch", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzsWlGP4jYQfudXjPZ98wN46EvVa6/SXU+6vUpVVXEmHsCL7cnZDgf99ZWdhA2JQwJkF04lbwT4vm/GM2PPJI+wxt0UUDLrRGqRmXQ1AXDCSZzCwy/1+w8TAI42NSJzgvQUfpoAABz8BhTxXOIEwKBEZnEKc3RsAmDROaGXdgp/P1grH/7x91Zk3CwlvRDLKSyYtP6fC4GS22kAfwTNFLYF+svtMpzC0lCelXci6g7h6pCpzK1Dk/hP+y8r1DXuvpPhtftR7OI69ECJG1iSSSet4K9BKvgRSuuYw5GJA2agbbIKzXHboqovVw9RE6C5kHWyxiIeM62H1V/vPXO5gDE2R47JKF3TvC7ddTROqU1SyrVr/aSClaSXkS97zPDXk5cKOldzNEALT5Yr1M6C0OBWWHg5OS6Oo0SHTSe+iryC6WSZ1pHBxIp/MZnvHNpTpS7IKOam0PXnwaZ4Cd6QvWZvQEA9Ih6XwdY3C4JC2J62X5hCRWZ3Zde+6C/kQG6Rw3wXfF1Jjbg7XpkSmyvFzO6tKlRmhGJGtFxwrxujyLvXjXvd6NV/Wt2A+45/z9x75v6AmVtZo2TyTPNLdnglB27vopkrF7QfX7T4liMoCc80P+it4CABmBux5/md5gVknI0zx2YhWm2SGUrRWuQzgykZPotFcWeE9Oj4VIEHSsBNO2BjmoTeMCn4jDOHo+p5WmEtDguDLXwXbgUo3AoNMFDCWqGXXhAWUQLk74fPbsUcpJRLDpoczBEyZizyyAG1FcCaeHs2cUL4Nv7fnMlU19t11h+J45HGeoPGCtIj85WoccrnjRq8r/el0J8f4L1eULO89h0H4lb3WT5AUCUq6oC6grLar5BlidDCXa3u/4YsA6/goNR7G/o31boRim2va4Ni2/NN0KSvvxQfST+OsByVLddckb0pw1flpW0P21GiJKVrJuM9wJxIImsmcN+QcVGBg8dG7pWUTotuBGF+ay/dDmZNlHM2BaG5SE8YZQyp0iUmNPV1aYFrNVS4FdaF7b5qWW63mbqhFuRHaz6qvq5nQgAj9qRn9ZyBtKeKPW+Ud2qSEcnRstYXz7Iv87hnJS7J7rSISRropT8kb0trr1u3vrrGYzsX9C0pDAjJplEdPwH4wLZdIVgXnCFb34jiT8jWQyXPbsfRQbYa5m1/nrgR2V+Ko83RGrWjPCrk4pz7ywPfs+4WFN+z7tayzuZmIzZkXiPxPpfY99y7BcX33Lt27nWegJdpkpKUmDoyo52Cf/0Z9qDxrBtwBq50HZsCXngcfmGAZXpuYejqFWHIog8Qui9AZ0dWD8nBKeiVvV4ciP7ffo/m4sJGXr6BS5LwnZAIdmcdKohD9yVheMB/lYnD3isGr/MouxLANkxINpdvq6L5kmqGmgu9nDlm15Mm9Qmzzq8xwK+QknZMaAsMyi/Af1FHqifp8SGoReNmZDg2z3XnPmx8HyChDVl7i4yMcPHEOedhawRuf2al3KQjPvv7HPASeEcGcMtUJr1BuXtULMtEQ/o+L4XCmdCzbznmmLTq09lPdYUKM7MA24pFu2Km/Zb0CcEXAMrgGRhNxfuB8YU96/nCk8kRxALcSlgQNswKS5JCX3xUWAxsx3LzwcPzoKRBHY+8cV9teApTUuawKeK/AAAA//+99Mih"
}
