// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package elasticsearch

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "elasticsearch", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzsWlGPozYQfs+vGO378gPy0Jeq116lu55020pVVeUcmCS+2B5qmzTpr69sCEuMCSTLbnI6eAuE7/tm7G8YGx5hi4c5oGDG8tQg0+lmBmC5FTiHh5+a5x9mABmaVPPcclJz+GEGAHDyH5CUFQJnABoFMoNzWKJlMwCD1nK1NnP468EY8fC3O7chbRcpqRVfz2HFhHF3rjiKzMw9+CMoJrEt0B32kOMc1pqKvDoTUXcK14RMRWEs6sT9qi8eUbd4+Jd01jgfxS6P0wxUuJ4lmXXS8uw1SHl2htJYZnFkYo/paUNWrjLct6iaw9VDFAKEA9kkCwbxXGg9rO5475irAYyxWbJMROnC8Lp0N9EySk2SUqFs6y9HWEFqHbnYE4Y7npxUUIVcogZaObJCorIGuAK7wTLLyXlxGQq0GCbxVeSVTBfLNJY0Job/h8nyYNFcKnVFWjI7h66bB4fiJLhAas0uAI96RjyufaxvNglKYTVtvzCJkvThxql91l/KgcJgBsuDz/VRaiTd8cqUmEJKpg9vVaFyzSXTvJWCqW6MIm+qG1Pd6NV/Wd2A6Yk/OXdy7jfo3HpVQFl7aXfB8z24P1zS1vG+2cLkI2V4Zl2yQ204qZH5KtQ45dedHFwWe8h+/eMDvFcrCmdnXzWNR90X+QBBR1HRBDQVVGbZIMsTrri9mW1+QZaDU3DiFBdDf01qBiHZ/rYxSLa/PgRF6vZD8ZHU4wjDcYzlliNShzJ8VJ5XPZSiMYkUlG6ZiLdQSyKBLDRw3x7N6ggODhszp6RKWvRB4Le/zEsfB4sQ5ZqHAlcZTy9YCQ6p0hUmhPq6tMCt+lHcc2O5Wj93fPfbi95RB/et9W7HtrhngQUjtvRXteyetKeKfd1Jl9QkJxKjudYVz6qtdbhXGZdEty1ikgZm6TeRtaW1x61bX1PjuScX9A0pDJiSYVAdfwH4wPZdU7ApOEe2vRPFn5Bth0pe3E+ivWw5LNuun7gT2b+Xrc3ZGnWgIirkxZ770wFPrrsHxZPr7s11ptA7viP9Gsb7XGFP3rsHxZP3bu29zg54nSYpCYGpJT1aF/zzj1CDxl03oAc+6jq3C/jCdviZAdbptYWha60IQwZ9gNC6AF09s3pITrqgV8562RB933mPenFlIt8uwEtM+I4LBHMwFiXEoftM6N+P3mTHoc6Kxtu8CTwKYDvGBVuKt1URfuOXo8q4Wi8sM9tZSH3BXueXGOAXSElZxpUBBtUFcBeaSE2Tnt8ENajtgnSGYV/Xmaje7/YcJLQhGx/hkOY2bpzL+T7F4OqelQqdjvju77PHS+AdacA9k7lwARX2UbI854H02pdc4oKrxT8FFpi06tO1gT9x6ffMPGxrLpoN0+2PTC+YfB6gmjwDZ1P5eVV8YK96v/CkCwS+ArvhBrjxe4UVSakvvlVYbtiOleYNNnaAvZKAOj7zLLMjTrwnv0vKLIYi/g8AAP//u6MS/Q=="
}
