The `cloudfront` metricset of aws module allows you to monitor your AWS CloudFront Distributions. `cloudfront` metricset fetches a set of values from
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/monitoring-using-cloudwatch.html[Amazon CloudFront Metrics].
CloudWatch metrics for Amazon CloudFront topics are automatically collected and pushed to CloudWatch every five minutes.

[float]
=== AWS Permissions
Some specific AWS permissions are required for IAM user to collect AWS CloudFront metrics.
----
cloudwatch:GetMetricData
cloudwatch:ListMetrics
ec2:DescribeRegions
cloudfront:ListDistributions
sts:GetCallerIdentity
iam:ListAccountAliases
----

[float]
=== Configuration example
[source,yaml]
----
- module: aws
  period: 300s
  metricsets:
    - cloudfront
  # This module uses the aws cloudwatch metricset, all
  # the options for this metricset are also available here.
----

[float]
=== Metrics
Please see more details for each metric in
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/monitoring-using-cloudwatch.html[Amazon CloudFront Metrics].

|===
|Metric Name|Statistic Method
|4xxErrorRate | Average
|401ErrorRate | Average
|403ErrorRate | Average
|404ErrorRate | Average
|5xxErrorRate | Average
|502ErrorRate | Average
|503ErrorRate | Average
|504ErrorRate | Average
|CacheHitRate | Average
|TotalErrorRate | Average
|BytesDownloaded | Sum
|BytesUploaded | Sum
|Requests | Sum
|Invocations | Sum
|ValidationErrors | Sum
|ExecutionErrors | Sum
|FunctionThrottles | Sum
|OriginLatency | Percentile
|===
