// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package redisenterpise

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "redisenterpise", asset.ModuleFieldsPri, AssetRedisenterpise); err != nil {
		panic(err)
	}
}

// AssetRedisenterpise returns asset data.
// This is the base64 encoded gzipped contents of module/redisenterpise.
func AssetRedisenterpise() string {
	return "eJykj0FOxDAUQ/c9hTX74QBZsOMCcIEJiQtfpEn0/wfR26OMRlWFiliMl7ZsPZ/xwTVAmcVYndpVjBPg4oUBp+eRnCYg05JKd2k14HECgGuGha6SDKmVwuTMmLUtt/Bp28QL9Yv6MAHKwmgMeIsTMAtLtnBdPKPGhUc8Q772UdL22W/OAdTQ5Vf/gtSqR6kGfyekzk2XOFqINcM8upiPE/+hD+2B99C1ZW7mEe3Q9v2VHnf+X6Nd2/d69+pPAAAA//9a0ZKZ"
}
