name: unit-test

inputs:
  beat:
    description: "Beat name"
    required: true
  command:
    description: "Command to run"
    default: "mage unitTest"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version-file: .go-version

    - uses: actions/setup-python@v6
      with:
        cache: "pip"
        python-version-file: .python-version
      continue-on-error: true

    - name: Install mage
      run: make mage
      shell: bash

    - name: Run unitTest
      run: ${COMMAND}
      shell: bash
      working-directory: ${{ inputs.beat }}
      env:
        COMMAND: ${{ inputs.command }}
