// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package beat

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "beat", asset.ModuleFieldsPri, AssetBeat); err != nil {
		panic(err)
	}
}

// AssetBeat returns asset data.
// This is the base64 encoded gzipped contents of module/beat.
func AssetBeat() string {
	return "eJzcV12P6zQQfe+vGPWZmx/QB0AIkO4LSHAlHhBauek0tdYfwZ7sUn49crJp8zF2kqa9lcjDqkp2zjkee2aOP8ErnnewR0EbAJKkcAfbH1DQdgNwQJ87WZK0ZgffbgAAwifQ9lAp3AA4VCg87qAQGwCPRNIUfgd/br1X229geyIqt3+Fbyfr6CW35iiLHRyF8iH+KFEd/K5G/gRGaGy0+BdPgrB+D0DnMlA4W5Ufb7pxw9jLSy6QC+4CnKyn3ocWRCgp/OBLKejUcGa13Kz+OYJoscPfldgjiBY7AK3EHkG02FUlDyuxRxAt9hs6L61ZCT9EuWRFavQkdDk6E0PsBnf7/SViOwLrnki46XDxW3jHUxA9vUOVMaVdMOHykyTMqXJDwWnRV+FBT5bE6SpnMrOIKIqRKMBFBElwywXHsw+JHejClkrQ0TrN/tOUduCOUL0U67Mkcro+78DOAbek0pQVZbmtzIpeHAPpk4TfQ6jFJGOQlqQZlGuXEkUZ0KxcTBTlcsQrapd7O0sM5NJm0b3JnCe4pY2NZldaL6v5Q1PGYN2htzBEyU4Tr8kb2bqAjJMa557xhXFP1ktag/WK53fruu9ZxOapHefnH7PxdO8blluhQ9wYfN60n8IeovT9cvukPMNXLIdx6vqhySM+FTx1aLn4Xqu+Wwa4ZnxFVNYUyQzEx3xqCYOLyboVMDYvrWK4hpuDmWvG/GDmHjE/eM35yVXlCd34FjIn+K6eOreGhDTo5L94ey4eZDVf0RlUSasXUwbTB2wZyCzbOwdojoFNbb8WRhSo0VCGRuzVaNsaiL21CsWQJjEewvPZQ46GnFAdGvig+e42QykNYYFumZBfKr1HB/b4ge+BW+tst5nK55SH5Pd0Sr/QGNQ34FB5PMD+XI9gVsTfFVasybqDhhob9ihNwQvpOgx/F4fhVzkMjXoIEpcTA+sCFvmLwX9uHLEatXXnTChl81UIZElwzWwGgvPxBjsKvMwJYQ4qUhDRLP4ez6ItMT7tkvKV1JKyk2A74+x4b48LtvAy40uSGjPN54Ghnaiq+ow3oCyfq0xNWFhnK5ImsgHLia8t8Qod2Eyoa2nivUXJ/SKzN6Hj57rYILdaWwNkQShVkw8XOlWVTW9cbBwm5IXn16brck0kJQymfSXMGvWzRIbny7nsjImkIHxDw64GJjO2QNBPgaW5kKCLsaXy15Us8lfWU/ZVs5W/WDj0KqRJVhBg7LvCQ5HQcVVL8i2254+V21Cnt7hzcxOUn9hb3+OV1hInFbRKD86W5XOPwJSEi9SqVDIX9My8+quKacFHIcfW/6uKnVBw6aTWamHOT1FK1oaLzHluacUs2qOUfgl8YAaZTc4BhyKW87tNgd9QHKLTExZMgP35WQVVM6eS1ZmsztnorHusyqAvxd9KfHeS0nbkDrv+RyD5X2x7SBexl5W+zifufL2jQwGpH/8FAAD//11MHm4="
}
