// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package meraki

import (
	"github.com/elastic/beats/v9/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "meraki", asset.ModuleFieldsPri, AssetMeraki); err != nil {
		panic(err)
	}
}

// AssetMeraki returns asset data.
// This is the base64 encoded zlib format compressed contents of module/meraki.
func AssetMeraki() string {
	return "eJycjzFOxTAQRPucYi6QCErcUnMIEw9oZceO1k6i3B4RZJQYiv//lLO7b2d6eO4GE9V66YAiJdDgVfKY8FZdZaDNNHhnsR3wIQwumw5Aj2gnnggAyj7T4FPTMv8Yp/1D9chxlZG/9j+Xh9r3VS32jM5UseEyqnjPfUvqmpmTiTFLigZFF/7JGlm2pP7hsCv1oF/efu8YvAzPw9ONvaTNfU+nrwAAAP//9Ot90A=="
}
