// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package cisco

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "cisco", asset.ModuleFieldsPri, AssetCisco); err != nil {
		panic(err)
	}
}

// AssetCisco returns asset data.
// This is the base64 encoded gzipped contents of module/cisco.
func AssetCisco() string {
	return "eJzsmE9v4zYQxe/5FHMp0AKOe/ehQOAkQIBmE1S7h54Mhhxa3FAclRxZ629fkJJtWatVHES7SADrEMT6896PI3L4oEt4xu0CpAmSLgDYsMUFLNufCoP0pmRDbgF/XQAA3JOqLIImD7lwyhq3bm4Hh1yTfwaFGyMRLK3D/AJAG7QqLNLDl+BEgQe7ePC2xAWsPVVle2bANR63SQi0p6J13FnEo2vTtRJB7M8NmY0Ydk3Jt55X2RXcGo+1sHbeubXvfyAoMASxxpVRR8oNyjNua/LHV0ZwAD7n2CFptcEodGy0QX9gGkAJldbm24kY+E0UZZwNAUMw5E5nfEjnhW39QGhGD79F4FNBqfISV8Yxei0kTlG5LGnCXjO9VM4RtKUayANu0PEolsLAxomoPy3b9UH4TYC+sriK/04B9UkUCKQTwpWUGAIsybEnC3+bwMkMOBcMhWCZowLOTTiBsn27VUD/M1ijbsNlQjrR+LXlPImw+6J/GWbH9DWshShLVKvdkikHOHsnX2ww7IULVjCqXe3uHkEo5TGEV7CU5HmAxpJbv5UnSp9CcrRiJy5N9329rj5dqp9RpC7Zi5Xi3KPglcUN2ml2qKgHSS/N40LYWniEP+GJ2CFHUq2NnMODS6thg357aameQfzTkytIoReMM8jNOo9tMN0ef5wyLCkY1+S3U4xs2WrtG/OPR3Yb2/VuA90YX4VZe09/fOzpq3AzQJaj45HkHMpmIk+SJL4481/VjQ5pWCLtNqMkRhblKpoOUIS8P51HGe6W94/pyZcNJampDKPU/LukqFlNmhRjSiypRr9bEdeo0QV8J/Hx9vP1x4qPEfgcH8/x8RwfP3R8hC8B4WaZtZfmpnxHibIP945j5h61c/3EYv7y+DnIeg6m52B6DqZHhsfBdGjrQ1l5w0OThp6+ovyxYc/uH1G3mTMVN2t14SbuF+H7cGwoTBqO7x6yo8+3MJqBRYoPK2vCUK960zYaO2oTTqL6aPG1kMYOF380AGc3y9e10p0RMEGdG5k3a7oN6x41+gC/68NKnkH26f5xBtm/2QyEi3taT1aT5/yPOVwdxKVw8IQgIBdepW7RfLmfgYDSE5MkO4O08ormoz/pfouI6WgbGAsIpDmKzOGOQaEjxqP01DYmKaqwr33zaL+tNsOcX/wfAAD//2QuogM="
}
