FROM java:8-jre

ENV ELASTICSEARCH_MAJOR 5.0
ENV ELASTICSEARCH_VERSION 5.0.0-alpha1

COPY setup.sh /
RUN bash setup.sh https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/5.0.0-alpha1/elasticsearch-5.0.0-alpha1.deb


ENV PATH /usr/share/elasticsearch/bin:$PATH

COPY config /usr/share/elasticsearch/config

VOLUME /usr/share/elasticsearch/data

# Shield currently not enabled
#RUN elasticsearch-plugin install -Des.plugins.staging=true -b xpack

COPY docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9200 9300

CMD ["elasticsearch"]

