FROM java:8-jre

ENV ELASTICSEARCH_MAJOR 5.0
ENV ELASTICSEARCH_VERSION 5.0.0-alpha2

COPY setup.sh /
RUN bash setup.sh http://download.elastic.co/elasticsearch/staging/5.0.0-alpha2-e3126df/org/elasticsearch/distribution/deb/elasticsearch/5.0.0-alpha2/elasticsearch-5.0.0-alpha2.deb


ENV PATH /usr/share/elasticsearch/bin:$PATH

COPY config /usr/share/elasticsearch/config

VOLUME /usr/share/elasticsearch/data

# Shield currently not enabled
#RUN elasticsearch-plugin install -Des.plugins.staging=true -b xpack

COPY docker-entrypoint.sh /

ENV ES_JAVA_OPTS "-Xms512m -Xmx512m"

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9200 9300

CMD ["elasticsearch"]

