This is the `collstats` metricset of the module mongodb.

It is using the `top` administrative command to return usage statistics for each collection. It provides the amount of time, in microseconds, used and a count of operations for the following types:

- total
- readLock
- writeLock
- queries
- getmore
- insert
- update
- remove
- commands

It requires the following privileges:

- https://docs.mongodb.com/manual/reference/privilege-actions/#top[`top` action] on https://docs.mongodb.com/manual/reference/resource-document/#cluster-resource[`cluster` resource]

You can use the following command in Mongo shell to create the role (make sure you are using the `admin` db by using `db` command in Mongo shell).

["source","js",subs="attributes"]
----
db.createRole(
   {
     role: "collstatsRole",
     privileges: [
       { resource: { cluster: true }, actions: ["top"] },
     ],
     roles: []
   }
)
----

You can then use the following command in Mongo shell to create the privileged user (make sure you are using the `admin` db by using `db` command in Mongo shell).

["source","js",subs="attributes"]
----
db.createUser(
    {
        user: "beats",
        pwd: "pass",
        roles: ["collstatsRole"]
    }
)
----

You can use the following command in Mongo shell to grant the role to an existing user (make sure you are using the `admin` db by using `db` command in Mongo shell).

["source","js",subs="attributes"]
----
db.grantRolesToUser("user", ["collstatsRole"])
----
