This module periodically fetches monitoring metrics from AWS Cloudwatch.

The default metricset is `ec2`.

[float]
=== Module-specific configuration notes

When configuring the `aws_config_profile_name` option, you must use the profile name in local AWS configuration file.
If `aws_config_profile_name` is not set, this module will report mock data instead.

The AWS CLI stores the credentials that you specify with aws configure in a local file named credentials in a folder
named .aws in your home directory `~/.aws/credentials`. The file generated by the AWS CLI for the profile configured
in the previous section look like this:

[source,yaml]
-----------------
[default]
 aws_access_key_id=AKIAIOSFODNN7EXAMPLE
 aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

[metricbeat-aws]
 aws_access_key_id=ASIAZENKQPPNZDBTSVNB
 aws_secret_access_key=Saxlp2wI09tMcaBhwkEMtWBjaGUwtrmGE
 aws_session_token=FQoGZXIvYXdzEHsaDKpiiMUFzVp16DT6MSKwAfm6efgVZWRcziaBt33Fn1Z3PvPfOOCXm0eWasKJlCenFLKfU2gaTLb0JursUeH+Af6qfJobz7MhpVYNbors7Ct59pOgYMRa8+3E1+3vW2iH7QDUdq/hIpK/kh03EotxMRb
-----------------

Both `default` and `metricbeat-aws`in the example above are profile names.

Here is an example of aws metricbeat module configuration:

[source,yaml]
----
metricbeat.modules:
- module: aws
  metricsets: [ec2]
  aws_config_profile_name: "metricbeat-aws"
----
