// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package zookeeper

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "zookeeper", asset.ModuleFieldsPri, AssetZookeeper); err != nil {
		panic(err)
	}
}

// AssetZookeeper returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/zookeeper.
func AssetZookeeper() string {
	return "eJy0mE1v20gPx+/+FEQvvbT+ADk8QIE+h2LRLrDoXnpx6RFtERkNlRnKjvPpFzPSyJItpU78cgosi/yRw5f/5DM80uEBXkQeiWryCwBltfQAH36J/JW++7AAKCgYz7WyuAf43wIAoH8OFalnE8CItWSUClgfQEuCjTT+syXV+CNxrOLZbcFIVaErwnIBEErxujLiNrx9gA3aQAsAT5Yw0ANscQGwYbJFeEheP4PDisbE8aOHOv7cS1N330wgx8/v/s3fYMQpsgsJNkfhqRbfBdHH2L8+ZI+fIduQr3J6fGkK7xXEhBkNXEB4mub2vZGpDnk5+HKc3/w5jWUYTylB41+jhzmuRzrsxRcnz16Jblw/2fZy0jPWtZdnrlBpVaDiKvDLNIYVt30bw5ejbYhmQTYDruhtmsmikjOHJe5OHb6bZEcet5Qtw5p0T+SAXKBqbSklKQA7qNhaDmRkUIVjOqpLqsijDSsjjdMbIf5oqjX5mKLeAbw4KWgGYyPWyp58uLn/3jKEmKOuDUzjPTlNmZomqvB5tWFLq+xJ/E0z9B2fuWoqcEdStgRHbwEwkRewEZ+gj9VWezEUZnKZC67C5xuz5oK7qLJ6DHa3wmD3dgzXVCu0vKO4OByZaPz2VTawDSqDk9ISFdD3FWcPkGimYaUmd9eq+zFfbdF3bo8LK00aDYquYLddeXpqKOjtUztwAtlJm1ZHVMRsryljHvecsU1Q8tPcNZpH0rD0ZIh3dLqMrmc+5s+R7sU/ZpeQXb4OFugOJz4PFd3NAFF7uuHgzO2PtrMOyXo8SYPeH+KJj5uoX2z9MJ+mDeR35FdBUW8oPv4RS3HWjBsjM82QHJyhYnW/tdY6GGy3XujtS3KAEJftKCHAASxhMdcUO/KBZXpWo2U8jaFGLduUs6Hl9NsXy7rudUBXwLphW0BQ33Z8G9Y08x7VlHcakMk2hcHgDqQgbR1YMWgvHZNJ+NyJshVVZzL/j3zjlnnb7eNj+9I7LhzB79JFpb1kfLzqlnHtOh8sb8vkdHjSne12vcQoztJ0pnMmGU7TOBfT0N75PeHVmM7iyrcDrGLBxfiUKwLFR3K9lOxOUAU8hVpcChS7TOQ1O4t4rizfhpj15D0Rz1TnGxE7rXljxB5PindvqO9xskegnmAJ3+Lo7HfSJ9CSA1R4AGItyUeJ1M5+EN8vjSX8HR/uOdAnYI0LIikttOJoWkxfN8h+iqId3HjS7PqTsryyuXvJ+NRQQwWgjhL3MyaKng1REeCFvLT7c3C6nWILUImnkQJ1XdIwShOVPGQnA7pKak5Ek+3lMfvKgHq3mJxwG21d4LJb56tiTohNPBi5/hoFS1fjv/I/4fKSGAxqdtCE6Vp9eebpbF/QYv86fmoIdmibCQz16AKm1QPfvsYaouQtro3AMU2ySe1YiymTpEFITZM6NZUMBcW15VAOVnbbn/HnHGJUaZoUpOQrdpR+o1TV4tGC+IKSPorrq0S3nemja3t1EGrIiehAuQtw5t9Kp08u9fv/lLQLM/8lJznw1vGGqdUiNXmWIhLuS45HkHs5NmvHv/gvAAD//1f3gz4="
}
