// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package zookeeper

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "zookeeper", asset.ModuleFieldsPri, AssetZookeeper); err != nil {
		panic(err)
	}
}

// AssetZookeeper returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/zookeeper.
func AssetZookeeper() string {
	return "eJy0WMuu2zgM3ecriG66afMBdzFAMZ1FMWinU3Q23biMzMRCZNGV6Dzu1w8kW46d2Glu4utVEFk8hxQfR34PWzo+wTPzlqgitwAQLYae4M0P5r/jf28WADl55XQlmu0T/LEAAOjWoSRxWnlQbAwpoRxWR5CCYM21e29IJLzEVgs7bTeguCzR5n65APAFO8kU27XePMEajacFgCND6OkJNrgAWGsyuX+KqO/BYklDxuGRYxVed1xX7T8jlMPzs9v5ExRbQW19JJu8cFSxa53ofOy297mHp8+tz0+xtaQCuO/WxlheYdrAjZk5B+0D62rwd8Lc0nHPLj9bu4Icnj87dPj0dRQthGoUz7Dd3A329dxqgvtVU03nTtwL+G80NhHiE6YjRXo3G+q31txvcT3Z+UPrh2YTVmnFPZKmP4OBG+rpvCk0+84yPhbYsvfnsBuk51oRFOwl/JqvFE7dLtlejiJjVTk+6BKFshwFM6+fx2m8/Bg/nGxDMAu87vEKaOOcDApZdVzi7hzwbiY7crihZBlWJHsiC2Q9lStDMUgetIVSG6M9Ke71zCE7qgoqyaHxmeJ6tpz/UpcrciFEHQA8W85pgsaajeE9OT87fmcZfIhRWwaqdo6sxEiNMyrxkK21oSwhsZs1Qp/xoMu6BHtiqg3BCc0DRuY5rNlF0qdsqxwr8hOxTAlX4mFmrinhbsqsjoa2c9HQ9uU0bF1maPSOsqmWP0eW9WyDcO+kpEABdF3GmSNENuNkuSL7qln3ZTrbAnYqjxszjWvxgjbXdpM5+lWTl/lD2wOBBNKE1RLlIdorSjRPc06Z2gu5cd4Vqi2JX84sLk6cT/GzJHt22wTZ6ZnrxGZUH7eQCnAThKg5XX+0av6jba1DtB5OUqFzx3DiwyLqBlvXzMfZenI7cpkXlBnFxzc2FHrNsDASpwkmR6soz15vrDUAvenWCb19QRYQwrAdBAS0B0OYTxXFjpzXPN6r0Wg896FCKZqQa0XL8d03y7p2O6DNYVVrk4MX11R849Y45z2KKl6pQUbb5HuN25MAN3lgWKG5tU1G4fNKLBtRdSHzf8tvWDIvu328bTbdceHwbhcvKs0l4+1Dt4xHx3lveBtNVvon3dpuxkvw4iJMFzpnlMN5GKd86tu7vCdc9enCr3Q7wDIkXPBPdEkguCXbScn2BIXBka/YRkexjUQas5MUL5XlyygmPfmaFC9U5wsptlpzZoodPc7vnlCfQ2cPhDoGS/gUWmc3k96BFNpDiUcgLQW5IJGa3g/suqGxhH/C4l57egdawoCISgsNWxoX0481su8saHo3nti7fqcsHyzuTjI2X68AZRC47yFQdFBEuYdnctzMz97ptorNQ8mOBgrUtkHDIE2EU5Od/zvWiDfJXmqzVxrU3WJyBDbYugGyHedZPiXERhYG0B+DYGlz/Ef6ZJyGRK9Rawu1H8/V54Mej/YNJfaf1b9qgh2aeoSGOLQe2y+zH0MOUUQLY8PrECZex3KsWBVR0iDEoomVGlOGvODKaF/0RnZTn+F17YNXsZvkJORKbSm+I1RW7NAAu5yiPgrjq0C7maijR2u156pPgWiJ6tbBic9K5yu34v4Vg3Zj5D+kIHu9sXqtqdEiFTnNeWC4L3Q4glTLoVhb/ov/AwAA//+mPilp"
}
