// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package ceph

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "ceph", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzEml9v2zYQwN/zKQ552oDE2F79MKDrCjTY0gZL+zQMKk2eJM4USZBUXH/7gdQfx/pvh3b11FrK3U93x+Pdifewxf0aKOr8BsBxJ3ANt+9R57c3AAwtNVw7ruQafrsBAPC3oFCsFHgDYHNlXEKVTHm2hpQI6381KJBYXMMGHfFPoXNcZnYN/9xaK27/vQFIOQpm10HmPUhSYEvhL7fXuIbMqFLXvwyw+Oub/6NvQJV0hEsLLkco0BlO/b+Jgx0aBEsN0cggNaqA9x+ePq5qAa8xjlBEaR2ahHG7bW8OYU2g+WtETtdCzdXFeY1EXggXZCNwtdk7tEfPNGRCyaxzYwLOX+8aqRCkgkqDCWvuzuOpMgVxa+gDNJBOOSKiAn7xEuPAlRZZVLavFtn5aN1Yy5EIl8eItp6kc+JNvaAhQiTWEVcOW2yL+50y7DSjfa7kQiV3ynBtUPECaY50a1eoFc0jee+RaHhBY7mSc2qNKiVbvRBRYiTlrXAIspcBxHbF85ELjkG60dnTPRydY5G2IGp7Gqaic8hx53sj7Gq1NSZDwpA05XRlkLDkpEwynp3m4Sr7gFcKLjeqzHJdOtBowCJVY9FTs+4Md3h12KD1DNpgWaUT7QMCaSz/vjYhV9qeZryL8VRWWgJUcKsFobgKO2xkjEY46AxkWWxG8nDLoDb/IXWxdtEeRS1+EYohjqtBEEuJQJakQhE3Et8aDUXZvXsqbh+hoWSYGcKQXcRpjfAZp7UMl3FaS7HAaS3Kj3NaizvuNJ2tGHHk6hlTZ+D1TtSvOluFJuDqaOS4SRiDC1F+dTh3aBDGwHzhf3Wusm0ORrBCwYOhqMPE/xhpaT5lobbG189NI1BV9hbUudqfc7WzkKsdFETuQWcWiEHgsoZS6eyr9/giF3u1g+x8vacsW6WlGE7dG6UEki7VjPIH64VCT+hrjRKJuYhWL3hGdVkkyrJYu0QnGLxkHwlzDV9DUupLw/jQVBVQG55fnyahuPwRUA+fJqEMFkRrZInOrk3294fHd09PH/4Y5YvZswdZ3RqjLQqV5E4tHqSc0aoeawg2sGHXXti1HmZ4msZKuIcJXl0ZNf384+fhmOmZB942RfhYGWNG6+HVt5vob/7n73Pqq8FkNNXVVHJebRg5RtMa5o3zSgWxLik1Iw67rqw0+zsnvi8vEHY5StgRC0OyG+WjhcxZsfWJFDj3utYpg6FSsCuhsqgT3r9UdhjwdgGWzJxfwxXc0qh0j9zSeHjWuqh0z89f4sFd/MPCWwFnF90ZwUes6621VztrwtLlmxx+12h4gfJ4EjE1l0Wdh7KRcbuF0pLMl/GVVY4L5qktj8eyRihgFcOuxNnE4/D7idOCVtVoa8LwhVNMqCA24jy+1etl3AEXAjMiwv+ASypKhpAzdgfWMkBHVxNbnY/aK3S7bXxUbfiLEuWIydqvb9ekqqJ2gurMr6ox2A5TlQk+nSWyLCItIdvtzUEo6rNLVdTz0CWOO2+sZr3U0K7jxVoGyXAwGTqDOJsOl6Q7LygkugW9wtUynzKwKekW3TVzYEfpaDb0OuJmwY7miXyoLLuDXFl3B0YpN5EW9xqTS/rEi3oYboNpzgUzODzBOt03tdZGKgjuX9+iJias5s0eqCoKMmwIakqbJzvkWT68nocW8tKdKwiHAeGHnVOPNJ+nOyFo7AtsVOF3bkc+eJw1ReO20mgdF6KS7mNAKvfTr/d7tHfwy71UPw/nccMLYvYJSVMuudvHMrxvjCpr+yLWIGFc1h8SwmGnWu9oYjc4EQhnHGvIsRXpgcbUxj7JcDhMEvIBd36vKwWDDUKpvZeY2g3PeC9TynlDVJIhSG7RBN8uKeJS4vLeOaI38mhiUNbJKvTU1YbfyWO9zVUrJd58EG5IyA/dVB9YM1fwaKftpm8eZYyqrHrJqx7167Es63w9Z9xPyp/CVDcslPpb8jJrXeFY3xtsdIEJ4HZzxPV/AAAA///CdzJc"
}
