// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/module_include_list/module_include_list.go - DO NOT EDIT.

// +build ibm

package include

import (
	// Import packages that need to register themselves.
	_ "github.com/elastic/beats/x-pack/metricbeat/module/ibmmq"
	_ "github.com/elastic/beats/x-pack/metricbeat/module/ibmmq/qmgr"
)
