include::{libbeat-dir}/shared/integration-link.asciidoc[]

:modulename!:

This module fetches metrics from https://www.docker.com/[Docker] containers. The default metricsets are: `container`, `cpu`, `diskio`, `healthcheck`, `info`, `memory` and `network`. The `image` metricset is not enabled by default.

[float]
=== Compatibility

The Docker module is currently tested on Linux and Mac with the community
edition engine, versions 1.11 and 17.09.0-ce. It is not tested on Windows,
but it should also work there.

The Docker module supports collection of metrics from Podman's Docker-compatible API on Metricbeat 8.16.2 and 8.17.1 or more recent.
It has been tested on Linux and Mac with Podman Rest API v2.0.0 and above.

[float]
=== Module-specific configuration notes

It is strongly recommended that you run Docker metricsets with a
<<metricset-period,`period`>> that is 3 seconds or longer. The request to the
Docker API already takes up to 2 seconds. Specifying less than 3 seconds will
result in requests that timeout, and no data will be reported for those
requests.
In the case of Podman, the configuration parameter `podman` should be set to `true`. 
This enables streaming of container stats output, which allows for more accurate 
CPU percentage calculations when using Podman.
