// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package prometheus

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "prometheus", asset.ModuleFieldsPri, AssetPrometheus); err != nil {
		panic(err)
	}
}

// AssetPrometheus returns asset data.
// This is the base64 encoded gzipped contents of module/prometheus.
func AssetPrometheus() string {
	return "eJzEkstqMzEMhfd+ioOX4U8ewIv/GQpdlhKUGcVx4xuWXJq3L8kMYXqjWRSinX0O0qeD1jjyyaG2klgP3GX9Vmk4GkCDRnawD1cJeqo8IrG2MIg1wMgytFA1lOzw3wDAo5IKZGh09u5bSSAsenAeawlZNwZoHJmEHTwZQFg1ZC8OT1Yk2n+wB9Vqnw2wDxxHcZcJa2RKvGTerDavFDtfZFwwHcruhQedv6bHdlLG0neRvyrbRLWG7GebXdnZ882a51ps5al7npP5GXIoPSu3+2HOAL+CNtI7hnmePt7MegiixTdKNwJ/9v8N87Xrkndi/njlUzXW3jJyiOY9AAD//85gGik="
}
