== Audit Module

The `audit` module reports security-relevant information based on data
captured from the operating system (OS) or services running on the OS. While it
doesn't provide additional security to your system, it does help make it
possible to discover violations of security policies and track to the actions
being performed.

[float]
=== Index Management

The data produced by this metricset may contain sensitive information and may
have different access and retention requirements than other data produced by
Metricbeat. For these reasons you may wish to store the data in a separate
index. Below is an example configuration demonstrating how to store the data
from the `audit` module in its own index.

[source,yaml]
----
metricbeat.modules:
- module: audit
  metricsets: ["kernel"]

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  indices:
  - index: "metricbeat-%{[beat.version]}-audit-%{+yyyy.MM.dd}"
    when.equals.metricset.module: "audit"
----

The default index template applied by Metricbeat will also apply to this index
because the pattern in the template matches the `metricbeat-%{[beat.version]}`
prefix.
