// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "Beat", asset.BeatFieldsPri, AssetBeat); err != nil {
		panic(err)
	}
}

// AssetBeat returns asset data.
// This is the base64 encoded gzipped contents of ./build/fields/beat.yml.
func AssetBeat() string {
	return "eJy0Vk2P2zYQvftXzG1bINHefSgKBA1aoIcC3bs9lkYUUYpkZkbr+N8XJEU51ireAnV8sijOe28++MSP8A9d9uCC2QGoVUd7+DMY6K0jaINX8roD6EhatlFt8Hv4ZQcA8Cl4ReslxZbtznqSZgfQW3Kd7Hd530fwOFKmaNK2JqIO+Q2AXiLtk4Jz4G5eY/oyWaZuDz06oXl1Q0D6vQxUuHsOI5wH2w6gQ5ECZxRgwq6Bl8FKUZVzyrLTNjxJcJMSJE2gIS9mkQvD58BAX3GMqTLH51fkZxfMs1xEaWxcMMfmbZ4SJm6pwa5jEnlUsn9nVJhR36QcDNAreV3yhmeQ9Jw2bogMfS+kN+Jc8OZ/taFgZj1MMbBSV3ohiqwCqCshokw4PqpCaXILIpwH8rkK1pvadOKUuHyAFj2cCJ5EuzDpEwTO/4n56Vae9XHSJul6I0d5+g9VyQA5sXW/rr0y5IlR6XZQrUAuZRnKV3QTgURqbW+pWzj6wPn9MVEcIWQRYH1eLORCbV4MfV78bB2dCDUVpbdmHvebrFPZDmpHEsUx3k/yDw8tCs18hkQh2ki56RFZqJy0Ba2UoQ7s7DDyAayCaGCSBTntCWyN9ejg+OuCcISfmCJTmu3U3ApfWl6Rbxzg51IRewXPNV7P4kWySWFrndXL407GDAj0VRnbdCaWIkS2ga1etqXUtw+TUgHrMBSeMovbEoReKUUcHJ7IPdK3h2nEckTx5Agq0f2m/HAZlWglI3JoSaSJHAw/zrCSgERQ+zHDb7h179DIe2DbX7kcWhm2Wj2oxoZJYvBCDTmMQsUAvjd431HwWwktx/FEeqZswl+mZAvoO6gk6TyO1jmb3Cn4Tu4qml3i4Mib1d3hfU2fSjCU4FqG319e/rqqOYVu3fBJiA9oyvXnymc4TNUR6zWnPNXA8I2DvQlZB13D+sm5Q/q7vFmP14285NpC2nwTsTWMd8Zu+Q7MUKAD6vVblO1yc1oq9Ri6yd2So7NY009Xqv0McLN1tIaxKMrf0H8DAAD//5uGP3E="
}
