// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/module_include_list/module_include_list.go - DO NOT EDIT.

package include

import (
	// Import packages that need to register themselves.
	_ "github.com/elastic/beats/v7/filebeat/input/azureeventhub"
	_ "github.com/elastic/beats/v7/filebeat/input/cloudfoundry"
	_ "github.com/elastic/beats/v7/filebeat/input/container"
	_ "github.com/elastic/beats/v7/filebeat/input/docker"
	_ "github.com/elastic/beats/v7/filebeat/input/googlepubsub"
	_ "github.com/elastic/beats/v7/filebeat/input/httpjson"
	_ "github.com/elastic/beats/v7/filebeat/input/kafka"
	_ "github.com/elastic/beats/v7/filebeat/input/log"
	_ "github.com/elastic/beats/v7/filebeat/input/mqtt"
	_ "github.com/elastic/beats/v7/filebeat/input/netflow"
	_ "github.com/elastic/beats/v7/filebeat/input/o365audit"
	_ "github.com/elastic/beats/v7/filebeat/input/redis"
	_ "github.com/elastic/beats/v7/filebeat/input/s3"
	_ "github.com/elastic/beats/v7/filebeat/input/stdin"
	_ "github.com/elastic/beats/v7/filebeat/input/syslog"
	_ "github.com/elastic/beats/v7/filebeat/input/tcp"
	_ "github.com/elastic/beats/v7/filebeat/input/udp"
	_ "github.com/elastic/beats/v7/filebeat/input/unix"
	_ "github.com/elastic/beats/v7/filebeat/module/activemq"
	_ "github.com/elastic/beats/v7/filebeat/module/apache"
	_ "github.com/elastic/beats/v7/filebeat/module/auditd"
	_ "github.com/elastic/beats/v7/filebeat/module/aws"
	_ "github.com/elastic/beats/v7/filebeat/module/azure"
	_ "github.com/elastic/beats/v7/filebeat/module/cef"
	_ "github.com/elastic/beats/v7/filebeat/module/checkpoint"
	_ "github.com/elastic/beats/v7/filebeat/module/cisco"
	_ "github.com/elastic/beats/v7/filebeat/module/coredns"
	_ "github.com/elastic/beats/v7/filebeat/module/crowdstrike"
	_ "github.com/elastic/beats/v7/filebeat/module/elasticsearch"
	_ "github.com/elastic/beats/v7/filebeat/module/envoyproxy"
	_ "github.com/elastic/beats/v7/filebeat/module/googlecloud"
	_ "github.com/elastic/beats/v7/filebeat/module/haproxy"
	_ "github.com/elastic/beats/v7/filebeat/module/ibmmq"
	_ "github.com/elastic/beats/v7/filebeat/module/icinga"
	_ "github.com/elastic/beats/v7/filebeat/module/iis"
	_ "github.com/elastic/beats/v7/filebeat/module/iptables"
	_ "github.com/elastic/beats/v7/filebeat/module/kafka"
	_ "github.com/elastic/beats/v7/filebeat/module/kibana"
	_ "github.com/elastic/beats/v7/filebeat/module/logstash"
	_ "github.com/elastic/beats/v7/filebeat/module/misp"
	_ "github.com/elastic/beats/v7/filebeat/module/mongodb"
	_ "github.com/elastic/beats/v7/filebeat/module/mssql"
	_ "github.com/elastic/beats/v7/filebeat/module/mysql"
	_ "github.com/elastic/beats/v7/filebeat/module/nats"
	_ "github.com/elastic/beats/v7/filebeat/module/netflow"
	_ "github.com/elastic/beats/v7/filebeat/module/nginx"
	_ "github.com/elastic/beats/v7/filebeat/module/o365"
	_ "github.com/elastic/beats/v7/filebeat/module/okta"
	_ "github.com/elastic/beats/v7/filebeat/module/osquery"
	_ "github.com/elastic/beats/v7/filebeat/module/panw"
	_ "github.com/elastic/beats/v7/filebeat/module/postgresql"
	_ "github.com/elastic/beats/v7/filebeat/module/rabbitmq"
	_ "github.com/elastic/beats/v7/filebeat/module/redis"
	_ "github.com/elastic/beats/v7/filebeat/module/santa"
	_ "github.com/elastic/beats/v7/filebeat/module/suricata"
	_ "github.com/elastic/beats/v7/filebeat/module/system"
	_ "github.com/elastic/beats/v7/filebeat/module/traefik"
	_ "github.com/elastic/beats/v7/filebeat/module/zeek"
)
