////
This file is generated! See scripts/changelog.py
////

[[release-notes-v5.0.0-rc1]]
=== Beats version v5.0.0-rc1
 https://github.com/elastic/beats/compare/v5.0.0-beta1...v5.0.0-rc1[View commits]

==== Bug

- Fix the `bpf_filter` setting.
  {issue}2660[2660]

[[release-notes-v5.0.0-beta1]]
=== Beats version v5.0.0-beta1
 https://github.com/elastic/beats/compare/v5.0.0-alpha5...v5.0.0-beta1[View commits]

==== Breaking

- Group HTTP fields under `http.request` and `http.response`
  {issue}2167[2167]
- Export `http.request.body` and `http.response.body` when configured under `include_body_for`
  {issue}2167[2167]
- Move `ignore_outgoing` config to `packetbeat.ignore_outgoing`
  {issue}2393[2393]

==== Bug

- Fix mapping for some Packetbeat flow metrics that were not marked as being longs.
  {issue}2177[2177]
- Fix handling of messages larger than the maximum message size (10MB).
  {issue}2470[2470]

==== Added

- Add Cassandra protocol analyzer to Packetbeat.
  {issue}1959[1959]
- Match connections with IPv6 addresses to processes
  {issue}2254[2254]
- Add IP address to -devices command output
  {issue}2327[2327]
- Add configuration option for the maximum message size. Used to be hard-coded to 10 MB.
  {issue}2470[2470]

[[release-notes-v5.0.0-alpha5]]
=== Beats version v5.0.0-alpha5
 https://github.com/elastic/beats/compare/v5.0.0-alpha4...v5.0.0-alpha5[View commits]

==== Breaking

- Set `enabled` ` in `packetbeat.protocols.icmp` configuration to `true` by default.
  {issue}1988[1988]

==== Added

- Add enabled setting to Packetbeat protocols.
  {issue}1988[1988]
- Add enabled setting to Packetbeat network flows configuration.
  {issue}1988[1988]

[[release-notes-v5.0.0-alpha4]]
=== Beats version v5.0.0-alpha4
 https://github.com/elastic/beats/compare/v5.0.0-alpha3...v5.0.0-alpha4[View commits]

==== Bug

- Add missing nil-check to memcached GapInStream handler.
  {issue}1162[1162]
- Fix NFSv4 Operation returning the first found first-class operation available in compound requests.
  {issue}1821[1821]
- Fix TCP overlapping segments not being handled correctly.
  {issue}1898[1898]

[[release-notes-v5.0.0-alpha3]]
=== Beats version v5.0.0-alpha3
 https://github.com/elastic/beats/compare/v5.0.0-alpha2...v5.0.0-alpha3[View commits]

[[release-notes-v5.0.0-alpha2]]
=== Beats version v5.0.0-alpha2
 https://github.com/elastic/beats/compare/v5.0.0-alpha1...v5.0.0-alpha2[View commits]

==== Breaking

- Configuration of redis topology support changed.
  {issue}1353[1353]
- Move all Packetbeat configuration options under the packetbeat namespace
  {issue}1417[1417]

==== Added

- Fix compile issues for OpenBSD.
  {issue}1347[1347]

[[release-notes-v5.0.0-alpha1]]
=== Beats version v5.0.0-alpha1
 https://github.com/elastic/beats/compare/v1.2.0...v5.0.0-alpha1[View commits]

==== Breaking

- Rename output fields in the dns package. Former flag `recursion_allowed` becomes `recursion_available`.
  {issue}803[803]
- The fully qualified domain names which are part of output fields values of the dns package now terminate with a dot.
  {issue}803[803]
- Remove the count field from the exported event
  {issue}1210[1210]

==== Bug

- Create a proper BPF filter when ICMP is the only enabled protocol
  {issue}757[757]
- Check column length in pgsql parser.
  {issue}565[565]
- Harden pgsql parser.
  {issue}565[565]

==== Added

- Change the DNS library used throughout the dns package to github.com/miekg/dns.
  {issue}803[803]
- Add support for NFS v3 and v4.
  {issue}1231[1231]
- Add support for EDNS and DNSSEC.
  {issue}1292[1292]

[[release-notes-v1.2.3]]
=== Beats version v1.2.3
 https://github.com/elastic/beats/compare/v1.2.2...v1.2.3[View commits]

[[release-notes-v1.2.2]]
=== Beats version v1.2.2
 https://github.com/elastic/beats/compare/v1.2.0...v1.2.2[View commits]

[[release-notes-v1.2.1]]
=== Beats version v1.2.1
 https://github.com/elastic/beats/compare/v1.2.0...v1.2.1[View commits]

[[release-notes-v1.2.0]]
=== Beats version v1.2.0
 https://github.com/elastic/beats/compare/v1.1.2...v1.2.0[View commits]

==== Bug

- Split real_ip_header value when it contains multiple IPs
  {issue}1241[1241]

[[release-notes-v1.1.2]]
=== Beats version v1.1.2
 https://github.com/elastic/beats/compare/v1.1.1...v1.1.2[View commits]

[[release-notes-v1.1.1]]
=== Beats version v1.1.1
 https://github.com/elastic/beats/compare/v1.1.0...v1.1.1[View commits]

[[release-notes-v1.1.0]]
=== Beats version v1.1.0
 https://github.com/elastic/beats/compare/v1.0.1...v1.1.0[View commits]

==== Added

- Add support for capturing DNS over TCP network traffic. {pull}486[486]
  {issue}554[554]

==== Bug

- Fix setting direction to out and use its value to decide when dropping events if ignore_outgoing is enabled
  {issue}557[557]
- Reduce memory usage by having separate queue sizes for single events and bulk events. {pull}649[649]
  {issue}516[516]
- Set default bulk_max_size value to 2048
  {issue}628[628]
- Fix logstash window size of 1 not increasing.
  {issue}598[598]
- Allow PF_RING sniffer type to be configured using pf_ring or pfring
  {issue}671[671]

[[release-notes-v1.0.1]]
=== Beats version v1.0.1
 https://github.com/elastic/beats/compare/v1.0.0...v1.0.1[View commits]

==== Bug

- Improve MongoDB message correlation.
  {issue}377[377]
- Improve redis parser performance.
  {issue}442[442]
- Fix panic on nil in redis protocol parser.
  {issue}384[384]
- Fix errors redis parser when messages are split in multiple TCP segments.
  {issue}402[402]
- Fix errors in redis parser when length prefixed strings contain sequences of CRLF.
  {issue}None[None]
- Fix errors in redis parser when dealing with nested arrays.
  {issue}402[402]

[[release-notes-master]]
=== Beats version master
 https://github.com/elastic/beats/compare/v5.0.0-rc1...master[View commits]

[[release-notes-1.0.0-rc2]]
=== Beats version 1.0.0-rc2
 https://github.com/elastic/beats/compare/1.0.0-rc1...1.0.0-rc2[View commits]

[[release-notes-1.0.0-rc1]]
=== Beats version 1.0.0-rc1
 https://github.com/elastic/beats/compare/1.0.0-beta4...1.0.0-rc1[View commits]

[[release-notes-1.0.0-beta4]]
=== Beats version 1.0.0-beta4
 https://github.com/elastic/beats/compare/1.0.0-beta3...1.0.0-beta4[View commits]

[[release-notes-1.0.0]]
=== Beats version 1.0.0
 https://github.com/elastic/beats/compare/1.0.0-rc2...1.0.0[View commits]

