[[community-beats]]
== Community Beats

The open source community has been hard at work developing new Beats. You can check
out some of them here:

[horizontal]
https://github.com/radoondas/apachebeat[apachebeat]:: Reads status from Apache HTTPD server-status.
https://github.com/Ingensi/dockerbeat[dockerbeat]:: Reads docker container
statistics and indexes them in Elasticsearch.
https://github.com/radoondas/elasticbeat[elasticbeat]:: Reads status from Elasticsearch cluster and index them to Elasticsearch.
https://github.com/christiangalsterer/execbeat[execbeat]:: Periodically executes shell commands and sends the standard output and standard error to
Logstash or Elasticsearch.
https://github.com/jarpy/factbeat[factbeat]:: Collects facts from https://puppetlabs.com/facter[Facter].
https://github.com/YaSuenag/hsbeat[hsbeat]:: Reads all performance counters in Java HotSpot VM.
https://github.com/christiangalsterer/httpbeat[httpbeat]:: Polls multiple HTTP(S) endpoints and sends the data to
Logstash or Elasticsearch. Supports all HTTP methods and proxies.
https://github.com/PhaedrusTheGreek/nagioscheckbeat[nagioscheckbeat]:: For Nagios checks and performance data.
https://github.com/mrkschan/nginxbeat[nginxbeat]:: Reads status from Nginx.
https://github.com/kozlice/phpfpmbeat[phpfpmbeat]:: Reads status from PHP-FPM.
https://github.com/joshuar/pingbeat[pingbeat]:: Sends ICMP pings to a list
of targets and stores the round trip time (RTT) in Elasticsearch.
https://github.com/chrsblck/redisbeat[redisbeat]:: Used for Redis monitoring.
https://github.com/buehler/go-elastic-twitterbeat[twitterbeat]:: Read tweets for specified screennames
https://github.com/cleesmith/unifiedbeat[unifiedbeat]:: Reads records from Unified2 binary files generated by
network intrusion detection software and indexes the records in Elasticsearch.
https://github.com/mrkschan/uwsgibeat[uwsgibeat]:: Reads stats from uWSGI.
https://github.com/gravitational/udpbeat[udpbeat]:: Ship Structured Logs via UDP

Have you created a Beat that's not listed? If so, add the name and description of your Beat to the source document for     
https://github.com/elastic/beats/blob/master/libbeat/docs/communitybeats.asciidoc[Community Beats] and https://help.github.com/articles/using-pull-requests[open a pull request] in GitHub to get your change merged. 

NOTE: Elastic provides no warranty or support for community-sourced Beats.

[float]
[[contributing-beats]]
=== Contributing to Beats

Remember, you can be a Beats developer, too. <<new-beat, Learn how>>

