//////////////////////////////////////////////////////////////////////////
//// This content is shared by all Elastic Beats. Make sure you keep the
//// descriptions here generic enough to work for all Beats that include
//// this file. When using cross references, make sure that the cross
//// references resolve correctly for any files that include this one.
//// Use the appropriate variables defined in the index.asciidoc file to
//// resolve Beat names: beatname_uc and beatname_lc.
//// Use the following include to pull this content into a doc file:
//// include::../../libbeat/docs/debugging.asciidoc[]
//////////////////////////////////////////////////////////////////////////

By default, {beatname_uc} sends all its output to syslog. When you run {beatname_uc} in
the foreground, you can use the `-e` command line flag to redirect the output to
standard error instead. For example:

["source","sh",subs="attributes"]
-----------------------------------------------
{beatname_lc} -e
-----------------------------------------------

The default configuration file is {beatname_lc}.yml (the location of the file varies by
platform). You can use a different configuration file by specifying the `-c` flag. For example:

["source","sh",subs="attributes"]
------------------------------------------------------------
{beatname_lc} -e -c my{beatname_lc}config.yml
------------------------------------------------------------

You can increase the verbosity of debug messages by enabling one or more debug
selectors. For example, to view the published transactions, you can start {beatname_uc}
with the `publish` selector like this:

["source","sh",subs="attributes"]
------------------------------------------------------------
{beatname_lc} -e -d "publish"
------------------------------------------------------------

If you want all the debugging output (fair warning, it's quite a lot), you can
use `*`, like this:

["source","sh",subs="attributes"]
------------------------------------------------------------
{beatname_lc} -e -d "*"
------------------------------------------------------------
