[id="{beatname_lc}-reference-yml"]
== {beatname_lc}.reference.yml

The following reference file is available with your {beatname_uc} installation. It
shows all non-deprecated {beatname_uc} options. You can copy from this file and paste
configurations into the +{beatname_lc}.yml+ file to customize it.

ifeval::["{beatname_lc}"!="auditbeat"]

TIP: For rpm and deb, you'll find the reference configuration file at +/etc/{beatname_lc}/{beatname_lc}.reference.yml+. Under
Docker, it's located at +/usr/share/{beatname_lc}/{beatname_lc}.reference.yml+. For mac and win,
look in the archive that you just extracted.

endif::[]

ifeval::["{beatname_lc}"=="auditbeat"]

TIP: For rpm and deb, you'll find the reference configuration file at +/etc/{beatname_lc}/{beatname_lc}.reference.yml+. Under
Docker, it's located at +/usr/share/{beatname_lc}/{beatname_lc}.reference.yml+. For mac and win,
look in the archive that you just extracted.

endif::[]

The contents of the file are included here for your convenience.

[source,yaml]
--
include::../../{beatname_lc}/{beatname_lc}.reference.yml[]
--
