//////////////////////////////////////////////////////////////////////////
//// This content is shared by all Elastic Beats. Make sure you keep the
//// descriptions here generic enough to work for all Beats that include
//// this file. When using cross references, make sure that the cross
//// references resolve correctly for any files that include this one.
//// Use the appropriate variables defined in the index.asciidoc file to
//// resolve Beat names: beatname_uc and beatname_lc.
//// Use the following include to pull this content into a doc file:
//// include::../../libbeat/docs/shared-faq.asciidoc[]
//////////////////////////////////////////////////////////////////////////

[[connection-problem]]
=== Why doesn't my connection to Logstash work?

You may have configured Logstash or the Beat incorrectly. To resolve the issue: 

* Make sure that Logstash is running and you can connect to it. First, try to ping the Logstash host to verify that you can reach it
from the host running the Beat. Then use either `nc` or `telnet` to make sure that the port is available. For example:
+
[source,shell]
----------------------------------------------------------------------
ping <hostname or IP>
telnet <hostname or IP> 5044
----------------------------------------------------------------------
* Verify that the config file for your Beat specifies the correct port where Logstash is running.  
* Make sure that the Elasticsearch output is commented out in the config file and the Logstash output is uncommented. 
* Confirm that the most recent Beats input plugin for Logstash is installed and configured. Note that Beats will not connect
to the Lumberjack input plugin. See
{libbeat}/logstash-installation.html#logstash-input-update[Updating the Beats Input Plugin for Logstash].

[[metadata-missing]]
=== Why is @metadata missing in Logstash?

Logstash outputs remove `@metadata` fields automatically. Therefore, if Logstash instances are chained directly or via some message
queue (for example, Redis or Kafka), the `@metadata` field will not be available in the final Logstash instance.

TIP: To preserve `@metadata` fields, use the Logstash mutate filter with the rename setting to rename the fields to
non-internal fields.

[[diff-logstash-beats]]
=== What is the difference between Logstash and Beats?

Beats are lightweight data shippers that you install as agents on your servers to send specific types of operational
data to Elasticsearch. Beats have a small footprint and use fewer system resources than Logstash.

Logstash has a larger footprint, but provides a broad array of input, filter, and output plugins for collecting, enriching,
and transforming data from a variety of sources. 

For more information, see the https://www.elastic.co/guide/en/logstash/current/introduction.html[Logstash Introduction] and
the https://www.elastic.co/guide/en/beats/libbeat/current/beats-reference.html[Beats Overview].

[[ssl-client-fails]]
=== Why does my SSL client fail to connect to Logstash?

The host running Logstash might be unreachable or the certificate may not be valid. To resolve your issue:

* Make sure that Logstash is running and you can connect to it. First, try to ping the Logstash host to verify that you can reach it
from the host running the Beat. Then use either `nc` or `telnet` to make sure that the port is available. For example:
+
[source,shell]
----------------------------------------------------------------------
ping <hostname or IP>
telnet <hostname or IP> 5044
----------------------------------------------------------------------

* Verify that the certificate is valid and that the hostname and IP match. 
+
TIP: For testing purposes only, you can set `insecure: true` to disable hostname checking.

* Make sure that you have enabled SSL (set `ssl => true`) when configuring the https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html[Beats input plugin for Logstash].
