[[ilm]]
[role="xpack"]
== Configure index lifecycle management

Use the {ref}/getting-started-index-lifecycle-management.html[index lifecycle
management] feature in {es} to manage your {beatname_uc} indices as they age.
For example, instead of creating daily indices where index size can vary based
on the number of Beats and number of events sent, use an index lifecycle policy
to automate a rollover to a new index when the existing index reaches a
specified size or age.

Starting with version 7.0, {beatname_uc} uses index lifecycle management by
default when it connects to a cluster that supports lifecycle management.
{beatname_uc} loads the default policy automatically and applies it to any
indices created by {beatname_uc}.

You can view and edit the policy in the *Index lifecycle policies* UI in {kib}.
For more information about working with the UI, see
{kibana-ref}/index-lifecycle-policies.html[Index lifecyle policies].

// REVIEWERS: I'm not going to describe the default policy as requested in the
// GitHub issue because the settings might change. If users want to know what
// the policy settings are, they should view the policy in Kibana. Sound fair?

Example configuration:

["source","yaml",subs="attributes"]
----
setup.ilm.enabled: auto
setup.ilm.rollover_alias: "{beatname_lc}"
setup.ilm.pattern: "{now/d}-000001" <1>
----
<1> Date math is supported here. For more information, see
{ref}/indices-rollover-index.html#_using_date_math_with_the_rollover_api[Using
date math with the rollover API].

// REVIEWERS: Rather than showing the default for setup.ilm.pattern, let's show
// something different than the default. What would you suggest here?

// TODO: The reference.yml is missing some of these options and incorrectly
// refers to the "elasticsearch.output.index" (it should be output.elasticsearch.index)
//
// Should I also update the reference.yml, or is it too late for 7.0?

[float]
=== Configuration options

You can specify the following settings in the `setup.ilm` section of the
+{beatname_lc}.yml+ config file:

[float]
[[setup-ilm-option]]
==== `setup.ilm.enabled`

Enables or disables index lifecycle management on any new indices created by
{beatname_uc}. Valid values are `true`, `false`, and `auto`. When `auto` (the
default) is specified, {beatname_uc} automatically uses index lifecycle
management if the feature is enabled in {es} and has the required license;
otherwise, {beatname_uc} creates daily indices.

[float]
[[setup-ilm-rollover_alias-option]]
==== `setup.ilm.rollover_alias`

The index lifecycle write alias name. The default is
+{beatname_lc}-\{{beat_version_key}\}+. Setting this option changes the prefix
in the alias name. It doesn't remove +{beat_version_key}+ from the alias name. 

NOTE: If you modify this setting after loading the index template, you must
overwrite the template to apply the changes.

[float]
[[setup-ilm-pattern-option]]
==== `setup.ilm.pattern`

The rollover index pattern. The default is `%{now/d}-000001`.

NOTE: If you modify this setting after loading the index template, you must
overwrite the template to apply the changes.

[float]
[[setup-ilm-policy_name-option]]
==== `setup.ilm.policy_name`

The name to use for the lifecycle policy. The default is
+{beatname_lc}-\{{beat_version_key}\}+.

[float]
[[setup-ilm-policy_file-option]]
==== `setup.ilm.policy_file`

The path to a JSON file that contains a lifecycle policy configuration. Use this
setting to load your own lifecycle policy.

[float]
[[setup-ilm-check_exists-option]]
==== `setup.ilm.check_exists`

When set to `false`, disables the check for an existing lifecycle policy. The
default is `true`. You need to disable this check if the {beatname_uc}
user connecting to a secured cluster doesn't have the `read_ilm` privilege.

If you set this option to `false`, set `setup.ilm.overwrite: true` so the
lifecycle policy can be installed.

[float]
[[setup-ilm-overwrite-option]]
==== `setup.ilm.overwrite`

When set to `true`, the lifecycle policy is overwritten at startup. The default
is `false`.

// REVIEWERS: I think the section about "advanced" settings is no longer required
// now that we use the alias to override the index setting, so I am deleting it.
