//REVIEWERS: This content underscores a problem in our docs where we recommend using sudo, but don't show sudo in all the examples (because some of the examples come from shared content like this topic). It's confusing to users when we show some commands with sudo and some without. I can conditionally code the content to make sudo part of the command only when it's required, but I want to make sure we have a full list of the Beats that require sudo. Can we identify a list of Beats where we expect users to always run as sudo? There's also the problem of providing platform-agnostic command examples.


If you've secured Elasticsearch and Kibana, you need to pass credentials when
you run {beatname_uc} commands. You can specify credentials from the command
line, or in the config file. For example, from the command line, specify:

ifeval::["{start-type}"=="setup-index"]

["source","sh",subs="attributes"]
----
{beatname_lc} setup --template -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic
----

endif::[]

ifeval::["{start-type}"=="setup-dashboards"]

["source","sh",subs="attributes"]
----
{beatname_lc} setup --dashboards -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic -E setup.kibana.username=elastic -E setup.kibana.password=elastic
----

endif::[]

ifeval::["{start-type}"=="start"]

["source","sh",subs="attributes"]
----
{beatname_lc} -e -c {beatname_lc}.yml -d "publish" -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic
----

If you start {beatname_uc} as a service instead of running it in the
foreground, you must specify credentials in the config file.

endif::[]

ifeval::["{start-type}"=="modules"]

["source","sh",subs="attributes"]
----
{beatname_lc} setup -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic -E setup.kibana.username=elastic -E setup.kibana.password=elastic
----

endif::[]

See <<{beatname_lc}-configuration>> for more information about specifying
credentials in the config file.
