//////////////////////////////////////////////////////////////////////////
//// This content is shared by all Elastic Beats. Make sure you keep the
//// descriptions here generic enough to work for all Beats that include
//// this file. When using cross references, make sure that the cross
//// references resolve correctly for any files that include this one.
//// Use the appropriate variables defined in the index.asciidoc file to
//// resolve Beat names: beatname_uc and beatname_lc.
//// Use the following include to pull this content into a doc file:
//// include::../../libbeat/docs/shared-path-config.asciidoc[]
//// Make sure this content appears below a level 2 heading.
//////////////////////////////////////////////////////////////////////////

[[configuration-path]]
=== Path

The `path` section contains configuration options that define where the Beat is
looking for its files. For example, all Beats look for the Elasticsearch
template file in the configuration path, Filebeat and Winlogbeat look for their
registry files in the data path and all Beats write their log files in the logs
path.

Please see the <<directory-layout>> section for more details.

Here is an example configuration:

[source,yaml]
------------------------------------------------------------------------------
path:
  home: /usr/share/beat
  conf: /etc/beat
  data: /var/lib/beat
  logs: /var/log/
------------------------------------------------------------------------------

Note that it is possible to override these options via command line flags.

==== Path Options

You can specify the following options under the `path` section:

===== home

The home path for a {beatname_uc} installation is the default base path for all the
other path settings as well for miscellaneous files coming with the distribution (e.g. the
sample dashboards). If not set via a CLI flag or via the configuration file, the default
for the home path is the location of the {beatname_uc} binary.

Example:

[source,yaml]
------------------------------------------------------------------------------
path:
  home: /usr/share/beats
------------------------------------------------------------------------------

===== conf

The configuration path for a {beatname_uc} installation is the default base path
for the configuration files, including the main YAML configuration file and the
Elasticsearch template file. If not set via a CLI flag, the default for the
configuration path is the same as the home path.

Example:

[source,yaml]
------------------------------------------------------------------------------
path:
  conf: /usr/share/beats/config
------------------------------------------------------------------------------

===== data

The data path for a {beatname_uc} installation is the default base path for all
the files in which {beatname_uc} needs to store its data. If not set via a CLI
flag or via the configuration file, the default for the data path is a `data`
subdirectory inside the home path.


Example:

[source,yaml]
------------------------------------------------------------------------------
path:
  data: /var/lib/beats
------------------------------------------------------------------------------

===== logs

The logs path for a {beatname_uc} installation is the default location for its
log files. If not set via a CLI flag or via the configuration file, the default
for the logs path is a `logs` subdirectory inside the home path.

Example:

[source,yaml]
------------------------------------------------------------------------------
path:
  logs: /var/log/beats
------------------------------------------------------------------------------
