//////////////////////////////////////////////////////////////////////////
//// This content is shared by all Elastic Beats. Make sure you keep the
//// descriptions here generic enough to work for all Beats that include
//// this file. When using cross references, make sure that the cross
//// references resolve correctly for any files that include this one.
//// Use the appropriate variables defined in the index.asciidoc file to
//// resolve Beat names: beatname_uc and beatname_lc
//// Use the following include to pull this content into a doc file:
//// include::../../libbeat/docs/shared-template-load.asciidoc[]
//// If you want to include conditional content, you also need to
//// add the following doc attribute definition  before the
//// include statement so that you have:
//// :allplatforms:
//// include::../../libbeat/docs/shared-template-load.asciidoc[]
//// This content must be embedded underneath a level 3 heading.
//////////////////////////////////////////////////////////////////////////


In Elasticsearch, http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html[index
templates] are used to define settings and mappings that determine how fields should be analyzed. 

The recommended index template file for {beatname_uc} is installed by the {beatname_uc} packages. By default,
{beatname_uc} loads the template automatically after successfully connecting to Elasticsearch. If the template
already exists, it's not overwritten unless you configure {beatname_uc} to do so.

If you want to disable automatic template loading, or you want to load your own template, 
you can change the settings for template loading in the {beatname_uc} configuration file. If you 
choose to disable automatic template loading, you need to load the template manually. 
For more information, see:

* <<load-template-auto>>
* <<load-template-manually>>

[[load-template-auto]]
==== Configuring Template Loading

By default, {beatname_uc} automatically loads the recommended template file, +{beatname_lc}.template.json+,
if elasticsearch output is enabled. You can configure {beatname_lc} to load a different template
by adjusting the `name` and `path` options under `template` in +{beatname_lc}.yml+ file:

["source","yaml",subs="attributes,callouts"]
----------------------------------------------------------------------
output:
  elasticsearch:
    hosts: ["localhost:9200"]

    # A template is used to set the mapping in Elasticsearch
    # By default template loading is disabled and no template is loaded.
    # These settings can be adjusted to load your own template or overwrite existing ones
    template:

      # Template name. By default the template name is {beatname_lc}.
      name: "{beatname_lc}"

      # Path to template file
      path: "{beatname_lc}.template.json"

      # Overwrite existing template
      overwrite: false
----------------------------------------------------------------------

By default, if a template already exists in the index, it is not overwritten. To overwrite an existing
template, set `overwrite: true` in the configuration file.

To disable automatic template loading, comment out the template part under elasticsearch output.

[[load-template-manually]]
==== Loading the Template Manually

If you disable automatic template loading, you need to run the following command to load the template:

ifdef::allplatforms[]

*deb or rpm:*

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
curl -XPUT 'http://localhost:9200/_template/{beatname_lc}' -d@/etc/{beatname_lc}/{beatname_lc}.template.json
----------------------------------------------------------------------

*mac:*

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
cd {beatname_lc}-{version}-darwin
curl -XPUT 'http://localhost:9200/_template/{beatname_lc}' -d@{beatname_lc}.template.json
----------------------------------------------------------------------

endif::allplatforms[]

*win:*

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
PS C:\Program Files{backslash}{beatname_uc}> Invoke-WebRequest -Method Put -InFile {beatname_lc}.template.json -Uri http://localhost:9200/_template/{beatname_lc}?pretty
----------------------------------------------------------------------

where `localhost:9200` is the IP and port where Elasticsearch is listening.

NOTE: If you've already used {beatname_uc} to index data into Elasticsearch,
the index may contain old documents. After you load the index template,
you can delete the old documents from {beatname_lc}-* to force Kibana to look
at the newest documents. Use this command:

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
curl -XDELETE 'http://localhost:9200/{beatname_lc}-*'
----------------------------------------------------------------------
