//////////////////////////////////////////////////////////////////////////
//// This content is shared by all Elastic Beats. Make sure you keep the
//// descriptions here generic enough to work for all Beats that include
//// this file. When using cross references, make sure that the cross
//// references resolve correctly for any files that include this one.
//// Use the appropriate variables defined in the index.asciidoc file to
//// resolve Beat names: beatname_uc and beatname_lc
//// Use the following include to pull this content into a doc file:
//// include::../../libbeat/docs/shared-template-load.asciidoc[]
//// If you want to include conditional content, you also need to
//// add the following doc attribute definition  before the
//// include statement so that you have:
//// :allplatforms:
//// include::../../libbeat/docs/shared-template-load.asciidoc[]
//// This content must be embedded underneath a level 3 heading.
//////////////////////////////////////////////////////////////////////////


In Elasticsearch, {elasticsearch}/indices-templates.html[index
templates] are used to define settings and mappings that determine how fields should be analyzed.

The recommended index template file for {beatname_uc} is installed by the {beatname_uc} packages. If you accept
the default configuration for template loading in the +{beatname_lc}.yml+ config file,
{beatname_uc} loads the template automatically after successfully connecting to Elasticsearch. If the template
already exists, it's not overwritten unless you configure {beatname_uc} to do so.

If you want to disable automatic template loading, or you want to load your own template,
you can change the settings for template loading in the {beatname_uc} configuration file. If you
choose to disable automatic template loading, you need to load the template manually.
For more information, see:

* <<load-template-auto>> - supported for Elasticsearch output only
* <<load-template-manually>> - required for Logstash output

[[load-template-auto]]
==== Configure template loading

By default, {beatname_uc} automatically loads the recommended template file, +fields.yml+,
if Elasticsearch output is enabled. You can configure {beatname_lc} to load a different template
by adjusting the `setup.template.name` and `setup.template.fields` options in
+{beatname_lc}.yml+ file:

["source","yaml",subs="attributes,callouts"]
----------------------------------------------------------------------
setup.template.name: "{beatname_lc}"
setup.template.fields: "path/to/fields.yml"
setup.template.overwrite: false
----------------------------------------------------------------------

By default, if a template already exists in the index, it is not overwritten. To overwrite an existing
template, set `setup.template.overwrite: true` in the configuration file.

To disable automatic template loading, set `setup.template.enabled: false`.

The options for auto loading the template are not supported if you are using the
Logstash output.

[[load-template-manually]]
==== Load the template manually

If you disable automatic template loading, you can run the `setup` command to
load the template.

["source","sh",subs="attributes"]
----
./{beatname_lc} setup --template
----

ifeval::["{requires-sudo}"=="yes"]

If you changed ownership of the config file to root, you'll need preface this
command with `sudo`.

endif::[]

//REVIEWERS: I'm keeping separate steps for the loading the index template and the dashboards since it seems like the index template loading happens automatically, but the dashboard loading must be specified. It might be confusing to describe this in one step. Plus having separate steps helps users understand that two very different operations are taking place (the loading of the index template into ES and the loading of dashboards into Kibana)

//TODO: I think this needs to be deleted. Commenting it out for now just in case. Also need to remove conditional flag

/////

ifdef::allplatforms[]

*deb or rpm:*

["source","sh",subs="attributes"]
----------------------------------------------------------------------
curl -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_template/{beatname_lc}' -d@/etc/{beatname_lc}/{beatname_lc}.template.json
----------------------------------------------------------------------

*mac:*

["source","sh",subs="attributes"]
----------------------------------------------------------------------
cd {beatname_lc}-{version}-darwin-x86_64
curl -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_template/{beatname_lc}' -d@{beatname_lc}.template.json
----------------------------------------------------------------------

ifeval::["{beatname_lc}"!="auditbeat"]

*docker:*

["source", "sh", subs="attributes"]
----------------------------------------------------------------------
docker run --rm {dockerimage} curl -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_template/{beatname_lc}' -d@{beatname_lc}.template.json
----------------------------------------------------------------------

endif::[]

*win:*

endif::allplatforms[]

["source","sh",subs="attributes"]
----------------------------------------------------------------------
PS C:\Program Files{backslash}{beatname_uc}> Invoke-WebRequest -Method Put -InFile {beatname_lc}.template.json -Uri  http://localhost:9200/_template/{beatname_lc}?pretty -ContentType application/json
----------------------------------------------------------------------

where `localhost:9200` is the IP and port where Elasticsearch is listening.

/////

NOTE: If you've already used {beatname_uc} to index data into Elasticsearch,
the index may contain old documents. After you load the index template,
you can delete the old documents from {beatname_lc}-* to force Kibana to look
at the newest documents. Use this command:

["source","sh",subs="attributes"]
----------------------------------------------------------------------
curl -XDELETE 'http://localhost:9200/{beatname_lc}-*'
----------------------------------------------------------------------
