//REVIEWERS: This content underscores a problem in our docs where we recommend using sudo, but don't show sudo in all the examples (because some of the examples come from shared content like this topic). It's confusing to users when we show some commands with sudo and some without. I can conditionally code the content to make sudo part of the command only when it's required, but I want to make sure we have a full list of the Beats that require sudo. Can we identify a list of Beats where we expect users to always run as sudo? There's also the problem of providing platform-agnostic command examples.

If you've secured Elasticsearch and Kibana, you need to pass credentials when
you run {beatname_uc} commands. For example:

ifeval::["{start-type}"=="setup-index"]

["source","sh",subs="attributes"]
----
{beatname_lc} setup --template -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic
----

endif::[]

ifeval::["{start-type}"=="setup-dashboards"]

["source","sh",subs="attributes"]
----
{beatname_lc} setup --dashboards -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic -E setup.kibana.username=elastic -E setup.kibana.password=elastic
----

endif::[]

ifeval::["{start-type}"=="start"]

["source","sh",subs="attributes"]
----
{beatname_lc} -e -c {beatname_lc}.yml -d "publish" -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic
----


//REVIEWERS: I don't include the kibana credentials here because my assumption us that users have already run the necessary commands to setup credentials.

endif::[]

ifeval::["{start-type}"=="modules"]

["source","sh",subs="attributes"]
----
{beatname_lc} setup -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic -E setup.kibana.username=elastic -E setup.kibana.password=elastic
----

endif::[]
