[[configuration-template]]

=== Template

The http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html[index
template] to use for setting mappings in Elasticsearch. By default, template loading is
enabled.

You can adjust the following settings to load your own template or overwrite an existing one:

*`enabled`*:: Set to false to disable template loading. If set this to false,
you must <<load-template-manually,load the template manually>>.

*`name`*:: The name of the template. The default is +{beatname_lc}+.

*`fields`*:: The path to the YAML file describing the fields. The default is +fields.yml+. If a
relative path is set, it is considered relative to the config path. See the <<directory-layout>>
section for details.

*`overwrite`*:: A boolean that specifies whether to overwrite the existing template. The default
is false.

*`settings.index`*:: A dictionary of settings to place into the `settings.index` dictionary of the
Elasticsearch template. For more details about the available Elasticsearch mapping options, please
see the Elasticsearch {elasticsearch}/mapping.html[mapping reference].

Example:

["source","yaml",subs="attributes,callouts"]
----------------------------------------------------------------------
setup.template.name: "{beatname_lc}"
setup.template.fields: "fields.yml"
setup.template.overwrite: false
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1
----------------------------------------------------------------------

*`settings._source`*:: A dictionary of settings for the `_source` field. For the available settings,
please see the Elasticsearch {elasticsearch}/mapping-source-field.html[reference].

Example:

["source","yaml",subs="attributes,callouts"]
----------------------------------------------------------------------
setup.template.name: "{beatname_lc}"
setup.template.fields: "fields.yml"
setup.template.overwrite: false
setup.template.settings:
  _source.enabled: false
----------------------------------------------------------------------

*`output_to_file.path`*:: If this option is set, {beatname_uc} generates the Elasticsearch template
  JSON object and writes into a file at the specified path. Immediately after writing the file,
  {beatname_uc} exists with the exit code 1.

For example, you can generate a template file ready to be uploaded to Elasticsearch like this:

["source","yaml",subs="attributes,callouts"]
----------------------------------------------------------------------
./{beatname_lc} -e -E "setup.template.output_to_file.path={beatname_lc}.template.json"
----------------------------------------------------------------------

*`output_to_file.version`*:: The Elasticsearch version for which to generate the template file. By
default, the {beatname_uc} version is used. This setting is only used if `output_to_file.path` is
also set.

For example, the following generates a template file for Elasticsearch 5.4:

["source","yaml",subs="attributes,callouts"]
----------------------------------------------------------------------
./{beatname_lc} -e -E "setup.template.output_to_file.path={beatname_lc}.template.json" -E "setup.template.output_to_file.version=5.4.0"
----------------------------------------------------------------------
