[[upgrading]]
== Upgrade

This section gives general recommendations for upgrading {beats} shippers:

* <<upgrade-minor-versions>>
* <<upgrade-7-to-8>>
* <<troubleshooting-upgrade>>

If you're upgrading other products in the stack, also read the
{stack-ref}/index.html[Elastic Stack Installation and Upgrade Guide].

[discrete]
[[upgrade-minor-versions]]
=== Upgrade between minor versions

As a general rule, you can upgrade between minor versions (for example, 8.x to
8.y, where x < y) by simply installing the new release and restarting the Beat
process. {beats} typically maintain backwards compatibility for configuration
settings and exported fields. Please review the
<<release-notes,release notes>> for potential exceptions.

Upgrading between non-consecutive major versions (e.g. 6.x to 8.x) is not
supported.

[discrete]
[[upgrade-7-to-8]]
=== Upgrade from 7.x to 8.x

Before upgrading your {beats}, review the <<breaking-changes,breaking changes>>
and the <<release-notes>>.

If you're upgrading other products in the stack, also read the
{stack-ref}/index.html[Elastic Stack Installation and Upgrade Guide].

We recommend that you fully upgrade {es} and {kib} to version 8.0
before upgrading {beats}. The {beats} version must be lower than or equal to the
{es} version. {beats} cannot send data to older versions of {es}.

If you're on {beats} 7.0 through 7.16, upgrade the {stack} and {beats} to
version 7.17 *before* proceeding with the 8.0 upgrade.

Upgrading between non-consecutive major versions (e.g. 6.x to 8.x) is not
supported.

IMPORTANT: Please read through all upgrade steps before proceeding. These steps
are required before running the software for the first time.

[discrete]
[[upgrade-to-7.17]]
==== Upgrade to {beats} 7.17 before upgrading to 8.0

The upgrade procedure assumes that you have {beats} 7.17 installed. If you're on
a previous 7.x version of {beats}, *upgrade to version 7.17 first*. If you're
using other products in the {stack}, upgrade {beats} as part of the
{stack-ref}/upgrading-elastic-stack.html[{stack} upgrade process].

After upgrading to 7.17, use the {ref}/index-templates.html#getting[Index
Template API] to verify that the 7.17 index template has been loaded into {es}.
If the 7.17 index template is not loaded, load it now. 

If you created custom dashboards prior to version 7.17, you must upgrade them to
7.17 before proceeding. Otherwise, the dashboards will stop working because
{kib} no longer provides the API used for dashboards in 7.x.

[discrete]
[[upgrade-beats-binaries]]
==== Upgrade {beats} binaries to 8.0

Before upgrading:

. Stop the existing {beats} process by using the appropriate command for your
system.
. Back up the `data` and `config` directories by copying them to another
location.
+
TIP: The location of these directories depends on the installation method. To
see the current paths, start the Beat from a terminal, and the `data` and
`config` paths are printed at startup.

To upgrade using a Debian or RPM package:

* Use `rpm` or `dpkg` to install the new package. All files are installed in the
appropriate location for the operating system and {beats} config files are not
overwritten.

To upgrade using a zip or compressed tarball:

. Extract the zip or tarball to a _new_ directory. This is critical if you
are not using external `config` and `data` directories.
. Set the following options in the {beats} configuration file:
+
--
* Set `path.config` to point to your external `config` directory. If you are
not using an external `config` directory, copy your old configuration over to
the new installation.
* Set `path.data` to point to your external data directory. If you are not using
an external `data` directory, copy your old data directory over to the new
installation.
* Set `path.logs` to point to the location where you want to store your logs. If
you do not specify this setting, logs are stored in the directory you extracted
the archive to.
--

Complete the upgrade tasks described in the following sections *before*
restarting the {beats} process.

[discrete]
[[migrate-config-files]]
==== Migrate configuration files

{beats} 8.0 comes with several backwards incompatible configuration changes.
Before upgrading, review the <<breaking-changes-8.0>> document. Also review
the full list of breaking changes in the <<release-notes-8.0.0>>.

Where possible, we kept the old configuration options working, but deprecated
them. However, deprecation was not always possible, so if you use any of the
settings described under breaking changes, make sure you understand the
alternatives that we provide.

//REVIEWERS: Do users need to load any other assets besides the index template
//and dashboards?

[discrete]
[[upgrade-index-template]]
==== Load the 8.0 {es} index templates

Starting in version 8.0, the default {es} index templates configure data streams
instead of traditional {es} indices. Data streams are optimized for storing
append-only time series data. They are well-suited for logs, events, metrics,
and other continuously generated data. However, unlike traditional {es} indices,
data streams support create operations only; they do not support update and
delete operations.

To use data streams, load the default index templates *before* ingesting any
data into {es}.

include::{libbeat-dir}/tab-widgets/load-index-template-widget.asciidoc[]

Not collecting time series data? You can continue to use {beats} to send data to
aliases and indices. To do this, create a custom index template and load it
manually. To learn more about creating index templates, refer to
{ref}/index-templates.html[Index templates].

//REVIEWERS: Do users need to explicitly disable template loading?

[discrete]
[[load-8.0-dashboards]]
==== Load 8.0 dashboards

We recommend that you load the 8.0 {kib} dashboards after upgrading {kib} and
{beats}. That way, you can take advantage of improvements added in 8.0. To load
the dashboards, run:

include::{libbeat-dir}/tab-widgets/load-dashboards-widget.asciidoc[]


[discrete]
[[migrate-custom-dashboards]]
==== Migrate custom dashboards and visualizations

All Elastic {beats} send events with ECS-compliant field names. If you have any
custom {kib} dashboards or visualizations that use old fields, adjust them now
to use ECS field names.

To learn more about ECS, refer to the {ecs-ref}/ecs-reference.html[ECS overview].

NOTE: If you enabled the compatibility layer in 7.x (that is, if you set
`migration.6_to_7.enabled: true`), make sure your custom dashboards no longer
rely on the old aliases created by that setting. The old aliases are no longer
supported. They may continue to work, but will be removed without notice in
a future release.

[discrete]
[[troubleshooting-upgrade]]
=== Troubleshoot {beats} upgrade issues

This section describes common problems you might encounter when upgrading to
{beats} 8.x.

You can avoid some of these problems by reading <<upgrade-7-to-8>> before
upgrading {beats}.

[discrete]
[[unable-to-update-or-delete]]
==== {beats} is unable to send update or deletion requests to a data stream

Data streams are designed for use cases where existing data is rarely, if ever,
updated. You cannot send update or deletion requests for existing documents
directly to a data stream.

If needed, you can update or delete documents by submitting requests directly to
the document’s backing index. To learn how, refer to the docs about
{ref}/use-a-data-stream.html[using a data stream].

[discrete]
[[missing-timestamp-field]]
==== Timestamp field is missing

//REVIEWERS: I think this section could be improved by more detail about
//the error message. What does the user see in the logs to indicate
//this problem?

{beats} requires a timestamp field to send data to data streams. If the
timestamp field added by {beats} is inadvertently removed by a processor, {beats}
will be unable to index the event. To fix the problem, modify your processor
configuration to avoid removing the timestamp field.

[discrete]
[[missing-fields]]
==== Missing fields or too many fields in the index

//REVIEWERS: IS this still necessary? I think the defaults might
//take care of this, but I'll need to do some testing.

You may have run the Beat before loading the required index template. To clean
up and start again:

. Delete the index that was created when you ran the Beat. For example:
+
["source","sh",subs="attributes"]
----
DELETE metricbeat-{version}-2019.04.02*
----
+
WARNING: Be careful when using wildcards to delete indices. Make sure the
pattern matches only the indices you want to delete. The example shown here
deletes all data indexed into the metricbeat-{version} indices on
2019.04.02.

. Delete the index template that was loaded earlier. For example:
+
["source","sh",subs="attributes"]
----
DELETE /_index_template/metricbeat-{version}
----

. Load the correct index template. See <<upgrade-index-template>>.

. Restart {beats}.
