// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

=== Beats version HEAD
https://github.com/elastic/beats/compare/v7.0.0-alpha2...master[Check the HEAD diff]

==== Breaking changes

*Affecting all Beats*


*Auditbeat*

*Filebeat*

*Heartbeat*


*Metricbeat*


*Packetbeat*

*Winlogbeat*


*Functionbeat*

==== Bugfixes

*Affecting all Beats*

- Fix OS name reported by add_host_metadata on Windows 11. {issue}30833[30833] {pull}32259[32259]
- Fix race condition when reloading runners {pull}32309[32309]

*Auditbeat*


*Filebeat*

- Adding a fix for threatintel module where MISP was paginating forever. {pull}31784[31784]
- Fix handling and mapping of syslog priority, facility and severity values in Cisco module. {pull}32025[32025]
- Fix http_endpoint input TLS handshake failures. {pull}32105[32105]
- Fix using log_group_name_prefix in aws-cloudwatch input. {pull}29695[29695]
- Fix wrong state ID in states registry for awss3 s3 direct input. {pull}32164[32164]
- Fix Cisco AMP rate limit and pagination. {pull}32030[32030]
- Fix race conditions when reloading input V2 and filestream input {pull}32309[32309]

*Heartbeat*


*Metricbeat*


*Packetbeat*


*Winlogbeat*



*Functionbeat*



*Elastic Logging Plugin*


==== Added

*Affecting all Beats*

- Improve performance of disk queue by coalescing writes. {pull}31935[31935]

*Auditbeat*

- Add `immutable` option to the auditd module. {issue}8352[8352] {pull}32381[32381]


*Filebeat*

- Add `text/csv` decoder to `httpjson` input {pull}28564[28564]
- Update `aws-s3` input to connect to non AWS S3 buckets {issue}28222[28222] {pull}28234[28234]
- Add support for '/var/log/pods/' path for add_kubernetes_metadata processor with `resource_type: pod`. {pull}28868[28868]
- Add documentation for add_kubernetes_metadata processors `log_path` matcher. {pull}28868[28868]
- Add support for parsers on journald input {pull}29070[29070]
- Add support in httpjson input for oAuth2ProviderDefault of password grant_type. {pull}29087[29087]
- threatintel module: Add new Recorded Future integration. {pull}30030[30030]
- Add `auth.oauth2.google.jwt_json` option to `httpjson` input. {pull}31750[31750]
- Add authentication fields to RabbitMQ module documents. {issue}31159[31159] {pull}31680[31680]
- Add template helper function for decoding hexadecimal strings. {pull}31886[31886]
- Add new `parser` called `include_message` to filter based on message contents. {issue}31794[31794] {pull}32094[32094]
- Extend list of mapped record types in o365 Audit module. {pull}32217[32217]
- Add references for CRI-O configuration in input-container and in our kubernetes manifests {issue}32149[32149] {pull}32151[32151]
- httpjson input: Add `replaceAll` helper function to template context. {pull}32365[32365]
- Optimize grok patterns in system.auth module pipeline. {pull}32360[32360]

*Auditbeat*

*Filebeat*


*Heartbeat*


*Metricbeat*


*Packetbeat*


*Functionbeat*


*Winlogbeat*



*Elastic Log Driver*


==== Deprecated

*Affecting all Beats*


*Filebeat*


*Heartbeat*

*Metricbeat*


*Packetbeat*

*Winlogbeat*

*Functionbeat*

==== Known Issue








