// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

=== Beats version HEAD
https://github.com/elastic/beats/compare/v7.0.0-alpha2...master[Check the HEAD diff]

==== Breaking changes

*Affecting all Beats*


*Auditbeat*

*Filebeat*

*Heartbeat*


*Metricbeat*


*Packetbeat*

*Winlogbeat*


*Functionbeat*

==== Bugfixes

*Affecting all Beats*

- Fix the ability for subcommands to be ran properly from the beats containers. {pull}30452[30452]
- Log errors when parsing and applying config blocks and if the input is disabled. {pull}30534[30534]
- Fixes Beats crashing when glibc >= 2.35 is used {issue}30576[30576]

*Auditbeat*

- Fix handling of execve call events which have no argument. {issue}30585[30585] {pull}30586[30586]

*Filebeat*

- Report the starting offset of the line in `log.offset` when using `filestream` instead of the end to be ECS compliant. {pull}30445[30445]
- auditd: Prevent mapping explosion when truncated EXECVE records are ingested. {pull}30382[30382]
- elasticsearch: fix duplicate ingest when using a common appender configuration {issue}30428[30428] {pull}30440[30440]
- Fix ECS version string in threatintel to be consistent with other modules and add event.timezone. {issue}30499[30499] {pull}30570[30570]
- Add default paths value to MySQL Enterprise module to prevent issues with pipeline installations {pull}30598[30598]
- Update documentation for accessing `last_response.url.params` in httpjson input. {pull}30739[30739]

*Heartbeat*


*Metricbeat*


*Packetbeat*


*Winlogbeat*


*Functionbeat*



*Elastic Logging Plugin*


==== Added

*Affecting all Beats*

*Auditbeat*

*Filebeat*

- Remove beta flag for some filebeat modules. {pull}14374[14374]
- Extend documentation about hints annotation for processors {pull}30561[30561]

*Heartbeat*


*Metricbeat*

- Add `kubernetes.container.status.last.reason` metric {pull}30306[30306]
- Extend documentation about `orchestrator.cluster` fields {pull}30518[30518]
- Fix overflow in `iostat` metrics {pull}30679[30679]
- Add `add_resource_metadata` configuration to Kubernetes module. {pull}29133[29133]
- Add `containerd` module with `cpu`, `memory`, `blkio` metricsets. {pull}29247[29247]
- Add `container.id` and `container.runtime` ECS fields in container metricset. {pull}29560[29560]
- Add `memory.workingset.limit.pct` field in Kubernetes container/pod metricset. {pull}29547[29547]
- Add k8s metadata in state_cronjob metricset. {pull}29572[29572]
- Add `xpack.enabled` support for Enterprise Search module. {pull}29871[29871]
- Add gcp firestore metricset. {pull}29918[29918]
- Remove strict parsing on RabbitMQ module {pull}30090[30090]
- Add `kubernetes.container.status.last.reason` metric {pull}30306[30306]
- Extend documentation about `orchestrator.cluster` fields {pull}30518[30518]
- Fix overflow in `iostat` metrics {pull}30679[30679]

*Packetbeat*


*Functionbeat*


*Winlogbeat*



*Elastic Log Driver*


==== Deprecated

*Affecting all Beats*


*Filebeat*


*Heartbeat*

*Metricbeat*


*Packetbeat*

*Winlogbeat*

*Functionbeat*

==== Known Issue

