// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

=== Beats version HEAD
https://github.com/elastic/beats/compare/v7.0.0-alpha2...master[Check the HEAD diff]

==== Breaking changes

*Affecting all Beats*


*Auditbeat*

*Filebeat*

*Heartbeat*


*Metricbeat*


*Packetbeat*

*Winlogbeat*


*Functionbeat*

==== Bugfixes

*Affecting all Beats*

- Fix OS name reported by add_host_metadata on Windows 11. {issue}30833[30833] {pull}32259[32259]
- Fix race condition when reloading runners {pull}32309[32309]
- Fix race condition when stopping runners {pull}32433[32433]

*Auditbeat*


*Filebeat*

- Adding a fix for threatintel module where MISP was paginating forever. {pull}31784[31784]
- Fix handling and mapping of syslog priority, facility and severity values in Cisco module. {pull}32025[32025]
- Fix http_endpoint input TLS handshake failures. {pull}32105[32105]
- Fix using log_group_name_prefix in aws-cloudwatch input. {pull}29695[29695]
- Fix wrong state ID in states registry for awss3 s3 direct input. {pull}32164[32164]
- Fix Cisco AMP rate limit and pagination. {pull}32030[32030]
- Fix race conditions when reloading input V2 and filestream input {pull}32309[32309]

*Heartbeat*


*Metricbeat*

- update kubernetes apiserver metricset to not collect deprecated metrics and fix dashboard {pull}31973[31973]
- Check for nil metadata in GCP. {pull}32281[32281]
- update kubernetes controllermanager metricset to not collect deprecated metrics and fix dashboard {pull}32037[32037]
- update elasticsearch node_stats metricset to use keyword for cgroup memory instead of long {pull}32197[32197]
- Fix to ARN parsing for Cloudwatch resource names with leading slashes {pull}32358[32358]

*Packetbeat*


*Winlogbeat*



*Functionbeat*



*Elastic Logging Plugin*


==== Added

*Affecting all Beats*


*Auditbeat*

*Filebeat*


*Heartbeat*


*Metricbeat*


*Packetbeat*


*Functionbeat*


*Winlogbeat*



*Elastic Log Driver*


==== Deprecated

*Affecting all Beats*


*Filebeat*


*Heartbeat*

*Metricbeat*


*Packetbeat*

*Winlogbeat*

*Functionbeat*

==== Known Issue








