// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

=== Beats version HEAD
https://github.com/elastic/beats/compare/v8.2.0\...main[Check the HEAD diff]

==== Breaking changes

*Affecting all Beats*


*Auditbeat*


*Filebeat*

*Heartbeat*


*Metricbeat*


*Packetbeat*


*Winlogbeat*


*Functionbeat*


==== Bugfixes

*Affecting all Beats*


- Allow loading secrets that contain commas from the keystore {pull}31694{pull}.
- Improve syslog parser/processor error handling. {issue}31246[31246] {pull}31798[31798]
- Fix Windows service timeouts when the "TCP/IP NetBIOS Helper" service is disabled. {issue}31810[31810] {pull}31835[31835]
- Expand fields in `decode_json_fields` if target is set. {issue}31712[31712] {pull}32010[32010]

*Auditbeat*


*Filebeat*


*Heartbeat*


*Metricbeat*

- Fix kubernetes module's internal cache expiration issue. This avoid metrics like `kubernetes.container.cpu.usage.limit.pct` from not being populated. {pull}31785[31785]
- in module/windows/perfmon, changed collection method of the second counter value required to create a displayable value {pull}32305[32305]
- Fix and improve AWS metric period calculation to avoid zero-length intervals {pull}32724[32724]
- Add missing cluster metadata to k8s module metricsets {pull}32979[32979] {pull}33032[33032]
- Add GCP CloudSQL region filter {pull}32943[32943]
- Fix logstash cgroup mappings {pull}33131[33131]
- Remove unused `elasticsearch.node_stats.indices.bulk.avg_time.bytes` mapping {pull}33263[33263]
- Fix kafka dashboard field names {pull}33555[33555]
- Add tags to events based on parsed identifier. {pull}33472[33472]
- Support Oracle-specific connection strings in SQL module {issue}32089[32089] {pull}32293[32293]
- Remove deprecated metrics from controller manager, scheduler and proxy {pull}34161[34161]
- Fix metrics split through different events and metadata not matching for aws cloudwatch. {pull}34483[34483]
- Fix metadata enricher with correct container ids for pods with multiple containers in container metricset. Align `kubernetes.container.id` and `container.id` fields for state_container metricset. {pull}34516[34516]


*Osquerybeat*


*Packetbeat*


*Winlogbeat*


*Functionbeat*



*Elastic Logging Plugin*


==== Added

*Affecting all Beats*



*Auditbeat*


*Filebeat*


*Auditbeat*



*Filebeat*


*Heartbeat*


*Metricbeat*


*Packetbeat*


*Functionbeat*


*Winlogbeat*



*Elastic Log Driver*


==== Deprecated

*Affecting all Beats*


*Filebeat*


*Heartbeat*

*Metricbeat*


*Packetbeat*

*Winlogbeat*

*Functionbeat*

==== Known Issue
















