// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

This changelog is intended for community Beat developers. It covers the major
breaking changes to the internal APIs in the official Beats and changes related
to developing a Beat like code generators or `fields.yml`. Only the major
changes will be covered in this changelog that are expected to affect community
developers. Each breaking change added here should have an explanation on how
other Beats should be migrated.

Note: This changelog documents the current changes which are not yet present in
an actual release.

=== Beats version HEAD
https://github.com/elastic/beats/compare/v6.6.0..6.x[Check the HEAD diff]

The list below covers the major changes between 6.6.0 and 6.x only.

==== Breaking changes

==== Bugfixes
- Align default index between elasticsearch and logstash and kafka output. {pull}10841[10841]

==== Added

- Allow multiple object type configurations per field. {pull}9772[9772]
