// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

=== Beats version HEAD
https://github.com/elastic/beats/compare/v7.0.0-alpha2...master[Check the HEAD diff]

==== Breaking changes

*Affecting all Beats*

*Auditbeat*

*Filebeat*

*Heartbeat*
- Update the recommended Node.js version to 18.12.0 for Synthetics {pull}15196[15196]

*Metricbeat*


*Packetbeat*

*Winlogbeat*


*Functionbeat*

==== Bugfixes

*Affecting all Beats*
- Fix panics when a processor is closed twice {pull}34647[34647]

*Auditbeat*


*Filebeat*

- [Azure Logs] Fix authentication_processing_details parsing in sign-in logs. {issue}34330[34330] {pull}34478[34478]
- Fix dropped events when monitor a beat under the agent and send its `Host info` log entry. {pull}34599[34599]

*Heartbeat*

- Enable nodejs engine strict validation when bundling synthetics. {pull}34471[34471]

*Metricbeat*


*Packetbeat*

- Handle truncated DNS records more gracefully. {issue}21495[21495] {pull}28297[28297]

*Winlogbeat*

- Fix handling of event data with keys containing dots. {issue}34345[34345] {pull}34549[34549]
- Gracefully handle channel not found errors. {issue}30201[30201] {pull}34605[34605]
- Clarify query term limits warning and remove link to missing Microsoft doc page. {pull}34715[34715]

*Functionbeat*

*Elastic Logging Plugin*


==== Added

*Affecting all Beats*



*Auditbeat*


*Filebeat*


*Auditbeat*


*Filebeat*


*Heartbeat*


*Metricbeat*

- Remove GCP Compute metadata cache {pull}33655[33655]

*Packetbeat*


*Functionbeat*


*Winlogbeat*



*Elastic Log Driver*


==== Deprecated

*Affecting all Beats*


*Filebeat*


*Heartbeat*

*Metricbeat*


*Packetbeat*

*Winlogbeat*

*Functionbeat*

==== Known Issue




















