// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

=== Beats version HEAD
https://github.com/elastic/beats/compare/v8.1.3\...main[Check the HEAD diff]

==== Breaking changes

*Affecting all Beats*

- Update to Go 1.17.9 {issue}31350[31350]

*Auditbeat*


*Filebeat*

*Heartbeat*


*Metricbeat*


*Packetbeat*


*Winlogbeat*


*Functionbeat*


==== Bugfixes

*Affecting all Beats*

- Fix dissect trim panics from DELETE (127)(\u007f) character {issue}30657[30657] {pull}30658[30658]

*Auditbeat*


*Filebeat*

- m365_defender: Fix processing when alerts.entities is an empty list. {issue}31223[31223] {pull}31227[31227]
- Prevent filestream from rereading whole files if they are rotated using rename. {pull}31268[31268]
- Netflow: replace invalid field value. {pull}31295[31295]
- google_workspace: Fix pagination to prevent skipped events when more than one page is present. {pull}31372[31372]

*Heartbeat*

*Metricbeat*

- Improve handling of disabled commands in Zookeeper Metricbeat module. {pull}31013[#31013]
- Fix kubernetes module's internal cache expiration issue. This avoid metrics like `kubernetes.container.cpu.usage.limit.pct` from not being populated. {pull}31785[31785]
- Fix metadata enricher with correct container ids for pods with multiple containers in container metricset. Align `kubernetes.container.id` and `container.id` fields for state_container metricset. {pull}34516[34516]

*Packetbeat*


*Winlogbeat*

- Fix routing for PowerShell events. {issue}31287[31287] {pull}31291[31291]
- Fix missing annotation of event.module. {issue}31330[31330] {pull}31331[31331]

*Functionbeat*



*Elastic Logging Plugin*


==== Added

*Affecting all Beats*


*Auditbeat*


*Filebeat*

- Add `storage_account_container` configuration option to Azure logs. {pull}31279[31279]
- Sanitize the Azure storage account container names with underscores (_). {pull}31384[31384]

*Auditbeat*


*Filebeat*


*Heartbeat*


*Metricbeat*


*Packetbeat*


*Functionbeat*


*Winlogbeat*



*Elastic Log Driver*


==== Deprecated

*Affecting all Beats*


*Filebeat*


*Heartbeat*

*Metricbeat*


*Packetbeat*

*Winlogbeat*

*Functionbeat*

==== Known Issue










