// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/beats/issues/
:pull: https://github.com/elastic/beats/pull/

=== Beats version HEAD
https://github.com/elastic/beats/compare/v7.0.0-alpha2...master[Check the HEAD diff]

==== Breaking changes

*Affecting all Beats*


*Auditbeat*

*Filebeat*

*Heartbeat*


*Metricbeat*


*Packetbeat*

*Winlogbeat*


*Functionbeat*

==== Bugfixes

*Affecting all Beats*

- Fix OS name reported by add_host_metadata on Windows 11. {issue}30833[30833] {pull}32259[32259]
- Fix race condition when reloading runners {pull}32309[32309]
- Fix race condition when stopping runners {pull}32433[32433]

*Auditbeat*

- auditd module: Fix parsing of audit rules where arguments are quoted (like file paths containing spaces). {pull}32421[32421]
- auditd module: Fix minimum AuditStatus length so that library can support kernels from 2.6.32. {pull}32421[32421]
- system/socket: Reduce memory usage of the dataset. {issue}32191[32191] {pull}32192[32192]
- system/package: Fix parsing of Installed-Size field of DEB packages. {issue}16661[16661] {pull}17188[17188]
- system module: Fix panic during initialisation when /proc/stat can't be read. {pull}17569[17569]
- system/package: Fix an error that can occur while trying to persist package metadata. {issue}18536[18536] {pull}18887[18887]
- system/socket: Fix bugs leading to wrong process being attributed to flows. {pull}29166[29166] {issue}17165[17165]
- system/socket: Fix process name and arg truncation for long names, paths and args lists. {issue}24667[24667] {pull}29410[29410]
- system/socket: Fix startup errors on newer 5.x kernels due to missing _do_fork function. {issue}29607[29607] {pull}29744[29744]
- libbeat/processors/add_process_metadata: Fix memory leak in process cache. {issue}24890[24890] {pull}29717[29717]

*Filebeat*

- Adding a fix for threatintel module where MISP was paginating forever. {pull}31784[31784]
- Fix handling and mapping of syslog priority, facility and severity values in Cisco module. {pull}32025[32025]
- Fix http_endpoint input TLS handshake failures. {pull}32105[32105]
- Fix using log_group_name_prefix in aws-cloudwatch input. {pull}29695[29695]
- Fix wrong state ID in states registry for awss3 s3 direct input. {pull}32164[32164]
- Fix Cisco AMP rate limit and pagination. {pull}32030[32030]
- Fix race conditions when reloading input V2 and filestream input {pull}32309[32309]
- Fix handling of Checkpoint event for R81. {issue}32380[32380] {pull}32458[32458]
- Fix MISP documentation for `var.filters` config option. {pull}31434[31434]

*Heartbeat*


*Metricbeat*

- Fix to ARN parsing for Cloudwatch resource names with leading slashes {pull}32445[32445]

*Packetbeat*


*Winlogbeat*



*Functionbeat*



*Elastic Logging Plugin*


==== Added

*Affecting all Beats*


*Auditbeat*


*Filebeat*

- Optimize grok patterns in system.auth module pipeline. {pull}32360[32360]

*Heartbeat*


*Metricbeat*


*Packetbeat*


*Functionbeat*


*Winlogbeat*



*Elastic Log Driver*


==== Deprecated

*Affecting all Beats*


*Filebeat*


*Heartbeat*

*Metricbeat*


*Packetbeat*

*Winlogbeat*

*Functionbeat*

==== Known Issue








