:modulename: iis

== IIS module

The +{modulename}+ module parses access and error logs created by the
Internet Information Services (IIS) HTTP server.

include::../include/what-happens.asciidoc[]

[float]
=== Compatibility

This module requires the
{elasticsearch-plugins}/ingest-user-agent.html[ingest-user-agent] and
{elasticsearch-plugins}/ingest-geoip.html[ingest-geoip] Elasticsearch plugins.

The IIS module was tested with logs from version 10.

Note: Running IIS on anything other than Windows is not supported.

include::../include/running-modules.asciidoc[]

include::../include/configuring-intro.asciidoc[]

The following example shows how to set paths in the +modules.d/{modulename}.yml+
file to override the default paths for access logs and error logs:

["source","yaml",subs="attributes"]
-----
- module: iis
  access:
    enabled: true
    var.paths: ["C:\inetpub\logs\LogFiles\*\*.log"]
-----

To specify the same settings at the command line, you use:

["source","sh",subs="attributes"]
-----
./{beatname_lc} -M "nginx.access.var.paths=[C:\inetpub\logs\LogFiles\*\*.log]"
-----

The command in the example assumes that you have already enabled the +{modulename}+ module. 

//set the fileset name used in the included example
:fileset_ex: access

include::../include/config-option-intro.asciidoc[]

[float]
==== `access` log fileset settings

include::../include/var-paths.asciidoc[]
