[[elastic-agent-configuration]]
[role="xpack"]
= Configuration settings

beta[]

// TODO: This topic assumes users know what standalone and fleet are. When we
// add the settings reference, we should clean this up: describe the available
// options, then show how to configure them manually for standalone. We should
// assume Fleet is the common use case, even if it's not the default, and make
// sure this reference is useful for both use cases.

By default {agent} runs in standalone mode to ingest system data and send it to
a local {es} instance running on port 9200. It uses the demo credentials of the
`elastic` user. It's also configured to monitor all programs managed by {agent}
and send the logs and metrics to the same {es} instance.

To alter this behavior, configure the output and other configuration settings.
When running the agent standalone, specify configuration settings in the
`elastic-agent.yml` file. When using {fleet}, do not modify settings in
the `elastic-agent.yml` file. Instead, use {ingest-manager} in {kib} to change
settings.

TIP: To get started quickly, you can use {fleet} to generate a standalone
configuration. For more information, see <<agent-standalone-mode>>.

[discrete]
[[elastic-agent-output-configuration]]
== Output settings

Specify one or more outputs. Specifying multiple outputs allows you to pair
each data source with a different output.

IMPORTANT: {agent} currently works with the {es} output only.

Example output configuration:

[source,yaml]
-------------------------------------------------------------------------------------
outputs:
  default:
    type: elasticsearch
    hosts: [127.0.0.1:9200]
    username: elastic
    password: changeme

  monitoring:
    type: elasticsearch
    api_key: VuaCfGcBCdbkQm-e5aOx:ui2lp2axTNmsyakw9tvNnw
    hosts: ["localhost:9200"]
    ca_sha256: "7lHLiyp4J8m9kw38SJ7SURJP4bXRZv/BNxyyXkCcE/M="
-------------------------------------------------------------------------------------

This example configures two outputs: `default` and  `monitoring`.
Notice that they use different authentication methods. The first one uses a
username and password pair, and the second one contains an API key.

[NOTE]
==============
A default output configuration is required.
==============

[discrete]
[[elastic-agent-monitoring-configuration]]
== {beats} monitoring settings

{agent} monitors {beats} by default. To disable or change monitoring
settings, set options under `agent.monitoring`:

[source,yaml]
-------------------------------------------------------------------------------------
agent.monitoring:
  # enabled turns on monitoring of running processes
  enabled: true
  # enables log monitoring
  logs: true
  # enables metrics monitoring
  metrics: true
  # specifies output to be used
  use_output: monitoring
-------------------------------------------------------------------------------------


To disable monitoring, set `agent.monitoring.enabled` to `false`. When set to
`false`, {beats} monitoring is turned off, and all other options in this section
are ignored.

To enable monitoring, set `agent.monitoring.enabled` to `true`. Also set the
`logs` and `metrics` settings to control whether logs, metrics, or both are
collected. If neither setting is specified, monitoring is disabled. Set
`use_output` to specify the output to which monitoring events are sent.

[discrete]
[[elastic-agent-input-configuration]]
== Input settings

By default {agent} collects system metrics, such as cpu, memory, network, and
filesystem metrics, and sends them to the default output. For example:


[source,yaml]
-------------------------------------------------------------------------------------
inputs:
  - type: system/metrics
    data_stream.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        data_stream.dataset: system.cpu
      - metricset: memory
        data_stream.dataset: system.memory
      - metricset: network
        data_stream.dataset: system.network
      - metricset: filesystem
        data_stream.dataset: system.filesystem
-------------------------------------------------------------------------------------

If `use_output` is not specified, the `default` output is used.

//For more examples, see
//<<elastic-agent-configuration-example,`elastic-agent_configuration_example.yml`>>.
