Stackdriver provides visibility into the performance, uptime, and overall health
of cloud-powered applications. It collects metrics, events, and metadata from
different services from Google Cloud. This metricset is to collect monitoring
metrics from Google Cloud using `ListTimeSeries` API. The full list of metric
types that Google Cloud monitoring supports can be found in
https://cloud.google.com/monitoring/api/metrics_gcp#gcp[Google Cloud Metrics].

Each monitoring metric from stackdriver has a sample period and/or ingest delay.
Sample period is the time interval between consecutive data points for metrics
that are written periodically. Ingest delay represents the time for data points
older than this value are guaranteed to be available to read. Sample period and
ingest delay are obtained from making
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/list[ListMetricDescriptors API]
call.

[float]
== Metricset config and parameters

* *metric_types*: Required, a list of metric type strings. Each call of the
`ListTimeSeries` API can return any number of time series from a single metric
type. Metric type is to used for identifying a specific time series.

* *aligner*: A single string with which aggregation operation need to be applied
onto time series data for ListTimeSeries API. If it's not given, default aligner
is set to be `ALIGN_NONE`. Google Cloud also supports `ALIGN_DELTA`, `ALIGN_RATE`,
`ALIGN_MIN`, `ALIGN_MAX`, `ALIGN_MEAN`, `ALIGN_COUNT`, `ALIGN_SUM` and etc.
Please see
https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.v3#aligner[Aggregation Aligner]
for the full list of aligners.


[float]
=== Example Configuration
* `stackdriver` metricset is enabled to collect metrics from all zones under
`europe-west1-c` region in `elastic-observability` project. Two sets of metrics
are specified: first one is to collect CPU usage time and utilization with
aggregation aligner ALIGN_MEAN; second one is to collect uptime with aggregation
aligner ALIGN_SUM. These metric types all have 240 seconds ingest delay time and
60 seconds sample period. With `period` specified as `300s` in the config below,
Metricbeat will collect compute metrics from googlecloud every 5-minute with
given aggregation aligner applied for each metric type.
+
[source,yaml]
----
- module: googlecloud
  metricsets:
    - stackdriver
  zone: "europe-west1-c"
  project_id: elastic-observability
  credentials_file_path: "your JSON credentials file path"
  exclude_labels: false
  period: 300s
  stackdriver:
    service: compute
    metrics:
      - aligner: ALIGN_MEAN
        metric_types:
          - "compute.googleapis.com/instance/cpu/usage_time"
          - "compute.googleapis.com/instance/cpu/utilization"
      - aligner: ALIGN_SUM
        metric_types:
          - "compute.googleapis.com/instance/uptime"

----

* `stackdriver` metricset is enabled to collect metrics from all zones under
`europe-west1-c` region in `elastic-observability` project. Two sets of metrics
are specified: first one is to collect CPU usage time and utilization with
aggregation aligner ALIGN_MEAN; second one is to collect uptime with aggregation
aligner ALIGN_SUM. These metric types all have 240 seconds ingest delay time and
60 seconds sample period. With `period` specified as `60s` in the config below,
Metricbeat will collect compute metrics from googlecloud every minute with no
aggregation. This case, the aligners specified in the configuration will be
ignored.
+
[source,yaml]
----
- module: googlecloud
  metricsets:
    - stackdriver
  zone: "europe-west1-c"
  project_id: elastic-observability
  credentials_file_path: "your JSON credentials file path"
  exclude_labels: false
  period: 60s
  stackdriver:
    service: compute
    metrics:
      - aligner: ALIGN_MEAN
        metric_types:
          - "compute.googleapis.com/instance/cpu/usage_time"
          - "compute.googleapis.com/instance/cpu/utilization"
      - aligner: ALIGN_SUM
        metric_types:
          - "compute.googleapis.com/instance/uptime"
----
