=== S3 and SQS Setup
Enable bucket notification: any new object creation in S3 bucket will also
create a notification through SQS. Please see
https://docs.aws.amazon.com/AmazonS3/latest/dev/ways-to-add-notification-config-to-bucket.html#step1-create-sqs-queue-for-notification[create-sqs-queue-for-notification]
for more details.
1. In SQS, edit policy document to create a new policy.
2. In S3 bucket, enable and configure event notification.
3. In order to make sure the S3-SQS setup is ready, upload a file into the S3
bucket and check if SQS gets a message showing that a new object is created with
its name.

=== Manual Testing
1. Upload fake log files into the S3 bucket that has SQS notification enabled.
2. Check from SQS if there are N messages received.
3. Start filebeat with `./filebeat -e` and check Kibana if there are events reported
with messages from the example logs. Depends on the number of log lines in each
fake log file, check if the number of events match the number of log lines total
from all log files.
4. Check SQS if messages are deleted successfully.
5. Interrupt the s3 input process by killing filebeat during processing new S3 logs,
check if messages in SQS are in flight instead of deleted.
