// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package sip

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("packetbeat", "sip", asset.ModuleFieldsPri, Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJys1V1vmzwUB/D7fIojrh8iQx9YQ9eq0rpJaNoWNdmuKk0unIBXsF0f0zXffnIaElonare83KBDzt+/OPEhhDtcZkBCjwCssA1mEMzyaTACKJEKI7QVSmYwy6chaSzEQhSADygtLAQ2JY1HsL7KRgAAIUjeYh/pXnapMYPKqK6vDD8/7GnR1qrclPvWO1z+VmZYf0a7GNwAB4VrvO+QLHx5mYePvNXuO+Zff+Tzjx7APDWGnRHHU3y/zncRSOisVhVerivjQrVZwlJ2Zg2XpJWx512pPSNZbjsKC1WiZ2yUrP4GSFpJQnBZ/62D4UXwxhszts+ia8PJ1/zDjq1BG4yXvOF8++xpFka1hyM+GdVCjbxEAw+86XauHtwEJLS+CeC9+x3d9WXExu4dXZxZXp3HJ+nJLJ/qOa8YiwIPa9Xh1Ll6E7SzvTNNWJIkLE7iy2gSj6P0dAuO0v9PJ704in1xwZsmFEc4nh9cUH71un2HgfD+CIAZ3r+6erRvSNyqcukZ1O0vLOyg/FT4+SbhvMZVKqgF2BpXxhaJeIVj8A+dKQ7cAtWZAiGfAi9Lg0TAZQlu4Ozch+0fZTWePE9J9jDPFZIVkrtbB6F6UCfFoxUtSi7Vs2fQYDzu4fStwAlcO2G/19ulkyiNJpM0TVmUvktSxtjoTwAAAP//t5juwA=="
}
