// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package http

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("packetbeat", "http", asset.ModuleFieldsPri, Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzUU7mO1EAQzf0VTxsz/gAHSCSITRDBSISrsrs8btZ90FVm8N+j9jGs7ZEQmmg76q7jvTpen/DKY4VONRaAWu25wtOX8/nbUwEYlibZqDb4Ctl4ksiNbW0D/sVe0VrujZQFlltVAMAJnhzfUPPRMXKFSwrDatlgP/s2JEf5AarDoNCOJ0Yk/jmwKMgbJJYYvHC5YLwlfUu85Nzsdzq5E3Os8R7HpkEmw0k2vhUn1D+40Z1rNr7MEa88XkMyu5BNpR93TuATHEU0wStZb/1lGlRDUYfEZiloqRltCm7yL72WB7TvnW26tQ1oWJFgJXO09jIkqnsu8dzewq5WuwlWyPEBcikhDwiUGDGxZKlYP+U4FqELf8iPEVfb96gZwpESKRvU4wGxCc6RlMWdNc9y+MeeD0H/v2hR0kFeYpdI9i1vKM+rbOcMzBn7wfNvcjH/tK9B8TkM3hTvXF/bf/n3PCSwA1oW3IMCO2DW401gfwIAAP//G5dzPQ=="
}
