////
This file is generated! See scripts/docs_collector.py
////

[[metricbeat-module-docker]]
== Docker module

This module fetches metrics from https://www.docker.com/[Docker] containers. The default metricsets are: `container`, `cpu`, `diskio`, `healthcheck`, `info`, `memory` and `network`. The `image` metricset is not enabled by default.

The Docker module is currently not tested on Windows.

[float]
=== Module-specific configuration notes

It is strongly recommended that you run Docker metricsets with a
<<metricset-period,`period`>> that is 3 seconds or longer. The request to the
Docker API already takes up to 2 seconds. Specifying less than 3 seconds will
result in requests that timeout, and no data will be reported for those
requests.


[float]
=== Example configuration

The Docker module supports the standard configuration options that are described
in <<configuration-metricbeat>>. Here is an example configuration:

[source,yaml]
----
metricbeat.modules:
- module: docker
  hosts: ["unix:///var/run/docker.sock"]

  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true
----

[float]
=== Metricsets

The following metricsets are available:

* <<metricbeat-metricset-docker-container,container>>

* <<metricbeat-metricset-docker-cpu,cpu>>

* <<metricbeat-metricset-docker-diskio,diskio>>

* <<metricbeat-metricset-docker-healthcheck,healthcheck>>

* <<metricbeat-metricset-docker-image,image>>

* <<metricbeat-metricset-docker-info,info>>

* <<metricbeat-metricset-docker-memory,memory>>

* <<metricbeat-metricset-docker-network,network>>

include::docker/container.asciidoc[]

include::docker/cpu.asciidoc[]

include::docker/diskio.asciidoc[]

include::docker/healthcheck.asciidoc[]

include::docker/image.asciidoc[]

include::docker/info.asciidoc[]

include::docker/memory.asciidoc[]

include::docker/network.asciidoc[]

