////
This file is generated! See scripts/mage/docs_collector.go
////

[[metricbeat-module-logstash]]
== Logstash module

There are two modules that collect metrics about {ls}:

* The `logstash` module tracks only the high-level metrics. The default metricsets in
this module are `node` and `node_stats`.
* The `logstash-xpack` module enables you to monitor more {ls} metrics with our
{stack} {monitor-features}. The metricsets automatically configured by this module
are `node` and `node_stats`.

[float]
=== Compatibility

Both modules work with {ls} 7.3.0 and later.


[float]
=== Example configuration

The Logstash module supports the standard configuration options that are described
in <<configuration-metricbeat>>. Here is an example configuration:

[source,yaml]
----
metricbeat.modules:
- module: logstash
  metricsets: ["node", "node_stats"]
  enabled: true
  period: 10s
  hosts: ["localhost:9600"]
----

This module supports TLS connections when using `ssl` config field, as described in <<configuration-ssl>>.
It also supports the options described in <<module-http-config-options>>.

[float]
=== Metricsets

The following metricsets are available:

* <<metricbeat-metricset-logstash-node,node>>

* <<metricbeat-metricset-logstash-node_stats,node_stats>>

include::logstash/node.asciidoc[]

include::logstash/node_stats.asciidoc[]

