////
This file is generated! See scripts/docs_collector.py
////

[[metricbeat-module-mongodb]]
== MongoDB Module

This module periodically fetches metrics from https://www.mongodb.com[MongoDB]
servers.

[float]
=== Module-Specific Configuration Notes

When configuring the `hosts` option, you must use MongoDB URLs of the following format:

-----------------------------------
[mongodb://host[:port][?options]
-----------------------------------

The URL can be as simple as:

[source,yaml]
----------------------------------------------------------------------
- module: mongodb
  hosts: ["localhost"]
----------------------------------------------------------------------

Or more complex like:

[source,yaml]
----------------------------------------------------------------------
- module: mongodb
  hosts: ["mongodb://myuser:mypass@localhost:40001", "otherhost:40001"]
----------------------------------------------------------------------

WARNING: In case you use username and password in the hosts array, this
information will be sent with each event as part of the `metricset.host` field.
To prevent sending username and password the config options `username` and
`password` can be used.

[source,yaml]
----
- module: mongodb
  metricsets: ["status"]
  hosts: ["localhost:27017"]
  username: root
  password: test
----



[float]
=== Compatibility

The MongoDB metricsets were tested with MongoDB 3.4 and 3.0 and are expected to work with all versions >= 2.8.


[float]
=== Example Configuration

The MongoDB module supports the standard configuration options that are described
in <<configuration-metricbeat>>. Here is an example configuration:

[source,yaml]
----
metricbeat.modules:
#- module: mongodb
  #metricsets: ["status"]
  #enabled: true
  #period: 10s

  # The hosts must be passed as MongoDB URLs in the format:
  # [mongodb://][user:pass@]host[:port].
  # Warning: specifying the user/password in the hosts array is possible
  # but it will result in the password being present in the output documents.
  # We recommend using the username and password options instead.
  #hosts: ["localhost:27017"]

  # Username to use when connecting to MongoDB. Empty by default.
  #username: user

  # Password to use when connecting to MongoDB. Empty by default.
  #password: pass

----

[float]
=== Metricsets

The following metricsets are available:

* <<metricbeat-metricset-mongodb-status,status>>

include::mongodb/status.asciidoc[]

