////
This file is generated! See scripts/mage/docs_collector.go
////

:modulename: openmetrics
:edit_url: https://github.com/elastic/beats/edit/main/metricbeat/module/openmetrics/_meta/docs.asciidoc


[[metricbeat-module-openmetrics]]
== Openmetrics module

beta[]

This module periodically fetches metrics from endpoints following https://openmetrics.io/[Openmetrics] format.

[float]
=== Filtering metrics

In order to filter out/in metrics one can make use of `metrics_filters.include` `metrics_filters.exclude` settings:

[source,yaml]
-------------------------------------------------------------------------------------
- module: openmetrics
  metricsets: ['collector']
  period: 10s
  hosts: ["localhost:9090"]
  metrics_path: /metrics
  metrics_filters:
    include: ["node_filesystem_*"]
    exclude: ["node_filesystem_device_*", "^node_filesystem_readonly$"]
-------------------------------------------------------------------------------------

The configuration above will include only metrics that match `node_filesystem_*` pattern and do not match `node_filesystem_device_*`
and are not `node_filesystem_readonly` metric.


:edit_url:

[float]
=== Example configuration

The Openmetrics module supports the standard configuration options that are described
in <<configuration-metricbeat>>. Here is an example configuration:

[source,yaml]
----
metricbeat.modules:
- module: openmetrics
  metricsets: ['collector']
  period: 10s
  hosts: ['localhost:9090']

  # This module uses the Prometheus collector metricset, all
  # the options for this metricset are also available here.
  metrics_path: /metrics
  metrics_filters:
    include: []
    exclude: []
----

This module supports TLS connections when using `ssl` config field, as described in <<configuration-ssl>>.
It also supports the options described in <<module-http-config-options>>.

[float]
=== Metricsets

The following metricsets are available:

* <<metricbeat-metricset-openmetrics-collector,collector>>

include::openmetrics/collector.asciidoc[]

:edit_url!:
