////
This file is generated! See scripts/mage/docs_collector.go
////

:modulename: php_fpm

[[metricbeat-module-php_fpm]]
== PHP_FPM module

This module periodically fetches metrics from https://php-fpm.org[PHP-FPM]
servers.

The default metricset is `pool`.

[float]
=== Module-specific configuration notes

You need to enable the PHP-FPM status page by properly configuring
`pm.status_path`.

Here is a sample nginx configuration to forward requests to the PHP-FPM status
page (assuming `pm.status_path` is configured with default value `/status`):

----
nginx
location ~ /status {
     allow 127.0.0.1;
     deny all;
     include fastcgi_params;
     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
     fastcgi_pass 127.0.0.1:9000;
}
----


[float]
=== Compatibility

The PHP_FPM metricsets were tested with PHP 7.1.1 and are expected to
work with all versions >= 5.


[float]
=== Example configuration

The PHP_FPM module supports the standard configuration options that are described
in <<configuration-metricbeat>>. Here is an example configuration:

[source,yaml]
----
metricbeat.modules:
- module: php_fpm
  metricsets:
  - pool
  #- process
  enabled: true
  period: 10s
  status_path: "/status"
  hosts: ["localhost:8080"]
----

This module supports TLS connections when using `ssl` config field, as described in <<configuration-ssl>>.
It also supports the options described in <<module-http-config-options>>.

[float]
=== Metricsets

The following metricsets are available:

* <<metricbeat-metricset-php_fpm-pool,pool>>

* <<metricbeat-metricset-php_fpm-process,process>>

include::php_fpm/pool.asciidoc[]

include::php_fpm/process.asciidoc[]

