////
This file is generated! See scripts/docs_collector.py
////

[[metricbeat-module-redis]]
== Redis Module

This module periodically fetches metrics from http://redis.io/[Redis] servers.

[float]
=== Configuration Options

Redis has two additional config options:

* `idle_timeout` - Close connections after remaining idle for this duration. If
  the value is zero, then idle connections are not closed. The default value
  is 2 times the module period to allow a connection to be reused across
  fetches. The `idle_timeout` should be set less than the server's connection
  timeout.
* `network` - Network type to be used for redis connection. The default value is
  `tcp`.
* `maxconn` - Maximum number of concurrent connections to Redis. The default value
  is 10.


[float]
=== Compatibility

The redis MetricSets were tested with redis 3.2 and are expected to work with all version
>= 3.0.


[float]
=== Example Configuration

The Redis Status module supports the standard configuration options which can be found
here (add link). Below is an example of a configuration option:

[source,yaml]
----
metricbeat.modules:
- module: redis
  metricsets: ["info"]
  enabled: true
  period: 10s

  # Redis hosts
  hosts: ["127.0.0.1:6379"]
----

[float]
=== MetricSets

The following MetricSets are available:

* <<metricbeat-metricset-redis-info,info>>

* <<metricbeat-metricset-redis-keyspace,keyspace>>

include::redis/info.asciidoc[]

include::redis/keyspace.asciidoc[]

