:modulename: tidb
:has-dashboards: false

== TiDB module

The +{modulename}+ module collects and parses the slow logs and other runtime logs
created by https://pingcap.com/products/tidb[TiDB].

include::../include/what-happens.asciidoc[]

include::../include/gs-link.asciidoc[]

[float]
=== Compatibility

The +{modulename}+ module is compatible with TiDB 4.0.x and newer.

The fields of the `slowlog` may change as the TiDB version changes. These changes may not be recorded in the documentation in time, but they do not affect daily ingesting and querying usage of `slowlog`.

[float]
=== Get started

include::../include/configuring-intro.asciidoc[]

There are two places of filebeat config files, which you can edit to enable TiDB module:

* In the +modules.d/{modulename}.yml+ file:

["source","yaml",subs="attributes"]
-----
- module: tidb
  slowlog:
    enabled: true
  tidb:
    enabled: true
  pd:
    enabled: true
  tikv:
    enabled: true
  tiflash:
    enabled: true
  binlog:
    enabled: true
  ticdc:
    enabled: true
  tispark:
    enabled: true
-----

* In the +filebeat.yml+ file

["source","yaml",subs="attributes"]
-----
filebeat.modules:
- module: tidb
  slowlog:
    enabled: true
  tidb:
    enabled: true
  pd:
    enabled: true
  tikv:
    enabled: true
  tiflash:
    enabled: true
  binlog:
    enabled: true
  ticdc:
    enabled: true
  tispark:
    enabled: true
-----

To specify the same settings at the command line, you use:

["source","sh",subs="attributes"]

-----
-M "tidb.pd.enabled=true" -M "tidb.slowlog.enabled=true"
-----

:fileset_ex: slowlog

[float]
=== Override default settings

[float]
====  Deployment environment of the TiDB cluster

The TiDB module assume TiDB cluster is deployed by TiUP. If you deploy the cluster in Kubernetes with TiDB operator, override the default environment:

["source","yaml",subs="attributes"]
-----
filebeat.modules:
- module: tidb
  slowlog:
    enabled: true
    var:
      deployment: container
  tidb:
    enabled: true
    var:
      deployment: container
  pd:
    enabled: true
    var:
      deployment: container
  tikv:
    enabled: true
    var:
      deployment: container
  tiflash:
    enabled: true
    var:
      deployment: container
  binlog:
    enabled: true
    var:
      deployment: container
  ticdc:
    enabled: true
    var:
      deployment: container
  tispark:
    enabled: true
    var:
      deployment: container
-----

[float]
==== Paths and files

The TiDB module come with two types of default paths:

* Log Paths generated by TiUP.
* Log Paths defined by TiDB operator, in the Kubernetes environment.

The module also defines a default regex rule to exclude log files.

The following example shows how to override those default paths and default excluded files:
["source","yaml",subs="attributes"]
-----
filebeat.modules:
- module: tidb
  slowlog:
    enabled: true
    var:
      paths: ["/tidb-deploy/tidb-4000/log/*slowlog*.log"]
      exclude_files: [".gz$"]
  tidb:
    enabled: true
    var:
      paths: ["/tidb-deploy/tidb-4000/log/*.log"]
      exclude_files: [".gz$", ".*slowlog.*\.log$"]
  pd:
    enabled: true
    var:
      paths: ["/tidb-deploy/pd-2379/log/*.log"]
      exclude_files: [".gz$"]
  tikv:
    enabled: true
    var:
      paths: ["/tidb-deploy/tikv-20160/log/*.log"]
      exclude_files: [".gz$"]
  tiflash:
    enabled: true
    var:
      paths: ["/tidb-deploy/tiflash-9000/log/*.log"]
      exclude_files: [".gz$"]
  binlog:
    enabled: true
    var:
      paths: ["/tidb-deploy/pump-8250/log/*.log","/tidb-deploy/drainer-8249/log/*.log"]
      exclude_files: [".gz$"]
  ticdc:
    enabled: true
    var:
      paths: ["/tidb-deploy/cdc-8300/log/*.log"]
      exclude_files: [".gz$"]
  tispark:
    enabled: true
    var:
      paths: ["/tidb-deploy/tispark-master-7077/log/*.log","/tidb-deploy/tispark-worker-7078/log/*.log"]
      exclude_files: [".gz$"]
-----

include::../include/config-option-intro.asciidoc[]

*`var.paths`*::

An array of glob-based paths that specify where to look for the log files. All
patterns supported by https://golang.org/pkg/path/filepath/#Glob[Go Glob]
are also supported here. For example, you can use wildcards to fetch all files
from a predefined level of subdirectories: `/path/to/log/*/*.log`. This
fetches all `.log` files from the subfolders of `/path/to/log`. It does not
fetch log files from the `/path/to/log` folder itself. If this setting is left
empty, {beatname_uc} will choose log paths based on your operating system.

*`var.exclude_files`*::

A list of regular expressions to match the files that you want Filebeat to ignore. By default no files are excluded.
See <<regexp-support>> support for a list of supported regexp patterns.

*`var.deployment`*::

Deployment environment of your TiDB cluster. This value is an enum of two values:

* `log` means the cluster is deployed by TiUP on bare-metal.
* `container` means the cluster is deployed by TiDB operator on Kubernetes.

:has-dashboards!:

:fileset_ex!:

:modulename!:
