:modulename: tidb
:has-dashboards: false

== TiDB module

The +{modulename}+ module collects and parses the slow logs and other runtime logs
created by https://pingcap.com/products/tidb[TiDB].

include::../include/what-happens.asciidoc[]

include::../include/gs-link.asciidoc[]

[float]
=== Compatibility

The +{modulename}+ module is compatible with TiDB 4.0.x and newer.

The fields of the `slowlog` may change as the TiDB version changes. These changes may not be recorded in the documentation in time, but they do not affect daily ingesting and querying usage of `slowlog`.

[float]
=== Get started

include::../include/configuring-intro.asciidoc[]

There are two places of filebeat config files, which you can edit to enable TiDB module:

* In the +modules.d/{modulename}.yml+ file:

["source","yaml",subs="attributes"]
-----
- module: tidb
  slowlog:
    enabled: true
  log:
    enabled: true
    input:
      exclude_files:
        - '.*slowlog.*\.log$'
-----

* In the +filebeat.yml+ file

["source","yaml",subs="attributes"]
-----
filebeat.modules:
- module: tidb
  slowlog:
    enabled: true
  log:
    enabled: true
    input:
      exclude_files:
        - '.*slowlog.*\.log$'
-----

To specify the same settings at the command line, you use:

["source","sh",subs="attributes"]
-----
-M "tidb.pd.enabled=true" -M "tidb.slowlog.enabled=true"
-----

:fileset_ex: slowlog

[float]
=== Override default settings

[float]
====  Deployment environment of the TiDB cluster

The TiDB module assume TiDB cluster is deployed by TiUP. If you deploy the cluster in Kubernetes with TiDB operator, override the default environment:

["source","yaml",subs="attributes"]
-----
filebeat.modules:
- module: tidb
  slowlog:
    enabled: true
    var:
      deployment: container
  log:
    enabled: true
    var:
      deployment: container
    input:
      exclude_files:
        - '.*slowlog.*\.log$'
-----

[float]
==== Paths and files

The TiDB module come with two types of default paths:

* Log Paths generated by TiUP.
* Log Paths defined by TiDB operator, in the Kubernetes environment.

The following example shows how to override those default paths and default excluded files:

["source","yaml",subs="attributes"]
-----
filebeat.modules:
- module: tidb
  slowlog:
    enabled: true
    var:
      paths: ["/tidb-deploy/tidb-4000/log/*slowlog*.log"]
  log:
    enabled: true
    var:
      paths: ["/tidb-deploy/tidb-4000/log/*.log"]
    input:
      exclude_files:
        - '.*slowlog.*\.log$'
-----

include::../include/config-option-intro.asciidoc[]

*`var.paths`*::

An array of glob-based paths that specify where to look for the log files. All
patterns supported by https://golang.org/pkg/path/filepath/#Glob[Go Glob]
are also supported here. For example, you can use wildcards to fetch all files
from a predefined level of subdirectories: `/path/to/log/*/*.log`. This
fetches all `.log` files from the subfolders of `/path/to/log`. It does not
fetch log files from the `/path/to/log` folder itself. If this setting is left
empty, {beatname_uc} will choose log paths based on your operating system.

*`var.deployment`*::

Deployment environment of your TiDB cluster. This value is an enum of two values:

* `log` means the cluster is deployed by TiUP on bare-metal.
* `container` means the cluster is deployed by TiDB operator on Kubernetes.

:has-dashboards!:

:fileset_ex!:

:modulename!:
