// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nginx

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "nginx", asset.ModuleFieldsPri, AssetNginx); err != nil {
		panic(err)
	}
}

// AssetNginx returns asset data.
// This is the base64 encoded zlib format compressed contents of module/nginx.
func AssetNginx() string {
	return "eJzsWU1v2zgTvudXDPpe3gVi/QAfFli0KDaHXRRFD725NDmWBqU46pBK1v9+QX3Yjj5sSU6yLWCdEsmc55lnhsMhuYLvuF+DS8n9cwcQKFhcw7u/4//v7gAMei1UBGK3ht/vAAD+YlNahB0LFEo8uRRChlANAcsp7MiiT+4AfMYSNprdjtI1BCnxDmBHaI1fV6ZW4FSOR/j4hH2Ba0iFy6J5M8AhPh8rQ7ATzscIxOcU7xRTaY3eH14PAZ8Bj897dkGR8w1EpciRSG0/8jlQGaJzSkkw54AbKjaWfHj2k5aeElH7zpczFOPzh6tHAe8aBHj4BMoYQe/RJ/AQgDwoiKCwRa1Kj0DVS815zg4CAzltS4P3sEVPBn3lqbaErksUTszfP4OqY5WhMigeLH1H+PZ19ZHlSYlBE//6lvSsfUZlwXMpuiJOHgR9YEETeX2rvyRUnAwdVHfLZr/x6EKy3Qf0w/JaUt0vhQrZGrIQikTQF+w8JtHWoJmcUlF1JJp87xMpPcom/jmTQhyXDIybgpljyNgs8/lHiT4kgxYmuSt2rqNiExZKyanu0CmAkfbmEcUTuyUeDw+dgtzmx0azmRvd5wnmgwqlH7IzjccORVCuifeIjSnwKu1XhSnJvakGzg39+Bwb59Gt8jBSmU9NGnwk3Y3GedcG3avtDE3kc1522YwMn8nlShI8BDKTAvtkV1o7VBDnURmzMJ/PtVSG83cJl3FLs2ZDikzddF8+ETS7QA5duEbxZtlOkZOL9qYKr7l0QfYb8jxUORdRu2hxKjnLuvrZ9aTOWJpKRjAldi8Uv/PGJgePwv6lEuqMqZkKvVwqXTY4Rq2lhCIsr7dhqczP2q9odg51qNwa7i0tu3TebuX9wSaQQRdoRygXOnuLjzi3x7ScJkPjpvQ3xYi342iFcNwNJv2RU/DCYryQCSqTLELN0XuVzm1jh0ddSm1yadwibuJSIGwtvkqeP9QoTb4fsW579Z9lr/6/NhNWJ9HxBWrakW7iMdzvFz4IqnzTODAele+4f2LpTogZcYlitnAzQ5OpAB4fUZQ9mvAoccfZw3xCwSpJlQ5owJRCLoVme9bOcHJpclaQ45bSoktD9orCHDxqIaGG/AW0CZTjmypjyroe/gLanBxFvKlENS5E3J9OpWcnJSOr8zJJoHT0o8ST5qdavlDpDP788uXTgWJg0CyCVgWsVi7YYnhCdE2l96Ccad0HchBEOa90nXU94C9ZxIRc7WHbCEMOTRyowLFb+aCcUWJqFvXCcA++1BkoD19Xn2teq4cPwAJfV+8bcsRu9fBhgox1sZjaRu5YchXWMHQIe0Hj6GqrYg0K/6+XzNMUsOTw/uBn1LL9smWz/+2yP7GmDHpjuNza7qfWn7YwzHSJcgS0qvBowJPTWC1TO5LIN0pUJ3zsBo83JgMtQa8MjJ5TL0rvKH202F1HL9QiZQOKU4Eecfzg/EUInSBNJddZYN8ogZvEbWgfiiZvm3l7CHKnEibwsDtUybY6TCqG9z0e0bwv81zJoTHKSxuosNjrAWKhrjvBOWvym82fDCHixV7TBWAHghrpsb3cPHjTl1V58KjZGQ9PFDLIyVqq38RhbMsI2i+4i8MwTfbozQLRx+8dlm7oo7QnS/lrZmwPuycdO7uv9TvD6EDEKh9zAY8yVutoRs3O8oKoI0euvdcTBDzuzHo7kJef1geRrvS/YBluFpclUTT383v/ap1h1bUoZzi3e0jRoajoVmy32vytQM8fld0uwW+X4LdL8Nsl+O0S/HYJfp7P7RL8dgl+uwS/XYL/x5fg/wYAAP//sBgP5g=="
}
