[role="xpack"]

:type: entity-analytics

[id="{beatname_lc}-input-{type}"]
=== Entity Analytics Input

++++
<titleabbrev>Entity Analytics</titleabbrev>
++++

experimental[]

The Entity Analytics input collects identity assets, such as users, from
external identity providers.

The following identity providers are supported:

- <<provider-azure-ad>>

==== Configuration options

The `entity-analytics` input supports the following configuration options plus
the <<{beatname_lc}-input-{type}-common-options>> described later.

[float]
==== `provider`

The identity provider. Must be one of: `azure-ad`.

[id="{beatname_lc}-input-{type}-common-options"]
include::../../../../filebeat/docs/inputs/input-common-options.asciidoc[]

[float]
=== Providers

[id="provider-azure-ad"]
==== Azure Active Directory (`azure-ad`)

The `azure-ad` provider allows the input to retrieve users, with group
memberships, from Azure Active Directory (AD).

[float]
==== Setup

The necessary API permissions need to be granted in Azure in order for the
provider to function properly:

|===
|Permission |Type

|GroupMember.Read.All
|Application

|User.Read.All
|Application
|===

For a full guide on how to set up the necessary App Registration, permission
granting, and secret configuration, follow this https://learn.microsoft.com/en-us/graph/auth-v2-service[guide].

[float]
==== How It Works

[float]
===== Overview

The Azure AD provider periodically contacts Azure Active Directory, retrieving
updates for users and groups, updates its internal cache of user metadata and
group membership information, and ships updated user metadata to Elasticsearch.

Fetching and shipping updates occurs in one of two processes: **full
synchronizations** and *incremental updates*. Full synchronizations will send the
entire list of users in state, along with write markers to indicate the start
and end of the synchronization event. Incremental updates will only send data
for changed users during that event. Changes on a user can come in many forms,
whether it be a change to the user's metadata, a user was added or deleted, or
group membership was changed (either direct or transitive).

[float]
===== API Interactions

The provider periodically retrieves changes to user and group metadata from the
Microsoft Graph API for Azure Active Directory. This is done through calls to
two API endpoints:

- https://learn.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=http[/users/delta]
- https://learn.microsoft.com/en-us/graph/api/group-delta?view=graph-rest-1.0&tabs=http[/groups/delta]

The `/delta` endpoint will provide changes that have occurred since the last
call, with state being tracked through a delta token. If the /delta endpoint is
called without a delta token, it will provide a full listing of users or groups,
similar to the non-delta endpoint. Since many results may be returned, there is
a paging mechanism that is used. In the response body, there are two fields that
may appear, `@odata.nextLink` and `@odata.deltaLink`.

- If a `@odata.nextLink` is returned, then there are more results to fetch, and
the value of this field will contain the URL which should be immediately fetched.
- If a `@odata.deltaLink` is returned, then there are currently no more results,
and the value of this field (a URL) should be saved for the next time updates
need to be fetched (the delta token).

The group metadata will be used to enrich users with group membership information.
Direct memberships, along with transitive memberships, will provided on users.

[float]
===== Sending User Metadata to Elasticsearch

During a full synchronization, all users stored in state will be sent to the
output, while incremental updates will only send users which have been updated.
Full synchronizations will be bounded on either side by write marker documents,
which will look something like this:

["source","json",subs="attributes"]
----
{
    "@timestamp": "2022-11-04T09:57:19.786056-05:00",
    "event": {
        "action": "started",
        "start": "2022-11-04T09:57:19.786056-05:00"
    },
    "labels": {
        "identity_source": "azure-1"
    }
}
----

User documents will show the current state of the user.

Example user document:

["source","json",subs="attributes"]
----
{
    "@timestamp": "2022-11-04T09:57:19.786056-05:00",
    "event": {
        "action": "user-discovered",
    },
    "azure_ad": {
        "userPrincipalName": "example.user@example.com",
        "mail": "example.user@example.com",
        "displayName": "Example User",
        "givenName": "Example",
        "surname": "User",
        "jobTitle": "Software Engineer",
        "mobilePhone": "123-555-1000",
        "businessPhones": ["123-555-0122"]
    },
    "user": {
        "id": "5ebc6a0f-05b7-4f42-9c8a-682bbc75d0fc",
        "group": [
            {
                "id": "331676df-b8fd-4492-82ed-02b927f8dd80",
                "name": "group1"
            },
            {
                "id": "d140978f-d641-4f01-802f-4ecc1acf8935",
                "name": "group2"
            }
        ]
    },
    "labels": {
        "identity_source": "azure-1"
    }
}
----

[float]
==== Configuration

Example configuration:

["source","yaml",subs="attributes"]
----
{beatname_lc}.inputs:
- type: entity-analytics
  enabled: true
  id: azure-1
  provider: azure-ad
  sync_interval: "12h"
  update_interval: "30m"
  client_id: "CLIENT_ID"
  tenant_id: "TENANT_ID"
  secret: "SECRET"
----

The `azure-ad` provider supports the following configuration:

[float]
===== `tenant_id`

The Tenant ID. Field is required.

[float]
===== `client_id`

The client/application ID. Used for authentication. Field is required.

[float]
===== `secret`

The secret value, used for authentication. Field is required.

[float]
===== `sync_interval`

The interval in which full synchronizations should occur. The interval must be
longer than the update interval (`update_interval`) Expressed as a duration
string (e.g., 1m, 3h, 24h). Defaults to `24h` (24 hours).

[float]
===== `update_interval`

The interval in which incremental updates should occur. The interval must be
shorter than the full synchronization interval (`sync_interval`). Expressed as a
duration string (e.g., 1m, 3h, 24h). Defaults to `15m` (15 minutes).

[float]
===== `login_endpoint`

Override the default authentication login endpoint. Only change if directed to do
so. Altering this value will also require a change to `login_scopes`.

[float]
===== `login_scopes`

Override the default authentication scopes. Only change if directed to do so.

[float]
==== Metrics

This input exposes metrics under the <<http-endpoint, HTTP monitoring endpoint>>.
These metrics are exposed under the `/inputs` path. They can be used to
observe the activity of the input.

[options="header"]
|=======
| Metric                   | Description
| `sync_total`             | The total number of full synchronizations.
| `sync_error`             | The number of full synchronizations that failed due to an error.
| `sync_processing_time`   | Histogram of the elapsed full synchronizations times in nanoseconds (time of API contact to items sent to output).
| `update_total`           | The total number of incremental updates.
| `update_error`           | The number of incremental updates that failed due to an error.
| `update_processing_time` | Histogram of the elapsed incremental updates times in nanoseconds (time of API contact to items sent to output).
|=======

NOTE: This input is experimental and is under active developement. Configuration
options and behaviors may change without warning. Use with caution and do not use
in production environments.

:type!:
