
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported fields

[partintro]

--
This document describes the fields that are exported by Packetbeat. They are
grouped in the following categories:

* <<exported-fields-amqp>>
* <<exported-fields-beat>>
* <<exported-fields-cassandra>>
* <<exported-fields-cloud>>
* <<exported-fields-common>>
* <<exported-fields-dhcpv4>>
* <<exported-fields-dns>>
* <<exported-fields-docker-processor>>
* <<exported-fields-ecs>>
* <<exported-fields-flows_event>>
* <<exported-fields-host-processor>>
* <<exported-fields-http>>
* <<exported-fields-icmp>>
* <<exported-fields-jolokia-autodiscover>>
* <<exported-fields-kubernetes-processor>>
* <<exported-fields-memcache>>
* <<exported-fields-mongodb>>
* <<exported-fields-mysql>>
* <<exported-fields-nfs>>
* <<exported-fields-pgsql>>
* <<exported-fields-process>>
* <<exported-fields-raw>>
* <<exported-fields-redis>>
* <<exported-fields-thrift>>
* <<exported-fields-tls>>
* <<exported-fields-trans_event>>
* <<exported-fields-trans_measurements>>

--
[[exported-fields-amqp]]
== AMQP fields

AMQP specific event fields.



*`amqp.reply-code`*::
+
--
type: long

example: 404

AMQP reply code to an error, similar to http reply-code


--

*`amqp.reply-text`*::
+
--
type: keyword

Text explaining the error.


--

*`amqp.class-id`*::
+
--
type: long

Failing method class.


--

*`amqp.method-id`*::
+
--
type: long

Failing method ID.


--

*`amqp.exchange`*::
+
--
type: keyword

Name of the exchange.


--

*`amqp.exchange-type`*::
+
--
type: keyword

example: fanout

Exchange type.


--

*`amqp.passive`*::
+
--
type: boolean

If set, do not create exchange/queue.


--

*`amqp.durable`*::
+
--
type: boolean

If set, request a durable exchange/queue.


--

*`amqp.exclusive`*::
+
--
type: boolean

If set, request an exclusive queue.


--

*`amqp.auto-delete`*::
+
--
type: boolean

If set, auto-delete queue when unused.


--

*`amqp.no-wait`*::
+
--
type: boolean

If set, the server will not respond to the method.


--

*`amqp.consumer-tag`*::
+
--
Identifier for the consumer, valid within the current channel.


--

*`amqp.delivery-tag`*::
+
--
type: long

The server-assigned and channel-specific delivery tag.


--

*`amqp.message-count`*::
+
--
type: long

The number of messages in the queue, which will be zero for newly-declared queues.


--

*`amqp.consumer-count`*::
+
--
type: long

The number of consumers of a queue.


--

*`amqp.routing-key`*::
+
--
type: keyword

Message routing key.


--

*`amqp.no-ack`*::
+
--
type: boolean

If set, the server does not expect acknowledgements for messages.


--

*`amqp.no-local`*::
+
--
type: boolean

If set, the server will not send messages to the connection that published them.


--

*`amqp.if-unused`*::
+
--
type: boolean

Delete only if unused.


--

*`amqp.if-empty`*::
+
--
type: boolean

Delete only if empty.


--

*`amqp.queue`*::
+
--
type: keyword

The queue name identifies the queue within the vhost.


--

*`amqp.redelivered`*::
+
--
type: boolean

Indicates that the message has been previously delivered to this or another client.


--

*`amqp.multiple`*::
+
--
type: boolean

Acknowledge multiple messages.


--

*`amqp.arguments`*::
+
--
type: object

Optional additional arguments passed to some methods. Can be of various types.


--

*`amqp.mandatory`*::
+
--
type: boolean

Indicates mandatory routing.


--

*`amqp.immediate`*::
+
--
type: boolean

Request immediate delivery.


--

*`amqp.content-type`*::
+
--
type: keyword

example: text/plain

MIME content type.


--

*`amqp.content-encoding`*::
+
--
type: keyword

MIME content encoding.


--

*`amqp.headers`*::
+
--
type: object

Message header field table.


--

*`amqp.delivery-mode`*::
+
--
type: keyword

Non-persistent (1) or persistent (2).


--

*`amqp.priority`*::
+
--
type: long

Message priority, 0 to 9.


--

*`amqp.correlation-id`*::
+
--
type: keyword

Application correlation identifier.


--

*`amqp.reply-to`*::
+
--
type: keyword

Address to reply to.


--

*`amqp.expiration`*::
+
--
type: keyword

Message expiration specification.


--

*`amqp.message-id`*::
+
--
type: keyword

Application message identifier.


--

*`amqp.timestamp`*::
+
--
type: keyword

Message timestamp.


--

*`amqp.type`*::
+
--
type: keyword

Message type name.


--

*`amqp.user-id`*::
+
--
type: keyword

Creating user id.


--

*`amqp.app-id`*::
+
--
type: keyword

Creating application id.


--

[[exported-fields-beat]]
== Beat fields

Contains common beat fields available in all event types.



*`agent.hostname`*::
+
--
type: keyword

Hostname of the agent.

--

*`beat.timezone`*::
+
--
type: alias

alias to: event.timezone

--

*`fields`*::
+
--
type: object

Contains user configurable fields.


--

[float]
== error fields

Error fields containing additional info in case of errors.



*`error.type`*::
+
--
type: keyword

Error type.


--

*`beat.name`*::
+
--
type: alias

alias to: host.name

--

*`beat.hostname`*::
+
--
type: alias

alias to: agent.hostname

--

[[exported-fields-cassandra]]
== Cassandra fields

Cassandra v4/3 specific event fields.


*`no_request`*::
+
--
type: alias

alias to: cassandra.no_request

--

[float]
== cassandra fields

Information about the Cassandra request and response.


*`cassandra.no_request`*::
+
--
type: boolean

Indicates that there is no request because this is a PUSH message.


--

[float]
== request fields

Cassandra request.


[float]
== headers fields

Cassandra request headers.


*`cassandra.request.headers.version`*::
+
--
type: long

The version of the protocol.

--

*`cassandra.request.headers.flags`*::
+
--
type: keyword

Flags applying to this frame.

--

*`cassandra.request.headers.stream`*::
+
--
type: keyword

A frame has a stream id.  If a client sends a request message with the stream id X, it is guaranteed that the stream id of the response to that message will be X.

--

*`cassandra.request.headers.op`*::
+
--
type: keyword

An operation type that distinguishes the actual message.

--

*`cassandra.request.headers.length`*::
+
--
type: long

A integer representing the length of the body of the frame (a frame is limited to 256MB in length).

--

*`cassandra.request.query`*::
+
--
type: keyword

The CQL query which client send to cassandra.

--

[float]
== response fields

Cassandra response.


[float]
== headers fields

Cassandra response headers, the structure is as same as request's header.


*`cassandra.response.headers.version`*::
+
--
type: long

The version of the protocol.

--

*`cassandra.response.headers.flags`*::
+
--
type: keyword

Flags applying to this frame.

--

*`cassandra.response.headers.stream`*::
+
--
type: keyword

A frame has a stream id.  If a client sends a request message with the stream id X, it is guaranteed that the stream id of the response to that message will be X.

--

*`cassandra.response.headers.op`*::
+
--
type: keyword

An operation type that distinguishes the actual message.

--

*`cassandra.response.headers.length`*::
+
--
type: long

A integer representing the length of the body of the frame (a frame is limited to 256MB in length).

--

[float]
== result fields

Details about the returned result.


*`cassandra.response.result.type`*::
+
--
type: keyword

Cassandra result type.

--

[float]
== rows fields

Details about the rows.


*`cassandra.response.result.rows.num_rows`*::
+
--
type: long

Representing the number of rows present in this result.

--

[float]
== meta fields

Composed of result metadata.


*`cassandra.response.result.rows.meta.keyspace`*::
+
--
type: keyword

Only present after set Global_tables_spec, the keyspace name.

--

*`cassandra.response.result.rows.meta.table`*::
+
--
type: keyword

Only present after set Global_tables_spec, the table name.

--

*`cassandra.response.result.rows.meta.flags`*::
+
--
type: keyword

Provides information on the formatting of the remaining information.

--

*`cassandra.response.result.rows.meta.col_count`*::
+
--
type: long

Representing the number of columns selected by the query that produced this result.

--

*`cassandra.response.result.rows.meta.pkey_columns`*::
+
--
type: long

Representing the PK columns index and counts.

--

*`cassandra.response.result.rows.meta.paging_state`*::
+
--
type: keyword

The paging_state is a bytes value that should be used in QUERY/EXECUTE to continue paging and retrieve the remainder of the result for this query.

--

*`cassandra.response.result.keyspace`*::
+
--
type: keyword

Indicating the name of the keyspace that has been set.

--

[float]
== schema_change fields

The result to a schema_change message.


*`cassandra.response.result.schema_change.change`*::
+
--
type: keyword

Representing the type of changed involved.

--

*`cassandra.response.result.schema_change.keyspace`*::
+
--
type: keyword

This describes which keyspace has changed.

--

*`cassandra.response.result.schema_change.table`*::
+
--
type: keyword

This describes which table has changed.

--

*`cassandra.response.result.schema_change.object`*::
+
--
type: keyword

This describes the name of said affected object (either the table, user type, function, or aggregate name).

--

*`cassandra.response.result.schema_change.target`*::
+
--
type: keyword

Target could be "FUNCTION" or "AGGREGATE", multiple arguments.

--

*`cassandra.response.result.schema_change.name`*::
+
--
type: keyword

The function/aggregate name.

--

*`cassandra.response.result.schema_change.args`*::
+
--
type: keyword

One string for each argument type (as CQL type).

--

[float]
== prepared fields

The result to a PREPARE message.


*`cassandra.response.result.prepared.prepared_id`*::
+
--
type: keyword

Representing the prepared query ID.

--

[float]
== req_meta fields

This describes the request metadata.


*`cassandra.response.result.prepared.req_meta.keyspace`*::
+
--
type: keyword

Only present after set Global_tables_spec, the keyspace name.

--

*`cassandra.response.result.prepared.req_meta.table`*::
+
--
type: keyword

Only present after set Global_tables_spec, the table name.

--

*`cassandra.response.result.prepared.req_meta.flags`*::
+
--
type: keyword

Provides information on the formatting of the remaining information.

--

*`cassandra.response.result.prepared.req_meta.col_count`*::
+
--
type: long

Representing the number of columns selected by the query that produced this result.

--

*`cassandra.response.result.prepared.req_meta.pkey_columns`*::
+
--
type: long

Representing the PK columns index and counts.

--

*`cassandra.response.result.prepared.req_meta.paging_state`*::
+
--
type: keyword

The paging_state is a bytes value that should be used in QUERY/EXECUTE to continue paging and retrieve the remainder of the result for this query.

--

[float]
== resp_meta fields

This describes the metadata for the result set.


*`cassandra.response.result.prepared.resp_meta.keyspace`*::
+
--
type: keyword

Only present after set Global_tables_spec, the keyspace name.

--

*`cassandra.response.result.prepared.resp_meta.table`*::
+
--
type: keyword

Only present after set Global_tables_spec, the table name.

--

*`cassandra.response.result.prepared.resp_meta.flags`*::
+
--
type: keyword

Provides information on the formatting of the remaining information.

--

*`cassandra.response.result.prepared.resp_meta.col_count`*::
+
--
type: long

Representing the number of columns selected by the query that produced this result.

--

*`cassandra.response.result.prepared.resp_meta.pkey_columns`*::
+
--
type: long

Representing the PK columns index and counts.

--

*`cassandra.response.result.prepared.resp_meta.paging_state`*::
+
--
type: keyword

The paging_state is a bytes value that should be used in QUERY/EXECUTE to continue paging and retrieve the remainder of the result for this query.

--

*`cassandra.response.supported`*::
+
--
type: object

Indicates which startup options are supported by the server. This message comes as a response to an OPTIONS message.

--

[float]
== authentication fields

Indicates that the server requires authentication, and which authentication mechanism to use.


*`cassandra.response.authentication.class`*::
+
--
type: keyword

Indicates the full class name of the IAuthenticator in use

--

*`cassandra.response.warnings`*::
+
--
type: keyword

The text of the warnings, only occur when Warning flag was set.

--

[float]
== event fields

Event pushed by the server. A client will only receive events for the types it has REGISTERed to.


*`cassandra.response.event.type`*::
+
--
type: keyword

Representing the event type.

--

*`cassandra.response.event.change`*::
+
--
type: keyword

The message corresponding respectively to the type of change followed by the address of the new/removed node.

--

*`cassandra.response.event.host`*::
+
--
type: keyword

Representing the node ip.

--

*`cassandra.response.event.port`*::
+
--
type: long

Representing the node port.

--

[float]
== schema_change fields

The events details related to schema change.


*`cassandra.response.event.schema_change.change`*::
+
--
type: keyword

Representing the type of changed involved.

--

*`cassandra.response.event.schema_change.keyspace`*::
+
--
type: keyword

This describes which keyspace has changed.

--

*`cassandra.response.event.schema_change.table`*::
+
--
type: keyword

This describes which table has changed.

--

*`cassandra.response.event.schema_change.object`*::
+
--
type: keyword

This describes the name of said affected object (either the table, user type, function, or aggregate name).

--

*`cassandra.response.event.schema_change.target`*::
+
--
type: keyword

Target could be "FUNCTION" or "AGGREGATE", multiple arguments.

--

*`cassandra.response.event.schema_change.name`*::
+
--
type: keyword

The function/aggregate name.

--

*`cassandra.response.event.schema_change.args`*::
+
--
type: keyword

One string for each argument type (as CQL type).

--

[float]
== error fields

Indicates an error processing a request. The body of the message will be an  error code followed by a error message. Then, depending on the exception, more content may follow.


*`cassandra.response.error.code`*::
+
--
type: long

The error code of the Cassandra response.

--

*`cassandra.response.error.msg`*::
+
--
type: keyword

The error message of the Cassandra response.

--

*`cassandra.response.error.type`*::
+
--
type: keyword

The error type of the Cassandra response.

--

[float]
== details fields

The details of the error.


*`cassandra.response.error.details.read_consistency`*::
+
--
type: keyword

Representing the consistency level of the query that triggered the exception.

--

*`cassandra.response.error.details.required`*::
+
--
type: long

Representing the number of nodes that should be alive to respect consistency level.

--

*`cassandra.response.error.details.alive`*::
+
--
type: long

Representing the number of replicas that were known to be alive when the request had been processed (since an unavailable exception has been triggered).

--

*`cassandra.response.error.details.received`*::
+
--
type: long

Representing the number of nodes having acknowledged the request.

--

*`cassandra.response.error.details.blockfor`*::
+
--
type: long

Representing the number of replicas whose acknowledgement is required to achieve consistency level.

--

*`cassandra.response.error.details.write_type`*::
+
--
type: keyword

Describe the type of the write that timed out.

--

*`cassandra.response.error.details.data_present`*::
+
--
type: boolean

It means the replica that was asked for data had responded.

--

*`cassandra.response.error.details.keyspace`*::
+
--
type: keyword

The keyspace of the failed function.

--

*`cassandra.response.error.details.table`*::
+
--
type: keyword

The keyspace of the failed function.

--

*`cassandra.response.error.details.stmt_id`*::
+
--
type: keyword

Representing the unknown ID.

--

*`cassandra.response.error.details.num_failures`*::
+
--
type: keyword

Representing the number of nodes that experience a failure while executing the request.

--

*`cassandra.response.error.details.function`*::
+
--
type: keyword

The name of the failed function.

--

*`cassandra.response.error.details.arg_types`*::
+
--
type: keyword

One string for each argument type (as CQL type) of the failed function.

--

[[exported-fields-cloud]]
== Cloud provider metadata fields

Metadata from cloud providers added by the add_cloud_metadata processor.



*`cloud.project.id`*::
+
--
example: project-x

Name of the project in Google Cloud.


--

*`meta.cloud.provider`*::
+
--
type: alias

alias to: cloud.provider

--

*`meta.cloud.instance_id`*::
+
--
type: alias

alias to: cloud.instance.id

--

*`meta.cloud.instance_name`*::
+
--
type: alias

alias to: cloud.instance.name

--

*`meta.cloud.machine_type`*::
+
--
type: alias

alias to: cloud.machine.type

--

*`meta.cloud.availability_zone`*::
+
--
type: alias

alias to: cloud.availability_zone

--

*`meta.cloud.project_id`*::
+
--
type: alias

alias to: cloud.project.id

--

*`meta.cloud.region`*::
+
--
type: alias

alias to: cloud.region

--

[[exported-fields-common]]
== Common fields

These fields contain data about the environment in which the transaction or flow was captured.



*`type`*::
+
--
required: True

The type of the transaction (for example, HTTP, MySQL, Redis, or RUM) or "flow" in case of flows.


--

*`server.process.name`*::
+
--
The name of the process that served the transaction.


--

*`server.process.args`*::
+
--
The command-line of the process that served the transaction.


--

*`server.process.executable`*::
+
--
Absolute path to the server process executable.


--

*`server.process.working_directory`*::
+
--
The working directory of the server process.


--

*`server.process.start`*::
+
--
The time the server process started.


--

*`client.process.name`*::
+
--
The name of the process that initiated the transaction.


--

*`client.process.args`*::
+
--
The command-line of the process that initiated the transaction.


--

*`client.process.executable`*::
+
--
Absolute path to the client process executable.


--

*`client.process.working_directory`*::
+
--
The working directory of the client process.


--

*`client.process.start`*::
+
--
The time the client process started.


--

*`real_ip`*::
+
--
type: alias

alias to: network.forwarded_ip

If the server initiating the transaction is a proxy, this field contains the original client IP address. For HTTP, for example, the IP address extracted from a configurable HTTP header, by default `X-Forwarded-For`.
Unless this field is disabled, it always has a value, and it matches the `client_ip` for non proxy clients.


--

*`transport`*::
+
--
type: alias

alias to: network.transport

The transport protocol used for the transaction. If not specified, then tcp is assumed.


--

[[exported-fields-dhcpv4]]
== DHCPv4 fields

DHCPv4 event fields



*`dhcpv4.transaction_id`*::
+
--
type: keyword

Transaction ID, a random number chosen by the
client, used by the client and server to associate
messages and responses between a client and a
server.


--

*`dhcpv4.seconds`*::
+
--
type: long

Number of seconds elapsed since client began address acquisition or
renewal process.


--

*`dhcpv4.flags`*::
+
--
type: keyword

Flags are set by the client to indicate how the DHCP server should
its reply -- either unicast or broadcast.


--

*`dhcpv4.client_ip`*::
+
--
type: ip

The current IP address of the client.

--

*`dhcpv4.assigned_ip`*::
+
--
type: ip

The IP address that the DHCP server is assigning to the client.
This field is also known as "your" IP address.


--

*`dhcpv4.server_ip`*::
+
--
type: ip

The IP address of the DHCP server that the client should use for the
next step in the bootstrap process.


--

*`dhcpv4.relay_ip`*::
+
--
type: ip

The relay IP address used by the client to contact the server
(i.e. a DHCP relay server).


--

*`dhcpv4.client_mac`*::
+
--
type: keyword

The client's MAC address (layer two).

--

*`dhcpv4.server_name`*::
+
--
type: keyword

The name of the server sending the message. Optional. Used in
DHCPOFFER or DHCPACK messages.


--

*`dhcpv4.op_code`*::
+
--
type: keyword

example: bootreply

The message op code (bootrequest or bootreply).


--

*`dhcpv4.hops`*::
+
--
type: long

The number of hops the DHCP message went through.

--

*`dhcpv4.hardware_type`*::
+
--
type: keyword

The type of hardware used for the local network (Ethernet,
LocalTalk, etc).


--


*`dhcpv4.option.message_type`*::
+
--
type: keyword

example: ack

The specific type of DHCP message being sent (e.g. discover,
offer, request, decline, ack, nak, release, inform).


--

*`dhcpv4.option.parameter_request_list`*::
+
--
type: keyword

This option is used by a DHCP client to request values for
specified configuration parameters.


--

*`dhcpv4.option.requested_ip_address`*::
+
--
type: ip

This option is used in a client request (DHCPDISCOVER) to allow
the client to request that a particular IP address be assigned.


--

*`dhcpv4.option.server_identifier`*::
+
--
type: ip

IP address of the individual DHCP server which handled this
message.


--

*`dhcpv4.option.broadcast_address`*::
+
--
type: ip

This option specifies the broadcast address in use on the
client's subnet.


--

*`dhcpv4.option.max_dhcp_message_size`*::
+
--
type: long

This option specifies the maximum length DHCP message that the
client is willing to accept.


--

*`dhcpv4.option.class_identifier`*::
+
--
type: keyword

This option is used by DHCP clients to optionally identify the
vendor type and configuration of a DHCP client. Vendors may
choose to define specific vendor class identifiers to convey
particular configuration or other identification information
about a client.  For example, the identifier may encode the
client's hardware configuration.


--

*`dhcpv4.option.domain_name`*::
+
--
type: keyword

This option specifies the domain name that client should use
when resolving hostnames via the Domain Name System.


--

*`dhcpv4.option.dns_servers`*::
+
--
type: ip

The domain name server option specifies a list of Domain Name
System servers available to the client.


--

*`dhcpv4.option.vendor_identifying_options`*::
+
--
type: object

A DHCP client may use this option to unambiguously identify the
vendor that manufactured the hardware on which the client is
running, the software in use, or an industry consortium to which
the vendor belongs. This field is described in RFC 3925.


--

*`dhcpv4.option.subnet_mask`*::
+
--
type: ip

The subnet mask that the client should use on the currnet
network.


--

*`dhcpv4.option.utc_time_offset_sec`*::
+
--
type: long

The time offset field specifies the offset of the client's
subnet in seconds from Coordinated Universal Time (UTC).


--

*`dhcpv4.option.router`*::
+
--
type: ip

The router option specifies a list of IP addresses for routers
on the client's subnet.


--

*`dhcpv4.option.time_servers`*::
+
--
type: ip

The time server option specifies a list of RFC 868 time servers
available to the client.


--

*`dhcpv4.option.ntp_servers`*::
+
--
type: ip

This option specifies a list of IP addresses indicating NTP
servers available to the client.


--

*`dhcpv4.option.hostname`*::
+
--
type: keyword

This option specifies the name of the client.


--

*`dhcpv4.option.ip_address_lease_time_sec`*::
+
--
type: long

This option is used in a client request (DHCPDISCOVER or
DHCPREQUEST) to allow the client to request a lease time for the
IP address.  In a server reply (DHCPOFFER), a DHCP server uses
this option to specify the lease time it is willing to offer.


--

*`dhcpv4.option.message`*::
+
--
type: text

This option is used by a DHCP server to provide an error message
to a DHCP client in a DHCPNAK message in the event of a failure.
A client may use this option in a DHCPDECLINE message to
indicate the why the client declined the offered parameters.


--

*`dhcpv4.option.renewal_time_sec`*::
+
--
type: long

This option specifies the time interval from address assignment
until the client transitions to the RENEWING state.


--

*`dhcpv4.option.rebinding_time_sec`*::
+
--
type: long

This option specifies the time interval from address assignment
until the client transitions to the REBINDING state.


--

*`dhcpv4.option.boot_file_name`*::
+
--
type: keyword

This option is used to identify a bootfile when the 'file' field
in the DHCP header has been used for DHCP options.


--

[[exported-fields-dns]]
== DNS fields

DNS-specific event fields.



*`dns.id`*::
+
--
type: long

The DNS packet identifier assigned by the program that generated the query. The identifier is copied to the response.


--

*`dns.op_code`*::
+
--
example: QUERY

The DNS operation code that specifies the kind of query in the message. This value is set by the originator of a query and copied into the response.


--

*`dns.flags.authoritative`*::
+
--
type: boolean

A DNS flag specifying that the responding server is an authority for the domain name used in the question.


--

*`dns.flags.recursion_available`*::
+
--
type: boolean

A DNS flag specifying whether recursive query support is available in the name server.


--

*`dns.flags.recursion_desired`*::
+
--
type: boolean

A DNS flag specifying that the client directs the server to pursue a query recursively. Recursive query support is optional.


--

*`dns.flags.authentic_data`*::
+
--
type: boolean

A DNS flag specifying that the recursive server considers the response authentic.


--

*`dns.flags.checking_disabled`*::
+
--
type: boolean

A DNS flag specifying that the client disables the server signature validation of the query.


--

*`dns.flags.truncated_response`*::
+
--
type: boolean

A DNS flag specifying that only the first 512 bytes of the reply were returned.


--

*`dns.response_code`*::
+
--
example: NOERROR

The DNS status code.

--

*`dns.question.name`*::
+
--
example: www.google.com.

The domain name being queried. If the name field contains non-printable characters (below 32 or above 126), then those characters are represented as escaped base 10 integers (\DDD). Back slashes and quotes are escaped. Tabs, carriage returns, and line feeds are converted to \t, \r, and \n respectively.


--

*`dns.question.type`*::
+
--
example: AAAA

The type of records being queried.

--

*`dns.question.class`*::
+
--
example: IN

The class of of records being queried.

--

*`dns.question.etld_plus_one`*::
+
--
example: amazon.co.uk.

The effective top-level domain (eTLD) plus one more label. For example, the eTLD+1 for "foo.bar.golang.org." is "golang.org.". The data for determining the eTLD comes from an embedded copy of the data from http://publicsuffix.org.

--

*`dns.answers`*::
+
--
type: object

An array containing a dictionary about each answer section returned by the server.


--

*`dns.answers_count`*::
+
--
type: long

The number of resource records contained in the `dns.answers` field.


--

*`dns.answers.name`*::
+
--
example: example.com.

The domain name to which this resource record pertains.

--

*`dns.answers.type`*::
+
--
example: MX

The type of data contained in this resource record.

--

*`dns.answers.class`*::
+
--
example: IN

The class of DNS data contained in this resource record.

--

*`dns.answers.ttl`*::
+
--
type: long

The time interval in seconds that this resource record may be cached before it should be discarded. Zero values mean that the data should not be cached.


--

*`dns.answers.data`*::
+
--
The data describing the resource. The meaning of this data depends on the type and class of the resource record.


--

*`dns.authorities`*::
+
--
type: object

An array containing a dictionary for each authority section from the answer.


--

*`dns.authorities_count`*::
+
--
type: long

The number of resource records contained in the `dns.authorities` field. The `dns.authorities` field may or may not be included depending on the configuration of Packetbeat.


--

*`dns.authorities.name`*::
+
--
example: example.com.

The domain name to which this resource record pertains.

--

*`dns.authorities.type`*::
+
--
example: NS

The type of data contained in this resource record.

--

*`dns.authorities.class`*::
+
--
example: IN

The class of DNS data contained in this resource record.

--

*`dns.additionals`*::
+
--
type: object

An array containing a dictionary for each additional section from the answer.


--

*`dns.additionals_count`*::
+
--
type: long

The number of resource records contained in the `dns.additionals` field. The `dns.additionals` field may or may not be included depending on the configuration of Packetbeat.


--

*`dns.additionals.name`*::
+
--
example: example.com.

The domain name to which this resource record pertains.

--

*`dns.additionals.type`*::
+
--
example: NS

The type of data contained in this resource record.

--

*`dns.additionals.class`*::
+
--
example: IN

The class of DNS data contained in this resource record.

--

*`dns.additionals.ttl`*::
+
--
type: long

The time interval in seconds that this resource record may be cached before it should be discarded. Zero values mean that the data should not be cached.


--

*`dns.additionals.data`*::
+
--
The data describing the resource. The meaning of this data depends on the type and class of the resource record.


--

*`dns.opt.version`*::
+
--
example: 0

The EDNS version.

--

*`dns.opt.do`*::
+
--
type: boolean

If set, the transaction uses DNSSEC.

--

*`dns.opt.ext_rcode`*::
+
--
example: BADVERS

Extended response code field.

--

*`dns.opt.udp_size`*::
+
--
type: long

Requestor's UDP payload size (in bytes).

--

[[exported-fields-docker-processor]]
== Docker fields

Docker stats collected from Docker.




*`docker.container.id`*::
+
--
type: alias

alias to: container.id

--

*`docker.container.image`*::
+
--
type: alias

alias to: container.image.name

--

*`docker.container.name`*::
+
--
type: alias

alias to: container.name

--

*`docker.container.labels`*::
+
--
type: object

Image labels.


--

[[exported-fields-ecs]]
== ECS fields

ECS Fields.


*`@timestamp`*::
+
--
type: date

example: 2016-05-23T08:05:34.853Z

required: True

Date/time when the event originated.
This is the date/time extracted from the event, typically representing when the event was generated by the source.
If the event source has no original timestamp, this value is typically populated by the first time the event was received by the pipeline.
Required field for all events.

--

*`labels`*::
+
--
type: object

example: {'application': 'foo-bar', 'env': 'production'}

Custom key/value pairs.
Can be used to add meta information to events. Should not contain nested objects. All values are stored as keyword.
Example: `docker` and `k8s` labels.

--

*`message`*::
+
--
type: text

example: Hello World

For log events the message field contains the log message, optimized for viewing in a log viewer.
For structured logs without an original message field, other fields can be concatenated to form a human-readable summary of the event.
If multiple messages exist, they can be combined into one message.

--

*`tags`*::
+
--
type: keyword

example: ["production", "env2"]

List of keywords used to tag each event.

--

[float]
== agent fields

The agent fields contain the data about the software entity, if any, that collects, detects, or observes events on a host, or takes measurements on a host.
Examples include Beats. Agents may also run on observers. ECS agent.* fields shall be populated with details of the agent running on the host or observer where the event happened or the measurement was taken.


*`agent.ephemeral_id`*::
+
--
type: keyword

example: 8a4f500f

Ephemeral identifier of this agent (if one exists).
This id normally changes across restarts, but `agent.id` does not.

--

*`agent.id`*::
+
--
type: keyword

example: 8a4f500d

Unique identifier of this agent (if one exists).
Example: For Beats this would be beat.id.

--

*`agent.name`*::
+
--
type: keyword

example: foo

Custom name of the agent.
This is a name that can be given to an agent. This can be helpful if for example two Filebeat instances are running on the same host but a human readable separation is needed on which Filebeat instance data is coming from.
If no name is given, the name is often left empty.

--

*`agent.type`*::
+
--
type: keyword

example: filebeat

Type of the agent.
The agent type stays always the same and should be given by the agent used. In case of Filebeat the agent would always be Filebeat also if two Filebeat instances are run on the same machine.

--

*`agent.version`*::
+
--
type: keyword

example: 6.0.0-rc2

Version of the agent.

--

[float]
== client fields

A client is defined as the initiator of a network connection for events regarding sessions, connections, or bidirectional flow records.
For TCP events, the client is the initiator of the TCP connection that sends the SYN packet(s). For other protocols, the client is generally the initiator or requestor in the network transaction. Some systems use the term "originator" to refer the client in TCP connections. The client fields describe details about the system acting as the client in the network event. Client fields are usually populated in conjunction with server fields.  Client fields are generally not populated for packet-level events.
Client / server representations can add semantic context to an exchange, which is helpful to visualize the data in certain situations. If your context falls in that category, you should still ensure that source and destination are filled appropriately.


*`client.address`*::
+
--
type: keyword

Some event client addresses are defined ambiguously. The event will sometimes list an IP, a domain or a unix socket.  You should always store the raw address in the `.address` field.
Then it should be duplicated to `.ip` or `.domain`, depending on which one it is.

--

*`client.bytes`*::
+
--
type: long

example: 184

format: bytes

Bytes sent from the client to the server.

--

*`client.domain`*::
+
--
type: keyword

Client domain.

--

*`client.geo.city_name`*::
+
--
type: keyword

example: Montreal

City name.

--

*`client.geo.continent_name`*::
+
--
type: keyword

example: North America

Name of the continent.

--

*`client.geo.country_iso_code`*::
+
--
type: keyword

example: CA

Country ISO code.

--

*`client.geo.country_name`*::
+
--
type: keyword

example: Canada

Country name.

--

*`client.geo.location`*::
+
--
type: geo_point

example: { "lon": -73.614830, "lat": 45.505918 }

Longitude and latitude.

--

*`client.geo.name`*::
+
--
type: keyword

example: boston-dc

User-defined description of a location, at the level of granularity they care about.
Could be the name of their data centers, the floor number, if this describes a local physical entity, city names.
Not typically used in automated geolocation.

--

*`client.geo.region_iso_code`*::
+
--
type: keyword

example: CA-QC

Region ISO code.

--

*`client.geo.region_name`*::
+
--
type: keyword

example: Quebec

Region name.

--

*`client.ip`*::
+
--
type: ip

IP address of the client.
Can be one or multiple IPv4 or IPv6 addresses.

--

*`client.mac`*::
+
--
type: keyword

MAC address of the client.

--

*`client.packets`*::
+
--
type: long

example: 12

Packets sent from the client to the server.

--

*`client.port`*::
+
--
type: long

Port of the client.

--

*`client.user.email`*::
+
--
type: keyword

User email address.

--

*`client.user.full_name`*::
+
--
type: keyword

example: Albert Einstein

User's full name, if available.

--

*`client.user.group.id`*::
+
--
type: keyword

Unique identifier for the group on the system/platform.

--

*`client.user.group.name`*::
+
--
type: keyword

Name of the group.

--

*`client.user.hash`*::
+
--
type: keyword

Unique user hash to correlate information for a user in anonymized form.
Useful if `user.id` or `user.name` contain confidential information and cannot be used.

--

*`client.user.id`*::
+
--
type: keyword

One or multiple unique identifiers of the user.

--

*`client.user.name`*::
+
--
type: keyword

example: albert

Short name or login of the user.

--

[float]
== cloud fields

Fields related to the cloud or infrastructure the events are coming from.


*`cloud.account.id`*::
+
--
type: keyword

example: 666777888999

The cloud account or organization id used to identify different entities in a multi-tenant environment.
Examples: AWS account id, Google Cloud ORG Id, or other unique identifier.

--

*`cloud.availability_zone`*::
+
--
type: keyword

example: us-east-1c

Availability zone in which this host is running.

--

*`cloud.instance.id`*::
+
--
type: keyword

example: i-1234567890abcdef0

Instance ID of the host machine.

--

*`cloud.instance.name`*::
+
--
type: keyword

Instance name of the host machine.

--

*`cloud.machine.type`*::
+
--
type: keyword

example: t2.medium

Machine type of the host machine.

--

*`cloud.provider`*::
+
--
type: keyword

example: aws

Name of the cloud provider. Example values are aws, azure, gcp, or digitalocean.

--

*`cloud.region`*::
+
--
type: keyword

example: us-east-1

Region in which this host is running.

--

[float]
== container fields

Container fields are used for meta information about the specific container that is the source of information.
These fields help correlate data based containers from any runtime.


*`container.id`*::
+
--
type: keyword

Unique container id.

--

*`container.image.name`*::
+
--
type: keyword

Name of the image the container was built on.

--

*`container.image.tag`*::
+
--
type: keyword

Container image tag.

--

*`container.labels`*::
+
--
type: object

Image labels.

--

*`container.name`*::
+
--
type: keyword

Container name.

--

*`container.runtime`*::
+
--
type: keyword

example: docker

Runtime managing this container.

--

[float]
== destination fields

Destination fields describe details about the destination of a packet/event.
Destination fields are usually populated in conjunction with source fields.


*`destination.address`*::
+
--
type: keyword

Some event destination addresses are defined ambiguously. The event will sometimes list an IP, a domain or a unix socket.  You should always store the raw address in the `.address` field.
Then it should be duplicated to `.ip` or `.domain`, depending on which one it is.

--

*`destination.bytes`*::
+
--
type: long

example: 184

format: bytes

Bytes sent from the destination to the source.

--

*`destination.domain`*::
+
--
type: keyword

Destination domain.

--

*`destination.geo.city_name`*::
+
--
type: keyword

example: Montreal

City name.

--

*`destination.geo.continent_name`*::
+
--
type: keyword

example: North America

Name of the continent.

--

*`destination.geo.country_iso_code`*::
+
--
type: keyword

example: CA

Country ISO code.

--

*`destination.geo.country_name`*::
+
--
type: keyword

example: Canada

Country name.

--

*`destination.geo.location`*::
+
--
type: geo_point

example: { "lon": -73.614830, "lat": 45.505918 }

Longitude and latitude.

--

*`destination.geo.name`*::
+
--
type: keyword

example: boston-dc

User-defined description of a location, at the level of granularity they care about.
Could be the name of their data centers, the floor number, if this describes a local physical entity, city names.
Not typically used in automated geolocation.

--

*`destination.geo.region_iso_code`*::
+
--
type: keyword

example: CA-QC

Region ISO code.

--

*`destination.geo.region_name`*::
+
--
type: keyword

example: Quebec

Region name.

--

*`destination.ip`*::
+
--
type: ip

IP address of the destination.
Can be one or multiple IPv4 or IPv6 addresses.

--

*`destination.mac`*::
+
--
type: keyword

MAC address of the destination.

--

*`destination.packets`*::
+
--
type: long

example: 12

Packets sent from the destination to the source.

--

*`destination.port`*::
+
--
type: long

Port of the destination.

--

*`destination.user.email`*::
+
--
type: keyword

User email address.

--

*`destination.user.full_name`*::
+
--
type: keyword

example: Albert Einstein

User's full name, if available.

--

*`destination.user.group.id`*::
+
--
type: keyword

Unique identifier for the group on the system/platform.

--

*`destination.user.group.name`*::
+
--
type: keyword

Name of the group.

--

*`destination.user.hash`*::
+
--
type: keyword

Unique user hash to correlate information for a user in anonymized form.
Useful if `user.id` or `user.name` contain confidential information and cannot be used.

--

*`destination.user.id`*::
+
--
type: keyword

One or multiple unique identifiers of the user.

--

*`destination.user.name`*::
+
--
type: keyword

example: albert

Short name or login of the user.

--

[float]
== ecs fields

Meta-information specific to ECS.


*`ecs.version`*::
+
--
type: keyword

example: 1.0.0

required: True

ECS version this event conforms to. `ecs.version` is a required field and must exist in all events.
When querying across multiple indices -- which may conform to slightly different ECS versions -- this field lets integrations adjust to the schema version of the events.

--

[float]
== error fields

These fields can represent errors of any kind.
Use them for errors that happen while fetching events or in cases where the event itself contains an error.


*`error.code`*::
+
--
type: keyword

Error code describing the error.

--

*`error.id`*::
+
--
type: keyword

Unique identifier for the error.

--

*`error.message`*::
+
--
type: text

Error message.

--

[float]
== event fields

The event fields are used for context information about the log or metric event itself.
A log is defined as an event containing details of something that happened. Log events must include the time at which the thing happened. Examples of log events include a process starting on a host, a network packet being sent from a source to a destination, or a network connection between a client and a server being initiated or closed. A metric is defined as an event containing one or more numerical or categorical measurements and the time at which the measurement was taken. Examples of metric events include memory pressure measured on a host, or vulnerabilities measured on a scanned host.


*`event.action`*::
+
--
type: keyword

example: user-password-change

The action captured by the event.
This describes the information in the event. It is more specific than `event.category`. Examples are `group-add`, `process-started`, `file-created`. The value is normally defined by the implementer.

--

*`event.category`*::
+
--
type: keyword

example: user-management

Event category.
This contains high-level information about the contents of the event. It is more generic than `event.action`, in the sense that typically a category contains multiple actions. Warning: In future versions of ECS, we plan to provide a list of acceptable values for this field, please use with caution.

--

*`event.created`*::
+
--
type: date

event.created contains the date/time when the event was first read by an agent, or by your pipeline.
This field is distinct from @timestamp in that @timestamp typically contain the time extracted from the original event.
In most situations, these two timestamps will be slightly different. The difference can be used to calculate the delay between your source generating an event, and the time when your agent first processed it. This can be used to monitor your agent's or pipeline's ability to keep up with your event source.
In case the two timestamps are identical, @timestamp should be used.

--

*`event.dataset`*::
+
--
type: keyword

example: stats

Name of the dataset.
The concept of a `dataset` (fileset / metricset) is used in Beats as a subset of modules. It contains the information which is currently stored in metricset.name and metricset.module or fileset.name.

--

*`event.duration`*::
+
--
type: long

format: duration

Duration of the event in nanoseconds.
If event.start and event.end are known this value should be the difference between the end and start time.

--

*`event.end`*::
+
--
type: date

event.end contains the date when the event ended or when the activity was last observed.

--

*`event.hash`*::
+
--
type: keyword

example: 123456789012345678901234567890ABCD

Hash (perhaps logstash fingerprint) of raw field to be able to demonstrate log integrity.

--

*`event.id`*::
+
--
type: keyword

example: 8a4f500d

Unique ID to describe the event.

--

*`event.kind`*::
+
--
type: keyword

example: state

The kind of the event.
This gives information about what type of information the event contains, without being specific to the contents of the event.  Examples are `event`, `state`, `alarm`. Warning: In future versions of ECS, we plan to provide a list of acceptable values for this field, please use with caution.

--

*`event.module`*::
+
--
type: keyword

example: mysql

Name of the module this data is coming from.
This information is coming from the modules used in Beats or Logstash.

--

*`event.original`*::
+
--
type: keyword

example: Sep 19 08:26:10 host CEF:0&#124;Security&#124; threatmanager&#124;1.0&#124;100&#124; worm successfully stopped&#124;10&#124;src=10.0.0.1 dst=2.1.2.2spt=1232

Raw text message of entire event. Used to demonstrate log integrity.
This field is not indexed and doc_values are disabled. It cannot be searched, but it can be retrieved from `_source`.

--

*`event.outcome`*::
+
--
type: keyword

example: success

The outcome of the event.
If the event describes an action, this fields contains the outcome of that action. Examples outcomes are `success` and `failure`. Warning: In future versions of ECS, we plan to provide a list of acceptable values for this field, please use with caution.

--

*`event.risk_score`*::
+
--
type: float

Risk score or priority of the event (e.g. security solutions). Use your system's original value here.

--

*`event.risk_score_norm`*::
+
--
type: float

Normalized risk score or priority of the event, on a scale of 0 to 100.
This is mainly useful if you use more than one system that assigns risk scores, and you want to see a normalized value across all systems.

--

*`event.severity`*::
+
--
type: long

example: 7

Severity describes the original severity of the event. What the different severity values mean can very different between use cases. It's up to the implementer to make sure severities are consistent across events.

--

*`event.start`*::
+
--
type: date

event.start contains the date when the event started or when the activity was first observed.

--

*`event.timezone`*::
+
--
type: keyword

This field should be populated when the event's timestamp does not include timezone information already (e.g. default Syslog timestamps). It's optional otherwise.
Acceptable timezone formats are: a canonical ID (e.g. "Europe/Amsterdam"), abbreviated (e.g. "EST") or an HH:mm differential (e.g. "-05:00").

--

*`event.type`*::
+
--
type: keyword

Reserved for future usage.
Please avoid using this field for user data.

--

[float]
== file fields

A file is defined as a set of information that has been created on, or has existed on a filesystem.
File objects can be associated with host events, network events, and/or file events (e.g., those produced by File Integrity Monitoring [FIM] products or services). File fields provide details about the affected file associated with the event or metric.


*`file.ctime`*::
+
--
type: date

Last time file metadata changed.

--

*`file.device`*::
+
--
type: keyword

Device that is the source of the file.

--

*`file.extension`*::
+
--
type: keyword

example: png

File extension.
This should allow easy filtering by file extensions.

--

*`file.gid`*::
+
--
type: keyword

Primary group ID (GID) of the file.

--

*`file.group`*::
+
--
type: keyword

Primary group name of the file.

--

*`file.inode`*::
+
--
type: keyword

Inode representing the file in the filesystem.

--

*`file.mode`*::
+
--
type: keyword

example: 416

Mode of the file in octal representation.

--

*`file.mtime`*::
+
--
type: date

Last time file content was modified.

--

*`file.owner`*::
+
--
type: keyword

File owner's username.

--

*`file.path`*::
+
--
type: keyword

Path to the file.

--

*`file.size`*::
+
--
type: long

File size in bytes (field is only added when `type` is `file`).

--

*`file.target_path`*::
+
--
type: keyword

Target path for symlinks.

--

*`file.type`*::
+
--
type: keyword

File type (file, dir, or symlink).

--

*`file.uid`*::
+
--
type: keyword

The user ID (UID) or security identifier (SID) of the file owner.

--

[float]
== geo fields

Geo fields can carry data about a specific location related to an event.
This geolocation information can be derived from techniques such as Geo IP, or be user-supplied.


*`geo.city_name`*::
+
--
type: keyword

example: Montreal

City name.

--

*`geo.continent_name`*::
+
--
type: keyword

example: North America

Name of the continent.

--

*`geo.country_iso_code`*::
+
--
type: keyword

example: CA

Country ISO code.

--

*`geo.country_name`*::
+
--
type: keyword

example: Canada

Country name.

--

*`geo.location`*::
+
--
type: geo_point

example: { "lon": -73.614830, "lat": 45.505918 }

Longitude and latitude.

--

*`geo.name`*::
+
--
type: keyword

example: boston-dc

User-defined description of a location, at the level of granularity they care about.
Could be the name of their data centers, the floor number, if this describes a local physical entity, city names.
Not typically used in automated geolocation.

--

*`geo.region_iso_code`*::
+
--
type: keyword

example: CA-QC

Region ISO code.

--

*`geo.region_name`*::
+
--
type: keyword

example: Quebec

Region name.

--

[float]
== group fields

The group fields are meant to represent groups that are relevant to the event.


*`group.id`*::
+
--
type: keyword

Unique identifier for the group on the system/platform.

--

*`group.name`*::
+
--
type: keyword

Name of the group.

--

[float]
== host fields

A host is defined as a general computing instance.
ECS host.* fields should be populated with details about the host on which the event happened, or from which the measurement was taken. Host types include hardware, virtual machines, Docker containers, and Kubernetes nodes.


*`host.architecture`*::
+
--
type: keyword

example: x86_64

Operating system architecture.

--

*`host.geo.city_name`*::
+
--
type: keyword

example: Montreal

City name.

--

*`host.geo.continent_name`*::
+
--
type: keyword

example: North America

Name of the continent.

--

*`host.geo.country_iso_code`*::
+
--
type: keyword

example: CA

Country ISO code.

--

*`host.geo.country_name`*::
+
--
type: keyword

example: Canada

Country name.

--

*`host.geo.location`*::
+
--
type: geo_point

example: { "lon": -73.614830, "lat": 45.505918 }

Longitude and latitude.

--

*`host.geo.name`*::
+
--
type: keyword

example: boston-dc

User-defined description of a location, at the level of granularity they care about.
Could be the name of their data centers, the floor number, if this describes a local physical entity, city names.
Not typically used in automated geolocation.

--

*`host.geo.region_iso_code`*::
+
--
type: keyword

example: CA-QC

Region ISO code.

--

*`host.geo.region_name`*::
+
--
type: keyword

example: Quebec

Region name.

--

*`host.hostname`*::
+
--
type: keyword

Hostname of the host.
It normally contains what the `hostname` command returns on the host machine.

--

*`host.id`*::
+
--
type: keyword

Unique host id.
As hostname is not always unique, use values that are meaningful in your environment.
Example: The current usage of `beat.name`.

--

*`host.ip`*::
+
--
type: ip

Host ip address.

--

*`host.mac`*::
+
--
type: keyword

Host mac address.

--

*`host.name`*::
+
--
type: keyword

Name of the host.
It can contain what `hostname` returns on Unix systems, the fully qualified domain name, or a name specified by the user. The sender decides which value to use.

--

*`host.os.family`*::
+
--
type: keyword

example: debian

OS family (such as redhat, debian, freebsd, windows).

--

*`host.os.full`*::
+
--
type: keyword

example: Mac OS Mojave

Operating system name, including the version or code name.

--

*`host.os.kernel`*::
+
--
type: keyword

example: 4.4.0-112-generic

Operating system kernel version as a raw string.

--

*`host.os.name`*::
+
--
type: keyword

example: Mac OS X

Operating system name, without the version.

--

*`host.os.platform`*::
+
--
type: keyword

example: darwin

Operating system platform (such centos, ubuntu, windows).

--

*`host.os.version`*::
+
--
type: keyword

example: 10.14.1

Operating system version as a raw string.

--

*`host.type`*::
+
--
type: keyword

Type of host.
For Cloud providers this can be the machine type like `t2.medium`. If vm, this could be the container, for example, or other information meaningful in your environment.

--

*`host.user.email`*::
+
--
type: keyword

User email address.

--

*`host.user.full_name`*::
+
--
type: keyword

example: Albert Einstein

User's full name, if available.

--

*`host.user.group.id`*::
+
--
type: keyword

Unique identifier for the group on the system/platform.

--

*`host.user.group.name`*::
+
--
type: keyword

Name of the group.

--

*`host.user.hash`*::
+
--
type: keyword

Unique user hash to correlate information for a user in anonymized form.
Useful if `user.id` or `user.name` contain confidential information and cannot be used.

--

*`host.user.id`*::
+
--
type: keyword

One or multiple unique identifiers of the user.

--

*`host.user.name`*::
+
--
type: keyword

example: albert

Short name or login of the user.

--

[float]
== http fields

Fields related to HTTP activity. Use the `url` field set to store the url of the request.


*`http.request.body.bytes`*::
+
--
type: long

example: 887

format: bytes

Size in bytes of the request body.

--

*`http.request.body.content`*::
+
--
type: keyword

example: Hello world

The full HTTP request body.

--

*`http.request.bytes`*::
+
--
type: long

example: 1437

format: bytes

Total size in bytes of the request (body and headers).

--

*`http.request.method`*::
+
--
type: keyword

example: get, post, put

HTTP request method.
The field value must be normalized to lowercase for querying. See the documentation section "Implementing ECS".

--

*`http.request.referrer`*::
+
--
type: keyword

example: https://blog.example.com/

Referrer for this HTTP request.

--

*`http.response.body.bytes`*::
+
--
type: long

example: 887

format: bytes

Size in bytes of the response body.

--

*`http.response.body.content`*::
+
--
type: keyword

example: Hello world

The full HTTP response body.

--

*`http.response.bytes`*::
+
--
type: long

example: 1437

format: bytes

Total size in bytes of the response (body and headers).

--

*`http.response.status_code`*::
+
--
type: long

example: 404

HTTP response status code.

--

*`http.version`*::
+
--
type: keyword

example: 1.1

HTTP version.

--

[float]
== log fields

Fields which are specific to log events.


*`log.level`*::
+
--
type: keyword

example: err

Original log level of the log event.
Some examples are `warn`, `error`, `i`.

--

*`log.original`*::
+
--
type: keyword

example: Sep 19 08:26:10 localhost My log

This is the original log message and contains the full log message before splitting it up in multiple parts.
In contrast to the `message` field which can contain an extracted part of the log message, this field contains the original, full log message. It can have already some modifications applied like encoding or new lines removed to clean up the log message.
This field is not indexed and doc_values are disabled so it can't be queried but the value can be retrieved from `_source`.

--

[float]
== network fields

The network is defined as the communication path over which a host or network event happens.
The network.* fields should be populated with details about the network activity associated with an event.


*`network.application`*::
+
--
type: keyword

example: aim

A name given to an application level protocol. This can be arbitrarily assigned for things like microservices, but also apply to things like skype, icq, facebook, twitter. This would be used in situations where the vendor or service can be decoded such as from the source/dest IP owners, ports, or wire format.
The field value must be normalized to lowercase for querying. See the documentation section "Implementing ECS".

--

*`network.bytes`*::
+
--
type: long

example: 368

format: bytes

Total bytes transferred in both directions.
If `source.bytes` and `destination.bytes` are known, `network.bytes` is their sum.

--

*`network.community_id`*::
+
--
type: keyword

example: 1:hO+sN4H+MG5MY/8hIrXPqc4ZQz0=

A hash of source and destination IPs and ports, as well as the protocol used in a communication. This is a tool-agnostic standard to identify flows.
Learn more at https://github.com/corelight/community-id-spec.

--

*`network.direction`*::
+
--
type: keyword

example: inbound

Direction of the network traffic.
Recommended values are:
  * inbound
  * outbound
  * internal
  * external
  * unknown

When mapping events from a host-based monitoring context, populate this field from the host's point of view.
When mapping events from a network or perimeter-based monitoring context, populate this field from the point of view of your network perimeter.

--

*`network.forwarded_ip`*::
+
--
type: ip

example: 192.1.1.2

Host IP address when the source IP address is the proxy.

--

*`network.iana_number`*::
+
--
type: keyword

example: 6

IANA Protocol Number (https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml). Standardized list of protocols. This aligns well with NetFlow and sFlow related logs which use the IANA Protocol Number.

--

*`network.name`*::
+
--
type: keyword

example: Guest Wifi

Name given by operators to sections of their network.

--

*`network.packets`*::
+
--
type: long

example: 24

Total packets transferred in both directions.
If `source.packets` and `destination.packets` are known, `network.packets` is their sum.

--

*`network.protocol`*::
+
--
type: keyword

example: http

L7 Network protocol name. ex. http, lumberjack, transport protocol.
The field value must be normalized to lowercase for querying. See the documentation section "Implementing ECS".

--

*`network.transport`*::
+
--
type: keyword

example: tcp

Same as network.iana_number, but instead using the Keyword name of the transport layer (udp, tcp, ipv6-icmp, etc.)
The field value must be normalized to lowercase for querying. See the documentation section "Implementing ECS".

--

*`network.type`*::
+
--
type: keyword

example: ipv4

In the OSI Model this would be the Network Layer. ipv4, ipv6, ipsec, pim, etc
The field value must be normalized to lowercase for querying. See the documentation section "Implementing ECS".

--

[float]
== observer fields

An observer is defined as a special network, security, or application device used to detect, observe, or create network, security, or application-related events and metrics.
This could be a custom hardware appliance or a server that has been configured to run special network, security, or application software. Examples include firewalls, intrusion detection/prevention systems, network monitoring sensors, web application firewalls, data loss prevention systems, and APM servers. The observer.* fields shall be populated with details of the system, if any, that detects, observes and/or creates a network, security, or application event or metric. Message queues and ETL components used in processing events or metrics are not considered observers in ECS.


*`observer.geo.city_name`*::
+
--
type: keyword

example: Montreal

City name.

--

*`observer.geo.continent_name`*::
+
--
type: keyword

example: North America

Name of the continent.

--

*`observer.geo.country_iso_code`*::
+
--
type: keyword

example: CA

Country ISO code.

--

*`observer.geo.country_name`*::
+
--
type: keyword

example: Canada

Country name.

--

*`observer.geo.location`*::
+
--
type: geo_point

example: { "lon": -73.614830, "lat": 45.505918 }

Longitude and latitude.

--

*`observer.geo.name`*::
+
--
type: keyword

example: boston-dc

User-defined description of a location, at the level of granularity they care about.
Could be the name of their data centers, the floor number, if this describes a local physical entity, city names.
Not typically used in automated geolocation.

--

*`observer.geo.region_iso_code`*::
+
--
type: keyword

example: CA-QC

Region ISO code.

--

*`observer.geo.region_name`*::
+
--
type: keyword

example: Quebec

Region name.

--

*`observer.hostname`*::
+
--
type: keyword

Hostname of the observer.

--

*`observer.ip`*::
+
--
type: ip

IP address of the observer.

--

*`observer.mac`*::
+
--
type: keyword

MAC address of the observer

--

*`observer.os.family`*::
+
--
type: keyword

example: debian

OS family (such as redhat, debian, freebsd, windows).

--

*`observer.os.full`*::
+
--
type: keyword

example: Mac OS Mojave

Operating system name, including the version or code name.

--

*`observer.os.kernel`*::
+
--
type: keyword

example: 4.4.0-112-generic

Operating system kernel version as a raw string.

--

*`observer.os.name`*::
+
--
type: keyword

example: Mac OS X

Operating system name, without the version.

--

*`observer.os.platform`*::
+
--
type: keyword

example: darwin

Operating system platform (such centos, ubuntu, windows).

--

*`observer.os.version`*::
+
--
type: keyword

example: 10.14.1

Operating system version as a raw string.

--

*`observer.serial_number`*::
+
--
type: keyword

Observer serial number.

--

*`observer.type`*::
+
--
type: keyword

example: firewall

The type of the observer the data is coming from.
There is no predefined list of observer types. Some examples are `forwarder`, `firewall`, `ids`, `ips`, `proxy`, `poller`, `sensor`, `APM server`.

--

*`observer.vendor`*::
+
--
type: keyword

observer vendor information.

--

*`observer.version`*::
+
--
type: keyword

Observer version.

--

[float]
== organization fields

The organization fields enrich data with information about the company or entity the data is associated with.
These fields help you arrange or filter data stored in an index by one or multiple organizations.


*`organization.id`*::
+
--
type: keyword

Unique identifier for the organization.

--

*`organization.name`*::
+
--
type: keyword

Organization name.

--

[float]
== os fields

The OS fields contain information about the operating system.


*`os.family`*::
+
--
type: keyword

example: debian

OS family (such as redhat, debian, freebsd, windows).

--

*`os.full`*::
+
--
type: keyword

example: Mac OS Mojave

Operating system name, including the version or code name.

--

*`os.kernel`*::
+
--
type: keyword

example: 4.4.0-112-generic

Operating system kernel version as a raw string.

--

*`os.name`*::
+
--
type: keyword

example: Mac OS X

Operating system name, without the version.

--

*`os.platform`*::
+
--
type: keyword

example: darwin

Operating system platform (such centos, ubuntu, windows).

--

*`os.version`*::
+
--
type: keyword

example: 10.14.1

Operating system version as a raw string.

--

[float]
== process fields

These fields contain information about a process.
These fields can help you correlate metrics information with a process id/name from a log message.  The `process.pid` often stays in the metric itself and is copied to the global field for correlation.


*`process.args`*::
+
--
type: keyword

example: ['ssh', '-l', 'user', '10.0.0.16']

Array of process arguments.
May be filtered to protect sensitive information.

--

*`process.executable`*::
+
--
type: keyword

example: /usr/bin/ssh

Absolute path to the process executable.

--

*`process.name`*::
+
--
type: keyword

example: ssh

Process name.
Sometimes called program name or similar.

--

*`process.pid`*::
+
--
type: long

Process id.

--

*`process.ppid`*::
+
--
type: long

Process parent id.

--

*`process.start`*::
+
--
type: date

example: 2016-05-23T08:05:34.853Z

The time the process started.

--

*`process.thread.id`*::
+
--
type: long

example: 4242

Thread ID.

--

*`process.title`*::
+
--
type: keyword

Process title.
The proctitle, some times the same as process name. Can also be different: for example a browser setting its title to the web page currently opened.

--

*`process.working_directory`*::
+
--
type: keyword

example: /home/alice

The working directory of the process.

--

[float]
== related fields

This field set is meant to facilitate pivoting around a piece of data.
Some pieces of information can be seen in many places in an ECS event. To facilitate searching for them, store an array of all seen values to their corresponding field in `related.`.
A concrete example is IP addresses, which can be under host, observer, source, destination, client, server, and network.forwarded_ip. If you append all IPs to `related.ip`, you can then search for a given IP trivially, no matter where it appeared, by querying `related.ip:a.b.c.d`.


*`related.ip`*::
+
--
type: ip

All of the IPs seen on your event.

--

[float]
== server fields

A Server is defined as the responder in a network connection for events regarding sessions, connections, or bidirectional flow records.
For TCP events, the server is the receiver of the initial SYN packet(s) of the TCP connection. For other protocols, the server is generally the responder in the network transaction. Some systems actually use the term "responder" to refer the server in TCP connections. The server fields describe details about the system acting as the server in the network event. Server fields are usually populated in conjunction with client fields. Server fields are generally not populated for packet-level events.
Client / server representations can add semantic context to an exchange, which is helpful to visualize the data in certain situations. If your context falls in that category, you should still ensure that source and destination are filled appropriately.


*`server.address`*::
+
--
type: keyword

Some event server addresses are defined ambiguously. The event will sometimes list an IP, a domain or a unix socket.  You should always store the raw address in the `.address` field.
Then it should be duplicated to `.ip` or `.domain`, depending on which one it is.

--

*`server.bytes`*::
+
--
type: long

example: 184

format: bytes

Bytes sent from the server to the client.

--

*`server.domain`*::
+
--
type: keyword

Server domain.

--

*`server.geo.city_name`*::
+
--
type: keyword

example: Montreal

City name.

--

*`server.geo.continent_name`*::
+
--
type: keyword

example: North America

Name of the continent.

--

*`server.geo.country_iso_code`*::
+
--
type: keyword

example: CA

Country ISO code.

--

*`server.geo.country_name`*::
+
--
type: keyword

example: Canada

Country name.

--

*`server.geo.location`*::
+
--
type: geo_point

example: { "lon": -73.614830, "lat": 45.505918 }

Longitude and latitude.

--

*`server.geo.name`*::
+
--
type: keyword

example: boston-dc

User-defined description of a location, at the level of granularity they care about.
Could be the name of their data centers, the floor number, if this describes a local physical entity, city names.
Not typically used in automated geolocation.

--

*`server.geo.region_iso_code`*::
+
--
type: keyword

example: CA-QC

Region ISO code.

--

*`server.geo.region_name`*::
+
--
type: keyword

example: Quebec

Region name.

--

*`server.ip`*::
+
--
type: ip

IP address of the server.
Can be one or multiple IPv4 or IPv6 addresses.

--

*`server.mac`*::
+
--
type: keyword

MAC address of the server.

--

*`server.packets`*::
+
--
type: long

example: 12

Packets sent from the server to the client.

--

*`server.port`*::
+
--
type: long

Port of the server.

--

*`server.user.email`*::
+
--
type: keyword

User email address.

--

*`server.user.full_name`*::
+
--
type: keyword

example: Albert Einstein

User's full name, if available.

--

*`server.user.group.id`*::
+
--
type: keyword

Unique identifier for the group on the system/platform.

--

*`server.user.group.name`*::
+
--
type: keyword

Name of the group.

--

*`server.user.hash`*::
+
--
type: keyword

Unique user hash to correlate information for a user in anonymized form.
Useful if `user.id` or `user.name` contain confidential information and cannot be used.

--

*`server.user.id`*::
+
--
type: keyword

One or multiple unique identifiers of the user.

--

*`server.user.name`*::
+
--
type: keyword

example: albert

Short name or login of the user.

--

[float]
== service fields

The service fields describe the service for or from which the data was collected.
These fields help you find and correlate logs for a specific service and version.


*`service.ephemeral_id`*::
+
--
type: keyword

example: 8a4f500f

Ephemeral identifier of this service (if one exists).
This id normally changes across restarts, but `service.id` does not.

--

*`service.id`*::
+
--
type: keyword

example: d37e5ebfe0ae6c4972dbe9f0174a1637bb8247f6

Unique identifier of the running service.
This id should uniquely identify this service. This makes it possible to correlate logs and metrics for one specific service.
Example: If you are experiencing issues with one redis instance, you can filter on that id to see metrics and logs for that single instance.

--

*`service.name`*::
+
--
type: keyword

example: elasticsearch-metrics

Name of the service data is collected from.
The name of the service is normally user given. This allows if two instances of the same service are running on the same machine they can be differentiated by the `service.name`.
Also it allows for distributed services that run on multiple hosts to correlate the related instances based on the name.
In the case of Elasticsearch the service.name could contain the cluster name. For Beats the service.name is by default a copy of the `service.type` field if no name is specified.

--

*`service.state`*::
+
--
type: keyword

Current state of the service.

--

*`service.type`*::
+
--
type: keyword

example: elasticsearch

The type of the service data is collected from.
The type can be used to group and correlate logs and metrics from one service type.
Example: If logs or metrics are collected from Elasticsearch, `service.type` would be `elasticsearch`.

--

*`service.version`*::
+
--
type: keyword

example: 3.2.4

Version of the service the data was collected from.
This allows to look at a data set only for a specific version of a service.

--

[float]
== source fields

Source fields describe details about the source of a packet/event.
Source fields are usually populated in conjunction with destination fields.


*`source.address`*::
+
--
type: keyword

Some event source addresses are defined ambiguously. The event will sometimes list an IP, a domain or a unix socket.  You should always store the raw address in the `.address` field.
Then it should be duplicated to `.ip` or `.domain`, depending on which one it is.

--

*`source.bytes`*::
+
--
type: long

example: 184

format: bytes

Bytes sent from the source to the destination.

--

*`source.domain`*::
+
--
type: keyword

Source domain.

--

*`source.geo.city_name`*::
+
--
type: keyword

example: Montreal

City name.

--

*`source.geo.continent_name`*::
+
--
type: keyword

example: North America

Name of the continent.

--

*`source.geo.country_iso_code`*::
+
--
type: keyword

example: CA

Country ISO code.

--

*`source.geo.country_name`*::
+
--
type: keyword

example: Canada

Country name.

--

*`source.geo.location`*::
+
--
type: geo_point

example: { "lon": -73.614830, "lat": 45.505918 }

Longitude and latitude.

--

*`source.geo.name`*::
+
--
type: keyword

example: boston-dc

User-defined description of a location, at the level of granularity they care about.
Could be the name of their data centers, the floor number, if this describes a local physical entity, city names.
Not typically used in automated geolocation.

--

*`source.geo.region_iso_code`*::
+
--
type: keyword

example: CA-QC

Region ISO code.

--

*`source.geo.region_name`*::
+
--
type: keyword

example: Quebec

Region name.

--

*`source.ip`*::
+
--
type: ip

IP address of the source.
Can be one or multiple IPv4 or IPv6 addresses.

--

*`source.mac`*::
+
--
type: keyword

MAC address of the source.

--

*`source.packets`*::
+
--
type: long

example: 12

Packets sent from the source to the destination.

--

*`source.port`*::
+
--
type: long

Port of the source.

--

*`source.user.email`*::
+
--
type: keyword

User email address.

--

*`source.user.full_name`*::
+
--
type: keyword

example: Albert Einstein

User's full name, if available.

--

*`source.user.group.id`*::
+
--
type: keyword

Unique identifier for the group on the system/platform.

--

*`source.user.group.name`*::
+
--
type: keyword

Name of the group.

--

*`source.user.hash`*::
+
--
type: keyword

Unique user hash to correlate information for a user in anonymized form.
Useful if `user.id` or `user.name` contain confidential information and cannot be used.

--

*`source.user.id`*::
+
--
type: keyword

One or multiple unique identifiers of the user.

--

*`source.user.name`*::
+
--
type: keyword

example: albert

Short name or login of the user.

--

[float]
== url fields

URL fields provide support for complete or partial URLs, and supports the breaking down into scheme, domain, path, and so on.


*`url.domain`*::
+
--
type: keyword

example: www.elastic.co

Domain of the url, such as "www.elastic.co".
In some cases a URL may refer to an IP and/or port directly, without a domain name. In this case, the IP address would go to the `domain` field.

--

*`url.fragment`*::
+
--
type: keyword

Portion of the url after the `#`, such as "top".
The `#` is not part of the fragment.

--

*`url.full`*::
+
--
type: keyword

example: https://www.elastic.co:443/search?q=elasticsearch#top

If full URLs are important to your use case, they should be stored in `url.full`, whether this field is reconstructed or present in the event source.

--

*`url.original`*::
+
--
type: keyword

example: https://www.elastic.co:443/search?q=elasticsearch#top or /search?q=elasticsearch

Unmodified original url as seen in the event source.
Note that in network monitoring, the observed URL may be a full URL, whereas in access logs, the URL is often just represented as a path.
This field is meant to represent the URL as it was observed, complete or not.

--

*`url.password`*::
+
--
type: keyword

Password of the request.

--

*`url.path`*::
+
--
type: keyword

Path of the request, such as "/search".

--

*`url.port`*::
+
--
type: long

example: 443

Port of the request, such as 443.

--

*`url.query`*::
+
--
type: keyword

The query field describes the query string of the request, such as "q=elasticsearch".
The `?` is excluded from the query string. If a URL contains no `?`, there is no query field. If there is a `?` but no query, the query field exists with an empty string. The `exists` query can be used to differentiate between the two cases.

--

*`url.scheme`*::
+
--
type: keyword

example: https

Scheme of the request, such as "https".
Note: The `:` is not part of the scheme.

--

*`url.username`*::
+
--
type: keyword

Username of the request.

--

[float]
== user fields

The user fields describe information about the user that is relevant to the event.
Fields can have one entry or multiple entries. If a user has more than one id, provide an array that includes all of them.


*`user.email`*::
+
--
type: keyword

User email address.

--

*`user.full_name`*::
+
--
type: keyword

example: Albert Einstein

User's full name, if available.

--

*`user.group.id`*::
+
--
type: keyword

Unique identifier for the group on the system/platform.

--

*`user.group.name`*::
+
--
type: keyword

Name of the group.

--

*`user.hash`*::
+
--
type: keyword

Unique user hash to correlate information for a user in anonymized form.
Useful if `user.id` or `user.name` contain confidential information and cannot be used.

--

*`user.id`*::
+
--
type: keyword

One or multiple unique identifiers of the user.

--

*`user.name`*::
+
--
type: keyword

example: albert

Short name or login of the user.

--

[float]
== user_agent fields

The user_agent fields normally come from a browser request.
They often show up in web service logs coming from the parsed user agent string.


*`user_agent.device.name`*::
+
--
type: keyword

example: iPhone

Name of the device.

--

*`user_agent.name`*::
+
--
type: keyword

example: Safari

Name of the user agent.

--

*`user_agent.original`*::
+
--
type: keyword

example: Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

Unparsed version of the user_agent.

--

*`user_agent.os.family`*::
+
--
type: keyword

example: debian

OS family (such as redhat, debian, freebsd, windows).

--

*`user_agent.os.full`*::
+
--
type: keyword

example: Mac OS Mojave

Operating system name, including the version or code name.

--

*`user_agent.os.kernel`*::
+
--
type: keyword

example: 4.4.0-112-generic

Operating system kernel version as a raw string.

--

*`user_agent.os.name`*::
+
--
type: keyword

example: Mac OS X

Operating system name, without the version.

--

*`user_agent.os.platform`*::
+
--
type: keyword

example: darwin

Operating system platform (such centos, ubuntu, windows).

--

*`user_agent.os.version`*::
+
--
type: keyword

example: 10.14.1

Operating system version as a raw string.

--

*`user_agent.version`*::
+
--
type: keyword

example: 12.0

Version of the user agent.

--

[[exported-fields-flows_event]]
== Flow Event fields

These fields contain data about the flow itself.



*`flow.final`*::
+
--
type: boolean

Indicates if event is last event in flow. If final is false, the event reports an intermediate flow state only.


--

*`flow.id`*::
+
--
Internal flow ID based on connection meta data and address.


--

*`flow.vlan`*::
+
--
type: long

VLAN identifier from the 802.1q frame. In case of a multi-tagged frame this field will be an array with the outer tag's VLAN identifier listed first.


--

*`flow_id`*::
+
--
type: alias

alias to: flow.id

--

*`final`*::
+
--
type: alias

alias to: flow.final

--

*`vlan`*::
+
--
type: alias

alias to: flow.vlan

--

*`source.stats.net_bytes_total`*::
+
--
type: alias

alias to: source.bytes

--

*`source.stats.net_packets_total`*::
+
--
type: alias

alias to: source.packets

--

*`dest.stats.net_bytes_total`*::
+
--
type: alias

alias to: destination.bytes

--

*`dest.stats.net_packets_total`*::
+
--
type: alias

alias to: destination.packets

--

[[exported-fields-host-processor]]
== Host fields

Info collected for the host machine.




*`host.containerized`*::
+
--
type: boolean

If the host is a container.


--

*`host.os.build`*::
+
--
type: keyword

example: 18D109

OS build information.


--

[[exported-fields-http]]
== HTTP fields

HTTP-specific event fields.


[float]
== http fields

Information about the HTTP request and response.


[float]
== request fields

HTTP request


*`http.request.headers`*::
+
--
type: object

A map containing the captured header fields from the request. Which headers to capture is configurable. If headers with the same header name are present in the message, they will be separated by commas.


--

*`http.request.params`*::
+
--
type: alias

alias to: url.query

--

[float]
== response fields

HTTP response


*`http.response.status_phrase`*::
+
--
example: Not Found

The HTTP status phrase.

--

*`http.response.headers`*::
+
--
type: object

A map containing the captured header fields from the response. Which headers to capture is configurable. If headers with the same header name are present in the message, they will be separated by commas.


--

*`http.response.code`*::
+
--
type: alias

alias to: http.response.status_code

--

*`http.response.phrase`*::
+
--
type: alias

alias to: http.response.status_phrase

--

[[exported-fields-icmp]]
== ICMP fields

ICMP specific event fields.




*`icmp.version`*::
+
--
The version of the ICMP protocol.

--

*`icmp.request.message`*::
+
--
type: keyword

A human readable form of the request.

--

*`icmp.request.type`*::
+
--
type: long

The request type.

--

*`icmp.request.code`*::
+
--
type: long

The request code.

--

*`icmp.response.message`*::
+
--
type: keyword

A human readable form of the response.

--

*`icmp.response.type`*::
+
--
type: long

The response type.

--

*`icmp.response.code`*::
+
--
type: long

The response code.

--

[[exported-fields-jolokia-autodiscover]]
== Jolokia Discovery autodiscover provider fields

Metadata from Jolokia Discovery added by the jolokia provider.



*`jolokia.agent.version`*::
+
--
type: keyword

Version number of jolokia agent.


--

*`jolokia.agent.id`*::
+
--
type: keyword

Each agent has a unique id which can be either provided during startup of the agent in form of a configuration parameter or being autodetected. If autodected, the id has several parts: The IP, the process id, hashcode of the agent and its type.


--

*`jolokia.server.product`*::
+
--
type: keyword

The container product if detected.


--

*`jolokia.server.version`*::
+
--
type: keyword

The container's version (if detected).


--

*`jolokia.server.vendor`*::
+
--
type: keyword

The vendor of the container the agent is running in.


--

*`jolokia.url`*::
+
--
type: keyword

The URL how this agent can be contacted.


--

*`jolokia.secured`*::
+
--
type: boolean

Whether the agent was configured for authentication or not.


--

[[exported-fields-kubernetes-processor]]
== Kubernetes fields

Kubernetes metadata added by the kubernetes processor




*`kubernetes.pod.name`*::
+
--
type: keyword

Kubernetes pod name


--

*`kubernetes.pod.uid`*::
+
--
type: keyword

Kubernetes Pod UID


--

*`kubernetes.namespace`*::
+
--
type: keyword

Kubernetes namespace


--

*`kubernetes.node.name`*::
+
--
type: keyword

Kubernetes node name


--

*`kubernetes.labels`*::
+
--
type: object

Kubernetes labels map


--

*`kubernetes.annotations`*::
+
--
type: object

Kubernetes annotations map


--

*`kubernetes.replicaset.name`*::
+
--
type: keyword

Kubernetes replicaset name


--

*`kubernetes.deployment.name`*::
+
--
type: keyword

Kubernetes deployment name


--

*`kubernetes.statefulset.name`*::
+
--
type: keyword

Kubernetes statefulset name


--

*`kubernetes.container.name`*::
+
--
type: keyword

Kubernetes container name


--

*`kubernetes.container.image`*::
+
--
type: keyword

Kubernetes container image


--

[[exported-fields-memcache]]
== Memcache fields

Memcached-specific event fields



*`memcache.protocol_type`*::
+
--
type: keyword

The memcache protocol implementation. The value can be "binary" for binary-based, "text" for text-based, or "unknown" for an unknown memcache protocol type.


--

*`memcache.request.line`*::
+
--
type: keyword

The raw command line for unknown commands ONLY.


--

*`memcache.request.command`*::
+
--
type: keyword

The memcache command being requested in the memcache text protocol. For example "set" or "get". The binary protocol opcodes are translated into memcache text protocol commands.


--

*`memcache.response.command`*::
+
--
type: keyword

Either the text based protocol response message type or the name of the originating request if binary protocol is used.


--

*`memcache.request.type`*::
+
--
type: keyword

The memcache command classification. This value can be "UNKNOWN", "Load", "Store", "Delete", "Counter", "Info", "SlabCtrl", "LRUCrawler", "Stats", "Success", "Fail", or "Auth".


--

*`memcache.response.type`*::
+
--
type: keyword

The memcache command classification. This value can be "UNKNOWN", "Load", "Store", "Delete", "Counter", "Info", "SlabCtrl", "LRUCrawler", "Stats", "Success", "Fail", or "Auth". The text based protocol will employ any of these, whereas the binary based protocol will mirror the request commands only (see `memcache.response.status` for binary protocol).


--

*`memcache.response.error_msg`*::
+
--
type: keyword

The optional error message in the memcache response (text based protocol only).


--

*`memcache.request.opcode`*::
+
--
type: keyword

The binary protocol message opcode name.


--

*`memcache.response.opcode`*::
+
--
type: keyword

The binary protocol message opcode name.


--

*`memcache.request.opcode_value`*::
+
--
type: long

The binary protocol message opcode value.


--

*`memcache.response.opcode_value`*::
+
--
type: long

The binary protocol message opcode value.


--

*`memcache.request.opaque`*::
+
--
type: long

The binary protocol opaque header value used for correlating request with response messages.


--

*`memcache.response.opaque`*::
+
--
type: long

The binary protocol opaque header value used for correlating request with response messages.


--

*`memcache.request.vbucket`*::
+
--
type: long

The vbucket index sent in the binary message.


--

*`memcache.response.status`*::
+
--
type: keyword

The textual representation of the response error code (binary protocol only).


--

*`memcache.response.status_code`*::
+
--
type: long

The status code value returned in the response (binary protocol only).


--

*`memcache.request.keys`*::
+
--
type: array

The list of keys sent in the store or load commands.


--

*`memcache.response.keys`*::
+
--
type: array

The list of keys returned for the load command (if present).


--

*`memcache.request.count_values`*::
+
--
type: long

The number of values found in the memcache request message. If the command does not send any data, this field is missing.


--

*`memcache.response.count_values`*::
+
--
type: long

The number of values found in the memcache response message. If the command does not send any data, this field is missing.


--

*`memcache.request.values`*::
+
--
type: array

The list of base64 encoded values sent with the request (if present).


--

*`memcache.response.values`*::
+
--
type: array

The list of base64 encoded values sent with the response (if present).


--

*`memcache.request.bytes`*::
+
--
type: long

format: bytes

The byte count of the values being transferred.


--

*`memcache.response.bytes`*::
+
--
type: long

format: bytes

The byte count of the values being transferred.


--

*`memcache.request.delta`*::
+
--
type: long

The counter increment/decrement delta value.


--

*`memcache.request.initial`*::
+
--
type: long

The counter increment/decrement initial value parameter (binary protocol only).


--

*`memcache.request.verbosity`*::
+
--
type: long

The value of the memcache "verbosity" command.


--

*`memcache.request.raw_args`*::
+
--
type: keyword

The text protocol raw arguments for the "stats ..." and "lru crawl ..." commands.


--

*`memcache.request.source_class`*::
+
--
type: long

The source class id in 'slab reassign' command.


--

*`memcache.request.dest_class`*::
+
--
type: long

The destination class id in 'slab reassign' command.


--

*`memcache.request.automove`*::
+
--
type: keyword

The automove mode in the 'slab automove' command expressed as a string. This value can be "standby"(=0), "slow"(=1), "aggressive"(=2), or the raw value if the value is unknown.


--

*`memcache.request.flags`*::
+
--
type: long

The memcache command flags sent in the request (if present).


--

*`memcache.response.flags`*::
+
--
type: long

The memcache message flags sent in the response (if present).


--

*`memcache.request.exptime`*::
+
--
type: long

The data expiry time in seconds sent with the memcache command (if present). If the value is <30 days, the expiry time is relative to "now", or else it is an absolute Unix time in seconds (32-bit).


--

*`memcache.request.sleep_us`*::
+
--
type: long

The sleep setting in microseconds for the 'lru_crawler sleep' command.


--

*`memcache.response.value`*::
+
--
type: long

The counter value returned by a counter operation.


--

*`memcache.request.noreply`*::
+
--
type: boolean

Set to true if noreply was set in the request. The `memcache.response` field will be missing.


--

*`memcache.request.quiet`*::
+
--
type: boolean

Set to true if the binary protocol message is to be treated as a quiet message.


--

*`memcache.request.cas_unique`*::
+
--
type: long

The CAS (compare-and-swap) identifier if present.


--

*`memcache.response.cas_unique`*::
+
--
type: long

The CAS (compare-and-swap) identifier to be used with CAS-based updates (if present).


--

*`memcache.response.stats`*::
+
--
type: array

The list of statistic values returned. Each entry is a dictionary with the fields "name" and "value".


--

*`memcache.response.version`*::
+
--
type: keyword

The returned memcache version string.


--

[[exported-fields-mongodb]]
== MongoDb fields

MongoDB-specific event fields. These fields mirror closely the fields for the MongoDB wire protocol. The higher level fields (for example, `query` and `resource`) apply to MongoDB events as well.




*`mongodb.error`*::
+
--
If the MongoDB request has resulted in an error, this field contains the error message returned by the server.


--

*`mongodb.fullCollectionName`*::
+
--
The full collection name. The full collection name is the concatenation of the database name with the collection name, using a dot (.) for the concatenation. For example, for the database foo and the collection bar, the full collection name is foo.bar.


--

*`mongodb.numberToSkip`*::
+
--
type: long

Sets the number of documents to omit - starting from the first document in the resulting dataset - when returning the result of the query.


--

*`mongodb.numberToReturn`*::
+
--
type: long

The requested maximum number of documents to be returned.


--

*`mongodb.numberReturned`*::
+
--
type: long

The number of documents in the reply.


--

*`mongodb.startingFrom`*::
+
--
Where in the cursor this reply is starting.


--

*`mongodb.query`*::
+
--
A JSON document that represents the query. The query will contain one or more elements, all of which must match for a document to be included in the result set. Possible elements include $query, $orderby, $hint, $explain, and $snapshot.


--

*`mongodb.returnFieldsSelector`*::
+
--
A JSON document that limits the fields in the returned documents. The returnFieldsSelector contains one or more elements, each of which is the name of a field that should be returned, and the integer value 1.


--

*`mongodb.selector`*::
+
--
A BSON document that specifies the query for selecting the document to update or delete.


--

*`mongodb.update`*::
+
--
A BSON document that specifies the update to be performed. For information on specifying updates, see the Update Operations documentation from the MongoDB Manual.


--

*`mongodb.cursorId`*::
+
--
The cursor identifier returned in the OP_REPLY. This must be the value that was returned from the database.


--

[[exported-fields-mysql]]
== MySQL fields

MySQL-specific event fields.




*`mysql.affected_rows`*::
+
--
type: long

If the MySQL command is successful, this field contains the affected number of rows of the last statement.


--

*`mysql.insert_id`*::
+
--
If the INSERT query is successful, this field contains the id of the newly inserted row.


--

*`mysql.num_fields`*::
+
--
If the SELECT query is successful, this field is set to the number of fields returned.


--

*`mysql.num_rows`*::
+
--
If the SELECT query is successful, this field is set to the number of rows returned.


--

*`mysql.query`*::
+
--
The row mysql query as read from the transaction's request.


--

*`mysql.error_code`*::
+
--
type: long

The error code returned by MySQL.


--

*`mysql.error_message`*::
+
--
The error info message returned by MySQL.


--

[[exported-fields-nfs]]
== NFS fields

NFS v4/3 specific event fields.



*`nfs.version`*::
+
--
type: long

NFS protocol version number.

--

*`nfs.minor_version`*::
+
--
type: long

NFS protocol minor version number.

--

*`nfs.tag`*::
+
--
NFS v4 COMPOUND operation tag.

--

*`nfs.opcode`*::
+
--
NFS operation name, or main operation name, in case of COMPOUND calls.


--

*`nfs.status`*::
+
--
NFS operation reply status.

--

[float]
== rpc fields

ONC RPC specific event fields.


*`rpc.xid`*::
+
--
RPC message transaction identifier.

--

*`rpc.status`*::
+
--
RPC message reply status.

--

*`rpc.auth_flavor`*::
+
--
RPC authentication flavor.

--

*`rpc.cred.uid`*::
+
--
type: long

RPC caller's user id, in case of auth-unix.

--

*`rpc.cred.gid`*::
+
--
type: long

RPC caller's group id, in case of auth-unix.

--

*`rpc.cred.gids`*::
+
--
RPC caller's secondary group ids, in case of auth-unix.

--

*`rpc.cred.stamp`*::
+
--
type: long

Arbitrary ID which the caller machine may generate.

--

*`rpc.cred.machinename`*::
+
--
The name of the caller's machine.

--

*`rpc.call_size`*::
+
--
type: alias

alias to: source.bytes

RPC call size with argument.

--

*`rpc.reply_size`*::
+
--
type: alias

alias to: destination.bytes

RPC reply size with argument.

--

[[exported-fields-pgsql]]
== PostgreSQL fields

PostgreSQL-specific event fields.




*`pgsql.error_code`*::
+
--
type: long

The PostgreSQL error code.

--

*`pgsql.error_message`*::
+
--
The PostgreSQL error message.

--

*`pgsql.error_severity`*::
+
--
The PostgreSQL error severity.

--

*`pgsql.num_fields`*::
+
--
If the SELECT query if successful, this field is set to the number of fields returned.


--

*`pgsql.num_rows`*::
+
--
If the SELECT query if successful, this field is set to the number of rows returned.


--

[[exported-fields-process]]
== Process fields

Process metadata fields




*`process.exe`*::
+
--
type: alias

alias to: process.executable

--

[[exported-fields-raw]]
== Raw fields

These fields contain the raw transaction data.


*`request`*::
+
--
type: text

For text protocols, this is the request as seen on the wire (application layer only). For binary protocols this is our representation of the request.


--

*`response`*::
+
--
type: text

For text protocols, this is the response as seen on the wire (application layer only). For binary protocols this is our representation of the request.


--

[[exported-fields-redis]]
== Redis fields

Redis-specific event fields.




*`redis.return_value`*::
+
--
The return value of the Redis command in a human readable format.


--

*`redis.error`*::
+
--
If the Redis command has resulted in an error, this field contains the error message returned by the Redis server.


--

[[exported-fields-thrift]]
== Thrift-RPC fields

Thrift-RPC specific event fields.




*`thrift.params`*::
+
--
The RPC method call parameters in a human readable format. If the IDL files are available, the parameters use names whenever possible. Otherwise, the IDs from the message are used.


--

*`thrift.service`*::
+
--
The name of the Thrift-RPC service as defined in the IDL files.


--

*`thrift.return_value`*::
+
--
The value returned by the Thrift-RPC call. This is encoded in a human readable format.


--

*`thrift.exceptions`*::
+
--
If the call resulted in exceptions, this field contains the exceptions in a human readable format.


--

[[exported-fields-tls]]
== TLS fields

TLS-specific event fields.




*`tls.version`*::
+
--
type: keyword

example: TLS 1.3

The version of the TLS protocol used.


--

*`tls.handshake_completed`*::
+
--
type: boolean

Whether the TLS negotiation has been successful and the session has transitioned to encrypted mode.


--

*`tls.resumed`*::
+
--
type: boolean

If the TLS session has been resumed from a previous session.


--

*`tls.resumption_method`*::
+
--
type: keyword

If the session has been resumed, the underlying method used. One of "id" for TLS session ID or "ticket" for TLS ticket extension.


--

*`tls.client_certificate_requested`*::
+
--
type: boolean

Whether the server has requested the client to authenticate itself using a client certificate.


--


*`tls.client_hello.version`*::
+
--
type: keyword

The version of the TLS protocol by which the client wishes to communicate during this session.


--

*`tls.client_hello.supported_ciphers`*::
+
--
type: array

List of ciphers the client is willing to use for this session. See https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4


--

*`tls.client_hello.supported_compression_methods`*::
+
--
type: array

The list of compression methods the client supports. See https://www.iana.org/assignments/comp-meth-ids/comp-meth-ids.xhtml


--

[float]
== extensions fields

The hello extensions provided by the client.


*`tls.client_hello.extensions.server_name_indication`*::
+
--
type: keyword

List of hostnames

--

*`tls.client_hello.extensions.application_layer_protocol_negotiation`*::
+
--
type: keyword

List of application-layer protocols the client is willing to use.


--

*`tls.client_hello.extensions.session_ticket`*::
+
--
type: keyword

Length of the session ticket, if provided, or an empty string to advertise support for tickets.


--

*`tls.client_hello.extensions.supported_versions`*::
+
--
type: keyword

List of TLS versions that the client is willing to use.


--

*`tls.client_hello.extensions.supported_groups`*::
+
--
type: keyword

List of Elliptic Curve Cryptography (ECC) curve groups supported by the client.


--

*`tls.client_hello.extensions.signature_algorithms`*::
+
--
type: keyword

List of signature algorithms that may be use in digital signatures.


--

*`tls.client_hello.extensions.ec_points_formats`*::
+
--
type: keyword

List of Elliptic Curve (EC) point formats. Indicates the set of point formats that the client can parse.


--

*`tls.client_hello.extensions._unparsed_`*::
+
--
type: keyword

List of extensions that were left unparsed by Packetbeat.


--


*`tls.server_hello.version`*::
+
--
type: keyword

The version of the TLS protocol that is used for this session. It is the highest version supported by the server not exceeding the version requested in the client hello.


--

*`tls.server_hello.selected_cipher`*::
+
--
type: keyword

The cipher suite selected by the server from the list provided by in the client hello.


--

*`tls.server_hello.selected_compression_method`*::
+
--
type: keyword

The compression method selected by the server from the list provided in the client hello.


--

*`tls.server_hello.session_id`*::
+
--
type: keyword

Unique number to identify the session for the corresponding connection with the client.


--

[float]
== extensions fields

The hello extensions provided by the server.


*`tls.server_hello.extensions.application_layer_protocol_negotiation`*::
+
--
type: array

Negotiated application layer protocol

--

*`tls.server_hello.extensions.session_ticket`*::
+
--
type: keyword

Used to announce that a session ticket will be provided by the server. Always an empty string.


--

*`tls.server_hello.extensions.supported_versions`*::
+
--
type: keyword

Negotiated TLS version to be used.


--

*`tls.server_hello.extensions.ec_points_formats`*::
+
--
type: keyword

List of Elliptic Curve (EC) point formats. Indicates the set of point formats that the server can parse.


--

*`tls.server_hello.extensions._unparsed_`*::
+
--
type: keyword

List of extensions that were left unparsed by Packetbeat.


--

[float]
== client_certificate fields

Certificate provided by the client for authentication.


*`tls.client_certificate.version`*::
+
--
type: long

X509 format version.

--

*`tls.client_certificate.serial_number`*::
+
--
type: keyword

The certificate's serial number.

--

*`tls.client_certificate.not_before`*::
+
--
type: date

Date before which the certificate is not valid.

--

*`tls.client_certificate.not_after`*::
+
--
type: date

Date after which the certificate expires.

--

*`tls.client_certificate.public_key_algorithm`*::
+
--
type: keyword

The algorithm used for this certificate's public key. One of RSA, DSA or ECDSA.


--

*`tls.client_certificate.public_key_size`*::
+
--
type: long

Size of the public key.

--

*`tls.client_certificate.signature_algorithm`*::
+
--
type: keyword

The algorithm used for the certificate's signature.


--

*`tls.client_certificate.alternative_names`*::
+
--
type: array

Subject Alternative Names for this certificate.

--

*`tls.client_certificate.raw`*::
+
--
type: keyword

The raw certificate in PEM format.

--

[float]
== subject fields

Subject represented by this certificate.


*`tls.client_certificate.subject.country`*::
+
--
type: keyword

Country code.

--

*`tls.client_certificate.subject.organization`*::
+
--
type: keyword

Organization name.

--

*`tls.client_certificate.subject.organizational_unit`*::
+
--
type: keyword

Unit within organization.

--

*`tls.client_certificate.subject.province`*::
+
--
type: keyword

Province or region within country.

--

*`tls.client_certificate.subject.common_name`*::
+
--
type: keyword

Name or host name identified by the certificate.

--

[float]
== issuer fields

Entity that issued and signed this certificate.


*`tls.client_certificate.issuer.country`*::
+
--
type: keyword

Country code.

--

*`tls.client_certificate.issuer.organization`*::
+
--
type: keyword

Organization name.

--

*`tls.client_certificate.issuer.organizational_unit`*::
+
--
type: keyword

Unit within organization.

--

*`tls.client_certificate.issuer.province`*::
+
--
type: keyword

Province or region within country.

--

*`tls.client_certificate.issuer.common_name`*::
+
--
type: keyword

Name or host name identified by the certificate.

--


*`tls.client_certificate.fingerprint.md5`*::
+
--
type: keyword

Certificate's MD5 fingerprint.

--

*`tls.client_certificate.fingerprint.sha1`*::
+
--
type: keyword

Certificate's SHA-1 fingerprint.

--

*`tls.client_certificate.fingerprint.sha256`*::
+
--
type: keyword

Certificate's SHA-256 fingerprint.

--

[float]
== server_certificate fields

Certificate provided by the server for authentication.


*`tls.server_certificate.version`*::
+
--
type: long

X509 format version.

--

*`tls.server_certificate.serial_number`*::
+
--
type: keyword

The certificate's serial number.

--

*`tls.server_certificate.not_before`*::
+
--
type: date

Date before which the certificate is not valid.

--

*`tls.server_certificate.not_after`*::
+
--
type: date

Date after which the certificate expires.

--

*`tls.server_certificate.public_key_algorithm`*::
+
--
type: keyword

The algorithm used for this certificate's public key. One of RSA, DSA or ECDSA.


--

*`tls.server_certificate.public_key_size`*::
+
--
type: long

Size of the public key.

--

*`tls.server_certificate.signature_algorithm`*::
+
--
type: keyword

The algorithm used for the certificate's signature.


--

*`tls.server_certificate.alternative_names`*::
+
--
type: array

Subject Alternative Names for this certificate.

--

*`tls.server_certificate.raw`*::
+
--
type: keyword

The raw certificate in PEM format.

--

[float]
== subject fields

Subject represented by this certificate.


*`tls.server_certificate.subject.country`*::
+
--
type: keyword

Country code.

--

*`tls.server_certificate.subject.organization`*::
+
--
type: keyword

Organization name.

--

*`tls.server_certificate.subject.organizational_unit`*::
+
--
type: keyword

Unit within organization.

--

*`tls.server_certificate.subject.province`*::
+
--
type: keyword

Province or region within country.

--

*`tls.server_certificate.subject.common_name`*::
+
--
type: keyword

Name or host name identified by the certificate.

--

[float]
== issuer fields

Entity that issued and signed this certificate.


*`tls.server_certificate.issuer.country`*::
+
--
type: keyword

Country code.

--

*`tls.server_certificate.issuer.organization`*::
+
--
type: keyword

Organization name.

--

*`tls.server_certificate.issuer.organizational_unit`*::
+
--
type: keyword

Unit within organization.

--

*`tls.server_certificate.issuer.province`*::
+
--
type: keyword

Province or region within country.

--

*`tls.server_certificate.issuer.common_name`*::
+
--
type: keyword

Name or host name identified by the certificate.

--


*`tls.server_certificate.fingerprint.md5`*::
+
--
type: keyword

Certificate's MD5 fingerprint.

--

*`tls.server_certificate.fingerprint.sha1`*::
+
--
type: keyword

Certificate's SHA-1 fingerprint.

--

*`tls.server_certificate.fingerprint.sha256`*::
+
--
type: keyword

Certificate's SHA-256 fingerprint.

--

*`tls.server_certificate_chain`*::
+
--
type: array

Chain of trust for the server certificate.

--

*`tls.client_certificate_chain`*::
+
--
type: array

Chain of trust for the client certificate.

--

*`tls.alert_types`*::
+
--
type: keyword

An array containing the TLS alert type for every alert received.


--

[float]
== fingerprints fields

Fingerprints for this TLS session.


[float]
== ja3 fields

JA3 TLS client fingerprint


*`tls.fingerprints.ja3.hash`*::
+
--
type: keyword

The JA3 fingerprint hash for the client side.


--

*`tls.fingerprints.ja3.str`*::
+
--
type: keyword

The JA3 string used to calculate the hash.


--

[[exported-fields-trans_event]]
== Transaction Event fields

These fields contain data about the transaction itself.



*`status`*::
+
--
required: True

The high level status of the transaction. The way to compute this value depends on the protocol, but the result has a meaning independent of the protocol.


--

*`method`*::
+
--
The command/verb/method of the transaction. For HTTP, this is the method name (GET, POST, PUT, and so on), for SQL this is the verb (SELECT, UPDATE, DELETE, and so on).


--

*`resource`*::
+
--
The logical resource that this transaction refers to. For HTTP, this is the URL path up to the last slash (/). For example, if the URL is `/users/1`, the resource is `/users`. For databases, the resource is typically the table name. The field is not filled for all transaction types.


--

*`path`*::
+
--
required: True

The path the transaction refers to. For HTTP, this is the URL. For SQL databases, this is the table name. For key-value stores, this is the key.


--

*`query`*::
+
--
type: keyword

The query in a human readable format. For HTTP, it will typically be something like `GET /users/_search?name=test`. For MySQL, it is something like `SELECT id from users where name=test`.


--

*`params`*::
+
--
type: text

The request parameters. For HTTP, these are the POST or GET parameters. For Thrift-RPC, these are the parameters from the request.


--

*`notes`*::
+
--
type: alias

alias to: error.message

Messages from Packetbeat itself. This field usually contains error messages for interpreting the raw data. This information can be helpful for troubleshooting.


--

[[exported-fields-trans_measurements]]
== Measurements (Transactions) fields

These fields contain measurements related to the transaction.



*`bytes_in`*::
+
--
type: alias

alias to: source.bytes

The number of bytes of the request. Note that this size is the application layer message length, without the length of the IP or TCP headers.


--

*`bytes_out`*::
+
--
type: alias

alias to: destination.bytes

The number of bytes of the response. Note that this size is the application layer message length, without the length of the IP or TCP headers.


--

