// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package awscloudwatch

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "awscloudwatch", asset.ModuleFieldsPri, AssetAwscloudwatch); err != nil {
		panic(err)
	}
}

// AssetAwscloudwatch returns asset data.
// This is the base64 encoded gzipped contents of input/awscloudwatch.
func AssetAwscloudwatch() string {
	return "eJxUzLENwjAQhtH+pviUHgZwQckexv4RJ0wc2RdFbJ867Sveja/+iXzM0vpejxzlYxAeTYnl4otB1SzDt/C+Jh4G8HS1OnmP/rs++LrtcTcYaspTiZci2xkAAP//DHMnag=="
}
