// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package awscloudwatch

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "awscloudwatch", asset.ModuleFieldsPri, AssetAwscloudwatch); err != nil {
		panic(err)
	}
}

// AssetAwscloudwatch returns asset data.
// This is the base64 encoded gzipped contents of input/awscloudwatch.
func AssetAwscloudwatch() string {
	return "eJyskUFqwzAQRfc6xSf75ABaFEqhF2ghy6BaE2uIrDHSpMK3L7IDsdsu2lItP/P/e6A9LjRZuFq6KFdfnXbBAMoayWK3yXcG8FS6zKOyJIsHAwDPTNEXnLMMeDy+4KkVjq2AKH05GOA8n9j5fI/kBvqKbE+nkSz6LNfxlnzD+yGzvTV3zY7Sn9aUO/tCU5XsV/nG4DXQPAE5QwO1oUUXKqiBuwANXEDvlBRvFCXdbbb8opnc8B8Cy9LvDDj1VNrkSXmgv1i03qywkKort1Hy4PTpVw7mIwAA//80Mb5N"
}
