// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package oracle

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "oracle", asset.ModuleFieldsPri, AssetOracle); err != nil {
		panic(err)
	}
}

// AssetOracle returns asset data.
// This is the base64 encoded gzipped contents of module/oracle.
func AssetOracle() string {
	return "eJzsVrFy2zAM3f0VOE/tkHyAhk65rh7ardfTQRKk4EyROhK62vn6HqU4liXScmK2UzTZIPXeA/FA4QH2dMzAWCwVbQCERVEG290Q2G4AKnKl5U7Y6AzGMFQoWKAjaE3VD++5Z2MlL42uucmgRuV81JIidJQBHTqy3JIWVH43ibBuXAa/toKFItdhSdvfG4CaSVUu2wAAPIDGlibq/CPHjjJorOm710hI4Zsw/0wxp7hn6relEP6CI/jenGRKVChT7nPHL/RYHIXcxaYTpTK6mS1csP7cPe2C6FWBeW2J8rmkeDoL8KfhT0EO5JnAowEdhLQ4YA2o1CTpIeS3nWwwAw6dxFltzYpyrmarVw5hpvQ7KwKuSAvXTBZ03xZkwdSjcr9aGi3ImnUzxMZEInLG0tyh54eg9WYekWZyrlMHrPAOXn6hSxr4wnoE/XotWfcoZmzDpMSvjTdSnAVEHSvUdrkv18cMu+iGmO/m2S+Wr2a+zrpWz2TwrJ2gLoPNk4wk1p1JCfyvKMOejn+MDSm4naTFQxQ/5Kzb0OMOg1tcBmuHuFDxLbIJYvrWvfjPRZwEOEHp492Qosq9I/tZ5v9b5pXr/M4p5AOXOiplShSqgpPV6jm84+KyFJ7eEnIMM1Z8TkzIlPRj8jcAAP//3A345A=="
}
