FROM alpine:3.16

ENV PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/go/bin

WORKDIR /usr/share/filebeat

COPY build/filebeat /usr/share/filebeat/filebeat

ENTRYPOINT ["./filebeat"]

CMD [ "-e" ]
