:type: container

[id="{beatname_lc}-input-{type}"]
=== Container input

deprecated:[7.16.0]

The container input is just a preset for the <<filebeat-input-log,`log`>> input. The <<filebeat-input-log,`log`>> input has been deprecated since 7.16.0, therefore the container input is also deprecated. Please use the <<filebeat-input-filestream,`filestream`>> input and its <<filebeat-input-filestream-parsers-container,`container`>> parser instead.

Example configuration of using the <<filebeat-input-filestream-parsers-container,`container`>> parser with the <<filebeat-input-filestream,`filestream`>> input:

["source","yaml",subs="attributes"]
----
{beatname_lc}.inputs:
- type: filestream
  id: unique-input-id <1>
  take_over: true <2>
  prospector.scanner.symlinks: true <3>
  parsers:
    - container:
        stream: stdout
        format: docker
  paths: <4>
    - '/var/log/containers/*.log'
----

<1> all <<filebeat-input-filestream,`filestream`>> inputs require a <<filebeat-input-filestream-id,`unique ID`>>.
<2> <<filebeat-input-filestream-take-over,`take_over: true`>> would migrate all states from the previously used container input to the <<filebeat-input-filestream,`filestream`>> input.
<3> container logs use symlinks, so they need to be <<filebeat-input-filestream-prospector-scanner-symlinks,`enabled`>>.
<4> `paths` is required.

++++
<titleabbrev>Container</titleabbrev>
++++

Due to deprecation of this input, it's possible to use it only in combination with the `allow_deprecated_use: true` setting as a part of the input configuration.

This input searches for container logs under the given path, and parse them into
common message lines, extracting timestamps too. Everything happens before line
filtering, multiline, and JSON decoding, so this input can be used in
combination with those settings.

Example configuration:

["source","yaml",subs="attributes"]
----
{beatname_lc}.inputs:
- type: container
  paths: <1>
    - '/var/log/containers/*.log'
----

<1> `paths` is required. All other settings are optional.


NOTE: '/var/log/containers/*.log' is normally a symlink to '/var/log/pods/*/*/.log',
so above path can be edited accordingly


==== Configuration options

The `container` input supports the following configuration options plus the
<<{beatname_lc}-input-{type}-common-options>> described later.

===== `stream`

Reads from the specified streams only: `all`, `stdout` or `stderr`. The default
is `all`.

===== `format`

Use the given format when reading the log file: `auto`, `docker` or `cri`. The
default is `auto`, it will automatically detect the format. To disable
autodetection set any of the other options.


The following input configures {beatname_uc} to read the `stdout` stream from
all containers under the default Kubernetes logs path:

[source,yaml]
----
- type: container
  stream: stdout
  paths:
    - "/var/log/containers/*.log"
----

include::../inputs/input-common-harvester-options.asciidoc[]

include::../inputs/input-common-file-options.asciidoc[]

[id="{beatname_lc}-input-{type}-common-options"]
include::../inputs/input-common-options.asciidoc[]

:type!:
