# beats contains the list of beats that are FIPS-enabled
beats:
  - agentbeat
  - auditbeat
  - filebeat
  - metricbeat
compile:
  env:
    # See https://go.dev/doc/security/fips140#go-cryptographic-module-v100
    # CMVP Certificate #5247: https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/5247
    # CAVP Certificate A6650: https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?product=19371
    GOFIPS140: v1.0.0
  tags:
    - requirefips
  platforms:
    # If the platform list changes, update the platforms for FIPS packaging in CI pipelines '.buildkite/**/pipeline.<beat>.yml' and '.buildkite/packaging-pipeline.yml'
    - linux/amd64
    - linux/arm64
