// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package postgresql

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "postgresql", asset.ModuleFieldsPri, AssetPostgresql); err != nil {
		panic(err)
	}
}

// AssetPostgresql returns asset data.
// This is the base64 encoded gzipped contents of module/postgresql.
func AssetPostgresql() string {
	return "eJyclE1P20AQhu/5Fa84QQUWVQ+VXKkXBCdoS+EebbxjZ9X1zrI7pri/vlqbkODYadw5RVnN+zz7Mb7AL2pzeI5SBYpPdgGIEUs5Tn70fz7c354sAE2xCMaLYZfj6wIA7lg3llBygFchGldB1oRtHyxXKI2lmC2AuOYgy4JdaaocEhpaAKUhq2Pe5V3AqZoGNqmk9ZSjCtz4139GbPq66fJQBq4HIp1Dql3kLtZytRO0zzzIfU8+dAybGmrsqoipKYqq/bvVhPeBCiWkc3zOPmWXe+uTeqke17SN3pomPWscZaMuBQdaGj0I64/HsqvmKVxxIAzSNiStRK1UpEETvajady+ybvXqZB7vm6oJXI5nb8BPDYV2kvpwfXt99YgPuPn5/Q5NpBC/zLS4TwBEUUI1ORk/6M5iGYWGt75VSWNGM9kPGypSNH6vyaHphpVehJwm3ZPhAwsXbHHKrjuzN9/zbr7pHCvjNDiAXqhohM4O7CP9nt6H5mWUWpaXfX38n1utzDM5CEO9buDfW3sLGhWnEDhkBeuh+HGP/Tq1I7UjkDTBkcaq3XwHIk5NCeXas8MSaT7/sBtXUNaoOFjxStY56Dm9q4nm2lRB9ZKvn90R7jqQ0lODPg32gQuKMfN7ncdQ0zTNBKaWbOR1HYOz9Ex2Js9ylY31HcOrKUZVzb3L8a4h728AAAD//1GCBzo="
}
