[[release-highlights-7.6.0]]
=== 7.6 release highlights
++++
<titleabbrev>7.6</titleabbrev>
++++

Each release of {beats} brings new features and product improvements. 
Following are the most notable features and enhancements in 7.6.

For a complete list of related highlights, see the 
https://www.elastic.co/blog/elastic-observability-7-6-0-released[Observability 7.6 release blog].

For a list of bug fixes and other changes, see the {beats}
<<breaking-changes-7.6, Breaking Changes>> and <<release-notes, Release Notes>>.

//NOTE: The notable-highlights tagged regions are re-used in the
//Installation and Upgrade Guide

// tag::notable-highlights[]

[float]
==== Support added for TLS 1.3

In 7.6, we've added support for TLS 1.3, enabling you to take advantage
of the security and performance improvements available in TLS 1.3 when {beats}
connects to an {es} cluster that supports it.

TLS 1.1, 1.2, and 1.3 are now enabled by default.

[float]
==== Azure cloud monitoring improvements

The new {metricbeat-ref}/metricbeat-metricset-azure-storage.html[`storage`]
metricset in the {metricbeat} {metricbeat-ref}/metricbeat-module-azure.html[Azure
module] adds the ability to collect metrics from storage accounts.

We've also made it easier for you to do a cost analysis on metrics
collection by adding a cost warning message to each metrics API call. The
message indicates the cost applied while retrieving metric values from Azure
resources.

[float]
==== Google cloud monitoring improvements

Starting with 7.6, you can deploy {functionbeat} as a Google Function via Google
Cloud Deployment Manager and pull log events from
https://cloud.google.com/pubsub/[Google Pub/Sub] and
https://cloud.google.com/storage/[Google Cloud Storage]. 

We've also expanded support in {metricbeat} by adding a beta release of the
{metricbeat-ref}/metricbeat-module-googlecloud.html[Google Cloud Platform module].
This module fetches monitoring metrics from Google Cloud Platform (GCP) by using
the
https://cloud.google.com/monitoring/api/metrics_gcp[Stackdriver Monitoring API]. 

On the logging side, we've added two new filesets to the {filebeat}
{filebeat-ref}/filebeat-module-googlecloud.html[Google Cloud module] to make it
easier for you to ingest Gloogle Cloud logs:

* The `audit` fileset parses
https://cloud.google.com/logging/docs/audit/[Google Cloud Audit Logs].
* The `firewall` fileset parses firewall logs generated by firewall rules
logging.

[float]
==== Better support for document deduplication

To help prevent duplicate events, we've introduced `document_id` settings
in {beats} that you can use to set the document ID _before_ sending events to
an output. The ID is stored in the {beats} `@metadata._id` field and used to
set the document ID during indexing. Both the `decode_json_fields` processor and
`json` options in the {filebeat} have been enhanced to include a
`document_id` setting to use when decoding JSON data. 

We've also added new processors for generating IDs when your data has no natural
key field. The {filebeat-ref}/add-id.html[`add_id`] processor generates a unique
ID for an event. The {filebeat-ref}/fingerprint.html[`fingerprint`] processor
generates a fingerprint of an event based on a specified subset of its fields.

To learn more, see {filebeat-ref}/filebeat-deduplication.html[Data
deduplication].

//Description

// end::notable-highlights[]
