BEATNAME=topbeat
SYSTEM_TESTS=true

# Only crosscompile for linux because other OS'es use cgo.
GOX_OS=linux

include ../libbeat/scripts/Makefile

# This is called by the beats packer before building starts
.PHONY: before-build
before-build:

