// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package appsearch

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "appsearch", asset.ModuleFieldsPri, AssetAppsearch); err != nil {
		panic(err)
	}
}

// AssetAppsearch returns asset data.
// This is the base64 encoded zlib format compressed contents of module/appsearch.
func AssetAppsearch() string {
	return "eJzs171u2zAQB/DdT3Hw3PgBNBQI2qEtkKBogXYoCoUS/5aY8Csk5URvX1CKVVm2IseFraUcaevux/OZIq/oAXVCzFoP5vJyQRREkEhoeW0tfW8mlwsiBwnmkVCGwBZEHiEIXfiEfi29l8t3tCxDsMvfCyIOnzthgzA6ofcLIqK/wUgZXkksiNYCkvuk+fyKNFPYhcQRaouECmcq+zJzIPhuqH44H1jw3eyhcHEM17YdB1O1o7eeYY6hpe+536id+THRRPY4vvy42Us9lr5PUFDG1WnlWYG9L73mOcIUx00Tn8bij/H6xBLMpkKLsMrqgOECd6XS6GLkC0dg4/gEZilmo8qDU1ZTKNGUV2hqAKtpbXz0ctp/gOZGKRHChbQfttma5BTMKWTFni+CvWHPLXOsvK9StdHpZRv31uirrnkFky9/7RO7o/NftkO6RXRp37aMLf+xQrWHPXlz/WncA9zhoFMbLNNM1kHkPsUGOvhVbiodRrfakRIeUb7bSmVwZNZkobnQBd2bzMc6xZLdDR137XL2u2AL5yavFHRIOXxwpoabi74vmcRDF0JjfvrQMQkXmuM5ZZzPZ+4RjuOCp9zkqYMym5nZu5RJvmJCzidus08iHdYOvky7v0HDnW0jGeEcsYz2F5qt3B1gkurzEoqlleUszOfdVUyi17Gb+AWwbaLW+sREvPfFo1wGcghOgB9+JTs8VvB7F5STX8rf2nikYtL8ra/l85fJIYcOso5HGSsRjzIjJejfd8WKV47FDOe4jV1//UwO3hrtQUEojFSPjryasU2xUuc+E15v4FiBAVxoUkJK4ZEbzV8/jMcrw9mZ8b7wNuKW94RstX0yjU+e46f/yHyZGeb4/wY4E3O6Af4EAAD//2c12Ks="
}
