// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package mariadb

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "mariadb", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzMlk1v8zYMx+/5FETPfXwYMAzIYcC2rkCBFtjQAjumikzbRGTRo+S8fPuBctJ4jpM2abanPFoW/z9SFKlvsMDNFGojZPL5BCBSdDiFmyf9cvfrzQQgx2CFmkjsp/DzBADgifPWIRQs0BgJ5EuIFcJ2EzguoSCHIZsACDo0AaeA6waFavTRuAlAqFjizLIvqJxClBYnAAWhy8M0iXwDb2rsw6nFTYNTKIXbZvtlhE/tPrmCQrg+DqfW1+zrogjL29cxZbVj4e3sCJ3ab+yjIR+2BD3UzfOfj52+4r6RjtH2iSPVGKKpm3+tnmRQe6lwv3VPoYly5DEb16oETT6jfOCuy5JjX54H8UsALraR/5j9lP1wC7GiABQSTCcHlGdwz7L9b4kSiH2ARogFIvd3HiikzIHdJV29NsIWQ1C3o0E6XKIbOMK1qZt0R/4y4smXNycCHc11Sqx6HhetMQRT4mheI67j+YfruCwx3znODio9OF45Lr9jrSvBWaXeBpTzE9GJ6V6IlYlgBU3EPIH83aJsxk/EtiLo4+x/Fa04XHDUuqtL7qpCwSRyQnpXGuSPRO5IA/8SLHRBW3v4A0yei97xqyfly/Ckn2bawbOAdrRvFI7NBScYORqXZkOPJjIvboE8BLTs83ALJoDpJPQl0DD5CL6t5yhH2irbxX/Ca2pufdRBMmBeGdKU6oOlG212oeNijmCWhpyZO8zUw4HXpXEt6hD6TLzCqzAL6IcRXTorNdROT0NV7yAYW/GYw3zzXmNJNDrFyOO1pvcIUbDGfwzo2LPlMzCtp3XvURPNAv1+6Lw+//6yX309BZeWztdPA+2E26u9m1TMsvdo9Q94uHsr8hPqwVZYm1GCBW5WLEO6j0ScfPY62u7mBcA12jYOiu2gGYzi5CYOF95heUx3e+ivX2tXEnrRFnN2uF2ztsZWOKtovCNcdAYPRQ+joghJ44K3+1B98k8AAAD///pfzIw="
}
