// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package etcd

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "etcd", asset.ModuleFieldsPri, AssetEtcd); err != nil {
		panic(err)
	}
}

// AssetEtcd returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/etcd.
func AssetEtcd() string {
	return "eJzMl8+O2zYQxu9+ioEvbYHGD+BDL0kOPRQogtyKohmTnyxiKVIhh3b89gVl2StZknfXUpDosFjI5MffzHD+6B094bQliNIrIjFisaX1R1F6vSLSiCqYWox3W/pjRUTNSvrL62SxIgqw4Igt7XlFFCFi3D5u6Z91jHb9O61LkXr974qoMLA6bhuNd+S4wvXU/MipzirBp7p9M3J2fr7kTV9IeSdsXKQoLCaKUZGkZKEjAiiANRXBV/Tx+YguQZfCgjXC9fUYyx2e/Ly/wDTOOet1wDadxX2HXZ5btC5e4a31R4S4UT45ib1FU7AvAOfncwlyqdohkC+oYGOhiZ2mmJRCjEWy9IkLoU9/v6eArwlReqZMgd+D37Tigw0XQ4wT7HvRGDXnHuPrYbLRc0lax01TDP8ZZ7IscOq0VHip1SPxBFYl1UAg40hKkLIpysC21wez1d7wAYH3mPRhVGyh/yusZ3mDrEohwA13zJSt+JupUrW4rHF3Zacu0q3iVTAKO81Bf8DBcI7v24kna9vz3iecjj7oe7fqzw+5NLCSxPZWalBGI2yxXBHNaouVUHNr5as9MMirnD3Jma8JZDScmMIgUOFD80uFXE/vZ/zZj8YVfjMvOsOcNzrHq0nwcwZdetEN1wROFA4iprrN5xlEmSUr0rFELj0mkvMadOSmcweBfokq1csicZWLf+OoDJYJWy+VHGkHuMmr3iXMf5f0k4ltlH6Jfe3R0wPUYcN1DafbhnPuaaNE4wXoBaLn0eB8zLWxdaKYHVYHnzvxRBwbzh07fTRaysAy7rM7lffVmLuTIFKdJy8o73SH08QMAnMwbk+/XuoteWdPv01j10/77wp8dejjzKPwEU5/37sxZkQzfPevRrzt4T3Cn+FWZJDGv20FaLy7oc95zYFtahYlp1EYB03eUTRuby+F/jJH3YzFPTN/+C1a3sZxY39s85himvD8QzwwUiJcuoUP18ltOAuJD5gzDOWPs0ak+31rnLIpB9UVPlTNZEi880kaT/kaoXk3moslO22h581Re0x+wU1Xk97mkS+u8Z0TCTXj/Dj/fA0LwcME7fZ5DKnWPIOh3T6PQQXMYWi3z2TwVc0B7HQ8cv04S19mKaaZN2Ug9HauUV18q03AG8aBUZUjiyoR7pv1fwAAAP//Jlp0/Q=="
}
