// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package etcd

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "etcd", asset.ModuleFieldsPri, AssetEtcd); err != nil {
		panic(err)
	}
}

// AssetEtcd returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/etcd.
func AssetEtcd() string {
	return "eJzMmc1v28YSwO/+KwbO4eU9vLB3H3qoYxRB66SwjQRFUSij3SG59XKX2RlaUf76Yvkh64OkJFN2okMQyNyZ38wO50tv4J6WF0Ci9BmAGLF0AedXovT5GYAmVsGUYry7gJ/PAKB+Eq69riydAQSyhEwXkOEZAJOIcRlfwF/nzPb8/3Cei5Tnf58BpIas5otaxhtwWNBKa/zIsoxSgq/K9pse3fHzOR76DMo7QeMYWFAMi1EMkqPAggJBINSQBl/A1aOKdYJ1CkuoKay+7mMZ4Ymfyw6mdk4jbw0sWXt402HdZxttHS/11voFBU6Ur5zwxkNDsHuA4+cuJ3BVMacAPoUUjSUN6DRwpRQxp5WFG0wFbv64hEBfKmLZMGUIfAw+aYXvHOgMMU4o27iNXnPGGA+HiUZPJWkdN0yx+59+JotCTi1Pdb3QygPxQKhyKIkCGAeSEyhbsezYdvhltrITfKCAGQ36kBVa0rPUepQjxKoqBHK7JyaKLfCrKari5GKNGxU7FEjbElcCWdBpDPotPRiM93s88WBuezx7T8uFD3osqt69jakBlVRot0XtpNGCJBjFU/JoTNadnCZ9x2D9qfuGnC692YiLVTqdk+xLqK/g9urm49XN+AvJFB4oJDnybMR586VsR/2e9/FTTpJTAOzqA301LDz0Ro6xNQJmKkeXUZvMeimtd9lxlO9XBaGlbJUAEzlAOZq1DL70jJZnyheFESH9TMDKOybHFcNKJzQ6SR+JWpLTxmUvCNpqPJKzqT0viNkoPIgyC6WasWB4vhtncgLZeNEdIsvR6efzXSBF5oH0IXSv4O2729/GybXh+6R4UGqm5zPxgnbG5hslMQ31N4Q99KkPBUqTu7YP7bHs1nyj2uPiA2nQKBiTwfXHy8sDwBdoZykvnZrpKtQFLXGczCt1T5L8rxffz/8htX0vzZezp17P721DlPoAi2DipAKYx0nB+oxjnxRpjzXjlAH0KRihdaZd4QcQ8U4vcjKerqdcVzGMN0d1T063mf/Hu/yWb1Xj9kbAiEGnDINfOq5azd4oGKE6XShsM+2NhFdwfXX94ebP8TgpqPBhmWR+VlARJ2aeobVevVhmu64BoFaKQrqRAcgx3V1TcRuZ4Fc/ZOT7q7tPH272pG9HsvDhPlHWkJNZUxrJyYtZWZehulw25tUl5Hjmrqy9LPeqmPaxP9Z2m04ZPTZXOFHayRY4ZnvGOnj+2nFI7L4rZ75UBEaTE5MaCnVOi38pKPYf49fatPXGpT6ZNhvuXpbR8Z2pB4Rmfu9miC2uAZy6VxRTbM9VE4giS5QIi5zimGUYnNcEC6z3hmF9MhigqsrTImERk3ntqAgWCVsv5cgwj1PW0KC9Thj/PaWfDLe39B/elN2rPZB6SLCMQ0vb247Uv/71xx6ix8Vko2bVQ6/dYnRYGbwi5oF7rDnn6PTCaMkD7szse/c+B2M2uamkAEzKO73GabhNYbHneN1te8A7u/zvMHZ5nz0r8MqhT2ceGLKcft7Y6DOiXv1vhgZvbxA3CH+EqOBm6IfXbQaovZvAXXzmAW1VP1Q5TalxpME7YOMy2yX6bg+ztZTfMPO7R9Hpbew39vsWjyGmAc8/iYdMvT/s/BhWe+PdXihO6VOaobucGiHrv64Zp2wVL9U1DZ3xDnDuq2Yn6Etqxo7ed7HbtkzqozIa/P1oOJtsHO75vaf/5MALNUE/T9evyZLQkwna49MYqlLjBIb2+DQGFWgKQ3t8IoMvSgyETvMCy6ezbIo5FdPESNkRdDxXr1z6WppAR7QDvVIWKCqnMG7WvwEAAP//akLCUA=="
}
