== Creating a Metricbeat module

Metricbeat modules are used to group multiple metricsets together and to implement shared functionality
of the MetricSets. In most cases, no implementation of the module is needed and the default module
implementation is automatically picked.

It is important to complete the configuration and documentation files for a module. All these files are in the `_beat`
directory and a default version is generate when using `make create-metricset`.

[float]
=== Module files

* config.yml and config.full.yml
* docs.asciidoc
* fields.yml

Make sure that after updating any of these files to run `make collect` in your beat directory so all
 generated files will be updated.


[float]
==== config.yml and config.full.yml

The `config.yml` contains the basic configuration option and looks as following:

[source,yaml]
----
include::../../scripts/module/config.yml[]
----

It contains the module name, your metricset and the default period. In case you have multiple
metricsets in your module, make sure to extend the metricset array:

[source,yaml]
----
  metricsets: ["{metricset1}", "{metricset2}"]
----

The `full.config.yml` is optional and by default has the same content as the `config.yml`. It is used
to add and document more advance configuration options which should not part of the minimal
config file which is shipped by default.

[float]
==== docs.asciidoc

The `dosc.asciidoc` contains the documentation about your module. By default during generation of the
documentation the default config file will be appended to the docs. Use this file to describe your
module more in detail and more specific configuration options.

[source,asciidoc]
----
include::../../scripts/module/docs.asciidoc[]
----

[float]
==== fields.yml

The `fields.yml` contains the top level structure of all your metricset. In combination with the fields.yml
in each metricset it is used to generate the template and the documentation for the fields.

The default file looks as following:

[source,yaml]
----
include::../../scripts/module/fields.yml[]
----

Make sure to update at least the description of the module.


[float]
=== Testing

It is a common pattern to use a `testing.go` file in the module package to share some testing functionality among
the metricsets. This file does not have `_test.go` in the name as otherwise it would not be compiled for sub packages.

For example of the `testing.go` file is is best to check out the https://github.com/elastic/beats/tree/master/metricbeat/module/mysql[mysql module].
