
include::./create-metricset.asciidoc[]

include::./testing.asciidoc[]

[[metricbeat-developer-guide]]
= Metricbeat Developer Guide

[partintro]
--

Metricbeat is periodically interrogating other services to fetch key metrics
information. As a developer Metricbeat can be used in two different ways:

* As application to extend
* As library

That means as a contributor you have different options on how to use metricbeat
and how to contribute.

If you are looking to contribute in general to beats or the foundation of
metricbeat, also have a look at the general contributor guide (add link here).

--

== Overview

Metricbeat consists of modules and metricsets. A metricbeat module is normally
called the same as the service the metrics should be fetch from (e.g. redis,
mysql, ...). Each module can contain multiple metricsets. A metricset represents
multiple metrics which are normally retrieved with one request from the remote
system (e.g. redis-info, mysql-status).


== Module & Metricsets Requirements

It is important for us that only high quality modules are part metricbeat to
guarantee the best user experience. Modules and Metricsets which are contributed
must fulfill the following requirements:

* Elasticsearch templates
* Kibana Dashboard
* Documentation
* Integration tests with docker environment
* 80% test coverage (unit, integration, system tests combined)

Metricbeat allows to build a wide variety of modules and metricset on top of it.
The module which will be accepted should be focused on fetching service metrics
directly from a service itself and not via a third party tool. The goal is to
have as few movable parts as possible and that metricbeat runs as close as
possible to the service which should be monitored.




== Documentation

Each module must be documented. The documentation is based on asciidoc and is in
the file \{module-name}.asciidoc in your module folder. This file contains the
documentation for the module itself and the containing metricsets. For details
on what should be documented, check the existing documented modules.

== Dashboards

TODO: Add details on how to create dashboards



