// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package mysqlenterprise

import (
	"github.com/elastic/beats/v8/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "mysqlenterprise", asset.ModuleFieldsPri, AssetMysqlenterprise); err != nil {
		panic(err)
	}
}

// AssetMysqlenterprise returns asset data.
// This is the base64 encoded zlib format compressed contents of module/mysqlenterprise.
func AssetMysqlenterprise() string {
	return "eJzsWEFv20YTvedXzNEGFOc7fIdChwKBkwAG0sRFHfQorMghOTC5y8zMSmZ/fTG7lExZSi21idA25cGwdnd23rzZnXnkS7jHYQ7dIJ9b9IrcMwm+AFDSFufw0/DLz+/h7XSmRCmYeqXg5/DjCwDYWwWvY0kKXShjayYVYVvKPK19Cd51eMilPTr0OIeaQ+zHkQPu7HmXtoSKQ7fv/n2oZVw5dT117wzhdvSQY3sYW3SCc1iiusn4F0AlLlLQUAWG3rGQr79EzwTlIaRTtEXrRHZmNojvcVgHLp/M/QE+e16DKBsyxp5R0Kv90AYBV+g1u7uCuwbzv1BiRR4lLTG/EKq8dAbrBj2ou7e/oUZtkGFN2ky2I8UOtHEK0mNBFY075VmJy+xvC/MwBcF7LCyiBT0N969Q4YG8Yo28T0bRUmJj6xmotOmKkI0dEqAcibgOweX/V66NCIwa2WMJyyGNXn/88OHt9d3Nxw+LmzcXl1BFn7c0rsjnXVCEgn+GiK8cffRCtQE9SIPzY5Zu3hyfn9Kpu5r8NoBfD/NdYqqITDqAqNN0GlO+HhOlYWSUV5arW+SOVLHM2RFwjKBF/4p6uLi7vn11czu1RlG3bEkaLFN+QlRAX/CQQF3OQKQ9xu6JUSjuUeHik6eHzY+K2inuy1lis1z01CNc/Eq+DGvJY5DGdtY6X4I0jrFcdNgFHh5N8jCMwxOrE9NoBMfDpacNvv6Kly10XYonOZzD/1IJlVgUKDIDH/xvyAGoSmeSOTCEoojMWJ4YUrn81pXUgTlaOsEE4QreBX4KYwakm/JRYuViq1urbGBnCRcuEbBnkiYfDf703XSqTMuoeDjHVetU0eOJtFw/3olHB7kFdFQ3CkuE3onk+lhSVSFblcmd8jrV3ecaQo0e2bWbiNLpOUeL3PQ/8qIcx3JjkWVAVmRsWRIYmyYpsWisP7jtMU8WjyUKGAukFZZZ0bix95xCgXxuF9+OhoSXfEmF07F9W6pS/e0sdebkFLifI/Jwlnzhg1q+nN9FnPVN7taF83Ykset1uIL3wdebRtG5wWaUo7fIy2yVfc2gpXucZLsNda7opIJtNbPLumZrPB5ikoKf7t69/AEuYm8d6v+wHIzMHhmKxrErFDk1iomQ2ABoTFOIVYlQ2YVeIR8hFnZPyD+hlj+jq8ZWn94eFsjsw8UlXMPr25utpHqGkjbU5K+iIJ/j9JGvAncuq8d8fWyqCevtJd+UZyscO7LlmDh6Dg9nuUbJERht04tDki+N5dLm8jKzIQEfrGQAVhUWz5UyaaKWYb1RHYmAswn9sQbfvDny9G3hgQxiLzcrx2QN+bkg1bHG/vuJMV/TsVT9u+LcU2ffoa7c5yCNfHsaMsrEwakI/9Md59Ad+7z//eWpK4oQvZ5NGqR++fQ9wEVtbE2xfZEYRYKT3YKWrA343hZRUPL3R6YVtVgjFA0W9+TrIxlogug5GBhDM3fHXOaseMJ5PoQ+KLJ37YTnaK+rZeTNkkmqTN31HLK8dQKCuvnw17exJp+NNezkd8LB1YvfAwAA//93D/4W"
}
