// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package generate

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"gopkg.in/yaml.v2"
)

type normalizationsFile struct {
	Normalizations []map[string]interface{} `yaml:"normalizations"`
}

// ECSMappings generates auditd-to-ECS mappings from a go-libaudit checkout.
// Replaces filebeat/module/auditd/log/ingest/gen-ecs-mappings.py.
// Set GOLIB_AUDIT_PATH to the path of the go-libaudit repository.
func ECSMappings() error {
	repoPath := os.Getenv("GOLIB_AUDIT_PATH")
	if repoPath == "" {
		return fmt.Errorf("GOLIB_AUDIT_PATH environment variable is required (path to go-libaudit repo)")
	}

	gitPath := repoPath + "/.git"
	normsPath := repoPath + "/aucoalesce/normalizations.yaml"

	if info, err := os.Stat(repoPath); err != nil || !info.IsDir() {
		return fmt.Errorf("path to go-libaudit is not a directory: %s", repoPath)
	}
	if info, err := os.Stat(gitPath); err != nil || !info.IsDir() {
		return fmt.Errorf("go-libaudit directory doesn't contain a git repository: %s", gitPath)
	}
	if _, err := os.Stat(normsPath); err != nil {
		return fmt.Errorf("go-libaudit repository doesn't contain the normalizations file: %s", normsPath)
	}

	revisionBytes, err := exec.Command("git", "--work-tree="+repoPath, "--git-dir="+gitPath, "describe", "--tags").Output()
	if err != nil {
		return fmt.Errorf("getting git revision: %w", err)
	}
	revision := strings.TrimSpace(string(revisionBytes))

	data, err := os.ReadFile(normsPath)
	if err != nil {
		return fmt.Errorf("reading normalizations file: %w", err)
	}

	var norms normalizationsFile
	if err := yaml.Unmarshal(data, &norms); err != nil {
		return fmt.Errorf("parsing normalizations YAML: %w", err)
	}

	types := make(map[string][]map[string]interface{})
	syscalls := make(map[string][]map[string]interface{})

	for _, entry := range norms.Normalizations {
		proto := convertAuditMapping(entry)
		if len(proto) == 0 {
			continue
		}

		if sysList, ok := entry["syscalls"]; ok {
			if err := appendToMultiMap(syscalls, sysList, proto); err != nil {
				return err
			}
		}
		if typeList, ok := entry["record_types"]; ok {
			if err := appendToMultiMap(types, typeList, proto); err != nil {
				return err
			}
		}
	}

	if _, ok := types["SYSCALL"]; ok {
		return fmt.Errorf("SYSCALL cannot be specified in record_types")
	}

	fmt.Printf("# Auditd record type to ECS mappings\n")
	fmt.Printf("# AUTOGENERATED FROM go-libaudit %s, DO NOT EDIT\n", revision)

	output := map[string]interface{}{
		"params": map[string]interface{}{
			"types":    types,
			"syscalls": syscalls,
		},
	}
	out, err := yaml.Marshal(output)
	if err != nil {
		return fmt.Errorf("marshaling output YAML: %w", err)
	}
	fmt.Print(string(out))
	fmt.Println("# END OF AUTOGENERATED")
	return nil
}

func appendToMultiMap(m map[string][]map[string]interface{}, keys interface{}, val map[string]interface{}) error {
	switch v := keys.(type) {
	case string:
		cp, err := deepCopyMap(val)
		if err != nil {
			return err
		}
		m[v] = append(m[v], cp)
	case []interface{}:
		for _, k := range v {
			if s, ok := k.(string); ok {
				cp, err := deepCopyMap(val)
				if err != nil {
					return err
				}
				m[s] = append(m[s], cp)
			}
		}
	}
	return nil
}

func deepCopyMap(m map[string]interface{}) (map[string]interface{}, error) {
	out, err := yaml.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("deep copy marshal: %w", err)
	}
	var result map[string]interface{}
	if err := yaml.Unmarshal(out, &result); err != nil {
		return nil, fmt.Errorf("deep copy unmarshal: %w", err)
	}
	return result, nil
}

func convertAuditMapping(m map[string]interface{}) map[string]interface{} {
	event := make(map[string]interface{})
	objects := map[string][]interface{}{
		"subject.primary":   {"auid"},
		"subject.secondary": {"uid"},
	}
	var mappings []interface{}
	var hasFields []interface{}

	for k, v := range m {
		switch k {
		case "action":
			event[k] = toList(v)
		case "ecs":
			if ecsMap, ok := v.(map[interface{}]interface{}); ok {
				for ek, ev := range ecsMap {
					switch ek {
					case "type":
						event["type"] = toList(ev)
					case "category":
						event["category"] = toList(ev)
					case "mappings":
						if ml, ok := ev.([]interface{}); ok {
							mappings = ml
						}
					}
				}
			}
		case "subject", "object":
			if entityMap, ok := v.(map[interface{}]interface{}); ok {
				for ek, ev := range entityMap {
					ekStr := fmt.Sprint(ek)
					if ekStr == "primary" || ekStr == "secondary" {
						objects[k+"."+ekStr] = toListStr(ev)
					}
				}
			}
		case "has_fields":
			if hf, ok := v.([]interface{}); ok {
				hasFields = hf
			}
		case "syscalls", "record_types", "how", "description", "source_ip":
			// ignored in output
		}
	}

	d := map[string]interface{}{
		"event": event,
	}

	if len(mappings) > 0 {
		var copies []map[string]interface{}
		for _, mp := range mappings {
			mpMap, ok := mp.(map[interface{}]interface{})
			if !ok {
				continue
			}
			ref := fmt.Sprint(mpMap["from"])
			to := fmt.Sprint(mpMap["to"])

			var source []interface{}
			if obj, ok := objects[ref]; ok {
				source = obj
			} else {
				parts := strings.SplitN(ref, ".", 2)
				if len(parts) == 2 && (parts[0] == "uid" || parts[0] == "data") {
					source = []interface{}{parts[1]}
				} else {
					continue
				}
			}
			copies = append(copies, map[string]interface{}{
				"from": source,
				"to":   to,
			})
		}
		if len(copies) > 0 {
			d["copy"] = copies
		}
	}

	if len(hasFields) > 0 {
		d["has_fields"] = hasFields
	}

	return d
}

func toList(v interface{}) []interface{} {
	if list, ok := v.([]interface{}); ok {
		return list
	}
	return []interface{}{v}
}

func toListStr(v interface{}) []interface{} {
	switch val := v.(type) {
	case []interface{}:
		return val
	case string:
		return []interface{}{val}
	default:
		return []interface{}{v}
	}
}
