// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

//go:build !requirefips

package gcppubsub

import (
	"context"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"cloud.google.com/go/pubsub"
	"github.com/stretchr/testify/assert"
	"golang.org/x/sync/errgroup"

	"github.com/elastic/beats/v7/filebeat/channel"
	"github.com/elastic/beats/v7/filebeat/input"
	"github.com/elastic/beats/v7/libbeat/beat"
	"github.com/elastic/beats/v7/libbeat/tests/resources"
	"github.com/elastic/beats/v7/x-pack/filebeat/input/gcppubsub/testutil"
	conf "github.com/elastic/elastic-agent-libs/config"
	"github.com/elastic/elastic-agent-libs/logp"
	"github.com/elastic/elastic-agent-libs/logp/logptest"
)

const (
	emulatorProjectID    = "test-project-id"
	emulatorTopic        = "test-topic-foo"
	emulatorSubscription = "test-subscription-bar"
)

func ifNotDone(ctx context.Context, f func()) func() {
	return func() {
		select {
		case <-ctx.Done():
			return
		default:
		}
		f()
	}
}

func defaultTestConfig() *conf.C {
	return conf.MustNewConfigFrom(map[string]interface{}{
		"project_id": emulatorProjectID,
		"topic":      emulatorTopic,
		"subscription": map[string]interface{}{
			"name":   emulatorSubscription,
			"create": true,
		},
		"credentials_file": "testdata/fake.json",
	})
}

func runTest(t *testing.T, cfg *conf.C, run func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T)) {
	runTestWithACKer(t, cfg, ackEvent, run)
}

func runTestWithACKer(t *testing.T, cfg *conf.C, onEvent eventHandler, run func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T)) {
	if !testutil.IsInDockerIntegTestEnv() {
		// Don't test goroutines when using our compose.EnsureUp.
		defer resources.NewGoroutinesChecker().Check(t)
	}

	// Create pubsub client for setting up and communicating to emulator.
	client, clientCancel := testutil.TestSetup(t)
	defer clientCancel()
	defer client.Close()

	// Simulate input.Context from Filebeat input runner.
	inputCtx := newInputContext()
	defer close(inputCtx.Done)

	// Stub outlet for receiving events generated by the input.
	eventOutlet := newStubOutlet(onEvent)
	defer eventOutlet.Close()

	connector := channel.ConnectorFunc(func(_ *conf.C, cliCfg beat.ClientConfig) (channel.Outleter, error) {
		eventOutlet.setClientConfig(cliCfg)
		return eventOutlet, nil
	})

	logger := logptest.NewTestingLogger(t, "")
	in, err := NewInput(cfg, connector, inputCtx, logger)
	if err != nil {
		t.Fatal(err)
	}
	//nolint:errcheck // ignore
	pubsubInput := in.(*pubsubInput)
	// Initialize metrics explicitly for tests
	pubsubInput.metrics = newInputMetrics("", nil, logp.NewNopLogger())
	defer pubsubInput.Stop()

	run(client, pubsubInput, eventOutlet, t)
}

func newInputContext() input.Context {
	return input.Context{
		Done: make(chan struct{}),
	}
}

type eventHandler func(beat.Event, beat.ClientConfig) bool

type stubOutleter struct {
	sync.Mutex
	cond         *sync.Cond
	done         bool
	Events       []beat.Event
	clientCfg    beat.ClientConfig
	eventHandler eventHandler
}

func newStubOutlet(onEvent eventHandler) *stubOutleter {
	o := &stubOutleter{
		eventHandler: onEvent,
	}
	o.cond = sync.NewCond(o)
	return o
}

func ackEvent(ev beat.Event, cfg beat.ClientConfig) bool {
	if cfg.EventListener == nil {
		return false
	}

	cfg.EventListener.AddEvent(ev, true)
	cfg.EventListener.ACKEvents(1)
	return true
}

func (o *stubOutleter) setClientConfig(cfg beat.ClientConfig) {
	o.Lock()
	defer o.Unlock()
	o.clientCfg = cfg
}

func (o *stubOutleter) waitForEvents(numEvents int) ([]beat.Event, bool) {
	o.Lock()
	defer o.Unlock()

	for len(o.Events) < numEvents && !o.done {
		o.cond.Wait()
	}

	size := numEvents
	if size >= len(o.Events) {
		size = len(o.Events)
	}

	out := make([]beat.Event, size)
	copy(out, o.Events)
	return out, len(out) == numEvents
}

func (o *stubOutleter) Close() error {
	o.Lock()
	defer o.Unlock()
	o.done = true
	return nil
}

func (o *stubOutleter) Done() <-chan struct{} { return nil }

func (o *stubOutleter) OnEvent(event beat.Event) bool {
	o.Lock()
	defer o.Unlock()
	acked := o.eventHandler(event, o.clientCfg)
	if acked {
		o.Events = append(o.Events, event)
		o.cond.Broadcast()
	}
	return !o.done
}

// --- Test Cases

func TestTopicDoesNotExist(t *testing.T) {
	cfg := defaultTestConfig()

	runTest(t, cfg, func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T) {
		err := input.run()
		if assert.Error(t, err) {
			assert.Contains(t, err.Error(), "failed to subscribe to pub/sub topic")
		}
	})
}

func TestSubscriptionDoesNotExistError(t *testing.T) {
	cfg := defaultTestConfig()
	_ = cfg.SetBool("subscription.create", -1, false)

	runTest(t, cfg, func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T) {
		testutil.CreateTopic(t, client)

		err := input.run()
		if assert.Error(t, err) {
			assert.Contains(t, err.Error(), "no subscription exists and 'subscription.create' is not enabled")
		}
	})
}

func TestSubscriptionExists(t *testing.T) {
	cfg := defaultTestConfig()

	runTest(t, cfg, func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T) {
		testutil.CreateTopic(t, client)
		testutil.CreateSubscription(t, emulatorSubscription, client)
		testutil.PublishMessages(t, client, 5)

		var group errgroup.Group
		group.Go(input.run)

		time.AfterFunc(10*time.Second, func() { out.Close() })
		events, ok := out.waitForEvents(5)
		if !ok {
			t.Fatalf("Expected 5 events, but got %d.", len(events))
		}
		input.Stop()

		if err := group.Wait(); err != nil {
			t.Fatal(err)
		}
	})
}

func TestSubscriptionCreate(t *testing.T) {
	cfg := defaultTestConfig()

	runTest(t, cfg, func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T) {
		testutil.CreateTopic(t, client)

		group, ctx := errgroup.WithContext(context.Background())
		group.Go(input.run)

		time.AfterFunc(1*time.Second, ifNotDone(ctx, func() { testutil.PublishMessages(t, client, 5) }))
		time.AfterFunc(10*time.Second, func() { out.Close() })

		events, ok := out.waitForEvents(5)
		if !ok {
			t.Fatalf("Expected 5 events, but got %d.", len(events))
		}
		input.Stop()

		if err := group.Wait(); err != nil {
			t.Fatal(err)
		}
	})
}

func TestRunStop(t *testing.T) {
	cfg := defaultTestConfig()

	runTest(t, cfg, func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T) {
		input.Run()
		input.Stop()
		input.Run()
		input.Stop()
	})
}

func TestEndToEndACK(t *testing.T) {
	cfg := defaultTestConfig()

	var count atomic.Int64
	seen := make(map[string]struct{})
	// ACK every other message
	halfAcker := func(ev beat.Event, clientConfig beat.ClientConfig) bool {
		//nolint:errcheck // ignore
		msg := ev.Private.(*pubsub.Message)
		seen[msg.ID] = struct{}{}
		if count.Add(1)&1 != 0 {
			// Nack will result in the Message being redelivered more quickly than if it were allowed to expire.
			msg.Nack()
			return false
		}
		return ackEvent(ev, clientConfig)
	}

	runTestWithACKer(t, cfg, halfAcker, func(client *pubsub.Client, input *pubsubInput, out *stubOutleter, t *testing.T) {
		testutil.CreateTopic(t, client)
		testutil.CreateSubscription(t, emulatorSubscription, client)

		group, _ := errgroup.WithContext(context.Background())
		group.Go(input.run)

		const numMsgs = 10
		testutil.PublishMessages(t, client, numMsgs)
		events, ok := out.waitForEvents(numMsgs)
		if !ok {
			t.Fatalf("Expected %d events, but got %d.", 1, len(events))
		}

		// Assert that all messages were eventually received
		assert.Len(t, events, len(seen))
		got := make(map[string]struct{})
		for _, ev := range events {
			//nolint:errcheck // ignore
			msg := ev.Private.(*pubsub.Message)
			got[msg.ID] = struct{}{}
		}
		for id := range seen {
			_, exists := got[id]
			assert.True(t, exists)
		}

		assert.EqualValues(t, input.metrics.ackedMessageCount.Get(), len(seen))

		input.Stop()
		out.Close()
		if err := group.Wait(); err != nil {
			t.Fatal(err)
		}
	})
}
