#!/usr/bin/env python
import os
import argparse
from subprocess import check_call

def main():
    parser = argparse.ArgumentParser(
        description="Builds OSX packages for Beats")
    parser.add_argument("--no-snapshot", action="store_true",
                        help="Don't append -SNAPSHOT to the version.")
    args = parser.parse_args()

    dir = os.path.dirname(__file__)
    os.chdir(dir + "/../")
    if args.no_snapshot:
        check_call("make SNAPSHOT=no osx-package", shell=True)
    else:
        check_call("make SNAPSHOT=yes osx-package", shell=True)
    print("All done")

if __name__ == "__main__":
    main()
