#!/usr/bin/env python
import os
import argparse

template = '''package beat

const defaultBeatVersion = "{}"
'''


def main():
    parser = argparse.ArgumentParser(
        description="Used to set the current version. Doesn't commit changes.")
    parser.add_argument("version",
                        help="The new version")
    args = parser.parse_args()

    dir = os.path.dirname(os.path.realpath(__file__))
    with open(dir + "/../libbeat/beat/version.go", "w") as f:
        f.write(template.format(args.version))

if __name__ == "__main__":
    main()
