// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package kvm

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "kvm", asset.ModuleFieldsPri, AssetKvm); err != nil {
		panic(err)
	}
}

// AssetKvm returns asset data.
// This is the base64 encoded zlib format compressed contents of module/kvm.
func AssetKvm() string {
	return "eJykk71uwyAUhXee4ih7+gAMnbpVWbvTchuhgLEAp/LbV/gnwvYtdlSZycB3vsuFM27US9zuTgDJJEsSp/ePy0kAgSypSBKflJQANMWvYNpkfCPxKgDkfXBed5YE8G3I6iiHiTMa5WgAvxg9/AJS35KE9c11+sEQ83jzTpkGRm9QGTotG2E36n980Id4j80FcVozwq7Bd20NVVZYgrR3jlxMKj2mOGZFMQ+Wsm4CwKsshVaQmtCu1jgu5HzoeTDvUvoUfVt+XBefNFvZ/ZU1q9yV7WouxfX8pwiXNFsYvZqoxu9GL1/MNo49k/rZH81coOe8XH8Xxd7dq2RsCM88hFKDxPGqd2qeKo5JJRK/AwB+5UMR"
}
