The `perfmon` metricset of the Windows module reads Windows
performance counters.

[float]
=== Configuration

You must configure queries for the Windows performance counters that you wish
to collect. The example below collects processor time and disk writes.
With `format` you can set the output format for a specific counter. Possible values are
`float` and `long`. If nothing is selected the default value is `float`.
With `instance_name`, you can specify the name of the instance. Use this setting when:
- You want to use an instance name that is different from the computed name. For example, `Total` instead of `_Total`.
- You specify a counter that has no instance. For example, `\TCPIP Performance Diagnostics\IPv4 NBLs/sec indicated without prevalidation`.
For wildcard queries this setting has no effect.


[source,yaml]
----
- module: windows
  metricsets: ["perfmon"]
  period: 10s
  perfmon.counters:
    - instance_label: "processor.name"
      instance_name: "Total"
      measurement_label: "processor.time.total.pct"
      query: '\Processor Information(_Total)\% Processor Time'
    - instance_label: "diskio.name"
      measurement_label: "diskio.write.bytes"
      query: '\PhysicalDisk(*)\Disk Writes/sec'
      format: "long"
----
