[[breaking-changes-7.7]]

=== Breaking changes in 7.7
++++
<titleabbrev>7.7</titleabbrev>
++++

{see-relnotes}

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

//tag::notable-breaking-changes[]

[float]
====  Environment variables can no longer reference other environment variables

Environment variables are still supported in the {beats} configuration.
However, starting in Version 7.7.0, you can no longer reference an environment
variable that references another environment variable.

For example, if you set `export NAME=${COMPANY_NAME}`, you cannot use
`name: ${NAME}` in the configuration.

[float]
==== Docker and kubernetes processors no longer allowed in script processor

Prior to this release, it was possible to use the `add_docker_metadata` and
`add_kubernetes_metadata` processors in the `script` processor. This was not a
good practice because it sometimes resulted in memory and file descriptor leaks.

Starting in version 7.7.0, scripts that use these processors will fail. To
resolve this problem, define the processors in your configuration instead of the
script.

// end::notable-breaking-changes[]
