[[breaking-changes-7.6]]

=== Breaking changes in 7.6
++++
<titleabbrev>7.6</titleabbrev>
++++

{see-relnotes}

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

//tag::notable-breaking-changes[]

[float]
==== Version removed from default ILM policy name

To prevent custom ILM policies from breaking during upgrades, the default 
ILM policy name no longer includes the {beats} version.

If you want to include the version, use the `setup.ilm.policy_name`
configuration setting. For example:

[source,yaml]
----
setup.ilm.policy_name: "%{[agent.name]}-%{[agent.version]}"
----

// end::notable-breaking-changes[]

//tag::notable-breaking-changes[]

[float]
==== Two Beat instances can no longer share the same data path

To prevent accidental overwriting of internal state, two instances of the
same Beat running on the same host can no longer share the same data path.
To customize the data path for a Beat, use the `path.data` configuration
setting. For example:

[source,yaml]
----
path.data: ${path.home}/data-instance1
----

// end::notable-breaking-changes[]
