[[breaking-changes-7.16]]

=== Breaking changes in 7.16
++++
<titleabbrev>7.16</titleabbrev>
++++

See the <<release-notes,release notes>> for a complete list of changes,
including changes to beta or experimental functionality.

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

// tag::notable-breaking-changes[]

[discrete]
==== {journalbeat} is removed in 7.16

{journalbeat}, a lightweight shipper for collecting logs written by the Journald
system service, is removed in 7.16. This functionality is instead provided as
a {filebeat} input. If you're currently using {journalbeat}, you should
use the `journald` input in {filebeat} instead. For more information, refer to
the
{filebeat-ref}/filebeat-input-journald.html[Journald input] documentation.

If you're using {agent} instead of {beats}, you can collect Journald logs by
adding the *Custom Journald logs* integration to your agent policy. For more
information, refer to
{fleet-guide}/add-integration-to-policy.html[Add an {agent} integration to a policy]. 

//TODO: Add pointer to the integrations docs for custom journald logs when
//available.

[discrete]
==== Custom {beats} generator is deprecated in 7.16

The generator code for creating custom {beats} is deprecated in 7.16.0 and will
be removed in 8.0.0. You can continue to build custom {beats} using the
generators available in 7.16, or refer to existing {beats} as working examples.

// end::notable-breaking-changes[]

