// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nats

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "nats", asset.ModuleFieldsPri, Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzUmL1y4zYQx3s/xc5VSXF6ABWZySTNFXERX2odBK4o5Agsb3chn/z0GZCiTFGgvkx7FBYuRHj/P/4Xu/j4DN9xO4dgVB4A1GmFc/j0aFQ+PQAUKJZdrY7CHH57AIBmJPxFRazwAWDlsCpk3rz5DMF43MdKj25rnEPJFOvdL5mI6fmW/ukbWApqXBAQNepEnRXQtVF4RkZgNAWsmDw8vkr0CfoUgrxBnrli/6bD+Y7bZ+L+7yNQ6fm6xl0o+PLnmIg6j0cyhVG8TOOpjZ+iAK3Ao7KzYBlNGn0kaikEtOmVHIn2rT6j+kfndZPR16DAWBnFYsfR1xh63adSUlMdvOmYXFAskQfvTpB1vofol8jJEhuZMWi1BWPVbRBs5TCoHHnDFBUntKWJd4+OMJZOFBmL4Tfv56YandCJjeEbfYj1oD5eaSoK5fUu1MiOCtDX0nQCsYZfBO2vWQSPfrbcHs6Mt1Ls5mSKTbyFKKZsyvfx969PUDNZFMnCWOIRkAnmRUWls6ZqRRqL+jzAMQj0esoBVx2zVKuKjN7uj63jgTly0pymaBb5FjepUY1QtW3bLBZHHaUPxehpbPJMXMsZpY7ChSzAsKIvlDeeYtAk74Il70KZViwzGJurazgoLEmpHVpzzp4LGE9wjop2VLlSf1+kY8WOheKwdiZKG0Ut6X+Qtj3n/aRtjzSeNqnoObUhiR753So/qcBepbfNodD07SzaWrVeMP5YNCv8jIl0EdllGWn5L9orm/eAce00LRmQdMBTcEqcvBtKjuClVv4yKV8er9G5ga/ZPX0EYCt0A6HEpXwEYKNzC1/6+xF8SedSvil7borX7Xn3O7x253ll392bNtrlcogXYHaojD8iivYP0JmxY5h91ON8XgZ6IewAGAonym4ZmxMohX6a//n7y9NIjFMfAsNj4cvosPNLzJVfBm/oAjn+prndA/7ZLpuj3xi+C/jEcS170xTvAf5sd87RpzX7HuBP7R36TncqE95bHIS9x5uc3Y3W2Of3z3+CfLR0TMbRhgeqkU1rlgsD9yonOnpA3rznATmFvw3NG7Xr90NT51HAtDLgBFYUQwErYjAHiPkrF2PXOBP3kr8em8Q6iZWCoDam6Rpb0RM4a6cLPry8ngApReySAYYRlpg6AadCxA3uLvbPsa1MoKgzb35OS+fNT+ejhzZ+u7krYLm9FMhshjeIbwQyG2RT4hjQfwEAAP//SzioHQ=="
}
