// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nats

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "nats", asset.ModuleFieldsPri, Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzUlz9z2zwMxnd/Clym9x2SD+Chd712ydAMTTo7NAXLbCRCAUH71E/fI20pikz5XxWfw8GDSfH5EQAfQbfwgvUUrBI3ARAjBU7h5kGJu5kAZOg0m0oM2Sl8mQBAXAk/KPMFTgAWBovMTePMLVhVYrtXGFJXOIWcyVfbfxI7hvEcHnoGTVaUsQ6cKDFOjHYgSyWwRkZgVBksmEp4eJPoEnQpNFmLOui4di4FtAcqjG8NUTz326bAWCjBDEoUNrqr0SfqUjnkFfLMZO9mGy4nbGzem9oDF8bTEre7wv33pKaldVItU4KnaT1udMSUCLTYHh00owpPJMWFRBVJeWMFc+TTT2t9OUcOANozo5WiBqXFrBB0YdCK2ymGUE4jlsFK8Yfk/wXrNXF/7nMXgK/C6qR+QecUe4VsKAN5O7Zx4Cv4z6H+P4lQYnk3rwXdiBTb0gt7E9fgncpjSB6+Pj1CxaTRuSSMJh4AGeFCFJQbrYqNSAxRlwfYWwcDedKVT1ItClJyfnx05d8Fx+0NTnSLWdq6Rw1UFCrqTelitmMcXSjGkoaKZwQUxtw4QcYsqdRQGJsE6HvYkfKqJG8lyBurqTQ2D26gemtTTgbvLpYLqe2H5lB4jmDcwzko2lClrvrHIu0qNizk+3dnpLSRl5w+QdpazutJW4s0nDZX0DrYkPMl8ofd/KACrUqnmyEbfTuJthSpZoyvs9jT3DGRzDybJCPNf6M+0bx7jEsj4ZUBQQdKskYo9KjQlxzAC1b+Z1S+NF7UOYOPyQteAnAjdAah83N3CcCocw5f+L0EX9A5lm9Mzw37NV1+2+FtOs8TfbcN2qDLpRCPwGxQGV89Oul+PifWDmF2UXfzeRzokbA9YMhM+PSd+/hlTbab5l8/7x8H9th3kO5hNndvcNnhV8yJJ4N/cIEUfzS3a8A/6LIp+pXiq4APHKeyR1O8BviD7pyiD+/sa4BP9Q5/AwAA//8WPjFM"
}
