// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nats

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "nats", asset.ModuleFieldsPri, Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy8lsFy2jwQx+88xU7uyQNw+Ga+aS89NJfkToS8MdtIWnd3FcZ5+o5MIIYKOjAYHS15fz/91xLcwxv2c0jOdAZgZAHncPfoTO9mAA2qF+qMOM3hvxkADCvhJzc54AzglTA0Oh9m7iG5iLtaZVjf4Rxa4dx9PqlULOOlvPQCnpM5SgpqzkiNvIKtnMEaBUHQNfAqHOHxCzE2GFu8O/nYPayZnLAp49tWZdjwuxMQDM6wgYgm5HW0+tBh7KEo7ygLavZmt0Jv2K9ZDudOaJXxvMLPsvDjexWaeF3FNc7wPNbThmMUEfj1c+/gBV15owrPXVld5QdO7fl77VCIG7CvbZPCXh+/4BFjlUzJsEU5H+6zCCYrhVl6yOraIYnH/5+foBP2qFo18Syo13VJOS5RCj1wS96FDWRIZuwDkpPCkfb4Lk+TkO/yXjx6Mh5jc2HhOSX0pfpkUQ2g0G++WWzAB8JkdSnByDZd1wRbUkPBpkraWlB6iNpe2cJFzsmKBSXPkVILEbW0qy7B2Sa14Gwt/9OC0sOyv3pHKln8TRkHManDLonjDhp4Xc6K5ogy2edZKLCjbM916IHTcL1U1VZm3ULw96L8ZOuDMNsiC1UdefkLvZ2neOC4Iis3GxQORE5kLCW7Q+QRvXLffFzVr643cC7wE86GtxDcgC4w1LzUWwgOnAv8yv++G+gVzKHdnwAAAP//fKoICA=="
}
