// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nats

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "nats", asset.ModuleFieldsPri, AssetNats); err != nil {
		panic(err)
	}
}

// AssetNats returns asset data.
// This is the base64 encoded gzipped contents of module/nats.
func AssetNats() string {
	return "eJy8kE1ORCEQhPecojL78QAsTNy405joBYgUhNj8hGbMzO0Nz/GFqFutHV+K/qCPeOPForihBhhpCC0O83gwgKe+9tRGqsXi1gDAQ/UnIULtaK5rKhGPdy/PkBoRklBvDBASxavdLhxRXOaumBmXRovY66ldyS+imfttDkKvebdsgplVsopa8jv7NvlJ6JRw3q98afPscpsrWJpXtrQ+3y+1xB9y4TvlT/VfpkxVF/kvXx08D/MRAAD//xMVoVs="
}
