// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package sysmon

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("winlogbeat", "sysmon", asset.ModuleFieldsPri, AssetSysmon); err != nil {
		panic(err)
	}
}

// AssetSysmon returns asset data.
// This is the base64 encoded zlib format compressed contents of module/sysmon.
func AssetSysmon() string {
	return "eJyszjFuQjEQBNDepxjR4wO4SJUmTRoipYyMPV+sYmzi3Q/5t48woAgJpUq7q5k3a3xyCdBF9606wMQKA1abccC+5blw5YBMTV0OJq0GPDkAeNtRidgJ2xE8shomYckKPTDJJAnWxvOuzjugszAqA7a06HDNBTeK16hxz9sqn6t6tWizji9gy4HhPPzUer7e7va9S83tpLikkFomOm3ulRlT62PT8+sGXzP74h+qkxT62NNOjrwhF3jbWmGsj+CXmiVFo0KmgWQW2hmVQpyi4tb4Byr6wW+m2eK28B/lit9a734GABH3plw="
}
