[id="configuration-{beatname_lc}"]
=== Specify which modules to run

To enable specific modules and metricsets, you add entries to the
`auditbeat.modules` list in the +{beatname_lc}.yml+ config file. Each entry in
the list begins with a dash (-) and is followed by settings for that module.

The following example shows a configuration that runs the `audit` module with
the `kernel` and `file` metricsets enabled:

[source,yaml]
----
auditbeat.modules:

- module: audit
  metricsets: [kernel]
  kernel.audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

- module: audit
  metricsets: [file]
  file.paths:
    binaries:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    conf:
- /etc
----

Notice that that the `audit` module is specified twice in the example because the
`kernel` and `file` metricsets required different settings.

==== Common config options

You can specify the following options for any {beatname_uc} module. Some modules
require additional configuration settings. See the <<{beatname_lc}-modules>>
section for more information.

*`module`*::

The name of the module to run.

*`metricsets`*::

A list of metricsets to execute. Make sure that you only list metricsets
that are available in the module. It is not possible to reference metricsets from other modules.


////
*`enabled`*::

A Boolean value that specifies whether the module is enabled. If you use the default config file, +{beatname_lc.yml}+,
the System module is enabled (set to `enabled: true`) by default. If the `enabled` option is missing from the
configuration block, the module is enabled by default.


REVIEWERS: WILL AUDITBEAT HAVE ANY SHARED OHTER SETTINGS LIKE WE ONES LISTED BELOW FOR THE METRICBEAT MODULE?
===== period

How often the metricsets are executed. If a system is not reachable, Metricbeat returns an error for each period. This setting is required.

===== hosts

A list of hosts to fetch information from. For some metricsets, this setting is optional.

===== fields

A dictionary of fields that will be sent with the metricset event. This setting is optional.

===== tags

A list of tags that will be sent with the metricset event. This setting is optional.

//////


