// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by ragel DO NOT EDIT.
//
// line-disable-directive parser/rfc3164_parser.rl:1
package syslog

//line rfc3164_parser.go:8
const syslog_rfc3154_start int = 0
const syslog_rfc3154_first_final int = 2
const syslog_rfc3154_error int = -1

const syslog_rfc3154_en_main int = 0
const syslog_rfc3154_en_catch_all int = 1

// line-disable-directive parser/rfc3164_parser.rl:9

var (
	noDuplicates = []byte{'-', '.'}
)

// Parse parses Syslog events.
func ParserRFC3164(data []byte, event *event) {
	var p, cs int
	pe := len(data)
	tok := 0
	eof := len(data)

//line rfc3164_parser.go:31
	{
		cs = syslog_rfc3154_start
	}

//line rfc3164_parser.go:36
	{
		if (p) == (pe) {
			goto _test_eof
		}
		switch cs {
		case 0:
			goto st_case_0
		case 2:
			goto st_case_2
		case 3:
			goto st_case_3
		case 4:
			goto st_case_4
		case 5:
			goto st_case_5
		case 6:
			goto st_case_6
		case 7:
			goto st_case_7
		case 8:
			goto st_case_8
		case 9:
			goto st_case_9
		case 10:
			goto st_case_10
		case 11:
			goto st_case_11
		case 12:
			goto st_case_12
		case 13:
			goto st_case_13
		case 14:
			goto st_case_14
		case 15:
			goto st_case_15
		case 16:
			goto st_case_16
		case 17:
			goto st_case_17
		case 18:
			goto st_case_18
		case 19:
			goto st_case_19
		case 20:
			goto st_case_20
		case 21:
			goto st_case_21
		case 22:
			goto st_case_22
		case 23:
			goto st_case_23
		case 24:
			goto st_case_24
		case 25:
			goto st_case_25
		case 26:
			goto st_case_26
		case 27:
			goto st_case_27
		case 28:
			goto st_case_28
		case 29:
			goto st_case_29
		case 30:
			goto st_case_30
		case 31:
			goto st_case_31
		case 32:
			goto st_case_32
		case 33:
			goto st_case_33
		case 34:
			goto st_case_34
		case 35:
			goto st_case_35
		case 36:
			goto st_case_36
		case 37:
			goto st_case_37
		case 38:
			goto st_case_38
		case 39:
			goto st_case_39
		case 40:
			goto st_case_40
		case 41:
			goto st_case_41
		case 42:
			goto st_case_42
		case 43:
			goto st_case_43
		case 44:
			goto st_case_44
		case 45:
			goto st_case_45
		case 46:
			goto st_case_46
		case 47:
			goto st_case_47
		case 48:
			goto st_case_48
		case 49:
			goto st_case_49
		case 50:
			goto st_case_50
		case 51:
			goto st_case_51
		case 52:
			goto st_case_52
		case 53:
			goto st_case_53
		case 54:
			goto st_case_54
		case 55:
			goto st_case_55
		case 56:
			goto st_case_56
		case 57:
			goto st_case_57
		case 58:
			goto st_case_58
		case 59:
			goto st_case_59
		case 60:
			goto st_case_60
		case 61:
			goto st_case_61
		case 62:
			goto st_case_62
		case 63:
			goto st_case_63
		case 64:
			goto st_case_64
		case 65:
			goto st_case_65
		case 66:
			goto st_case_66
		case 67:
			goto st_case_67
		case 68:
			goto st_case_68
		case 69:
			goto st_case_69
		case 70:
			goto st_case_70
		case 71:
			goto st_case_71
		case 72:
			goto st_case_72
		case 73:
			goto st_case_73
		case 74:
			goto st_case_74
		case 75:
			goto st_case_75
		case 76:
			goto st_case_76
		case 77:
			goto st_case_77
		case 78:
			goto st_case_78
		case 79:
			goto st_case_79
		case 80:
			goto st_case_80
		case 81:
			goto st_case_81
		case 82:
			goto st_case_82
		case 83:
			goto st_case_83
		case 84:
			goto st_case_84
		case 85:
			goto st_case_85
		case 86:
			goto st_case_86
		case 87:
			goto st_case_87
		case 88:
			goto st_case_88
		case 89:
			goto st_case_89
		case 90:
			goto st_case_90
		case 91:
			goto st_case_91
		case 92:
			goto st_case_92
		case 93:
			goto st_case_93
		case 94:
			goto st_case_94
		case 95:
			goto st_case_95
		case 96:
			goto st_case_96
		case 97:
			goto st_case_97
		case 98:
			goto st_case_98
		case 99:
			goto st_case_99
		case 100:
			goto st_case_100
		case 101:
			goto st_case_101
		case 102:
			goto st_case_102
		case 103:
			goto st_case_103
		case 104:
			goto st_case_104
		case 105:
			goto st_case_105
		case 106:
			goto st_case_106
		case 107:
			goto st_case_107
		case 108:
			goto st_case_108
		case 109:
			goto st_case_109
		case 110:
			goto st_case_110
		case 111:
			goto st_case_111
		case 112:
			goto st_case_112
		case 113:
			goto st_case_113
		case 114:
			goto st_case_114
		case 115:
			goto st_case_115
		case 116:
			goto st_case_116
		case 117:
			goto st_case_117
		case 118:
			goto st_case_118
		case 119:
			goto st_case_119
		case 120:
			goto st_case_120
		case 121:
			goto st_case_121
		case 122:
			goto st_case_122
		case 123:
			goto st_case_123
		case 124:
			goto st_case_124
		case 125:
			goto st_case_125
		case 126:
			goto st_case_126
		case 127:
			goto st_case_127
		case 128:
			goto st_case_128
		case 129:
			goto st_case_129
		case 130:
			goto st_case_130
		case 131:
			goto st_case_131
		case 132:
			goto st_case_132
		case 133:
			goto st_case_133
		case 134:
			goto st_case_134
		case 135:
			goto st_case_135
		case 136:
			goto st_case_136
		case 137:
			goto st_case_137
		case 138:
			goto st_case_138
		case 139:
			goto st_case_139
		case 140:
			goto st_case_140
		case 141:
			goto st_case_141
		case 142:
			goto st_case_142
		case 143:
			goto st_case_143
		case 144:
			goto st_case_144
		case 145:
			goto st_case_145
		case 146:
			goto st_case_146
		case 147:
			goto st_case_147
		case 148:
			goto st_case_148
		case 149:
			goto st_case_149
		case 150:
			goto st_case_150
		case 151:
			goto st_case_151
		case 152:
			goto st_case_152
		case 153:
			goto st_case_153
		case 154:
			goto st_case_154
		case 155:
			goto st_case_155
		case 156:
			goto st_case_156
		case 157:
			goto st_case_157
		case 158:
			goto st_case_158
		case 159:
			goto st_case_159
		case 160:
			goto st_case_160
		case 161:
			goto st_case_161
		case 162:
			goto st_case_162
		case 163:
			goto st_case_163
		case 164:
			goto st_case_164
		case 165:
			goto st_case_165
		case 166:
			goto st_case_166
		case 167:
			goto st_case_167
		case 168:
			goto st_case_168
		case 169:
			goto st_case_169
		case 170:
			goto st_case_170
		case 171:
			goto st_case_171
		case 172:
			goto st_case_172
		case 173:
			goto st_case_173
		case 174:
			goto st_case_174
		case 175:
			goto st_case_175
		case 176:
			goto st_case_176
		case 177:
			goto st_case_177
		case 178:
			goto st_case_178
		case 179:
			goto st_case_179
		case 180:
			goto st_case_180
		case 181:
			goto st_case_181
		case 182:
			goto st_case_182
		case 1:
			goto st_case_1
		case 183:
			goto st_case_183
		}
		goto st_out
	st_case_0:
		switch data[(p)] {
		case 32:
			goto tr1
		case 42:
			goto tr1
		case 46:
			goto tr1
		case 60:
			goto tr3
		case 65:
			goto tr4
		case 68:
			goto tr5
		case 70:
			goto tr6
		case 74:
			goto tr7
		case 77:
			goto tr8
		case 78:
			goto tr9
		case 79:
			goto tr10
		case 83:
			goto tr11
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr2
		}
		goto tr0
	tr0:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st2
	st2:
		if (p)++; (p) == (pe) {
			goto _test_eof2
		}
	st_case_2:
//line rfc3164_parser.go:454
		goto st2
	tr1:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st3
	st3:
		if (p)++; (p) == (pe) {
			goto _test_eof3
		}
	st_case_3:
//line rfc3164_parser.go:467
		switch data[(p)] {
		case 65:
			goto tr4
		case 68:
			goto tr5
		case 70:
			goto tr6
		case 74:
			goto tr7
		case 77:
			goto tr8
		case 78:
			goto tr9
		case 79:
			goto tr10
		case 83:
			goto tr11
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr14
		}
		goto st2
	tr14:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st4
	st4:
		if (p)++; (p) == (pe) {
			goto _test_eof4
		}
	st_case_4:
//line rfc3164_parser.go:501
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st5
		}
		goto st2
	st5:
		if (p)++; (p) == (pe) {
			goto _test_eof5
		}
	st_case_5:
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st6
		}
		goto st2
	st6:
		if (p)++; (p) == (pe) {
			goto _test_eof6
		}
	st_case_6:
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st7
		}
		goto st2
	st7:
		if (p)++; (p) == (pe) {
			goto _test_eof7
		}
	st_case_7:
		if data[(p)] == 45 {
			goto tr18
		}
		goto st2
	tr18:
		// line-disable-directive parser/common.rl:19

		event.SetYear(data[tok:p])

		goto st8
	st8:
		if (p)++; (p) == (pe) {
			goto _test_eof8
		}
	st_case_8:
//line rfc3164_parser.go:544
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr19
		}
		goto st2
	tr19:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st9
	st9:
		if (p)++; (p) == (pe) {
			goto _test_eof9
		}
	st_case_9:
//line rfc3164_parser.go:560
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st10
		}
		goto st2
	st10:
		if (p)++; (p) == (pe) {
			goto _test_eof10
		}
	st_case_10:
		if data[(p)] == 45 {
			goto tr21
		}
		goto st2
	tr21:
		// line-disable-directive parser/common.rl:23

		event.SetMonthNumeric(data[tok:p])

		goto st11
	st11:
		if (p)++; (p) == (pe) {
			goto _test_eof11
		}
	st_case_11:
//line rfc3164_parser.go:585
		if 48 <= data[(p)] && data[(p)] <= 51 {
			goto tr22
		}
		goto st2
	tr22:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st12
	st12:
		if (p)++; (p) == (pe) {
			goto _test_eof12
		}
	st_case_12:
//line rfc3164_parser.go:601
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st13
		}
		goto st2
	st13:
		if (p)++; (p) == (pe) {
			goto _test_eof13
		}
	st_case_13:
		switch data[(p)] {
		case 32:
			goto tr24
		case 84:
			goto tr24
		case 116:
			goto tr24
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr24
		}
		goto st2
	tr24:
		// line-disable-directive parser/common.rl:27

		event.SetDay(data[tok:p])

		goto st14
	st14:
		if (p)++; (p) == (pe) {
			goto _test_eof14
		}
	st_case_14:
//line rfc3164_parser.go:634
		if data[(p)] == 50 {
			goto tr26
		}
		if 48 <= data[(p)] && data[(p)] <= 49 {
			goto tr25
		}
		goto st2
	tr25:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st15
	st15:
		if (p)++; (p) == (pe) {
			goto _test_eof15
		}
	st_case_15:
//line rfc3164_parser.go:653
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st16
		}
		goto st2
	st16:
		if (p)++; (p) == (pe) {
			goto _test_eof16
		}
	st_case_16:
		if data[(p)] == 58 {
			goto tr28
		}
		goto st2
	tr28:
		// line-disable-directive parser/common.rl:31

		event.SetHour(data[tok:p])

		goto st17
	st17:
		if (p)++; (p) == (pe) {
			goto _test_eof17
		}
	st_case_17:
//line rfc3164_parser.go:678
		if 48 <= data[(p)] && data[(p)] <= 53 {
			goto tr29
		}
		goto st2
	tr29:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st18
	st18:
		if (p)++; (p) == (pe) {
			goto _test_eof18
		}
	st_case_18:
//line rfc3164_parser.go:694
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st19
		}
		goto st2
	st19:
		if (p)++; (p) == (pe) {
			goto _test_eof19
		}
	st_case_19:
		if data[(p)] == 58 {
			goto tr31
		}
		goto st2
	tr31:
		// line-disable-directive parser/common.rl:35

		event.SetMinute(data[tok:p])

		goto st20
	st20:
		if (p)++; (p) == (pe) {
			goto _test_eof20
		}
	st_case_20:
//line rfc3164_parser.go:719
		if 48 <= data[(p)] && data[(p)] <= 53 {
			goto tr32
		}
		goto st2
	tr32:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st21
	st21:
		if (p)++; (p) == (pe) {
			goto _test_eof21
		}
	st_case_21:
//line rfc3164_parser.go:735
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st22
		}
		goto st2
	st22:
		if (p)++; (p) == (pe) {
			goto _test_eof22
		}
	st_case_22:
		switch data[(p)] {
		case 32:
			goto tr34
		case 43:
			goto tr35
		case 45:
			goto tr35
		case 46:
			goto tr36
		case 58:
			goto tr37
		case 90:
			goto tr38
		case 122:
			goto tr38
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr34
		}
		goto st2
	tr34:
		// line-disable-directive parser/common.rl:39

		event.SetSecond(data[tok:p])

		goto st23
	tr61:
		// line-disable-directive parser/common.rl:103

		event.SetTimeZone(data[tok:p])

		goto st23
	tr68:
		// line-disable-directive parser/common.rl:43

		event.SetNanosecond(data[tok:p])

		goto st23
	st23:
		if (p)++; (p) == (pe) {
			goto _test_eof23
		}
	st_case_23:
//line rfc3164_parser.go:788
		switch data[(p)] {
		case 58:
			goto tr41
		case 95:
			goto tr39
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto tr39
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto tr40
				}
			case data[(p)] >= 65:
				goto tr40
			}
		default:
			goto tr40
		}
		goto tr0
	tr39:
		// line-disable-directive parser/common.rl:3

		tok = p

		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		goto st24
	tr42:
		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		goto st24
	st24:
		if (p)++; (p) == (pe) {
			goto _test_eof24
		}
	st_case_24:
//line rfc3164_parser.go:848
		switch data[(p)] {
		case 58:
			goto tr44
		case 95:
			goto tr42
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto tr42
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto tr43
				}
			case data[(p)] >= 65:
				goto tr43
			}
		default:
			goto tr43
		}
		goto st2
	tr40:
		// line-disable-directive parser/common.rl:3

		tok = p

		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		goto st25
	tr43:
		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		goto st25
	st25:
		if (p)++; (p) == (pe) {
			goto _test_eof25
		}
	st_case_25:
//line rfc3164_parser.go:908
		switch data[(p)] {
		case 32:
			goto tr45
		case 58:
			goto tr46
		case 95:
			goto tr42
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto tr42
				}
			case data[(p)] >= 9:
				goto tr45
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto tr43
				}
			case data[(p)] >= 65:
				goto tr43
			}
		default:
			goto tr43
		}
		goto st2
	tr45:
		// line-disable-directive parser/common.rl:91

		event.SetHostname(data[tok:p])

		goto st26
	st26:
		if (p)++; (p) == (pe) {
			goto _test_eof26
		}
	st_case_26:
//line rfc3164_parser.go:951
		switch data[(p)] {
		case 32:
			goto tr0
		case 91:
			goto tr0
		case 93:
			goto tr0
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr0
		}
		goto tr47
	tr47:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st27
	st27:
		if (p)++; (p) == (pe) {
			goto _test_eof27
		}
	st_case_27:
//line rfc3164_parser.go:975
		switch data[(p)] {
		case 32:
			goto st2
		case 58:
			goto tr49
		case 91:
			goto tr50
		case 93:
			goto st2
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto st2
		}
		goto st27
	tr49:
		// line-disable-directive parser/common.rl:95

		event.SetProgram(data[tok:p])

		goto st28
	st28:
		if (p)++; (p) == (pe) {
			goto _test_eof28
		}
	st_case_28:
//line rfc3164_parser.go:1001
		switch data[(p)] {
		case 32:
			goto st29
		case 58:
			goto tr49
		case 91:
			goto tr50
		case 93:
			goto st2
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto st29
		}
		goto st27
	st29:
		if (p)++; (p) == (pe) {
			goto _test_eof29
		}
	st_case_29:
		goto tr0
	tr50:
		// line-disable-directive parser/common.rl:95

		event.SetProgram(data[tok:p])

		goto st30
	st30:
		if (p)++; (p) == (pe) {
			goto _test_eof30
		}
	st_case_30:
//line rfc3164_parser.go:1033
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr52
		}
		goto st2
	tr52:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st31
	st31:
		if (p)++; (p) == (pe) {
			goto _test_eof31
		}
	st_case_31:
//line rfc3164_parser.go:1049
		if data[(p)] == 93 {
			goto tr54
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st31
		}
		goto st2
	tr54:
		// line-disable-directive parser/common.rl:99

		event.SetPid(data[tok:p])

		goto st32
	st32:
		if (p)++; (p) == (pe) {
			goto _test_eof32
		}
	st_case_32:
//line rfc3164_parser.go:1068
		if data[(p)] == 58 {
			goto st33
		}
		goto st2
	st33:
		if (p)++; (p) == (pe) {
			goto _test_eof33
		}
	st_case_33:
		if data[(p)] == 32 {
			goto st29
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto st29
		}
		goto st2
	tr46:
		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		// line-disable-directive parser/common.rl:91

		event.SetHostname(data[tok:p])

		goto st34
	st34:
		if (p)++; (p) == (pe) {
			goto _test_eof34
		}
	st_case_34:
//line rfc3164_parser.go:1107
		switch data[(p)] {
		case 32:
			goto st26
		case 58:
			goto tr57
		case 95:
			goto tr42
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto tr42
				}
			case data[(p)] >= 9:
				goto st26
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto tr43
				}
			case data[(p)] >= 65:
				goto tr43
			}
		default:
			goto tr43
		}
		goto st2
	tr57:
		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		goto st35
	tr58:
		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		// line-disable-directive parser/common.rl:91

		event.SetHostname(data[tok:p])

		goto st35
	st35:
		if (p)++; (p) == (pe) {
			goto _test_eof35
		}
	st_case_35:
//line rfc3164_parser.go:1174
		switch data[(p)] {
		case 32:
			goto tr45
		case 58:
			goto tr58
		case 95:
			goto tr42
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto tr42
				}
			case data[(p)] >= 9:
				goto tr45
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto tr43
				}
			case data[(p)] >= 65:
				goto tr43
			}
		default:
			goto tr43
		}
		goto st2
	tr41:
		// line-disable-directive parser/common.rl:3

		tok = p

		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		goto st36
	tr44:
		// line-disable-directive parser/common.rl:80

		if p-1 > 0 {
			for _, b := range noDuplicates {
				if data[p] == b && data[p-1] == b {
					p = tok - 1
					{
						goto st1
					}
				}
			}
		}

		goto st36
	st36:
		if (p)++; (p) == (pe) {
			goto _test_eof36
		}
	st_case_36:
//line rfc3164_parser.go:1241
		switch data[(p)] {
		case 58:
			goto tr57
		case 95:
			goto tr42
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto tr42
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto tr43
				}
			case data[(p)] >= 65:
				goto tr43
			}
		default:
			goto tr43
		}
		goto st2
	tr35:
		// line-disable-directive parser/common.rl:39

		event.SetSecond(data[tok:p])

		// line-disable-directive parser/common.rl:3

		tok = p

		goto st37
	tr69:
		// line-disable-directive parser/common.rl:43

		event.SetNanosecond(data[tok:p])

		// line-disable-directive parser/common.rl:3

		tok = p

		goto st37
	st37:
		if (p)++; (p) == (pe) {
			goto _test_eof37
		}
	st_case_37:
//line rfc3164_parser.go:1291
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st38
		}
		goto st2
	st38:
		if (p)++; (p) == (pe) {
			goto _test_eof38
		}
	st_case_38:
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st39
		}
		goto st2
	st39:
		if (p)++; (p) == (pe) {
			goto _test_eof39
		}
	st_case_39:
		switch data[(p)] {
		case 32:
			goto tr61
		case 58:
			goto tr63
		}
		switch {
		case data[(p)] > 13:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto st40
			}
		case data[(p)] >= 9:
			goto tr61
		}
		goto st2
	st40:
		if (p)++; (p) == (pe) {
			goto _test_eof40
		}
	st_case_40:
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st41
		}
		goto st2
	st41:
		if (p)++; (p) == (pe) {
			goto _test_eof41
		}
	st_case_41:
		switch data[(p)] {
		case 32:
			goto tr61
		case 58:
			goto tr65
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr61
		}
		goto st2
	tr37:
		// line-disable-directive parser/common.rl:39

		event.SetSecond(data[tok:p])

		goto st42
	tr65:
		// line-disable-directive parser/common.rl:103

		event.SetTimeZone(data[tok:p])

		goto st42
	tr71:
		// line-disable-directive parser/common.rl:43

		event.SetNanosecond(data[tok:p])

		goto st42
	st42:
		if (p)++; (p) == (pe) {
			goto _test_eof42
		}
	st_case_42:
//line rfc3164_parser.go:1372
		if data[(p)] == 32 {
			goto st23
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto st23
		}
		goto st2
	tr63:
		// line-disable-directive parser/common.rl:103

		event.SetTimeZone(data[tok:p])

		goto st43
	st43:
		if (p)++; (p) == (pe) {
			goto _test_eof43
		}
	st_case_43:
//line rfc3164_parser.go:1391
		if data[(p)] == 32 {
			goto st23
		}
		switch {
		case data[(p)] > 13:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto st40
			}
		case data[(p)] >= 9:
			goto st23
		}
		goto st2
	tr36:
		// line-disable-directive parser/common.rl:39

		event.SetSecond(data[tok:p])

		goto st44
	st44:
		if (p)++; (p) == (pe) {
			goto _test_eof44
		}
	st_case_44:
//line rfc3164_parser.go:1415
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr67
		}
		goto st2
	tr67:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st45
	st45:
		if (p)++; (p) == (pe) {
			goto _test_eof45
		}
	st_case_45:
//line rfc3164_parser.go:1431
		switch data[(p)] {
		case 32:
			goto tr68
		case 43:
			goto tr69
		case 45:
			goto tr69
		case 58:
			goto tr71
		case 90:
			goto tr72
		case 122:
			goto tr72
		}
		switch {
		case data[(p)] > 13:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto st45
			}
		case data[(p)] >= 9:
			goto tr68
		}
		goto st2
	tr38:
		// line-disable-directive parser/common.rl:39

		event.SetSecond(data[tok:p])

		// line-disable-directive parser/common.rl:3

		tok = p

		goto st46
	tr72:
		// line-disable-directive parser/common.rl:43

		event.SetNanosecond(data[tok:p])

		// line-disable-directive parser/common.rl:3

		tok = p

		goto st46
	st46:
		if (p)++; (p) == (pe) {
			goto _test_eof46
		}
	st_case_46:
//line rfc3164_parser.go:1480
		switch data[(p)] {
		case 32:
			goto tr61
		case 43:
			goto st37
		case 45:
			goto st37
		case 58:
			goto tr65
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr61
		}
		goto st2
	tr26:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st47
	st47:
		if (p)++; (p) == (pe) {
			goto _test_eof47
		}
	st_case_47:
//line rfc3164_parser.go:1506
		if 48 <= data[(p)] && data[(p)] <= 51 {
			goto st16
		}
		goto st2
	tr4:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st48
	st48:
		if (p)++; (p) == (pe) {
			goto _test_eof48
		}
	st_case_48:
//line rfc3164_parser.go:1522
		switch data[(p)] {
		case 112:
			goto st49
		case 117:
			goto st71
		}
		goto st2
	st49:
		if (p)++; (p) == (pe) {
			goto _test_eof49
		}
	st_case_49:
		if data[(p)] == 114 {
			goto st50
		}
		goto st2
	st50:
		if (p)++; (p) == (pe) {
			goto _test_eof50
		}
	st_case_50:
		switch data[(p)] {
		case 32:
			goto tr77
		case 105:
			goto st69
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	tr77:
		// line-disable-directive parser/common.rl:15

		event.SetMonth(data[tok:p])

		goto st51
	st51:
		if (p)++; (p) == (pe) {
			goto _test_eof51
		}
	st_case_51:
//line rfc3164_parser.go:1565
		switch data[(p)] {
		case 32:
			goto st52
		case 48:
			goto tr80
		case 51:
			goto tr82
		}
		switch {
		case data[(p)] < 49:
			if 9 <= data[(p)] && data[(p)] <= 13 {
				goto st52
			}
		case data[(p)] > 50:
			if 52 <= data[(p)] && data[(p)] <= 57 {
				goto tr83
			}
		default:
			goto tr81
		}
		goto st2
	st52:
		if (p)++; (p) == (pe) {
			goto _test_eof52
		}
	st_case_52:
		if 49 <= data[(p)] && data[(p)] <= 57 {
			goto tr83
		}
		goto st2
	tr83:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st53
	st53:
		if (p)++; (p) == (pe) {
			goto _test_eof53
		}
	st_case_53:
//line rfc3164_parser.go:1607
		if data[(p)] == 32 {
			goto tr84
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr84
		}
		goto st2
	tr84:
		// line-disable-directive parser/common.rl:27

		event.SetDay(data[tok:p])

		goto st54
	st54:
		if (p)++; (p) == (pe) {
			goto _test_eof54
		}
	st_case_54:
//line rfc3164_parser.go:1626
		if data[(p)] == 50 {
			goto tr86
		}
		if 48 <= data[(p)] && data[(p)] <= 49 {
			goto tr85
		}
		goto st2
	tr85:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st55
	st55:
		if (p)++; (p) == (pe) {
			goto _test_eof55
		}
	st_case_55:
//line rfc3164_parser.go:1645
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st56
		}
		goto st2
	st56:
		if (p)++; (p) == (pe) {
			goto _test_eof56
		}
	st_case_56:
		if data[(p)] == 58 {
			goto tr88
		}
		goto st2
	tr88:
		// line-disable-directive parser/common.rl:31

		event.SetHour(data[tok:p])

		goto st57
	st57:
		if (p)++; (p) == (pe) {
			goto _test_eof57
		}
	st_case_57:
//line rfc3164_parser.go:1670
		if 48 <= data[(p)] && data[(p)] <= 53 {
			goto tr89
		}
		goto st2
	tr89:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st58
	st58:
		if (p)++; (p) == (pe) {
			goto _test_eof58
		}
	st_case_58:
//line rfc3164_parser.go:1686
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st59
		}
		goto st2
	st59:
		if (p)++; (p) == (pe) {
			goto _test_eof59
		}
	st_case_59:
		if data[(p)] == 58 {
			goto tr91
		}
		goto st2
	tr91:
		// line-disable-directive parser/common.rl:35

		event.SetMinute(data[tok:p])

		goto st60
	st60:
		if (p)++; (p) == (pe) {
			goto _test_eof60
		}
	st_case_60:
//line rfc3164_parser.go:1711
		if 48 <= data[(p)] && data[(p)] <= 53 {
			goto tr92
		}
		goto st2
	tr92:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st61
	st61:
		if (p)++; (p) == (pe) {
			goto _test_eof61
		}
	st_case_61:
//line rfc3164_parser.go:1727
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st62
		}
		goto st2
	st62:
		if (p)++; (p) == (pe) {
			goto _test_eof62
		}
	st_case_62:
		switch data[(p)] {
		case 32:
			goto tr34
		case 46:
			goto tr94
		case 58:
			goto tr37
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr34
		}
		goto st2
	tr94:
		// line-disable-directive parser/common.rl:39

		event.SetSecond(data[tok:p])

		goto st63
	st63:
		if (p)++; (p) == (pe) {
			goto _test_eof63
		}
	st_case_63:
//line rfc3164_parser.go:1760
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr95
		}
		goto st2
	tr95:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st64
	st64:
		if (p)++; (p) == (pe) {
			goto _test_eof64
		}
	st_case_64:
//line rfc3164_parser.go:1776
		switch data[(p)] {
		case 32:
			goto tr68
		case 58:
			goto tr71
		}
		switch {
		case data[(p)] > 13:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto st64
			}
		case data[(p)] >= 9:
			goto tr68
		}
		goto st2
	tr86:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st65
	st65:
		if (p)++; (p) == (pe) {
			goto _test_eof65
		}
	st_case_65:
//line rfc3164_parser.go:1803
		if 48 <= data[(p)] && data[(p)] <= 51 {
			goto st56
		}
		goto st2
	tr80:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st66
	st66:
		if (p)++; (p) == (pe) {
			goto _test_eof66
		}
	st_case_66:
//line rfc3164_parser.go:1819
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st53
		}
		goto st2
	tr81:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st67
	st67:
		if (p)++; (p) == (pe) {
			goto _test_eof67
		}
	st_case_67:
//line rfc3164_parser.go:1835
		if data[(p)] == 32 {
			goto tr84
		}
		switch {
		case data[(p)] > 13:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto st53
			}
		case data[(p)] >= 9:
			goto tr84
		}
		goto st2
	tr82:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st68
	st68:
		if (p)++; (p) == (pe) {
			goto _test_eof68
		}
	st_case_68:
//line rfc3164_parser.go:1859
		if data[(p)] == 32 {
			goto tr84
		}
		switch {
		case data[(p)] > 13:
			if 48 <= data[(p)] && data[(p)] <= 49 {
				goto st53
			}
		case data[(p)] >= 9:
			goto tr84
		}
		goto st2
	st69:
		if (p)++; (p) == (pe) {
			goto _test_eof69
		}
	st_case_69:
		if data[(p)] == 108 {
			goto st70
		}
		goto st2
	st70:
		if (p)++; (p) == (pe) {
			goto _test_eof70
		}
	st_case_70:
		if data[(p)] == 32 {
			goto tr77
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st71:
		if (p)++; (p) == (pe) {
			goto _test_eof71
		}
	st_case_71:
		if data[(p)] == 103 {
			goto st72
		}
		goto st2
	st72:
		if (p)++; (p) == (pe) {
			goto _test_eof72
		}
	st_case_72:
		switch data[(p)] {
		case 32:
			goto tr77
		case 117:
			goto st73
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st73:
		if (p)++; (p) == (pe) {
			goto _test_eof73
		}
	st_case_73:
		if data[(p)] == 115 {
			goto st74
		}
		goto st2
	st74:
		if (p)++; (p) == (pe) {
			goto _test_eof74
		}
	st_case_74:
		if data[(p)] == 116 {
			goto st70
		}
		goto st2
	tr5:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st75
	st75:
		if (p)++; (p) == (pe) {
			goto _test_eof75
		}
	st_case_75:
//line rfc3164_parser.go:1946
		if data[(p)] == 101 {
			goto st76
		}
		goto st2
	st76:
		if (p)++; (p) == (pe) {
			goto _test_eof76
		}
	st_case_76:
		if data[(p)] == 99 {
			goto st77
		}
		goto st2
	st77:
		if (p)++; (p) == (pe) {
			goto _test_eof77
		}
	st_case_77:
		switch data[(p)] {
		case 32:
			goto tr77
		case 101:
			goto st78
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st78:
		if (p)++; (p) == (pe) {
			goto _test_eof78
		}
	st_case_78:
		if data[(p)] == 109 {
			goto st79
		}
		goto st2
	st79:
		if (p)++; (p) == (pe) {
			goto _test_eof79
		}
	st_case_79:
		if data[(p)] == 98 {
			goto st80
		}
		goto st2
	st80:
		if (p)++; (p) == (pe) {
			goto _test_eof80
		}
	st_case_80:
		if data[(p)] == 101 {
			goto st81
		}
		goto st2
	st81:
		if (p)++; (p) == (pe) {
			goto _test_eof81
		}
	st_case_81:
		if data[(p)] == 114 {
			goto st70
		}
		goto st2
	tr6:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st82
	st82:
		if (p)++; (p) == (pe) {
			goto _test_eof82
		}
	st_case_82:
//line rfc3164_parser.go:2022
		if data[(p)] == 101 {
			goto st83
		}
		goto st2
	st83:
		if (p)++; (p) == (pe) {
			goto _test_eof83
		}
	st_case_83:
		if data[(p)] == 98 {
			goto st84
		}
		goto st2
	st84:
		if (p)++; (p) == (pe) {
			goto _test_eof84
		}
	st_case_84:
		switch data[(p)] {
		case 32:
			goto tr77
		case 114:
			goto st85
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st85:
		if (p)++; (p) == (pe) {
			goto _test_eof85
		}
	st_case_85:
		if data[(p)] == 117 {
			goto st86
		}
		goto st2
	st86:
		if (p)++; (p) == (pe) {
			goto _test_eof86
		}
	st_case_86:
		if data[(p)] == 97 {
			goto st87
		}
		goto st2
	st87:
		if (p)++; (p) == (pe) {
			goto _test_eof87
		}
	st_case_87:
		if data[(p)] == 114 {
			goto st88
		}
		goto st2
	st88:
		if (p)++; (p) == (pe) {
			goto _test_eof88
		}
	st_case_88:
		if data[(p)] == 121 {
			goto st70
		}
		goto st2
	tr7:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st89
	st89:
		if (p)++; (p) == (pe) {
			goto _test_eof89
		}
	st_case_89:
//line rfc3164_parser.go:2098
		switch data[(p)] {
		case 97:
			goto st90
		case 117:
			goto st92
		}
		goto st2
	st90:
		if (p)++; (p) == (pe) {
			goto _test_eof90
		}
	st_case_90:
		if data[(p)] == 110 {
			goto st91
		}
		goto st2
	st91:
		if (p)++; (p) == (pe) {
			goto _test_eof91
		}
	st_case_91:
		switch data[(p)] {
		case 32:
			goto tr77
		case 117:
			goto st86
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st92:
		if (p)++; (p) == (pe) {
			goto _test_eof92
		}
	st_case_92:
		switch data[(p)] {
		case 108:
			goto st93
		case 110:
			goto st94
		}
		goto st2
	st93:
		if (p)++; (p) == (pe) {
			goto _test_eof93
		}
	st_case_93:
		switch data[(p)] {
		case 32:
			goto tr77
		case 121:
			goto st70
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st94:
		if (p)++; (p) == (pe) {
			goto _test_eof94
		}
	st_case_94:
		switch data[(p)] {
		case 32:
			goto tr77
		case 101:
			goto st70
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	tr8:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st95
	st95:
		if (p)++; (p) == (pe) {
			goto _test_eof95
		}
	st_case_95:
//line rfc3164_parser.go:2183
		if data[(p)] == 97 {
			goto st96
		}
		goto st2
	st96:
		if (p)++; (p) == (pe) {
			goto _test_eof96
		}
	st_case_96:
		switch data[(p)] {
		case 32:
			goto tr77
		case 114:
			goto st97
		case 121:
			goto st70
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st97:
		if (p)++; (p) == (pe) {
			goto _test_eof97
		}
	st_case_97:
		switch data[(p)] {
		case 32:
			goto tr77
		case 99:
			goto st98
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st98:
		if (p)++; (p) == (pe) {
			goto _test_eof98
		}
	st_case_98:
		if data[(p)] == 104 {
			goto st70
		}
		goto st2
	tr9:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st99
	st99:
		if (p)++; (p) == (pe) {
			goto _test_eof99
		}
	st_case_99:
//line rfc3164_parser.go:2240
		if data[(p)] == 111 {
			goto st100
		}
		goto st2
	st100:
		if (p)++; (p) == (pe) {
			goto _test_eof100
		}
	st_case_100:
		if data[(p)] == 118 {
			goto st77
		}
		goto st2
	tr10:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st101
	st101:
		if (p)++; (p) == (pe) {
			goto _test_eof101
		}
	st_case_101:
//line rfc3164_parser.go:2265
		if data[(p)] == 99 {
			goto st102
		}
		goto st2
	st102:
		if (p)++; (p) == (pe) {
			goto _test_eof102
		}
	st_case_102:
		if data[(p)] == 116 {
			goto st103
		}
		goto st2
	st103:
		if (p)++; (p) == (pe) {
			goto _test_eof103
		}
	st_case_103:
		switch data[(p)] {
		case 32:
			goto tr77
		case 111:
			goto st79
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	tr11:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st104
	st104:
		if (p)++; (p) == (pe) {
			goto _test_eof104
		}
	st_case_104:
//line rfc3164_parser.go:2305
		if data[(p)] == 101 {
			goto st105
		}
		goto st2
	st105:
		if (p)++; (p) == (pe) {
			goto _test_eof105
		}
	st_case_105:
		if data[(p)] == 112 {
			goto st106
		}
		goto st2
	st106:
		if (p)++; (p) == (pe) {
			goto _test_eof106
		}
	st_case_106:
		switch data[(p)] {
		case 32:
			goto tr77
		case 116:
			goto st107
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto tr77
		}
		goto st2
	st107:
		if (p)++; (p) == (pe) {
			goto _test_eof107
		}
	st_case_107:
		if data[(p)] == 101 {
			goto st78
		}
		goto st2
	tr2:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st108
	st108:
		if (p)++; (p) == (pe) {
			goto _test_eof108
		}
	st_case_108:
//line rfc3164_parser.go:2354
		if data[(p)] == 58 {
			goto tr129
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st109
		}
		goto st2
	st109:
		if (p)++; (p) == (pe) {
			goto _test_eof109
		}
	st_case_109:
		if data[(p)] == 58 {
			goto tr129
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st110
		}
		goto st2
	st110:
		if (p)++; (p) == (pe) {
			goto _test_eof110
		}
	st_case_110:
		if data[(p)] == 58 {
			goto tr129
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st111
		}
		goto st2
	st111:
		if (p)++; (p) == (pe) {
			goto _test_eof111
		}
	st_case_111:
		switch data[(p)] {
		case 45:
			goto tr18
		case 58:
			goto tr129
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st112
		}
		goto st2
	st112:
		if (p)++; (p) == (pe) {
			goto _test_eof112
		}
	st_case_112:
		if data[(p)] == 58 {
			goto tr129
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st112
		}
		goto st2
	tr129:
		// line-disable-directive parser/common.rl:107

		event.SetSequence(data[tok:p])

		goto st113
	st113:
		if (p)++; (p) == (pe) {
			goto _test_eof113
		}
	st_case_113:
//line rfc3164_parser.go:2424
		if data[(p)] == 32 {
			goto st114
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto st114
		}
		goto st2
	st114:
		if (p)++; (p) == (pe) {
			goto _test_eof114
		}
	st_case_114:
		switch data[(p)] {
		case 32:
			goto tr1
		case 42:
			goto tr1
		case 45:
			goto tr134
		case 46:
			goto tr135
		case 65:
			goto tr137
		case 68:
			goto tr138
		case 70:
			goto tr139
		case 74:
			goto tr140
		case 77:
			goto tr141
		case 78:
			goto tr142
		case 79:
			goto tr143
		case 83:
			goto tr144
		}
		switch {
		case data[(p)] < 66:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto tr136
			}
		case data[(p)] > 90:
			if 97 <= data[(p)] && data[(p)] <= 122 {
				goto tr134
			}
		default:
			goto tr134
		}
		goto tr0
	tr134:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st115
	st115:
		if (p)++; (p) == (pe) {
			goto _test_eof115
		}
	st_case_115:
//line rfc3164_parser.go:2487
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr146:
		// line-disable-directive parser/common.rl:91

		event.SetHostname(data[tok:p])

		goto st116
	st116:
		if (p)++; (p) == (pe) {
			goto _test_eof116
		}
	st_case_116:
//line rfc3164_parser.go:2520
		if data[(p)] == 32 {
			goto st117
		}
		if 9 <= data[(p)] && data[(p)] <= 13 {
			goto st117
		}
		goto st2
	st117:
		if (p)++; (p) == (pe) {
			goto _test_eof117
		}
	st_case_117:
		switch data[(p)] {
		case 32:
			goto tr1
		case 42:
			goto tr1
		case 46:
			goto tr1
		case 65:
			goto tr4
		case 68:
			goto tr5
		case 70:
			goto tr6
		case 74:
			goto tr7
		case 77:
			goto tr8
		case 78:
			goto tr9
		case 79:
			goto tr10
		case 83:
			goto tr11
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr14
		}
		goto tr0
	tr135:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st118
	st118:
		if (p)++; (p) == (pe) {
			goto _test_eof118
		}
	st_case_118:
//line rfc3164_parser.go:2572
		switch data[(p)] {
		case 58:
			goto tr146
		case 65:
			goto tr137
		case 68:
			goto tr138
		case 70:
			goto tr139
		case 74:
			goto tr140
		case 77:
			goto tr141
		case 78:
			goto tr142
		case 79:
			goto tr143
		case 83:
			goto tr144
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 66:
				goto st115
			}
		default:
			goto tr136
		}
		goto st2
	tr136:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st119
	st119:
		if (p)++; (p) == (pe) {
			goto _test_eof119
		}
	st_case_119:
//line rfc3164_parser.go:2622
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st120
		}
		goto st2
	st120:
		if (p)++; (p) == (pe) {
			goto _test_eof120
		}
	st_case_120:
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st121
		}
		goto st2
	st121:
		if (p)++; (p) == (pe) {
			goto _test_eof121
		}
	st_case_121:
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st122
		}
		goto st2
	st122:
		if (p)++; (p) == (pe) {
			goto _test_eof122
		}
	st_case_122:
		switch data[(p)] {
		case 45:
			goto tr151
		case 46:
			goto st115
		case 58:
			goto tr146
		}
		switch {
		case data[(p)] < 65:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto st115
			}
		case data[(p)] > 90:
			if 97 <= data[(p)] && data[(p)] <= 122 {
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr151:
		// line-disable-directive parser/common.rl:19

		event.SetYear(data[tok:p])

		goto st123
	st123:
		if (p)++; (p) == (pe) {
			goto _test_eof123
		}
	st_case_123:
//line rfc3164_parser.go:2733
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto tr152
		}
		goto st2
	tr152:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st124
	st124:
		if (p)++; (p) == (pe) {
			goto _test_eof124
		}
	st_case_124:
//line rfc3164_parser.go:2766
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st125
		}
		goto st2
	st125:
		if (p)++; (p) == (pe) {
			goto _test_eof125
		}
	st_case_125:
		switch data[(p)] {
		case 45:
			goto tr154
		case 46:
			goto st115
		case 58:
			goto tr146
		}
		switch {
		case data[(p)] < 65:
			if 48 <= data[(p)] && data[(p)] <= 57 {
				goto st115
			}
		case data[(p)] > 90:
			if 97 <= data[(p)] && data[(p)] <= 122 {
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr154:
		// line-disable-directive parser/common.rl:23

		event.SetMonthNumeric(data[tok:p])

		goto st126
	st126:
		if (p)++; (p) == (pe) {
			goto _test_eof126
		}
	st_case_126:
//line rfc3164_parser.go:2825
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 52:
			switch {
			case data[(p)] > 46:
				if 48 <= data[(p)] && data[(p)] <= 51 {
					goto tr155
				}
			case data[(p)] >= 45:
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr155:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st127
	st127:
		if (p)++; (p) == (pe) {
			goto _test_eof127
		}
	st_case_127:
//line rfc3164_parser.go:2863
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st128
		}
		goto st2
	st128:
		if (p)++; (p) == (pe) {
			goto _test_eof128
		}
	st_case_128:
		switch data[(p)] {
		case 32:
			goto tr24
		case 58:
			goto tr146
		case 84:
			goto tr157
		case 116:
			goto tr157
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr24
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr157:
		// line-disable-directive parser/common.rl:27

		event.SetDay(data[tok:p])

		goto st129
	st129:
		if (p)++; (p) == (pe) {
			goto _test_eof129
		}
	st_case_129:
//line rfc3164_parser.go:2934
		switch data[(p)] {
		case 50:
			goto tr159
		case 58:
			goto tr146
		}
		switch {
		case data[(p)] < 51:
			switch {
			case data[(p)] > 46:
				if 48 <= data[(p)] && data[(p)] <= 49 {
					goto tr158
				}
			case data[(p)] >= 45:
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr158:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st130
	st130:
		if (p)++; (p) == (pe) {
			goto _test_eof130
		}
	st_case_130:
//line rfc3164_parser.go:2975
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st131
		}
		goto st2
	st131:
		if (p)++; (p) == (pe) {
			goto _test_eof131
		}
	st_case_131:
		if data[(p)] == 58 {
			goto tr161
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr161:
		// line-disable-directive parser/common.rl:91

		event.SetHostname(data[tok:p])

		// line-disable-directive parser/common.rl:31

		event.SetHour(data[tok:p])

		goto st132
	st132:
		if (p)++; (p) == (pe) {
			goto _test_eof132
		}
	st_case_132:
//line rfc3164_parser.go:3038
		if data[(p)] == 32 {
			goto st117
		}
		switch {
		case data[(p)] > 13:
			if 48 <= data[(p)] && data[(p)] <= 53 {
				goto tr29
			}
		case data[(p)] >= 9:
			goto st117
		}
		goto st2
	tr159:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st133
	st133:
		if (p)++; (p) == (pe) {
			goto _test_eof133
		}
	st_case_133:
//line rfc3164_parser.go:3062
		if data[(p)] == 58 {
			goto tr146
		}
		switch {
		case data[(p)] < 52:
			switch {
			case data[(p)] > 46:
				if 48 <= data[(p)] && data[(p)] <= 51 {
					goto st131
				}
			case data[(p)] >= 45:
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr137:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st134
	st134:
		if (p)++; (p) == (pe) {
			goto _test_eof134
		}
	st_case_134:
//line rfc3164_parser.go:3100
		switch data[(p)] {
		case 58:
			goto tr146
		case 112:
			goto st135
		case 117:
			goto st139
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st135:
		if (p)++; (p) == (pe) {
			goto _test_eof135
		}
	st_case_135:
		switch data[(p)] {
		case 58:
			goto tr146
		case 114:
			goto st136
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st136:
		if (p)++; (p) == (pe) {
			goto _test_eof136
		}
	st_case_136:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 105:
			goto st137
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st137:
		if (p)++; (p) == (pe) {
			goto _test_eof137
		}
	st_case_137:
		switch data[(p)] {
		case 58:
			goto tr146
		case 108:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st138:
		if (p)++; (p) == (pe) {
			goto _test_eof138
		}
	st_case_138:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st139:
		if (p)++; (p) == (pe) {
			goto _test_eof139
		}
	st_case_139:
		switch data[(p)] {
		case 58:
			goto tr146
		case 103:
			goto st140
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st140:
		if (p)++; (p) == (pe) {
			goto _test_eof140
		}
	st_case_140:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 117:
			goto st141
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st141:
		if (p)++; (p) == (pe) {
			goto _test_eof141
		}
	st_case_141:
		switch data[(p)] {
		case 58:
			goto tr146
		case 115:
			goto st142
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st142:
		if (p)++; (p) == (pe) {
			goto _test_eof142
		}
	st_case_142:
		switch data[(p)] {
		case 58:
			goto tr146
		case 116:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr138:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st143
	st143:
		if (p)++; (p) == (pe) {
			goto _test_eof143
		}
	st_case_143:
//line rfc3164_parser.go:3389
		switch data[(p)] {
		case 58:
			goto tr146
		case 101:
			goto st144
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st144:
		if (p)++; (p) == (pe) {
			goto _test_eof144
		}
	st_case_144:
		switch data[(p)] {
		case 58:
			goto tr146
		case 99:
			goto st145
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st145:
		if (p)++; (p) == (pe) {
			goto _test_eof145
		}
	st_case_145:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 101:
			goto st146
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st146:
		if (p)++; (p) == (pe) {
			goto _test_eof146
		}
	st_case_146:
		switch data[(p)] {
		case 58:
			goto tr146
		case 109:
			goto st147
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st147:
		if (p)++; (p) == (pe) {
			goto _test_eof147
		}
	st_case_147:
		switch data[(p)] {
		case 58:
			goto tr146
		case 98:
			goto st148
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st148:
		if (p)++; (p) == (pe) {
			goto _test_eof148
		}
	st_case_148:
		switch data[(p)] {
		case 58:
			goto tr146
		case 101:
			goto st149
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st149:
		if (p)++; (p) == (pe) {
			goto _test_eof149
		}
	st_case_149:
		switch data[(p)] {
		case 58:
			goto tr146
		case 114:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr139:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st150
	st150:
		if (p)++; (p) == (pe) {
			goto _test_eof150
		}
	st_case_150:
//line rfc3164_parser.go:3606
		switch data[(p)] {
		case 58:
			goto tr146
		case 101:
			goto st151
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st151:
		if (p)++; (p) == (pe) {
			goto _test_eof151
		}
	st_case_151:
		switch data[(p)] {
		case 58:
			goto tr146
		case 98:
			goto st152
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st152:
		if (p)++; (p) == (pe) {
			goto _test_eof152
		}
	st_case_152:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 114:
			goto st153
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st153:
		if (p)++; (p) == (pe) {
			goto _test_eof153
		}
	st_case_153:
		switch data[(p)] {
		case 58:
			goto tr146
		case 117:
			goto st154
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st154:
		if (p)++; (p) == (pe) {
			goto _test_eof154
		}
	st_case_154:
		switch data[(p)] {
		case 58:
			goto tr146
		case 97:
			goto st155
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 98 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st155:
		if (p)++; (p) == (pe) {
			goto _test_eof155
		}
	st_case_155:
		switch data[(p)] {
		case 58:
			goto tr146
		case 114:
			goto st156
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st156:
		if (p)++; (p) == (pe) {
			goto _test_eof156
		}
	st_case_156:
		switch data[(p)] {
		case 58:
			goto tr146
		case 121:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr140:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st157
	st157:
		if (p)++; (p) == (pe) {
			goto _test_eof157
		}
	st_case_157:
//line rfc3164_parser.go:3823
		switch data[(p)] {
		case 58:
			goto tr146
		case 97:
			goto st158
		case 117:
			goto st160
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 98 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st158:
		if (p)++; (p) == (pe) {
			goto _test_eof158
		}
	st_case_158:
		switch data[(p)] {
		case 58:
			goto tr146
		case 110:
			goto st159
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st159:
		if (p)++; (p) == (pe) {
			goto _test_eof159
		}
	st_case_159:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 117:
			goto st154
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st160:
		if (p)++; (p) == (pe) {
			goto _test_eof160
		}
	st_case_160:
		switch data[(p)] {
		case 58:
			goto tr146
		case 108:
			goto st161
		case 110:
			goto st162
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st161:
		if (p)++; (p) == (pe) {
			goto _test_eof161
		}
	st_case_161:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 121:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st162:
		if (p)++; (p) == (pe) {
			goto _test_eof162
		}
	st_case_162:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 101:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr141:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st163
	st163:
		if (p)++; (p) == (pe) {
			goto _test_eof163
		}
	st_case_163:
//line rfc3164_parser.go:4029
		switch data[(p)] {
		case 58:
			goto tr146
		case 97:
			goto st164
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 98 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st164:
		if (p)++; (p) == (pe) {
			goto _test_eof164
		}
	st_case_164:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 114:
			goto st165
		case 121:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st165:
		if (p)++; (p) == (pe) {
			goto _test_eof165
		}
	st_case_165:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 99:
			goto st166
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st166:
		if (p)++; (p) == (pe) {
			goto _test_eof166
		}
	st_case_166:
		switch data[(p)] {
		case 58:
			goto tr146
		case 104:
			goto st138
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr142:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st167
	st167:
		if (p)++; (p) == (pe) {
			goto _test_eof167
		}
	st_case_167:
//line rfc3164_parser.go:4168
		switch data[(p)] {
		case 58:
			goto tr146
		case 111:
			goto st168
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st168:
		if (p)++; (p) == (pe) {
			goto _test_eof168
		}
	st_case_168:
		switch data[(p)] {
		case 58:
			goto tr146
		case 118:
			goto st145
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr143:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st169
	st169:
		if (p)++; (p) == (pe) {
			goto _test_eof169
		}
	st_case_169:
//line rfc3164_parser.go:4233
		switch data[(p)] {
		case 58:
			goto tr146
		case 99:
			goto st170
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st170:
		if (p)++; (p) == (pe) {
			goto _test_eof170
		}
	st_case_170:
		switch data[(p)] {
		case 58:
			goto tr146
		case 116:
			goto st171
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st171:
		if (p)++; (p) == (pe) {
			goto _test_eof171
		}
	st_case_171:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 111:
			goto st147
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr144:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st172
	st172:
		if (p)++; (p) == (pe) {
			goto _test_eof172
		}
	st_case_172:
//line rfc3164_parser.go:4334
		switch data[(p)] {
		case 58:
			goto tr146
		case 101:
			goto st173
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st173:
		if (p)++; (p) == (pe) {
			goto _test_eof173
		}
	st_case_173:
		switch data[(p)] {
		case 58:
			goto tr146
		case 112:
			goto st174
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st174:
		if (p)++; (p) == (pe) {
			goto _test_eof174
		}
	st_case_174:
		switch data[(p)] {
		case 32:
			goto tr77
		case 58:
			goto tr146
		case 116:
			goto st175
		}
		switch {
		case data[(p)] < 48:
			switch {
			case data[(p)] > 13:
				if 45 <= data[(p)] && data[(p)] <= 46 {
					goto st115
				}
			case data[(p)] >= 9:
				goto tr77
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	st175:
		if (p)++; (p) == (pe) {
			goto _test_eof175
		}
	st_case_175:
		switch data[(p)] {
		case 58:
			goto tr146
		case 101:
			goto st146
		}
		switch {
		case data[(p)] < 48:
			if 45 <= data[(p)] && data[(p)] <= 46 {
				goto st115
			}
		case data[(p)] > 57:
			switch {
			case data[(p)] > 90:
				if 97 <= data[(p)] && data[(p)] <= 122 {
					goto st115
				}
			case data[(p)] >= 65:
				goto st115
			}
		default:
			goto st115
		}
		goto st2
	tr3:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st176
	st176:
		if (p)++; (p) == (pe) {
			goto _test_eof176
		}
	st_case_176:
//line rfc3164_parser.go:4464
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr196
		}
		goto st2
	tr196:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st177
	st177:
		if (p)++; (p) == (pe) {
			goto _test_eof177
		}
	st_case_177:
//line rfc3164_parser.go:4480
		if data[(p)] == 62 {
			goto tr198
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st178
		}
		goto st2
	st178:
		if (p)++; (p) == (pe) {
			goto _test_eof178
		}
	st_case_178:
		if data[(p)] == 62 {
			goto tr198
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st179
		}
		goto st2
	st179:
		if (p)++; (p) == (pe) {
			goto _test_eof179
		}
	st_case_179:
		if data[(p)] == 62 {
			goto tr198
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st180
		}
		goto st2
	st180:
		if (p)++; (p) == (pe) {
			goto _test_eof180
		}
	st_case_180:
		if data[(p)] == 62 {
			goto tr198
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto st181
		}
		goto st2
	st181:
		if (p)++; (p) == (pe) {
			goto _test_eof181
		}
	st_case_181:
		if data[(p)] == 62 {
			goto tr198
		}
		goto st2
	tr198:
		// line-disable-directive parser/common.rl:7

		event.SetPriority(data[tok:p])

		goto st182
	st182:
		if (p)++; (p) == (pe) {
			goto _test_eof182
		}
	st_case_182:
//line rfc3164_parser.go:4544
		switch data[(p)] {
		case 32:
			goto tr1
		case 42:
			goto tr1
		case 46:
			goto tr1
		case 65:
			goto tr4
		case 68:
			goto tr5
		case 70:
			goto tr6
		case 74:
			goto tr7
		case 77:
			goto tr8
		case 78:
			goto tr9
		case 79:
			goto tr10
		case 83:
			goto tr11
		}
		if 48 <= data[(p)] && data[(p)] <= 57 {
			goto tr2
		}
		goto tr0
	st1:
		if (p)++; (p) == (pe) {
			goto _test_eof1
		}
	st_case_1:
		goto tr12
	tr12:
		// line-disable-directive parser/common.rl:3

		tok = p

		goto st183
	st183:
		if (p)++; (p) == (pe) {
			goto _test_eof183
		}
	st_case_183:
//line rfc3164_parser.go:4590
		goto st183
	st_out:
	_test_eof2:
		cs = 2
		goto _test_eof
	_test_eof3:
		cs = 3
		goto _test_eof
	_test_eof4:
		cs = 4
		goto _test_eof
	_test_eof5:
		cs = 5
		goto _test_eof
	_test_eof6:
		cs = 6
		goto _test_eof
	_test_eof7:
		cs = 7
		goto _test_eof
	_test_eof8:
		cs = 8
		goto _test_eof
	_test_eof9:
		cs = 9
		goto _test_eof
	_test_eof10:
		cs = 10
		goto _test_eof
	_test_eof11:
		cs = 11
		goto _test_eof
	_test_eof12:
		cs = 12
		goto _test_eof
	_test_eof13:
		cs = 13
		goto _test_eof
	_test_eof14:
		cs = 14
		goto _test_eof
	_test_eof15:
		cs = 15
		goto _test_eof
	_test_eof16:
		cs = 16
		goto _test_eof
	_test_eof17:
		cs = 17
		goto _test_eof
	_test_eof18:
		cs = 18
		goto _test_eof
	_test_eof19:
		cs = 19
		goto _test_eof
	_test_eof20:
		cs = 20
		goto _test_eof
	_test_eof21:
		cs = 21
		goto _test_eof
	_test_eof22:
		cs = 22
		goto _test_eof
	_test_eof23:
		cs = 23
		goto _test_eof
	_test_eof24:
		cs = 24
		goto _test_eof
	_test_eof25:
		cs = 25
		goto _test_eof
	_test_eof26:
		cs = 26
		goto _test_eof
	_test_eof27:
		cs = 27
		goto _test_eof
	_test_eof28:
		cs = 28
		goto _test_eof
	_test_eof29:
		cs = 29
		goto _test_eof
	_test_eof30:
		cs = 30
		goto _test_eof
	_test_eof31:
		cs = 31
		goto _test_eof
	_test_eof32:
		cs = 32
		goto _test_eof
	_test_eof33:
		cs = 33
		goto _test_eof
	_test_eof34:
		cs = 34
		goto _test_eof
	_test_eof35:
		cs = 35
		goto _test_eof
	_test_eof36:
		cs = 36
		goto _test_eof
	_test_eof37:
		cs = 37
		goto _test_eof
	_test_eof38:
		cs = 38
		goto _test_eof
	_test_eof39:
		cs = 39
		goto _test_eof
	_test_eof40:
		cs = 40
		goto _test_eof
	_test_eof41:
		cs = 41
		goto _test_eof
	_test_eof42:
		cs = 42
		goto _test_eof
	_test_eof43:
		cs = 43
		goto _test_eof
	_test_eof44:
		cs = 44
		goto _test_eof
	_test_eof45:
		cs = 45
		goto _test_eof
	_test_eof46:
		cs = 46
		goto _test_eof
	_test_eof47:
		cs = 47
		goto _test_eof
	_test_eof48:
		cs = 48
		goto _test_eof
	_test_eof49:
		cs = 49
		goto _test_eof
	_test_eof50:
		cs = 50
		goto _test_eof
	_test_eof51:
		cs = 51
		goto _test_eof
	_test_eof52:
		cs = 52
		goto _test_eof
	_test_eof53:
		cs = 53
		goto _test_eof
	_test_eof54:
		cs = 54
		goto _test_eof
	_test_eof55:
		cs = 55
		goto _test_eof
	_test_eof56:
		cs = 56
		goto _test_eof
	_test_eof57:
		cs = 57
		goto _test_eof
	_test_eof58:
		cs = 58
		goto _test_eof
	_test_eof59:
		cs = 59
		goto _test_eof
	_test_eof60:
		cs = 60
		goto _test_eof
	_test_eof61:
		cs = 61
		goto _test_eof
	_test_eof62:
		cs = 62
		goto _test_eof
	_test_eof63:
		cs = 63
		goto _test_eof
	_test_eof64:
		cs = 64
		goto _test_eof
	_test_eof65:
		cs = 65
		goto _test_eof
	_test_eof66:
		cs = 66
		goto _test_eof
	_test_eof67:
		cs = 67
		goto _test_eof
	_test_eof68:
		cs = 68
		goto _test_eof
	_test_eof69:
		cs = 69
		goto _test_eof
	_test_eof70:
		cs = 70
		goto _test_eof
	_test_eof71:
		cs = 71
		goto _test_eof
	_test_eof72:
		cs = 72
		goto _test_eof
	_test_eof73:
		cs = 73
		goto _test_eof
	_test_eof74:
		cs = 74
		goto _test_eof
	_test_eof75:
		cs = 75
		goto _test_eof
	_test_eof76:
		cs = 76
		goto _test_eof
	_test_eof77:
		cs = 77
		goto _test_eof
	_test_eof78:
		cs = 78
		goto _test_eof
	_test_eof79:
		cs = 79
		goto _test_eof
	_test_eof80:
		cs = 80
		goto _test_eof
	_test_eof81:
		cs = 81
		goto _test_eof
	_test_eof82:
		cs = 82
		goto _test_eof
	_test_eof83:
		cs = 83
		goto _test_eof
	_test_eof84:
		cs = 84
		goto _test_eof
	_test_eof85:
		cs = 85
		goto _test_eof
	_test_eof86:
		cs = 86
		goto _test_eof
	_test_eof87:
		cs = 87
		goto _test_eof
	_test_eof88:
		cs = 88
		goto _test_eof
	_test_eof89:
		cs = 89
		goto _test_eof
	_test_eof90:
		cs = 90
		goto _test_eof
	_test_eof91:
		cs = 91
		goto _test_eof
	_test_eof92:
		cs = 92
		goto _test_eof
	_test_eof93:
		cs = 93
		goto _test_eof
	_test_eof94:
		cs = 94
		goto _test_eof
	_test_eof95:
		cs = 95
		goto _test_eof
	_test_eof96:
		cs = 96
		goto _test_eof
	_test_eof97:
		cs = 97
		goto _test_eof
	_test_eof98:
		cs = 98
		goto _test_eof
	_test_eof99:
		cs = 99
		goto _test_eof
	_test_eof100:
		cs = 100
		goto _test_eof
	_test_eof101:
		cs = 101
		goto _test_eof
	_test_eof102:
		cs = 102
		goto _test_eof
	_test_eof103:
		cs = 103
		goto _test_eof
	_test_eof104:
		cs = 104
		goto _test_eof
	_test_eof105:
		cs = 105
		goto _test_eof
	_test_eof106:
		cs = 106
		goto _test_eof
	_test_eof107:
		cs = 107
		goto _test_eof
	_test_eof108:
		cs = 108
		goto _test_eof
	_test_eof109:
		cs = 109
		goto _test_eof
	_test_eof110:
		cs = 110
		goto _test_eof
	_test_eof111:
		cs = 111
		goto _test_eof
	_test_eof112:
		cs = 112
		goto _test_eof
	_test_eof113:
		cs = 113
		goto _test_eof
	_test_eof114:
		cs = 114
		goto _test_eof
	_test_eof115:
		cs = 115
		goto _test_eof
	_test_eof116:
		cs = 116
		goto _test_eof
	_test_eof117:
		cs = 117
		goto _test_eof
	_test_eof118:
		cs = 118
		goto _test_eof
	_test_eof119:
		cs = 119
		goto _test_eof
	_test_eof120:
		cs = 120
		goto _test_eof
	_test_eof121:
		cs = 121
		goto _test_eof
	_test_eof122:
		cs = 122
		goto _test_eof
	_test_eof123:
		cs = 123
		goto _test_eof
	_test_eof124:
		cs = 124
		goto _test_eof
	_test_eof125:
		cs = 125
		goto _test_eof
	_test_eof126:
		cs = 126
		goto _test_eof
	_test_eof127:
		cs = 127
		goto _test_eof
	_test_eof128:
		cs = 128
		goto _test_eof
	_test_eof129:
		cs = 129
		goto _test_eof
	_test_eof130:
		cs = 130
		goto _test_eof
	_test_eof131:
		cs = 131
		goto _test_eof
	_test_eof132:
		cs = 132
		goto _test_eof
	_test_eof133:
		cs = 133
		goto _test_eof
	_test_eof134:
		cs = 134
		goto _test_eof
	_test_eof135:
		cs = 135
		goto _test_eof
	_test_eof136:
		cs = 136
		goto _test_eof
	_test_eof137:
		cs = 137
		goto _test_eof
	_test_eof138:
		cs = 138
		goto _test_eof
	_test_eof139:
		cs = 139
		goto _test_eof
	_test_eof140:
		cs = 140
		goto _test_eof
	_test_eof141:
		cs = 141
		goto _test_eof
	_test_eof142:
		cs = 142
		goto _test_eof
	_test_eof143:
		cs = 143
		goto _test_eof
	_test_eof144:
		cs = 144
		goto _test_eof
	_test_eof145:
		cs = 145
		goto _test_eof
	_test_eof146:
		cs = 146
		goto _test_eof
	_test_eof147:
		cs = 147
		goto _test_eof
	_test_eof148:
		cs = 148
		goto _test_eof
	_test_eof149:
		cs = 149
		goto _test_eof
	_test_eof150:
		cs = 150
		goto _test_eof
	_test_eof151:
		cs = 151
		goto _test_eof
	_test_eof152:
		cs = 152
		goto _test_eof
	_test_eof153:
		cs = 153
		goto _test_eof
	_test_eof154:
		cs = 154
		goto _test_eof
	_test_eof155:
		cs = 155
		goto _test_eof
	_test_eof156:
		cs = 156
		goto _test_eof
	_test_eof157:
		cs = 157
		goto _test_eof
	_test_eof158:
		cs = 158
		goto _test_eof
	_test_eof159:
		cs = 159
		goto _test_eof
	_test_eof160:
		cs = 160
		goto _test_eof
	_test_eof161:
		cs = 161
		goto _test_eof
	_test_eof162:
		cs = 162
		goto _test_eof
	_test_eof163:
		cs = 163
		goto _test_eof
	_test_eof164:
		cs = 164
		goto _test_eof
	_test_eof165:
		cs = 165
		goto _test_eof
	_test_eof166:
		cs = 166
		goto _test_eof
	_test_eof167:
		cs = 167
		goto _test_eof
	_test_eof168:
		cs = 168
		goto _test_eof
	_test_eof169:
		cs = 169
		goto _test_eof
	_test_eof170:
		cs = 170
		goto _test_eof
	_test_eof171:
		cs = 171
		goto _test_eof
	_test_eof172:
		cs = 172
		goto _test_eof
	_test_eof173:
		cs = 173
		goto _test_eof
	_test_eof174:
		cs = 174
		goto _test_eof
	_test_eof175:
		cs = 175
		goto _test_eof
	_test_eof176:
		cs = 176
		goto _test_eof
	_test_eof177:
		cs = 177
		goto _test_eof
	_test_eof178:
		cs = 178
		goto _test_eof
	_test_eof179:
		cs = 179
		goto _test_eof
	_test_eof180:
		cs = 180
		goto _test_eof
	_test_eof181:
		cs = 181
		goto _test_eof
	_test_eof182:
		cs = 182
		goto _test_eof
	_test_eof1:
		cs = 1
		goto _test_eof
	_test_eof183:
		cs = 183
		goto _test_eof

	_test_eof:
		{
		}
		if (p) == eof {
			switch cs {
			case 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183:
				// line-disable-directive parser/common.rl:11

				event.SetMessage(data[tok:p])

//line rfc3164_parser.go:4785
			}
		}

	}

	// line-disable-directive parser/rfc3164_parser.rl:28

}
