[role="xpack"]
[[monitoring]]
= Monitoring {beatname_uc}

[partintro]
--

You can use the {stack} {monitor-features} to gain insight into the health of
ifndef::apm-server[]
{beatname_uc} instances running in your environment. 
endif::[]
ifdef::apm-server[]
{beatname_uc}. 
endif::[]

To monitor {beatname_uc}, make sure monitoring is enabled on your {es} cluster,
then configure the method used to collect {beatname_uc} metrics. You can use one
of following methods:

ifndef::serverless[]
* <<monitoring-metricbeat-collection, {metricbeat} collection>> - 
{metricbeat} sends monitoring data directly to your monitoring cluster.
endif::[]
* <<monitoring-internal-collection,Internal collection>> - Internal
collectors send monitoring data directly to your monitoring cluster.
* <<monitoring-internal-collection-legacy,Legacy collection (deprecated)>> - 
Legacy collectors send monitoring data to your production cluster.


//Commenting out this link temporarily until the general monitoring docs can be
//updated. 
//To learn about monitoring in general, see 
//{ref}/monitor-elasticsearch-cluster.html[Monitor a cluster]. 

--

ifndef::serverless[]
include::monitoring-metricbeat.asciidoc[]
endif::[]

include::monitoring-internal-collection.asciidoc[]

include::monitoring-internal-collection-legacy.asciidoc[]

