//////////////////////////////////////////////////////////////////////////
//// This content is shared by all Elastic Beats. Make sure you keep the
//// descriptions here generic enough to work for all Beats that include
//// this file. When using cross references, make sure that the cross
//// references resolve correctly for any files that include this one.
//// Use the appropriate variables defined in the index.asciidoc file to
//// resolve Beat names: beatname_uc and beatname_lc.
//// Use the following include to pull this content into a doc file:
//// include::../../libbeat/docs/monitoring/monitoring-internal-collection.asciidoc[]
//////////////////////////////////////////////////////////////////////////

[role="xpack"]
[[monitoring-internal-collection]]
== Collect {beatname_uc} monitoring data with internal collectors
++++
<titleabbrev>Internal collection</titleabbrev>
++++

The following method involves sending the metrics to the production cluster, 
which ultimately routes them to the monitoring cluster.
ifndef::serverless[]
For an alternative method, see <<monitoring-metricbeat-collection>>.
endif::[]

To learn about monitoring in general, see 
{stack-ov}/xpack-monitoring.html[Monitoring the {stack}]. 

//TODO: Not sure if these docs need to be updated to be parallel with other
//stack components since this is the old way of configuring monitoring. 

. Create a user that has appropriate authority to send system-level monitoring
data to {es}. For example, you can use the built-in +{beat_monitoring_user}+ user or
assign the built-in +{beat_monitoring_user}+ role to another user. For more
information, see
{stack-ov}/setting-up-authentication.html[Setting Up User Authentication] and
{stack-ov}/built-in-roles.html[Built-in Roles].

. Add the `monitoring` settings in the {beatname_uc} configuration file. If you
configured the {es} output and want to send {beatname_uc} monitoring events to
the same {es} cluster, specify the following minimal configuration:
+
["source","yml",subs="attributes"]
--------------------
monitoring:
  enabled: true
  elasticsearch:
    username: {beat_monitoring_user}
    password: somepassword
--------------------
+
If you
ifndef::only-elasticsearch[]
configured a different output, such as {ls} or you
endif::only-elasticsearch[]
want to send {beatname_uc} monitoring events to a separate {es} cluster
(referred to as the _monitoring cluster_), you must specify additional
configuration options. For example:
+
["source","yml",subs="attributes"]
--------------------
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://example.com:9200", "https://example2.com:9200"] <1>
    username: {beat_monitoring_user}
    password: somepassword
--------------------
<1> This setting identifies the hosts and port numbers of {es} nodes
that are part of the monitoring cluster.

ifndef::serverless[]
. Start {beatname_uc}.
endif::[]

ifdef::serverless[]
. Deploy {beatname_uc}.
endif::[]

. {kibana-ref}/monitoring-data.html[View the monitoring data in {kib}]. 


include::shared-monitor-config.asciidoc[]
