[role="xpack"]
[[monitoring]]
= Monitoring {beatname_uc}

[partintro]
--

You can use the {stack} {monitor-features} to gain insight into the health of
{beatname_uc} agents running in your environment. 

To monitor {beatname_uc}, make sure monitoring is enabled on your {es} cluster,
then configure the method used to collect {beatname_uc} metrics. You can use one
of following methods:

* <<monitoring-internal-collection,Internal collection>> - Internal
collectors send monitoring data directly to your monitoring cluster.
ifndef::serverless[]
* <<monitoring-metricbeat-collection, {metricbeat} collection>> - 
{metricbeat} collects monitoring data from your {beatname_uc} instance
and sends it directly to your monitoring cluster.
endif::[]
* <<monitoring-internal-collection-legacy,Legacy internal collection (deprecated)>> - 
Legacy internal collectors send monitoring data to your production cluster.


To learn about monitoring in general, see 
{stack-ov}/xpack-monitoring.html[Monitoring the {stack}]. 

--

include::monitoring-internal-collection.asciidoc[]

ifndef::serverless[]
include::monitoring-metricbeat.asciidoc[]
endif::[]

include::monitoring-internal-collection-legacy.asciidoc[]
