//TODO: Remove this file and the widget after the naming changes are building
// tag::deb[]

// tag::install-tip[]
TIP: We recommend that you run this command as the root user because some
integrations require root privileges to collect sensitive data.

// end::install-tip[]

[source,shell]
----
elastic-agent install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
----

include::install.asciidoc[tag=where-description]
// end::deb[]

// tag::rpm[]

include::install.asciidoc[tag=install-tip]

[source,shell]
----
elastic-agent install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
----

include::install.asciidoc[tag=where-description]
// end::rpm[]

// tag::mac[]

include::install.asciidoc[tag=install-tip]

[source,shell]
----
./elastic-agent install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
----

include::install.asciidoc[tag=where-description]
// end::mac[]

// tag::linux[]

include::install.asciidoc[tag=install-tip]

[source,shell]
----
./elastic-agent install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
----

include::install.asciidoc[tag=where-description]
// end::linux[]

// tag::win[]
Open a PowerShell prompt as an Administrator (right-click the PowerShell icon
and select **Run As Administrator**).

From the PowerShell prompt, change to the directory where you installed {agent},
and run:

[source,shell]
----
.\elastic-agent.exe install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
----

include::install.asciidoc[tag=where-description]
// end::win[]

// tag::where-description[]
Where `KIBANA_URL` is the {kib} URL where {fleet} is running, and
`ENROLLMENT_KEY` is the enrollment token acquired from {fleet}.

Don't have a {fleet} enrollment key? Read the 
{ingest-guide}/ingest-management-getting-started.html[Quick start guide] to learn how to generate
one.

// end::where-description[]