// tag::deb[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-amd64.deb
sudo dpkg -i elastic-agent-{version}-amd64.deb
----

endif::[]
// end::deb[]

// tag::rpm[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-x86_64.rpm
sudo rpm -vi elastic-agent-{version}-x86_64.rpm
----
endif::[]
// end::rpm[]

// tag::mac[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-darwin-x86_64.tar.gz
tar xzvf elastic-agent-{version}-darwin-x86_64.tar.gz
----

endif::[]
// end::mac[]

// tag::linux[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-linux-x86_64.tar.gz
tar xzvf elastic-agent-{version}-linux-x86_64.tar.gz
----

NOTE: We recommend that you use the DEB or RPM distribution, instead of the
tarball, to ensure that {agent} restarts automatically if the system is
rebooted.

endif::[]
// end::linux[]

// tag::win[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

. Download the {agent} Windows zip file from the
https://www.elastic.co/downloads/beats/elastic-agent[downloads page].

. Extract the contents of the zip file into `C:\Program Files`.

. Rename the `elastic-agent-<version>-windows` directory to `Elastic-Agent`.

endif::[]
// end::win[]
