// tag::deb[]

// tag::install-tip[]
TIP: We recommend that you run this command as the root user because some
integrations require root privileges to collect sensitive data.

// end::install-tip[]

[source,shell]
----
elastic-agent enroll KIBANA_URL ENROLLMENT_KEY
systemctl enable elastic-agent <1>
systemctl start elastic-agent
----
<1> The DEB package includes a service unit for Linux systems with systemd. On
these systems, you can manage {agent} by using the usual systemd commands. If
you don't have systemd, run `sudo service elastic-agent start`.

include::install.asciidoc[tag=where-description]

TIP: {agent} will restart automatically if the system is rebooted.

// end::deb[]

// tag::rpm[]

include::install.asciidoc[tag=install-tip]

[source,shell]
----
elastic-agent enroll KIBANA_URL ENROLLMENT_KEY
systemctl enable elastic-agent <1>
systemctl start elastic-agent
----
<1> The RPM package includes a service unit for Linux systems with systemd. On
these systems, you can manage {agent} by using the usual systemd commands. If
you don't have systemd, run `sudo service elastic-agent start`.

TIP: {agent} will restart automatically if the system is rebooted.

// end::rpm[]

// tag::mac[]

include::install.asciidoc[tag=install-tip]

[source,shell]
----
./elastic-agent install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
----

include::install.asciidoc[tag=where-description]

Omit `-f` to run an interactive installation.

// end::mac[]

// tag::linux[]

include::install.asciidoc[tag=install-tip]

[source,shell]
----
./elastic-agent install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY <1>
----
<1> This command requires a system and service manager like systemd.

include::install.asciidoc[tag=where-description]

Omit `-f` to run an interactive installation.

// end::linux[]

// tag::win[]
Open a PowerShell prompt as an Administrator (right-click the PowerShell icon
and select **Run As Administrator**).

From the PowerShell prompt, change to the directory where you installed {agent},
and run:

[source,shell]
----
.\elastic-agent.exe install -f --kibana-url=KIBANA_URL --enrollment-token=ENROLLMENT_KEY
----

include::install.asciidoc[tag=where-description]

Omit `-f` to run an interactive installation.

// end::win[]

// tag::where-description[]
`KIBANA_URL` is the {kib} URL where {fleet} is running, and
`ENROLLMENT_KEY` is the enrollment token acquired from {fleet}. Don't have a
{fleet} enrollment key? Read the
{ingest-guide}/ingest-management-getting-started.html[Quick start guide] to
learn how to generate one.

// end::where-description[]