// tag::deb[]

The DEB package includes a service unit for Linux systems with systemd. On these
systems, you can manage {agent} by using the usual systemd commands:

[source,shell]
----
systemctl enable elastic-agent
systemctl start elastic-agent
----

Otherwise, use:

[source,shell]
----
sudo service elastic-agent start
----

NOTE: {agent} will restart automatically if the system is rebooted.

// end::deb[]

// tag::rpm[]
The RPM package includes a service unit for Linux systems with systemd. On these
systems, you can manage {agent} by using the usual systemd commands:

[source,shell]
----
systemctl enable elastic-agent
systemctl start elastic-agent
----

Otherwise, use:

[source,shell]
----
sudo service elastic-agent start
----

NOTE: {agent} will restart automatically if the system is rebooted.

// end::rpm[]

// tag::mac[]
[source,shell]
----
./elastic-agent run
----

NOTE: You must restart {agent} manually if the agent terminates or the system is
rebooted.

// end::mac[]

// tag::linux[]
[source,shell]
----
./elastic-agent run
----

NOTE: You must restart {agent} manually if the agent terminates or the system is
rebooted.

// end::linux[]

// tag::win[]
[source,shell]
----
Start-Service elastic-agent <1>
----
<1> On Windows, you must run {agent} under the SYSTEM account if you plan
to use the {elastic-endpoint} integration.

NOTE: {agent} will restart automatically if the system is rebooted.

// end::win[]
