// tag::deb[]

The DEB package includes a service unit for Linux systems with systemd. On these
systems, you can manage {agent} by using the usual systemd commands:

[source,shell]
----
systemctl enable elastic-agent
systemctl start elastic-agent
----

Otherwise, use:

[source,shell]
----
sudo service elastic-agent start
----

NOTE: {agent} will restart automatically if the system is rebooted.

// end::deb[]

// tag::rpm[]
The RPM package includes a service unit for Linux systems with systemd. On these
systems, you can manage {agent} by using the usual systemd commands:

[source,shell]
----
systemctl enable elastic-agent
systemctl start elastic-agent
----

Otherwise, use:

[source,shell]
----
sudo service elastic-agent start
----

NOTE: {agent} will restart automatically if the system is rebooted.

// end::rpm[]

// tag::mac[]
[source,shell]
----
./elastic-agent run
----

[NOTE]
====
This command starts {agent} in the foreground. You must restart {agent}
manually if the agent terminates or the system is rebooted.

To start the agent automatically when the system is rebooted, 
{ingest-guide}/elastic-agent-installation.html#elastic-agent-install-service-macos[Install the agent as a service].
====

// end::mac[]

// tag::linux[]
[source,shell]
----
./elastic-agent run
----

[NOTE]
====
This command starts {agent} in the foreground. You must restart {agent} manually
if the agent terminates or the system is rebooted.

To start the agent automatically when the system is rebooted, 
use the DEB or RPM package instead of the tarball.
====

// end::linux[]

// tag::win[]
The first time you run {agent}, you need to install it as auto-starting Windows
service. To do this, run the PowerShell script provided in the archive you
downloaded:

. Open a PowerShell prompt as an Administrator (right-click the PowerShell icon
and select *Run As Administrator*).

. From the PowerShell prompt, run the following commands to install {agent} as
an service and start the service:
+
[source,shell]
----
cd 'C:\Program Files\Elastic-Agent'
.\install-service-elastic-agent.ps1 <1> <2>
----
<1> You must run {agent} under the SYSTEM account if you plan
to use the {elastic-endpoint} integration.
<2> If script execution is disabled on your system, set the execution policy for
the current session to allow the script to run. For example:
`PowerShell.exe -ExecutionPolicy UnRestricted -File .\install-service-elastic-agent.ps1`.
+
If the service stops and you need to restart it manually, run:
+
[source,shell]
----
Start-Service elastic-agent
----

NOTE: {agent} will restart automatically if the system is rebooted.

// end::win[]
