[[configuration-topbeat]]
=== Topbeat

The `topbeat` section specifies how often Topbeat reads server statistics and which
statistics it captures. Here is an example configuration:

[source,yaml]
------------------------------------------------------------------------------
# In seconds, defines how often to read server statistics
topbeat.period: 10

# Regular expression to match the processes that are monitored
# By default, all the processes are monitored
topbeat.procs: [".*"]

# Statistics to collect (all enabled by default)
topbeat.stats:
  # per system statistics, by default is true
  system: true

  # per process statistics, by default is true
  process: true

  # file system information, by default is true
  filesystem: true

  # cpu usage per core, by default is false
  core: false

  # cpu usage expressed in ticks, by default is false
  cpu_ticks: false

------------------------------------------------------------------------------

==== Topbeat Options

You can specify the following options in the `topbeat` section:

===== period

How often, in seconds, to read system-wide and per-process statistics from your servers. The default is 10.

[[procs-option]]
===== procs

A list of regular expressions to match all the processes that need to be monitored. By
default, all the running processes are monitored.

===== stats

The statistics to collect. You can specify the following settings:

* `system` to export system-wide statistics, including statistics about
system load, CPU usage, memory usage, and swap usage.
* `process` to export per-process statistics, such as the process name,
parent pid, state, pid, CPU usage, and memory usage.
* `filesystem` to export file system statistics, including details about the
mounted disks, such as the total and used disk space, and details about each
disk, such as the device name and the mounting place.
* `core` to export the CPU usage per core. By default, this setting is false. For each core, there is document created of `type=core`.

[source,json]
----------------------------------------------------------------------------------
{
  "@timestamp": "2016-05-23T20:15:12.078Z",
  "beat": {
    "hostname": "mar.local",
    "name": "mar.local"
  },
  "core": {
    "id": 3,
    "idle_p": 0.953,
    "iowait_p": 0,
    "irq_p": 0,
    "nice_p": 0,
    "softirq_p": 0,
    "steal_p": 0,
    "system_p": 0.017,
    "user_p": 0.03
  },
  "type": "core"
}
----------------------------------------------------------------------------------

* `cpu_ticks` to export the CPU usage in ticks. By default, it's set to false. The following fields are
 exported: `idle`, `iowait`, `irq`, `nice`, `softirq`, `steal`, `user` and `system`.

[source,json]
----------------------------------------------------------------------------------
{
  "@timestamp": "2016-05-23T20:16:43.286Z",
  "beat": {
    "hostname": "mar.local",
    "name": "mar.local"
  },
  "cpu": {
    "idle": 98724834,
    "idle_p": 0.9015,
    "iowait": 0,
    "iowait_p": 0,
    "irq": 0,
    "irq_p": 0,
    "nice": 0,
    "nice_p": 0,
    "softirq": 0,
    "softirq_p": 0,
    "steal": 0,
    "steal_p": 0,
    "system": 5682346,
    "system_p": 0.0337,
    "user": 10161651,
    "user_p": 0.0647
  },
  "load": {
    "load1": 1.685546875,
    "load15": 1.958984375,
    "load5": 1.76953125
  },
  "mem": {
    "actual_free": 5022871552,
    "actual_used": 12156997632,
    "actual_used_p": 0.7076,
    "free": 65003520,
    "total": 17179869184,
    "used": 17114865664,
    "used_p": 0.9962
  },
  "swap": {
    "free": 1460666368,
    "total": 4294967296,
    "used": 2834300928,
    "used_p": 0.6599
  },
  "type": "system"
}
----------------------------------------------------------------------------------
For more information about the exported fields, see <<exported-fields-system>>.

include::../../../../libbeat/docs/outputconfig.asciidoc[]

include::../../../../libbeat/docs/generalconfig.asciidoc[]

include::../../../../libbeat/docs/shared-path-config.asciidoc[]

include::../../../../libbeat/docs/loggingconfig.asciidoc[]

include::../../../../libbeat/docs/runconfig.asciidoc[]

include::../../../../libbeat/docs/filteringconfig.asciidoc[]


