// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package statsd

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "statsd", asset.ModuleFieldsPri, AssetStatsd); err != nil {
		panic(err)
	}
}

// AssetStatsd returns asset data.
// This is the base64 encoded gzipped contents of module/statsd.
func AssetStatsd() string {
	return "eJxsjkEOwiAQRfec4odlk3oAFl7CAzS0fA1KC+lMF729CUVjGpe8/8K8Hi/uDqJeJRhAoyY62FsF1gCBMq2xaMyLw9UAwDFizmFLNMDKRC90GKneAPfIFMRVt8fiZ34uXLoKAd0LHfL45KQNHY/hWELexvr3aRlmX0pcHk2znW3On8zfVOoaJ/ni/tT8DgAA//919U7/"
}
