// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package statsd

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "statsd", asset.ModuleFieldsPri, AssetStatsd); err != nil {
		panic(err)
	}
}

// AssetStatsd returns asset data.
// This is the base64 encoded gzipped contents of module/statsd.
func AssetStatsd() string {
	return "eJx0UEuOhCAQ3XOKFzadkHQfgMVcYg7QQSkNIwqBMhNvP1Fkgklby/epqveemGjTyGw4WwGwY08a8vsApAAs5T65yC4sGl8CAAqJOdjVkwASeTKZNEYjgMGRt1kfyicWM1Ozfx/e4q5NYY0n0lpa20O91OMfrc7Q/VDPDVyAd2EHH8wN+Z5NjG4ZT6VUstF9yFmn5iVOrs+XYN505PNLidsHL89NtP2GVIu4OXmeK6ubTtqa/wIAAP//hgt7mw=="
}
