// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package pgsql

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("packetbeat", "pgsql", asset.ModuleFieldsPri, AssetPgsql); err != nil {
		panic(err)
	}
}

// AssetPgsql returns asset data.
// This is the base64 encoded gzipped contents of ../../packetbeat/protos/pgsql.
func AssetPgsql() string {
	return "eJzEkcFu6jAURPf5ihHrBx+QBRJCPAkJtRTYI0gmwapjB1+bKn9fhaTF0GbBqllF1z4zR9djvLNJUZdy1gnglddMMVpb8aXj9m01SoCckjlVe2VNimkCALcLY6mZqUJl4IXGo1DUuUwS9H/p9f4Y5lDxVtR+vqmZonQ21P0kJmKKzlm3z2zO76MHq92JkVMHoAUmEdEVamvKZKCiosihfK6lZyZDmcILnfLNU6FfUKxfWxF11NxfDjowWlPXudhsXjcPs/+z3Wz1MFvPXpbzn7ImVPtu/0Oi07ugZQF/IraL1WK+wznQNVAFJGQZRYqg/8GflHRvCiUQenh7hUyojnR3cbboXx+OPjjD/JeFto7OfvyZYdsd+30GAAD//yg57bo="
}
