The `wmi` metricset of the Windows module collects metrics via link:https://learn.microsoft.com/en-us/windows/win32/wmisdk/about-wmi[Windows Management Instrumentation] (WMI), a core management technology in the Windows Operating system.

By leveraging WMI Query Language (WQL), this metricset allows you to extract detailed
system information and metrics to monitor the health and performance of Windows
Systems.

This metricset leverages the link:https://github.com/microsoft/wmi[Microsoft WMI] library, a
convenient wrapper around the link:https://github.com/go-ole[Go-OLE] library, which allows to invoke the
link:https://learn.microsoft.com/en-us/windows/win32/wmisdk/scripting-api-for-wmi[Scripting API for WMI].

[float]
=== WMI Query Language (WQL) Support

This metricset supports the execution of link:https://learn.microsoft.com/en-us/windows/win32/wmisdk/wql-sql-for-wmi[WQL] queries, a SQL-like query language for retrieving information from WMI namespaces.

Currently, the metricset supports queries with `SELECT`, `FROM` and `WHERE` clauses.

NOTE: When working with WMI queries, it is the user's responsibility to ensure that queries are safe, efficient, and do not cause unintended side effects. A notorious example of a problematic WMI class is Win32_Product. Read more in link:https://learn.microsoft.com/en-us/troubleshoot/windows-server/admin-development/windows-installer-reconfigured-all-applications#more-information[Windows Documentation].

[float]
[[wmi-arbitrator-and-query-execution]]
==== WMI Arbitrator and Query Execution

Query execution is managed by the underlying WMI Framework, specifically the link:https://learn.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/new-wmi-arbitrator-behavior-in-windows-server[WMI Arbitrator].
The Arbitrator is responsible for:

- Scheduling and controlling query execution
- Throttling or stopping queries based on system resource availability and conditions

There is no way to directly stop a query once it has started. To prevent Metricbeat from waiting indefinitely for a query to return a result or fail, Metricbeat has a timeout mechanism that stops waiting for query results after a specified timeout. This is controlled by the `wmi.warning_threshold` setting.

NOTE: While Metricbeat stops waiting for the result, the underlying WMI query may continue running until the WMI Arbitrator decides to stop execution.

[float]
[[wmi-type-support]]
==== WMI type support

The `microsoft/wmi` library internally uses the WMI Scripting API. This API, as per the
link:https://learn.microsoft.com/en-us/windows/win32/wmisdk/querying-wmi[official WMI Documentation],
does not provide direct type conversion for `uint64`, `sint64`, and `datetime`
link:https://learn.microsoft.com/en-us/windows/win32/wmisdk/common-information-model[Common Information Model] (CIM) types;
instead, these values are returned as strings.

To ensure the correct data type is reported, Metricbeat dynamically fetches the
CIM type definitions for the properties of the WMI instance classes returned by the query,
and then performs the necessary data type conversions.

To optimize performance and avoid repeatedly fetching these schema definitions
for every row and every request, an LRU cache is utilized. This cache stores
the schema definition for each WMI class-property pair encountered. For queries involving
superclasses, such as `CIM_LogicalDevice`, the cache will populate with individual entries
for each specific derived class (leaf of the class hierarchy) whose instances are returned by the query (for example, `Win32_DiskDrive` or `Win32_NetworkAdapter`).

NOTE: The properties of type `CIM_Object` (embedded objects) are not yet supported and are ignored.


NOTE: Properties of type `CIM_Reference` (references), which are used in link:https://learn.microsoft.com/en-us/windows/win32/wmisdk/declaring-an-association-class[WMI Association Classes], are currently returned as string values exactly as reported by the 
link:https://github.com/microsoft/wmi[Microsoft WMI] library.


[float]
=== Configuration

[source,yaml]
----
- module: windows
  metricsets: ["wmi"]
  period: 10m
  wmi:
    namespace: "root\\cimv2" # Default Namespace
    warning_threshold: 10m
    include_queries: true
    include_null_properties: false
    include_empty_strings_properties: false
    queries:
    - class: Win32_OperatingSystem
      properties:
      - FreePhysicalMemory
      - FreeSpaceInPagingFiles
      - NumberOfUsers
      where: ""
    - class: Win32_PowerPlan
      properties: []
      where: "IsActive = True"
      namespace: "root\\cimv2\\power" # Overwrites the module namespace in this query
----

*`wmi.namespace`*::
The default WMI namespace used for queries. This can be overridden per query.
The default is `root\cimv2`.

*`wmi.warning_threshold`*:: The time threshold after which Metricbeat will stop
waiting for the query result and return control to the main flow of the program.
A warning is logged indicating that the query execution has exceeded the threshold.
The default is equal to the period. See <<wmi-arbitrator-and-query-execution, WMI Arbitrator and Query Execution>>
for more details.

*`wmi.include_query_class`*:: If set to `true` the metricset include the queried class. Useful if superclasses are queried. The default value is `false`.

*`wmi.include_queries`*:: If set to `true` the metricset includes the query in the output document. The default value is `false`.

*`wmi.include_null_properties`*:: If set to `true` the metricset includes the properties that have null value in the output document.
properties that have a `null` value in the output document. The default value is `false`.

*`wmi.include_empty_string_properties`*:: A boolean option that causes the metricset to include
the properties that are empty string. The default value is `false`.

*`wmi.max_rows_per_query`*:: Limits the number of rows returned by a single WMI query.
The default value is `0`, which is a special value indicating that all fetched
results should be returned without a row limit.

*`wmi.schema_cache_size`*:: The maximum number of WMI class-property pairs that can be cached per single query. Every query keeps its own separate cache.
This cache helps improve performance when dealing with queries that involve inheritance hierarchies. Read more in <<wmi-type-support,  WMI Type Support>>. For example, if a superclass is queried, the cache stores entries for each WMI concrete instance class (the leaves of the class hierarchy) and their associated properties. Therefore, querying a superclass that returns a result set containing instances of `10` different classes, each with `50` properties, will result in a cache size of `500` entries (`10×50`).
The default value is `1000`.

*`wmi.queries`*:: The list of queries to execute. The list cannot be empty. See <<query-configuration, Query Configuration>> for the format of the queries.

[float]
[[query-configuration]]
==== Query Configuration

Each item in the `queries` list specifies a wmi query to perform.

*`class`*:: The wmi class. In the query it specifies the `FROM` clause. Required

*`properties`*:: List of properties to return. In the query it specifies the `SELECT` clause. Set it to the empty list (default value) to retrieve all available properties.

*`where`*:: The where clause. In the query it specifies the `WHERE` clause. Read more about the format link:https://learn.microsoft.com/en-us/windows/win32/wmisdk/where-clause[in the Windows Documentation].

*`namespace`*:: The WMI Namespace for this particular query (it overwrites the metricset's `namespace` value)

[float]
===== Example

Example WQL Query:

[source,sql]
----
SELECT Name, ProcessId, WorkingSetSize
FROM Win32_Process
WHERE Name = 'lsass.exe' AND WorkingSetSize > 104857600
----

Equivalent YAML Configuration:

[source,yaml]
----
- class: Win32_Process
  properties:
  - Name
  - ProcessId
  - WorkingSetSize
  where: "Name = 'lsass.exe' AND WorkingSetSize > 104857600"
----


[float]
=== Best Practices

- Test your queries in isolation using the link:https://learn.microsoft.com/en-us/powershell/module/cimcmdlets/get-ciminstance[`Get-CimInstance`] PowerShell cmdlet or link:https://github.com/vinaypamnani/wmie2[the WMI Explorer tool].

- Ensure that `wmi.warning_threshold` is less than or equal to the module's `period`.
  This configuration prevents Metricbeat from starting multiple concurrent executions of the same query.

- When possible, try querying concrete (leaf) classes or classes closer to the leaves of the WMI inheritance hierarchy. Querying abstract superclasses may require fetching and caching the schema definitions for numerous derived classes, which can lead to increased memory usage and potential performance penalties due to cache misses.

- Set up Kibana Alerts for documents generated by this metricset with the `error.message` field.

- Configure collection of WMI-Activity Operational Logs (found in Event Viewer under `Applications and Services Logs/Microsoft/Windows/WMI-Activity/Operational`). These logs can be invaluable for correlating issues with Metricbeat WMI warnings or documents containing `error.message`.


[float]
=== Compatibility

This module has been tested on the following platform:

[options="header"]
|===
| Operating System | Architecture

| Microsoft Windows Server 2019 Datacenter | x64
| Microsoft Windows 11 Pro | x64
|===

Other Windows versions and architectures may also work but have not been explicitly tested.

