BEAT_NAME=libbeat
TEST_ENVIRONMENT?=true
SYSTEM_TESTS=true
GOX_OS=linux darwin windows netbsd openbsd

include scripts/Makefile

# Collects all dependencies and then calls update
.PHONY: collect
collect:
