package elf

import "debug/elf"

var machineNames = map[elf.Machine]string{
	elf.EM_NONE:          "Unknown machine",
	elf.EM_M32:           "AT&T WE32100",
	elf.EM_SPARC:         "Sun SPARC",
	elf.EM_386:           "Intel i386",
	elf.EM_68K:           "Motorola 68000",
	elf.EM_88K:           "Motorola 88000",
	elf.EM_860:           "Intel i860",
	elf.EM_MIPS:          "MIPS R3000 Big-Endian only",
	elf.EM_S370:          "IBM System/370",
	elf.EM_MIPS_RS3_LE:   "MIPS R3000 Little-Endian",
	elf.EM_PARISC:        "HP PA-RISC",
	elf.EM_VPP500:        "Fujitsu VPP500",
	elf.EM_SPARC32PLUS:   "SPARC v8plus",
	elf.EM_960:           "Intel 80960",
	elf.EM_PPC:           "PowerPC 32-bit",
	elf.EM_PPC64:         "PowerPC 64-bit",
	elf.EM_S390:          "IBM System/390",
	elf.EM_V800:          "NEC V800",
	elf.EM_FR20:          "Fujitsu FR20",
	elf.EM_RH32:          "TRW RH-32",
	elf.EM_RCE:           "Motorola RCE",
	elf.EM_ARM:           "ARM",
	elf.EM_SH:            "Hitachi SH",
	elf.EM_SPARCV9:       "SPARC v9 64-bit",
	elf.EM_TRICORE:       "Siemens TriCore embedded processor",
	elf.EM_ARC:           "Argonaut RISC Core",
	elf.EM_H8_300:        "Hitachi H8/300",
	elf.EM_H8_300H:       "Hitachi H8/300H",
	elf.EM_H8S:           "Hitachi H8S",
	elf.EM_H8_500:        "Hitachi H8/500",
	elf.EM_IA_64:         "Intel IA-64 Processor",
	elf.EM_MIPS_X:        "Stanford MIPS-X",
	elf.EM_COLDFIRE:      "Motorola ColdFire",
	elf.EM_68HC12:        "Motorola M68HC12",
	elf.EM_MMA:           "Fujitsu MMA",
	elf.EM_PCP:           "Siemens PCP",
	elf.EM_NCPU:          "Sony nCPU",
	elf.EM_NDR1:          "Denso NDR1 microprocessor",
	elf.EM_STARCORE:      "Motorola Star*Core processor",
	elf.EM_ME16:          "Toyota ME16 processor",
	elf.EM_ST100:         "STMicroelectronics ST100 processor",
	elf.EM_TINYJ:         "Advanced Logic Corp. TinyJ processor",
	elf.EM_X86_64:        "Advanced Micro Devices x86-64",
	elf.EM_PDSP:          "Sony DSP Processor",
	elf.EM_PDP10:         "Digital Equipment Corp. PDP-10",
	elf.EM_PDP11:         "Digital Equipment Corp. PDP-11",
	elf.EM_FX66:          "Siemens FX66 microcontroller",
	elf.EM_ST9PLUS:       "STMicroelectronics ST9+ 8/16 bit microcontroller",
	elf.EM_ST7:           "STMicroelectronics ST7 8-bit microcontroller",
	elf.EM_68HC16:        "Motorola MC68HC16 Microcontroller",
	elf.EM_68HC11:        "Motorola MC68HC11 Microcontroller",
	elf.EM_68HC08:        "Motorola MC68HC08 Microcontroller",
	elf.EM_68HC05:        "Motorola MC68HC05 Microcontroller",
	elf.EM_SVX:           "Silicon Graphics SVx",
	elf.EM_ST19:          "STMicroelectronics ST19 8-bit microcontroller",
	elf.EM_VAX:           "Digital VAX",
	elf.EM_CRIS:          "Axis Communications 32-bit embedded processor",
	elf.EM_JAVELIN:       "Infineon Technologies 32-bit embedded processor",
	elf.EM_FIREPATH:      "Element 14 64-bit DSP Processor",
	elf.EM_ZSP:           "LSI Logic 16-bit DSP Processor",
	elf.EM_MMIX:          "Donald Knuth's educational 64-bit processor",
	elf.EM_HUANY:         "Harvard University machine-independent object files",
	elf.EM_PRISM:         "SiTera Prism",
	elf.EM_AVR:           "Atmel AVR 8-bit microcontroller",
	elf.EM_FR30:          "Fujitsu FR30",
	elf.EM_D10V:          "Mitsubishi D10V",
	elf.EM_D30V:          "Mitsubishi D30V",
	elf.EM_V850:          "NEC v850",
	elf.EM_M32R:          "Mitsubishi M32R",
	elf.EM_MN10300:       "Matsushita MN10300",
	elf.EM_MN10200:       "Matsushita MN10200",
	elf.EM_PJ:            "picoJava",
	elf.EM_OPENRISC:      "OpenRISC 32-bit embedded processor",
	elf.EM_ARC_COMPACT:   "ARC International ARCompact processor (old spelling/synonym: EM_ARC_A5)",
	elf.EM_XTENSA:        "Tensilica Xtensa Architecture",
	elf.EM_VIDEOCORE:     "Alphamosaic VideoCore processor",
	elf.EM_TMM_GPP:       "Thompson Multimedia General Purpose Processor",
	elf.EM_NS32K:         "National Semiconductor 32000 series",
	elf.EM_TPC:           "Tenor Network TPC processor",
	elf.EM_SNP1K:         "Trebia SNP 1000 processor",
	elf.EM_ST200:         "STMicroelectronics (www.st.com) ST200 microcontroller",
	elf.EM_IP2K:          "Ubicom IP2xxx microcontroller family",
	elf.EM_MAX:           "MAX Processor",
	elf.EM_CR:            "National Semiconductor CompactRISC microprocessor",
	elf.EM_F2MC16:        "Fujitsu F2MC16",
	elf.EM_MSP430:        "Texas Instruments embedded microcontroller msp430",
	elf.EM_BLACKFIN:      "Analog Devices Blackfin (DSP) processor",
	elf.EM_SE_C33:        "S1C33 Family of Seiko Epson processors",
	elf.EM_SEP:           "Sharp embedded microprocessor",
	elf.EM_ARCA:          "Arca RISC Microprocessor",
	elf.EM_UNICORE:       "Microprocessor series from PKU-Unity Ltd. and MPRC of Peking University",
	elf.EM_EXCESS:        "eXcess: 16/32/64-bit configurable embedded CPU",
	elf.EM_DXP:           "Icera Semiconductor Inc. Deep Execution Processor",
	elf.EM_ALTERA_NIOS2:  "Altera Nios II soft-core processor",
	elf.EM_CRX:           "National Semiconductor CompactRISC CRX microprocessor",
	elf.EM_XGATE:         "Motorola XGATE embedded processor",
	elf.EM_C166:          "Infineon C16x/XC16x processor",
	elf.EM_M16C:          "Renesas M16C series microprocessors",
	elf.EM_DSPIC30F:      "Microchip Technology dsPIC30F Digital Signal Controller",
	elf.EM_CE:            "Freescale Communication Engine RISC core",
	elf.EM_M32C:          "Renesas M32C series microprocessors",
	elf.EM_TSK3000:       "Altium TSK3000 core",
	elf.EM_RS08:          "Freescale RS08 embedded processor",
	elf.EM_SHARC:         "Analog Devices SHARC family of 32-bit DSP processors",
	elf.EM_ECOG2:         "Cyan Technology eCOG2 microprocessor",
	elf.EM_SCORE7:        "Sunplus S+core7 RISC processor",
	elf.EM_DSP24:         "New Japan Radio (NJR) 24-bit DSP Processor",
	elf.EM_VIDEOCORE3:    "Broadcom VideoCore III processor",
	elf.EM_LATTICEMICO32: "RISC processor for Lattice FPGA architecture",
	elf.EM_SE_C17:        "Seiko Epson C17 family",
	elf.EM_TI_C6000:      "The Texas Instruments TMS320C6000 DSP family",
	elf.EM_TI_C2000:      "The Texas Instruments TMS320C2000 DSP family",
	elf.EM_TI_C5500:      "The Texas Instruments TMS320C55x DSP family",
	elf.EM_TI_ARP32:      "Texas Instruments Application Specific RISC Processor, 32bit fetch",
	elf.EM_TI_PRU:        "Texas Instruments Programmable Realtime Unit",
	elf.EM_MMDSP_PLUS:    "STMicroelectronics 64bit VLIW Data Signal Processor",
	elf.EM_CYPRESS_M8C:   "Cypress M8C microprocessor",
	elf.EM_R32C:          "Renesas R32C series microprocessors",
	elf.EM_TRIMEDIA:      "NXP Semiconductors TriMedia architecture family",
	elf.EM_QDSP6:         "QUALCOMM DSP6 Processor",
	elf.EM_8051:          "Intel 8051 and variants",
	elf.EM_STXP7X:        "STMicroelectronics STxP7x family of configurable and extensible RISC processors",
	elf.EM_NDS32:         "Andes Technology compact code size embedded RISC processor family",
	// elf.EM_ECOG1:         "Cyan Technology eCOG1X family",
	elf.EM_ECOG1X:       "Cyan Technology eCOG1X family",
	elf.EM_MAXQ30:       "Dallas Semiconductor MAXQ30 Core Micro-controllers",
	elf.EM_XIMO16:       "New Japan Radio (NJR) 16-bit DSP Processor",
	elf.EM_MANIK:        "M2000 Reconfigurable RISC Microprocessor",
	elf.EM_CRAYNV2:      "Cray Inc. NV2 vector architecture",
	elf.EM_RX:           "Renesas RX family",
	elf.EM_METAG:        "Imagination Technologies META processor architecture",
	elf.EM_MCST_ELBRUS:  "MCST Elbrus general purpose hardware architecture",
	elf.EM_ECOG16:       "Cyan Technology eCOG16 family",
	elf.EM_CR16:         "National Semiconductor CompactRISC CR16 16-bit microprocessor",
	elf.EM_ETPU:         "Freescale Extended Time Processing Unit",
	elf.EM_SLE9X:        "Infineon Technologies SLE9X core",
	elf.EM_L10M:         "Intel L10M",
	elf.EM_K10M:         "Intel K10M",
	elf.EM_AARCH64:      "ARM 64-bit Architecture (AArch64)",
	elf.EM_AVR32:        "Atmel Corporation 32-bit microprocessor family",
	elf.EM_STM8:         "STMicroeletronics STM8 8-bit microcontroller",
	elf.EM_TILE64:       "Tilera TILE64 multicore architecture family",
	elf.EM_TILEPRO:      "Tilera TILEPro multicore architecture family",
	elf.EM_MICROBLAZE:   "Xilinx MicroBlaze 32-bit RISC soft processor core",
	elf.EM_CUDA:         "NVIDIA CUDA architecture",
	elf.EM_TILEGX:       "Tilera TILE-Gx multicore architecture family",
	elf.EM_CLOUDSHIELD:  "CloudShield architecture family",
	elf.EM_COREA_1ST:    "KIPO-KAIST Core-A 1st generation processor family",
	elf.EM_COREA_2ND:    "KIPO-KAIST Core-A 2nd generation processor family",
	elf.EM_ARC_COMPACT2: "Synopsys ARCompact V2",
	elf.EM_OPEN8:        "Open8 8-bit RISC soft processor core",
	elf.EM_RL78:         "Renesas RL78 family",
	elf.EM_VIDEOCORE5:   "Broadcom VideoCore V processor",
	elf.EM_78KOR:        "Renesas 78KOR family",
	elf.EM_56800EX:      "Freescale 56800EX Digital Signal Controller (DSC)",
	elf.EM_BA1:          "Beyond BA1 CPU architecture",
	elf.EM_BA2:          "Beyond BA2 CPU architecture",
	elf.EM_XCORE:        "XMOS xCORE processor family",
	elf.EM_MCHP_PIC:     "Microchip 8-bit PIC(r) family",
	elf.EM_INTEL205:     "Reserved by Intel",
	elf.EM_INTEL206:     "Reserved by Intel",
	elf.EM_INTEL207:     "Reserved by Intel",
	elf.EM_INTEL208:     "Reserved by Intel",
	elf.EM_INTEL209:     "Reserved by Intel",
	elf.EM_KM32:         "KM211 KM32 32-bit processor",
	elf.EM_KMX32:        "KM211 KMX32 32-bit processor",
	elf.EM_KMX16:        "KM211 KMX16 16-bit processor",
	elf.EM_KMX8:         "KM211 KMX8 8-bit processor",
	elf.EM_KVARC:        "KM211 KVARC processor",
	elf.EM_CDP:          "Paneve CDP architecture family",
	elf.EM_COGE:         "Cognitive Smart Memory Processor",
	elf.EM_COOL:         "Bluechip Systems CoolEngine",
	elf.EM_NORC:         "Nanoradio Optimized RISC",
	elf.EM_CSR_KALIMBA:  "CSR Kalimba architecture family",
	elf.EM_Z80:          "Zilog Z80",
	elf.EM_VISIUM:       "Controls and Data Services VISIUMcore processor",
	elf.EM_FT32:         "FTDI Chip FT32 high performance 32-bit RISC architecture",
	elf.EM_MOXIE:        "Moxie processor family",
	elf.EM_AMDGPU:       "AMD GPU architecture",
	elf.EM_RISCV:        "RISC-V",
	elf.EM_LANAI:        "Lanai 32-bit processor",
	elf.EM_BPF:          "Linux BPF – in-kernel virtual machine",
	// deprecated
	elf.EM_486: "Intel i486",
	// elf.EM_MIPS_RS4_BE:   "MIPS R4000 Big-Endian",
	elf.EM_ALPHA_STD: "Digital Alpha (standard value)",
	elf.EM_ALPHA:     "Alpha (written in the absence of an ABI)",
}

func translateMachine(machine elf.Machine) string {
	if found, ok := machineNames[machine]; ok {
		return found
	}
	return "Unknown machine"
}
