// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package googlecloud

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "googlecloud", asset.ModuleFieldsPri, AssetGooglecloud); err != nil {
		panic(err)
	}
}

// AssetGooglecloud returns asset data.
// This is the base64 encoded gzipped contents of module/googlecloud.
func AssetGooglecloud() string {
	return "eJzsl8Fu4zYQhu9+irmlBbJ6gBwKLJzdYtENkMZGDr0YDDmS2NAcgaQsuE9fDCnZkiU7ydobYIHoZJPSzMeZn8PhJ3jG7Q0URIVBaahWM4Cgg8Eb+DMOwrwdVeil01XQZG/gjxkAwB2p2iDk5KAUVhltCzBUeMgdrQffZzOAXKNR/iZ++QmsWOOhY37CtuJxR3XVjkw45udrNDd2FQmy9rW+z75fhT5oK9hmpq0PwkrcvTQFcQKEn285hBL7ZoHSkCRrUcaRRngQ8HgHhqQIqIBsfMWLNcLj/fx6YDKU2id+0B4qqmoTP2p0KNlIhw0Kg9DGZ/DNgoBFKRwqNjewJsnmuqhdZLuGytG/KMNKK5DkHPqKrPIQKAK1sxBKEYAa63l0YK5zfg21r4Ux27QQdBstd99nvU8OE9FPxh5mMN2l4Rm3DbnDuRPJiAm57RLQLUaSDUJb1igPP95ls0kah4UmezmSh2ivoznq9j+yeDmn/5DFSZdTG2BTyV9K+/dzsBgacs8X1z7rPbGX5MOvLeRNJVf863IsHHnOZall2frm/FCFHFtbHAHx9VObrwvzLHaGX4u1Q6LaSbxk6U8Wf0T5Ue0Dkx9V/6Pq/5Sq38r+MgX/XRT/Ues/an18Xl3rD4ly7bARxpyj+O6uQW541fja2h7cOWBSObtCUxtctVKejWNzCPVCXG73k510uvVGT0nmaxFkiSq1VfuNmo234IHY+3LX5HTYjvKSsA3ZYjQ1IF9GVScjMZAj1uyIaxFhjzie1tKB78+pLsVYsNsYmQpdTm7tWU4xQMf8K+3wbITbzkhMkxN5rmU/OT4l51QcHObocNitvJnjoTPSnfqvSkEq9SsnbHGW9+/ax6LbHh3Rnt/nZShdUVVG8zQdzcz+ynE5tv495ijgy2xtyIIY74s3QI3rIOxAmaN3DgdRnBHKIFyB4T1wk6czcXW1qsiFlbY5HQEWzolxuXo1rq74EA4kyXgQViUoKZ64dJALnTa4lDG0f0EIbZe8ElJSbcM7iaLrzVuv5wvknZfRiuWcZfRapNxQ8zPaAO6V2PZb2gBkEaGbaAGmgncycHy0eq2w7Ypa0yrFx1CTwVxYeEJAHUp0cLV4mF8BObi6/bJYXu2BpzhDyNZTjcroxD+J+F0EtHILwsMaha+5df+N47ic30dGPobN9ndQteua3aDXCNoGdBthMljy+XhwbYD9i2hE5VHBE4YG0YJHq9iSgMWXv+MGdihRb9LY/jLA/z/P/zowy+/rXfsdb8K7e8jDcsnraJDPgTTV1oZ0ZmC6vyg0YpvN/g8AAP//5uSKiw=="
}
