// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package http

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "http", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzEkzFPwzAUhPf8ilNmihg6ZWBmQgzdEIMbX1u3SWz8Xgr59yhNWtKmFVCQ8Gj73Xe6syfYsMmwUg2TkhpdLgmgTgtmSB9ms6c0ASwljy6o81WG+wQA2iOU3tYFEyCyoBFmWJoEEKq6aikZnlORIr1B2gLSlwRYOBZWsp3GBJUp2dFvI19riu4OAG1CqxZ9HfqdMx66tXPST8NVCx9L097qrwyBR1AayygDoY7p52vmOti+CAZmK3b4XgzCSkekubfNCLNh8+aj/SEnmKbwxn5yTiKU4Cvh1Rl24/8dYmROt6Ud0XJv+UdBihqt5VSR76YM7cuf3k1H9LCKRr7DP6g8esXC19WV5k6Aex9rOdRyvuUvMO08+r/OYUfHn3i/LlUvjFvG3xgZKRwMzKnnLHwEAAD//70LQJc="
}
