////
This file is generated! See scripts/changelog.py
////

[[release-notes-v5.0.0-rc1]]
=== Beats version v5.0.0-rc1
 https://github.com/elastic/beats/compare/v5.0.0-beta1...v5.0.0-rc1[View commits]

==== Bug

- Fix default configuration file on Windows to not enabled the `load` metricset.
  {issue}2632[2632]

[[release-notes-v5.0.0-beta1]]
=== Beats version v5.0.0-beta1
 https://github.com/elastic/beats/compare/v5.0.0-alpha5...v5.0.0-beta1[View commits]

==== Breaking

- Change field type system.process.cpu.start_time from keyword to date.
  {issue}1565[1565]

==== Bug

- Fix module filters to work properly with drop_event filter.
  {issue}2249[2249]

==== Added

- Use the new scaled_float Elasticsearch type for the percentage values.
  {issue}2156[2156]
- Add experimental cgroup metrics to the system/process MetricSet.
  {issue}2184[2184]
- Added a PostgreSQL module.
  {issue}2253[2253]
- Improve mapping by converting half_float to scaled_float and integers to long.
  {issue}2430[2430]
- Add experimental haproxy module.
  {issue}2384[2384]
- Add Kibana dashboard for cgroups data
  {issue}2555[2555]

[[release-notes-v5.0.0-alpha5]]
=== Beats version v5.0.0-alpha5
 https://github.com/elastic/beats/compare/v5.0.0-alpha4...v5.0.0-alpha5[View commits]

==== Breaking

- Create a separate metricSet for load under the system module and remove load information from CPU stats.
  {issue}2101[2101]
- Add `system.load.norm.1`, `system.load.norm.5` and `system.load.norm.15`.
  {issue}2101[2101]
- Add threads fields to mysql module.
  {issue}2484[2484]

==== Bug

- Do not send zero values when no value was present in the source.
  {issue}1972[1972]

==== Added

- Add pgid field to process information.
  {issue}None[None]

[[release-notes-v5.0.0-alpha4]]
=== Beats version v5.0.0-alpha4
 https://github.com/elastic/beats/compare/v5.0.0-alpha3...v5.0.0-alpha4[View commits]

==== Added

- Add MongoDB module.
  {issue}1837[1837]

==== Bug

- Fix the CPU values returned for each core.
  {issue}1863[1863]

[[release-notes-v5.0.0-alpha3]]
=== Beats version v5.0.0-alpha3
 https://github.com/elastic/beats/compare/v5.0.0-alpha2...v5.0.0-alpha3[View commits]

[[release-notes-v5.0.0-alpha2]]
=== Beats version v5.0.0-alpha2
 https://github.com/elastic/beats/compare/v5.0.0-alpha1...v5.0.0-alpha2[View commits]

[[release-notes-v5.0.0-alpha1]]
=== Beats version v5.0.0-alpha1
 https://github.com/elastic/beats/compare/v1.2.0...v5.0.0-alpha1[View commits]

[[release-notes-v1.2.3]]
=== Beats version v1.2.3
 https://github.com/elastic/beats/compare/v1.2.2...v1.2.3[View commits]

[[release-notes-v1.2.2]]
=== Beats version v1.2.2
 https://github.com/elastic/beats/compare/v1.2.0...v1.2.2[View commits]

[[release-notes-v1.2.1]]
=== Beats version v1.2.1
 https://github.com/elastic/beats/compare/v1.2.0...v1.2.1[View commits]

[[release-notes-v1.2.0]]
=== Beats version v1.2.0
 https://github.com/elastic/beats/compare/v1.1.2...v1.2.0[View commits]

[[release-notes-v1.1.2]]
=== Beats version v1.1.2
 https://github.com/elastic/beats/compare/v1.1.1...v1.1.2[View commits]

[[release-notes-v1.1.1]]
=== Beats version v1.1.1
 https://github.com/elastic/beats/compare/v1.1.0...v1.1.1[View commits]

[[release-notes-v1.1.0]]
=== Beats version v1.1.0
 https://github.com/elastic/beats/compare/v1.0.1...v1.1.0[View commits]

[[release-notes-v1.0.1]]
=== Beats version v1.0.1
 https://github.com/elastic/beats/compare/v1.0.0...v1.0.1[View commits]

[[release-notes-master]]
=== Beats version master
 https://github.com/elastic/beats/compare/v5.0.0-rc1...master[View commits]

==== Added

- Add experimental filebeat metricset in the beats module.
  {issue}2297[2297]
- Add experimental libbeat metricset in the beats module.
  {issue}2339[2339]

==== Bug

- Fix high CPU usage on macOS when encountering processes with long command lines.
  {issue}2747[2747]
- Fix high value of `system.memory.actual.free` and `system.memory.actual.used`.
  {issue}2653[2653]
- Change several `OpenProcess` calls on Windows to request the lowest possible access provilege. 
  {issue}1897[1897]
- Fix system.memory.actual.free high value on Windows.
  {issue}2653[2653]
- Calculate the fsstat values per mounting point, and not filesystem.
  {issue}2777[2777]

[[release-notes-1.0.0-rc2]]
=== Beats version 1.0.0-rc2
 https://github.com/elastic/beats/compare/1.0.0-rc1...1.0.0-rc2[View commits]

[[release-notes-1.0.0-rc1]]
=== Beats version 1.0.0-rc1
 https://github.com/elastic/beats/compare/1.0.0-beta4...1.0.0-rc1[View commits]

[[release-notes-1.0.0-beta4]]
=== Beats version 1.0.0-beta4
 https://github.com/elastic/beats/compare/1.0.0-beta3...1.0.0-beta4[View commits]

[[release-notes-1.0.0]]
=== Beats version 1.0.0
 https://github.com/elastic/beats/compare/1.0.0-rc2...1.0.0[View commits]

