// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package cloudfoundry

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "cloudfoundry", asset.ModuleFieldsPri, AssetCloudfoundry); err != nil {
		panic(err)
	}
}

// AssetCloudfoundry returns asset data.
// This is the base64 encoded gzipped contents of module/cloudfoundry.
func AssetCloudfoundry() string {
	return "eJzclUFz2jAQhe/8ip1cuDT8AB96aDqdyS2H9NwI6Rk0yJIqrSD+9x0JTGwwgRaSQ31ghrX03tO3lnRPK7QVSeOSql2yKrQTItZsUNFdv3w3IVKIMmjP2tmKvk6IiB7yEPqxHUONU8lgQhRgICIqwqtH0A0sCzMhqjWMilWZek9WNDgyzw+3HhUtgkt+VxmxHqr1FfP0fbFTW6HduKB69VHN7fO8RJlGriasYZnq4JrhameDGU8uRj03oLUwCZG0lSYp0FQ6y0JbhOmX/CdZRpiSsIqmZeh0dpRfeH8Uvw/jgvDCe6OlyK+Jl6AGHLQkHUnE6KQWDEUbzcv+Kg559jNpNSifpnomXBfw8Xtmy8Ooxyj29K4B8rJXeekE45vyjk080+JTn/RF8GxkYSV+aavwOgrSOLv4K4qPWapj2Bn0ez1H1ozEbjYaSvo085JH09TGicM3Z5r68PSTUhQLkEeQmc4C48YNGhfa2bxlxNuwoG9ZK8NIEaozeM/8d3IsPiaCWAttRD4K3suhdFx9IILILpxsQPH+FAJHMd72dTkIr9zVRWOwp0vlE3Z0/r3tgZgVu+28W8eJ7sGwuFHLsrHSdY2AfHrMwRtge2MYEZlYN+gn2l2GTsoUAtR4QHZDjtcGLHrbe5VqF8YJdeZl2FWfVVH4Dz+qsq7xjiWrx++BfzbOihcYH3aLrrmBnjuvA+M/AQAA///wT+lI"
}
