// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package couchbase

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
<<<<<<< HEAD
	if err := asset.SetFields("metricbeat", "couchbase", asset.ModuleFieldsPri, AssetCouchbase); err != nil {
=======
	if err := asset.SetFields("metricbeat", "Couchbase", asset.ModuleFieldsPri, AssetCouchbase); err != nil {
>>>>>>> Introduce local fields generation
		panic(err)
	}
}

// AssetCouchbase returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/couchbase.
func AssetCouchbase() string {
<<<<<<< HEAD
	return "eJzMmVFv28YPwN/zKYgAfyAF/tXe/TCg6DB0DymKLnsaBpW+o61bJJ12pOK6n37gnWTLruXYiWpPD3mwFPLHI4/k8d7CI61nYHxrijky3QCIk5JmcPu+/+32BsASm+Aacb6ewc83AAD3JMEZBuPLkoyQhUXwFWz+DZjCEwXObgC48EFy4+uFW85ggWXUFKgkZJrBEvUbEnH1kmfw5y1zeft/uC1Emtu/bgAWjkrLs6j3LdRY0S6zPrJuVFTwbdP9cgBany+b//wCxteCrmaQgqDqLJICBVYUCNgEbL6zLOtEDamGZPPWPJJsfj6EdgRPn+0iJlk9Wjb4anf1+mefacilf3de9GSPtF75YPfeHeHT5yNWBH4RVy5RZge1qorptD6sm5O0WhTMWiabzddCvCdn4UOFMoND7xJc6evleWS/u2+RrGUKUT2snBSu7jC5p+aGjFs4ssCCQinaMBAEYmepFnA1fH53P2KX48dsQWKKycA/ttWcguKpcOiEH1F/0WV9V/m2lg2d6oa7qODNYcSKKh/W14JM2hPmfD0I0+PQ/7ReMAtYXQH587v7F/K2TFljZIS2oWCo3n+beNlgSTZflB73P3iG+1OSikvaYb9b+ABoxD0R+PnfZITfAC41t0u0KhWfNqidyUDWDXv3vxELfcN5QyFnMpPvM99QQP2MdZGAyfjaHsZwQlVu1FWTU6hoBmT2xqHWb81XBxPrpuSWLQuFaSpbJ2ya0lZYmy0C0cW2z6+BCAoMFmzQmOMGDWnmjrHWmXZ0Cyly2kbiBcuLkX/YQkf1ENWrqvPYL0v9ECG/W3B8QlfivCQQfx5+rA9PWLaXi5kP+/TDrHse+Hydxw7nP4Eem51zQr/Cr3nKMZOmtnv82uf2KLY/UhwrYa629DXveoZqPhVJ6gLS/uooNjvsN1UZT0fOENzd60odLbMXpds48BiXNirD3HXZfaRF/8Wpax9da3zt7TXod7Z/G4L2/opy1l7a2nOFjDZiywu4L+8GrF7mhlFrrlEQ1QE7NfDktb9StLwoTq5S8vZpT6pym1GLtzRNmxwjcZIe2VQ2X9L054hlrLdVhbXlw4rVmMx6w5me4XM9eF1rfrDbvcRlBiU7HoRDC1Dwshb8ooHH3XRpQLx/csMUKycYwg2Kw/IZW147CEvH8LRvtER3WuHJ0eqk9d5gHg2aHxIYZ7PGD69BmgLiXM6LOv50xKbNW3Gl+xanI3lAOTRgeu0I6aEgeP/pDxioAlU1Pgzq2oI8jkxS1Zw8jfatR9JxAkbsNybtJuoTZkOxSTtIR00+X+ZpfLw/1Z92Ng0NBc20ZIFdbSjN1eN1E6yQgQWD0MhEbUmSF06mn55rHVTBI0d3zzLtBYyGcS+1v1wY905lbH/MxbL0Rr16nfm4QQ2QflK+gXlmZLDFDxRdfZj+BxD2+k66dhgdQk52taAaNkfe5yt+xzV+OHldyui9uD+HOxls9J7mldONYev+PIxvps8Hu1P+Ll/5+vt75F0UXmHzw9ylwlMveeK+izST+2gb1Alo29EchWkbcRVl013JPLiKwLbB1UtYFc5sS1ysI67eOhHumMwI19M8D9SUzmCuJTrV58njKUr9yXrTVlQLDy+Oo27Obv4NAAD//w/9DiA="
=======
	return "eJzMmcGO4zYPgO95CiLAD8wC/7r3HAostii2h1ksttNTUXhpiYnVsS1XopPNPn1ByU4cT5xJZjxJfZhD7CE/ihRJUe/hkbYLULZReYaeZgBsuKAFzD92v81nAJq8cqZmY6sF/DwDALgndkZ5ULYoSDFpWDpbwu7fwJNbk/PJDMDn1nGqbLU0qwUssQiaHBWEnhaQEaN8RcymWvkF/Dn3vpj/H+Y5cz3/awawNFRovwia30OFJR1Sy8Pbmhawcrap21+OYMvzbfef30DZitFUHjgnKFubOEeGDTkCrxzWT2xLWlF9qj5Z1qhH4t3Px9BO4MmzX8Yoq0NLel8N1697hlR9Mvl78KJje6Ttxjo9eHeCUJ7PWBLYZVi7yJkc1SoqptP6sK3P0qqRMWk86STbMvmBnKV1JfICjr2LcIWtVpeR/W5+BLLGkwvqYWM4N1WL6TtqX5MyS0MaPCNTjDd0BI680VQxmAq+frgfscv4x2RJrPLJwD83ZUZO8EQ4tMJPqL/qsn4obVPxjk50w11Q8O44YkmlddtbQUbtETPb9sL0NPQ/jWVMHJY3QP764f6FvI2npFY8QluTU1QN30Zer7AgnS4Li8MPnuH+EqXiig7Y75bWASo2awKb/U2K/TvAlWR3DlbFAtQ4sTMa6GXD3v1vxEJb+7Qml3pSk+8zW5ND+czLIoEnZSt9HMMwlakSV01OIaI9oPdWGZQaLvnqaGLdFd2i8UxumtrWCpuquOVaJ0tHdLUN9KsjghydBu0k6nyNiiR3h2hrjTu5iQQ5biS2jMXVyD/toYN6COpF1WXs16V+CJBPFhzXaArMCgK2l+GHCrHGorlezHwa0vfz7mXg2TYNPc5/Aj20O5eEfonf05hlJk1u9/i9y+5BbHesOFXETKXpe9p2DWU2FUnsA+L+ail2O+w3URnOSEYR3N3LSp0stFel2znwFJe0Kv3cdd19JGX/xalriC5VvrL6FvQH279xTrp/QbloL+3tuUFGG7HlBdzXdwOWL3PDqDW3KIjigIMaePba3yhaXhQnNyl5Q9qzqtxu2GI1TdMoh0icqEtWpU5XNP1ZYhUqbllipf1xxWJOoq3yiZzjUzl83WqGcNi/hIUGITsdhn0LkPG6FvwioefbCVOPeHh6wxgtZxjia2SDxTO2vHYYFo/icedIkW61wtrQ5qz13mGeDJo3CYyLWcOHtyCNAXEp51Udfz5i3aQNm8L8CBOS1CEfGzK9doz0kBN8/PIH9FSBqBofCLWNQRrGJrFuTp5Gu+Yj6jgDI3Qck/YT1RnzodCmHaWjOs1WaRwhDyf7086noSYnmZY0eFMpirP1cO0EG/TgGR3TyFRtRZzmhqefoEsdFMEjh3fredpLGAnjTmp3wTDunVLp7qCLRWGVePU2M3KFEiDdtHwH88zQYI/vKLj6OP0bEHb6zrp6GB1DTna9IBp2h97nK37LNX48eV3K6Lw4nMSdDTZ6V/PK+Ua/eX8extbT54PDSX+br2z19Db5EMVvsH4zd4nw2Eueue8CzeQ+2gd1BNp3NCdhmppNScl01zIPpiTQjTPVCja5UfsSF+qIqfZOhDtPaoRrnaWO6sIoTKVEx/o8eTwFqT9pq5qSKvb9y+Og2yezfwMAAP//Z04RcA=="
>>>>>>> Introduce local fields generation
}
