// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package threatintel

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "threatintel", asset.ModuleFieldsPri, AssetThreatintel); err != nil {
		panic(err)
	}
}

// AssetThreatintel returns asset data.
// This is the base64 encoded gzipped contents of module/threatintel.
func AssetThreatintel() string {
	return "eJyslsFu4zgMhu95Ct62Bdo8QA4LdFEsUCAFFtmm14Cx6FiIInpIKoHffiA7ST2TiSdT16dWpv//E0VSeYQtNTOwSgjNR6MwATBvgX5edKSF+No8xxn8PQEAePsIgFd2KdAEoPQUnM7agEeIuLtQyo81Nc1gI5zq44qjElOwVfv9DEoMSudXF9b5+bd1glJ413eYHgP6IH2Y0gdaZf/zmxPOlpoDi+utX3Hu3AO138EmkSo5WDewXMwrTDo9R164q99EtCQj3V8xHFAIStz54JsBwyQhI60cH2JgdON851xgXoe75WJ+D4eKhKDhBAVGOFkAQsF1A1yCVV7bjA8Q7r0kNTYMUyFNwcYhPr2DI6OixZSW9jbzmqSgeOleBkb7hLePcJS8zT/4uB15Oj5uwRisIng/C4NQzTIE4Xd1hVqNM3+rqD3pvzTrsRhkzQfwJeAefcD1YBWoOqL6yxA6uT9DsPCFOchig/bn5I9syez58tw1G+V2v2EYCJUkFIuRU+hUb8exBxRNfjOLVmpoScdvuUgiFA06vdP2l4v5FP5jVb8OBHsMiRRQaAYcg4/0AFyW+Q/A6CDFbeTD0Hjo7pXxtJ0OFCxCWnN0Pm66TvUKu+Mwz/DXUdYBi23wajrVJOswDur/5eKf+YfmMY1XcpcjyLUpi2yr7t/bSGvcddfPaOCjEjz/ivs6TDf8SMaf4dvBm5FAhdEFOlVc1s+rVmE78U6G7uJs4Y4FMHJsdpz0foA5oPQT/Cnil+h8gUaaL2mrWkL6ASfDrolij7i7OipWy/VZC++9I4E7k0TA0v0qux9oF9yMbO2nttja5OJGAVW58JjhDt6qFu9bIvHk+nuZfA8AAP//1Jf+qQ=="
}
