// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package system

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("auditbeat", "system", asset.ModuleFieldsPri, AssetSystem); err != nil {
		panic(err)
	}
}

// AssetSystem returns asset data.
// This is the base64 encoded gzipped contents of module/system.
func AssetSystem() string {
	return "eJy8WF1v2zYUffevuOhLbcBVX4Zi8MOAdgW2AusSwCm2t/hKvJK4SKTAS8VRf/1A6sNflF03SvQShJbOOffjXFJ6Bw/UrIAbtlTOAKy0Ba3gzdovvJkBCOLEyMpKrVbw2wwA4C4nJkBDYHOCVFIhGDJSZNCSgLjx6y0mlFrUBUUzAEMFIdMK6KkiI0tSFosZdAArD/0OFJbUC4qwFtL6HwBsU9EKMqPrqlsJSDtE20fMNdthMYQ2itheGwewgUQri1L18RYeF6RKtSnRPRftPTUWcX8da92prSsrSzoQ0CoutMoOls9Idtc3DwRSgUKlmRKtBEcBxlhrO8Ip0NI1nJ+0tuCwQjxdAsnI7yQCZLHWBaG6hm9NFmTaVYIBdxwhAU7Yd60ocv8GBDxQs9VGXCPgbywJdOrbvofv/3eqlkBRFsGn9d1ZQTpNmWzElExQ+LudDofqOuBM9Z3K6fLxZ4cWYpKhov8kB3z5HKJAk+TSUmJrM2FAB7Aw9xV9+vXD/YdfFiERJYaq+BPcXz/+DiiEIWYK1k5WAaKjxQscX27PU2gOUBwPzwssG81743NvYgLGurbeLLpye4hUWb8BHGCcjsudwqpA6xCPSMezfjEnN+sBtKt2QspqXkId18rWS9hKJfSWF1FQ0YmdnqvGAXZKvmLiVv4doU6xlEUzKXkL2dEbEjnaJQiKJaolpIYoZnEpI49kWGo1qa4OM0z4QEZRMR3fXaBF33JHcypl6E2jE2J+1umjw9hzEAoh3a1Y9AQvcAyZalrfKPhLqvoJUAk3Gm/WMP+MZivVYumdbwgLqJnM0UwfHv+nba32bqakNtI2IAUpK1NJBubrL58X/a7bZwQT/8fqB1KhwUavFyGlKSVWPlIozOHc+3p6GB9JnNOSvW7xvRumqr4s0TQd5LUt8Xpx71oiFPzQE68nqO2JUzHDPGAyzxpjDuDiKcDdxOCWAseA64fZS23JAN+ceY4PuuPTcwq2Y3+MmfWZXH8EzdiTCWmmDuwtQ65LctCUWG2aMDPnVEy4oQPcGp0ZLMFqMLUCtFDoTI6cJ1xj3u/1bFCIpSd7dbq7jwl+Gu/v4oNlnT8lu9db55CMEs1tq4+0w8nZvJen4/8ouVLgxsOd9S2qbtzyYGEntkJj3QCex9RoJYbf3vLhkF4cT/2QjeG8leFCL/xQJWBo/lNfw1m/7eilspTRsUWupB/zXoXMgeDGXsku17YHPF/eoWrd3TBXup3Ww4q0TEV6dSWd8peq5McT2Q42glvNLOOC4BGLmth/y9xwjkJv74d8jGDOD4LOkXPX6FK1G6jHgFQWtFjucnsvJGNckNgsR1A3Su+YHUdrdoEqI6NrBmTnMa0IElRuSIHftVGFkuMRE9NUdh90m5M6LJmvjdP+nmzy3i8LYKKSR0Ct7rsEUAEpz0FiQDyp/q7OBbK9T3IX0Lh1Tj41ttcPFdu9nQlsDmZMH+gW2QuATkA0+z8AAP//A2AH4A=="
}
