[[filtering-and-enhancing-data]]
== Filter and enhance the exported data

IMPORTANT: This documentation is placeholder content. It has not yet been reviewed.

Your use case might require only a subset of the data exported by {beatname_uc},
or you might need to enhance the exported data (for example, by adding
metadata). {beatname_uc} provides a couple of options for filtering and
enhancing exported data.

You can configure each input to include or exclude specific lines or files. This
allows you to specify different filtering criteria for each input. To do this,
you use the `include_lines`, `exclude_lines`, and `exclude_files` options under
the +{beatname_lc}.inputs+ section of the config file (see
<<configuration-{beatname_lc}-options>>). The disadvantage of this approach is
that you need to implement a configuration option for each filtering criteria
that you need.

Another approach (the one described here) is to define processors to configure
global processing across all data exported by {beatname_uc}.


[float]
[[using-processors]]
=== Processors

include::../../libbeat/docs/processors.asciidoc[]

[float]
[[specific-example]]
==== XYZ example

ADD EXAMPLES SPECIFIC TO THE BEAT, OR DELETE THIS SECTION

// You must set the processor-scope attribute to resolve the attribute reference
// defined in processors-using.asciidoc. The attribute is used to indicate where
// processors are valid. If processors are valid in more than two locations
// (root and :processor-scope:), you need to add a conditionally coded section
// to processors-using.asciidoc.

:processor-scope: input
include::../../libbeat/docs/processors-using.asciidoc[]
:processor-scope!:
