This is the IBM MQ metricbeat module. This module uses PCF messages to collect metrics and status information from different IBM MQ objects.
With IBM MQ > v9 its also possible to collect data using the subscribe mode.

At the moment this is collecting data from Queue Manager.

[float]
=== Compability

This module is tested with IBM MQ v9.1.0 but older version will work as well. The subscribe mode only works with IBM MQ > v9.

=== How to use module on Darwin
First download the IBM client library. This is a dynamically loaded library:
```
wget https://github.com/ChrsMark/ibm_client_plugin/raw/master/ibmqlib_darwin.so
```
Then set the IBM_LIBRARY_PATH variable to point to the downloaded file:
```
export IBM_LIBRARY_PATH=~/Downloads/ibmqlib_darwin.so
```
Then you are ready to go. You can build and execute Metricbeat and enable the module to collect metrics data
from IBM MQ:
```
go build  (or mage build)
./metricbeat modules enable ibmmq
./metricbeat -e -d "*"
```

=== How to use module on Linux
First download the IBM client library. This is a dynamically loaded library:
```
https://github.com/ChrsMark/ibm_client_plugin/raw/master/ibmqlib_linux.so
```
Then set the IBM_LIBRARY_PATH variable to point to the downloaded file:
```
export IBM_LIBRARY_PATH=~/Downloads/ibmqlib_darwin.so
```
Then you are ready to go. You can build and execute Metricbeat and enable the module to collect metrics data
from IBM MQ:
```
go build  (or mage build)
./metricbeat modules enable ibmmq
./metricbeat -e -d "*"
```
