package fix

type typeBlock struct {
    name    string
    dtype   string
}

var fixFields map[int]typeBlock = map[int]typeBlock{
    1: typeBlock{name: "Account", dtype: "int"},
    2: typeBlock{name: "AdvId", dtype: "string"},
    3: typeBlock{name: "AdvRefID", dtype: "int"},
    4: typeBlock{name: "AdvSide", dtype: "string"},
    5: typeBlock{name: "AdvTransType", dtype: "string"},
    6: typeBlock{name: "AvgPx", dtype: "string"},
    7: typeBlock{name: "BeginSeqNo", dtype: "string"},
    8: typeBlock{name: "BeginString", dtype: "string"},
    9: typeBlock{name: "BodyLength", dtype: "int"},
    10: typeBlock{name: "CheckSum", dtype: "string"},
    11: typeBlock{name: "ClOrdID", dtype: "string"},
    12: typeBlock{name: "Commission", dtype: "string"},
    13: typeBlock{name: "CommType", dtype: "string"},
    14: typeBlock{name: "CumQty", dtype: "int"},
    15: typeBlock{name: "Currency", dtype: "string"},
    16: typeBlock{name: "EndSeqNo", dtype: "string"},
    17: typeBlock{name: "ExecID", dtype: "string"},
    18: typeBlock{name: "ExecInst", dtype: "string"},
    19: typeBlock{name: "ExecRefID", dtype: "string"},
    20: typeBlock{name: "ExecTransType", dtype: "string"},
    21: typeBlock{name: "HandlInst", dtype: "string"},
    22: typeBlock{name: "IDSource", dtype: "int"},
    23: typeBlock{name: "IOIid", dtype: "string"},
    24: typeBlock{name: "IOIOthSvc (no longer used)", dtype: "string"},
    25: typeBlock{name: "IOIQltyInd", dtype: "string"},
    26: typeBlock{name: "IOIRefID", dtype: "string"},
    27: typeBlock{name: "IOIShares", dtype: "int"},
    28: typeBlock{name: "IOITransType", dtype: "string"},
    29: typeBlock{name: "LastCapacity", dtype: "string"},
    30: typeBlock{name: "LastMkt", dtype: "string"},
    31: typeBlock{name: "LastPx", dtype: "float"},
    32: typeBlock{name: "LastShares", dtype: "int"},
    33: typeBlock{name: "LinesOfText", dtype: "string"},
    34: typeBlock{name: "MsgSeqNum", dtype: "int"},
    35: typeBlock{name: "MsgType", dtype: "int"},
    36: typeBlock{name: "NewSeqNo", dtype: "string"},
    37: typeBlock{name: "OrderID", dtype: "string"},
    38: typeBlock{name: "OrderQty", dtype: "int"},
    39: typeBlock{name: "OrdStatus", dtype: "int"},
    40: typeBlock{name: "OrdType", dtype: "string"},
    41: typeBlock{name: "OrigClOrdID", dtype: "string"},
    42: typeBlock{name: "OrigTime", dtype: "string"},
    43: typeBlock{name: "PossDupFlag", dtype: "string"},
    44: typeBlock{name: "Price", dtype: "float"},
    45: typeBlock{name: "RefSeqNum", dtype: "string"},
    46: typeBlock{name: "RelatdSym", dtype: "string"},
    47: typeBlock{name: "Rule80A(aka OrderCapacity)", dtype: "string"},
    48: typeBlock{name: "SecurityID", dtype: "string"},
    49: typeBlock{name: "SenderCompID", dtype: "string"},
    50: typeBlock{name: "SenderSubID", dtype: "string"},
    51: typeBlock{name: "SendingDate (no longer used)", dtype: "string"},
    52: typeBlock{name: "SendingTime", dtype: "string"},
    53: typeBlock{name: "Shares", dtype: "string"},
    54: typeBlock{name: "Side", dtype: "int"},
    55: typeBlock{name: "Symbol", dtype: "string"},
    56: typeBlock{name: "TargetCompID", dtype: "string"},
    57: typeBlock{name: "TargetSubID", dtype: "string"},
    58: typeBlock{name: "Text", dtype: "string"},
    59: typeBlock{name: "TimeInForce", dtype: "string"},
    60: typeBlock{name: "TransactTime", dtype: "string"},
    61: typeBlock{name: "Urgency", dtype: "string"},
    62: typeBlock{name: "ValidUntilTime", dtype: "string"},
    63: typeBlock{name: "SettlmntTyp", dtype: "string"},
    64: typeBlock{name: "FutSettDate", dtype: "string"},
    65: typeBlock{name: "SymbolSfx", dtype: "string"},
    66: typeBlock{name: "ListID", dtype: "string"},
    67: typeBlock{name: "ListSeqNo", dtype: "string"},
    68: typeBlock{name: "TotNoOrders(formerly named: ListNoOrds)", dtype: "string"},
    69: typeBlock{name: "ListExecInst", dtype: "string"},
    70: typeBlock{name: "AllocID", dtype: "string"},
    71: typeBlock{name: "AllocTransType", dtype: "string"},
    72: typeBlock{name: "RefAllocID", dtype: "string"},
    73: typeBlock{name: "NoOrders", dtype: "string"},
    74: typeBlock{name: "AvgPrxPrecision", dtype: "string"},
    75: typeBlock{name: "TradeDate", dtype: "string"},
    76: typeBlock{name: "ExecBroker", dtype: "string"},
    77: typeBlock{name: "OpenClose", dtype: "string"},
    78: typeBlock{name: "NoAllocs", dtype: "string"},
    79: typeBlock{name: "AllocAccount", dtype: "string"},
    80: typeBlock{name: "AllocShares", dtype: "string"},
    81: typeBlock{name: "ProcessCode", dtype: "string"},
    82: typeBlock{name: "NoRpts", dtype: "string"},
    83: typeBlock{name: "RptSeq", dtype: "string"},
    84: typeBlock{name: "CxlQty", dtype: "string"},
    85: typeBlock{name: "NoDlvyInst(no longer used)", dtype: "string"},
    86: typeBlock{name: "DlvyInst(no longer used)", dtype: "string"},
    87: typeBlock{name: "AllocStatus", dtype: "string"},
    88: typeBlock{name: "AllocRejCode", dtype: "string"},
    89: typeBlock{name: "Signature", dtype: "string"},
    90: typeBlock{name: "SecureDataLen", dtype: "string"},
    91: typeBlock{name: "SecureData", dtype: "string"},
    92: typeBlock{name: "BrokerOfCredit", dtype: "string"},
    93: typeBlock{name: "SignatureLength", dtype: "string"},
    94: typeBlock{name: "EmailType", dtype: "string"},
    95: typeBlock{name: "RawDataLength", dtype: "string"},
    96: typeBlock{name: "RawData", dtype: "string"},
    97: typeBlock{name: "PossResend", dtype: "string"},
    98: typeBlock{name: "EncryptMethod", dtype: "string"},
    99: typeBlock{name: "StopPx", dtype: "string"},
    100: typeBlock{name: "ExDestination", dtype: "string"},
    102: typeBlock{name: "CxlRejReason", dtype: "string"},
    103: typeBlock{name: "OrdRejReason", dtype: "string"},
    104: typeBlock{name: "IOIQualifier", dtype: "string"},
    105: typeBlock{name: "WaveNo", dtype: "string"},
    106: typeBlock{name: "Issuer", dtype: "string"},
    107: typeBlock{name: "SecurityDesc", dtype: "string"},
    108: typeBlock{name: "HeartBtInt", dtype: "string"},
    109: typeBlock{name: "ClientID", dtype: "string"},
    110: typeBlock{name: "MinQty", dtype: "string"},
    111: typeBlock{name: "MaxFloor", dtype: "string"},
    112: typeBlock{name: "TestReqID", dtype: "string"},
    113: typeBlock{name: "ReportToExch", dtype: "string"},
    114: typeBlock{name: "LocateReqd", dtype: "string"},
    115: typeBlock{name: "OnBehalfOfCompID", dtype: "string"},
    116: typeBlock{name: "OnBehalfOfSubID", dtype: "string"},
    117: typeBlock{name: "QuoteID", dtype: "string"},
    118: typeBlock{name: "NetMoney", dtype: "string"},
    119: typeBlock{name: "SettlCurrAmt", dtype: "string"},
    120: typeBlock{name: "SettlCurrency", dtype: "string"},
    121: typeBlock{name: "ForexReq", dtype: "string"},
    122: typeBlock{name: "OrigSendingTime", dtype: "string"},
    123: typeBlock{name: "GapFillFlag", dtype: "string"},
    124: typeBlock{name: "NoExecs", dtype: "string"},
    125: typeBlock{name: "CxlType(no longer used)", dtype: "string"},
    126: typeBlock{name: "ExpireTime", dtype: "string"},
    127: typeBlock{name: "DKReason", dtype: "string"},
    128: typeBlock{name: "DeliverToCompID", dtype: "string"},
    129: typeBlock{name: "DeliverToSubID", dtype: "string"},
    130: typeBlock{name: "IOINaturalFlag", dtype: "string"},
    131: typeBlock{name: "QuoteReqID", dtype: "string"},
    132: typeBlock{name: "BidPx", dtype: "string"},
    133: typeBlock{name: "OfferPx", dtype: "string"},
    134: typeBlock{name: "BidSize", dtype: "string"},
    135: typeBlock{name: "OfferSize", dtype: "string"},
    136: typeBlock{name: "NoMiscFees", dtype: "string"},
    137: typeBlock{name: "MiscFeeAmt", dtype: "string"},
    138: typeBlock{name: "MiscFeeCurr", dtype: "string"},
    139: typeBlock{name: "MiscFeeType", dtype: "string"},
    140: typeBlock{name: "PrevClosePx", dtype: "string"},
    141: typeBlock{name: "ResetSeqNumFlag", dtype: "string"},
    142: typeBlock{name: "SenderLocationID", dtype: "string"},
    143: typeBlock{name: "TargetLocationID", dtype: "string"},
    144: typeBlock{name: "OnBehalfOfLocationID", dtype: "string"},
    145: typeBlock{name: "DeliverToLocationID", dtype: "string"},
    146: typeBlock{name: "NoRelatedSym", dtype: "string"},
    147: typeBlock{name: "Subject", dtype: "string"},
    148: typeBlock{name: "Headline", dtype: "string"},
    149: typeBlock{name: "URLLink", dtype: "string"},
    150: typeBlock{name: "ExecType", dtype: "string"},
    151: typeBlock{name: "LeavesQty", dtype: "string"},
    152: typeBlock{name: "CashOrderQty", dtype: "string"},
    153: typeBlock{name: "AllocAvgPx", dtype: "string"},
    154: typeBlock{name: "AllocNetMoney", dtype: "string"},
    155: typeBlock{name: "SettlCurrFxRate", dtype: "string"},
    156: typeBlock{name: "SettlCurrFxRateCalc", dtype: "string"},
    157: typeBlock{name: "NumDaysInterest", dtype: "string"},
    158: typeBlock{name: "AccruedInterestRate", dtype: "string"},
    159: typeBlock{name: "AccruedInterestAmt", dtype: "string"},
    160: typeBlock{name: "SettlInstMode", dtype: "string"},
    161: typeBlock{name: "AllocText", dtype: "string"},
    162: typeBlock{name: "SettlInstID", dtype: "string"},
    163: typeBlock{name: "SettlInstTransType", dtype: "string"},
    164: typeBlock{name: "EmailThreadID", dtype: "string"},
    165: typeBlock{name: "SettlInstSource", dtype: "string"},
    166: typeBlock{name: "SettlLocation", dtype: "string"},
    167: typeBlock{name: "SecurityType", dtype: "string"},
    168: typeBlock{name: "EffectiveTime", dtype: "string"},
    169: typeBlock{name: "StandInstDbType", dtype: "string"},
    170: typeBlock{name: "StandInstDbName", dtype: "string"},
    171: typeBlock{name: "StandInstDbID", dtype: "string"},
    172: typeBlock{name: "SettlDeliveryType", dtype: "string"},
    173: typeBlock{name: "SettlDepositoryCode", dtype: "string"},
    174: typeBlock{name: "SettlBrkrCode", dtype: "string"},
    175: typeBlock{name: "SettlInstCode", dtype: "string"},
    176: typeBlock{name: "SecuritySettlAgentName", dtype: "string"},
    177: typeBlock{name: "SecuritySettlAgentCode", dtype: "string"},
    178: typeBlock{name: "SecuritySettlAgentAcctNum", dtype: "string"},
    179: typeBlock{name: "SecuritySettlAgentAcctName", dtype: "string"},
    180: typeBlock{name: "SecuritySettlAgentContactName", dtype: "string"},
    181: typeBlock{name: "SecuritySettlAgentContactPhone", dtype: "string"},
    182: typeBlock{name: "CashSettlAgentName", dtype: "string"},
    183: typeBlock{name: "CashSettlAgentCode", dtype: "string"},
    184: typeBlock{name: "CashSettlAgentAcctNum", dtype: "string"},
    185: typeBlock{name: "CashSettlAgentAcctName", dtype: "string"},
    186: typeBlock{name: "CashSettlAgentContactName", dtype: "string"},
    187: typeBlock{name: "CashSettlAgentContactPhone", dtype: "string"},
    188: typeBlock{name: "BidSpotRate", dtype: "string"},
    189: typeBlock{name: "BidForwardPoints", dtype: "string"},
    190: typeBlock{name: "OfferSpotRate", dtype: "string"},
    191: typeBlock{name: "OfferForwardPoints", dtype: "string"},
    192: typeBlock{name: "OrderQty2", dtype: "string"},
    193: typeBlock{name: "FutSettDate2", dtype: "string"},
    194: typeBlock{name: "LastSpotRate", dtype: "string"},
    195: typeBlock{name: "LastForwardPoints", dtype: "string"},
    196: typeBlock{name: "AllocLinkID", dtype: "string"},
    197: typeBlock{name: "AllocLinkType", dtype: "string"},
    198: typeBlock{name: "SecondaryOrderID", dtype: "string"},
    199: typeBlock{name: "NoIOIQualifiers", dtype: "string"},
    200: typeBlock{name: "MaturityMonthYear", dtype: "string"},
    201: typeBlock{name: "PutOrCall", dtype: "string"},
    202: typeBlock{name: "StrikePrice", dtype: "string"},
    203: typeBlock{name: "CoveredOrUncovered", dtype: "string"},
    204: typeBlock{name: "CustomerOrFirm", dtype: "string"},
    205: typeBlock{name: "MaturityDay", dtype: "string"},
    206: typeBlock{name: "OptAttribute", dtype: "string"},
    207: typeBlock{name: "SecurityExchange", dtype: "string"},
    208: typeBlock{name: "NotifyBrokerOfCredit", dtype: "string"},
    209: typeBlock{name: "AllocHandlInst", dtype: "string"},
    210: typeBlock{name: "MaxShow", dtype: "string"},
    211: typeBlock{name: "PegDifference", dtype: "string"},
    212: typeBlock{name: "XmlDataLen", dtype: "string"},
    213: typeBlock{name: "XmlData", dtype: "string"},
    214: typeBlock{name: "SettlInstRefID", dtype: "string"},
    215: typeBlock{name: "NoRoutingIDs", dtype: "string"},
    216: typeBlock{name: "RoutingType", dtype: "string"},
    217: typeBlock{name: "RoutingID", dtype: "string"},
    218: typeBlock{name: "SpreadToBenchmark", dtype: "string"},
    219: typeBlock{name: "Benchmark", dtype: "string"},
    223: typeBlock{name: "CouponRate", dtype: "string"},
    231: typeBlock{name: "ContractMultiplier", dtype: "string"},
    262: typeBlock{name: "MDReqID", dtype: "string"},
    263: typeBlock{name: "SubscriptionRequestType", dtype: "string"},
    264: typeBlock{name: "MarketDepth", dtype: "string"},
    265: typeBlock{name: "MDUpdateType", dtype: "string"},
    266: typeBlock{name: "AggregatedBook", dtype: "string"},
    267: typeBlock{name: "NoMDEntryTypes", dtype: "string"},
    268: typeBlock{name: "NoMDEntries", dtype: "string"},
    269: typeBlock{name: "MDEntryType", dtype: "string"},
    270: typeBlock{name: "MDEntryPx", dtype: "string"},
    271: typeBlock{name: "MDEntrySize", dtype: "string"},
    272: typeBlock{name: "MDEntryDate", dtype: "string"},
    273: typeBlock{name: "MDEntryTime", dtype: "string"},
    274: typeBlock{name: "TickDirection", dtype: "string"},
    275: typeBlock{name: "MDMkt", dtype: "string"},
    276: typeBlock{name: "QuoteCondition", dtype: "string"},
    277: typeBlock{name: "TradeCondition", dtype: "string"},
    278: typeBlock{name: "MDEntryID", dtype: "string"},
    279: typeBlock{name: "MDUpdateAction", dtype: "string"},
    280: typeBlock{name: "MDEntryRefID", dtype: "string"},
    281: typeBlock{name: "MDReqRejReason", dtype: "string"},
    282: typeBlock{name: "MDEntryOriginator", dtype: "string"},
    283: typeBlock{name: "LocationID", dtype: "string"},
    284: typeBlock{name: "DeskID", dtype: "string"},
    285: typeBlock{name: "DeleteReason", dtype: "string"},
    286: typeBlock{name: "OpenCloseSettleFlag", dtype: "string"},
    287: typeBlock{name: "SellerDays", dtype: "string"},
    288: typeBlock{name: "MDEntryBuyer", dtype: "string"},
    289: typeBlock{name: "MDEntrySeller", dtype: "string"},
    290: typeBlock{name: "MDEntryPositionNo", dtype: "string"},
    291: typeBlock{name: "FinancialStatus", dtype: "string"},
    292: typeBlock{name: "CorporateAction", dtype: "string"},
    293: typeBlock{name: "DefBidSize", dtype: "string"},
    294: typeBlock{name: "DefOfferSize", dtype: "string"},
    295: typeBlock{name: "NoQuoteEntries", dtype: "string"},
    296: typeBlock{name: "NoQuoteSets", dtype: "string"},
    297: typeBlock{name: "QuoteAckStatus", dtype: "string"},
    298: typeBlock{name: "QuoteCancelType", dtype: "string"},
    299: typeBlock{name: "QuoteEntryID", dtype: "string"},
    300: typeBlock{name: "QuoteRejectReason", dtype: "string"},
    301: typeBlock{name: "QuoteResponseLevel", dtype: "string"},
    302: typeBlock{name: "QuoteSetID", dtype: "string"},
    303: typeBlock{name: "QuoteRequestType", dtype: "string"},
    304: typeBlock{name: "TotQuoteEntries", dtype: "string"},
    305: typeBlock{name: "UnderlyingIDSource", dtype: "string"},
    306: typeBlock{name: "UnderlyingIssuer", dtype: "string"},
    307: typeBlock{name: "UnderlyingSecurityDesc", dtype: "string"},
    308: typeBlock{name: "UnderlyingSecurityExchange", dtype: "string"},
    309: typeBlock{name: "UnderlyingSecurityID", dtype: "string"},
    310: typeBlock{name: "UnderlyingSecurityType", dtype: "string"},
    311: typeBlock{name: "UnderlyingSymbol", dtype: "string"},
    312: typeBlock{name: "UnderlyingSymbolSfx", dtype: "string"},
    313: typeBlock{name: "UnderlyingMaturityMonthYear", dtype: "string"},
    314: typeBlock{name: "UnderlyingMaturityDay", dtype: "string"},
    315: typeBlock{name: "UnderlyingPutOrCall", dtype: "string"},
    316: typeBlock{name: "UnderlyingStrikePrice", dtype: "string"},
    317: typeBlock{name: "UnderlyingOptAttribute", dtype: "string"},
    318: typeBlock{name: "Underlying Currency", dtype: "string"},
    319: typeBlock{name: "RatioQty", dtype: "string"},
    320: typeBlock{name: "SecurityReqID", dtype: "string"},
    321: typeBlock{name: "SecurityRequestType", dtype: "string"},
    322: typeBlock{name: "SecurityResponseID", dtype: "string"},
    323: typeBlock{name: "SecurityResponseType", dtype: "string"},
    324: typeBlock{name: "SecurityStatusReqID", dtype: "string"},
    325: typeBlock{name: "UnsolicitedIndicator", dtype: "string"},
    326: typeBlock{name: "SecurityTradingStatus", dtype: "string"},
    327: typeBlock{name: "HaltReason", dtype: "string"},
    328: typeBlock{name: "InViewOfCommon", dtype: "string"},
    329: typeBlock{name: "DueToRelated", dtype: "string"},
    330: typeBlock{name: "BuyVolume", dtype: "string"},
    331: typeBlock{name: "SellVolume", dtype: "string"},
    332: typeBlock{name: "HighPx", dtype: "string"},
    333: typeBlock{name: "LowPx", dtype: "string"},
    334: typeBlock{name: "Adjustment", dtype: "string"},
    335: typeBlock{name: "TradSesReqID", dtype: "string"},
    336: typeBlock{name: "TradingSessionID", dtype: "string"},
    337: typeBlock{name: "ContraTrader", dtype: "string"},
    338: typeBlock{name: "TradSesMethod", dtype: "string"},
    339: typeBlock{name: "TradSesMode", dtype: "string"},
    340: typeBlock{name: "TradSesStatus", dtype: "string"},
    341: typeBlock{name: "TradSesStartTime", dtype: "string"},
    342: typeBlock{name: "TradSesOpenTime", dtype: "string"},
    343: typeBlock{name: "TradSesPreCloseTime", dtype: "string"},
    344: typeBlock{name: "TradSesCloseTime", dtype: "string"},
    345: typeBlock{name: "TradSesEndTime", dtype: "string"},
    346: typeBlock{name: "NumberOfOrders", dtype: "string"},
    347: typeBlock{name: "MessageEncoding", dtype: "string"},
    348: typeBlock{name: "EncodedIssuerLen", dtype: "string"},
    349: typeBlock{name: "EncodedIssuer", dtype: "string"},
    350: typeBlock{name: "EncodedSecurityDescLen", dtype: "string"},
    351: typeBlock{name: "EncodedSecurityDesc", dtype: "string"},
    352: typeBlock{name: "EncodedListExecInstLen", dtype: "string"},
    353: typeBlock{name: "EncodedListExecInst", dtype: "string"},
    354: typeBlock{name: "EncodedTextLen", dtype: "string"},
    355: typeBlock{name: "EncodedText", dtype: "string"},
    356: typeBlock{name: "EncodedSubjectLen", dtype: "string"},
    357: typeBlock{name: "EncodedSubject", dtype: "string"},
    358: typeBlock{name: "EncodedHeadlineLen", dtype: "string"},
    359: typeBlock{name: "EncodedHeadline", dtype: "string"},
    360: typeBlock{name: "EncodedAllocTextLen", dtype: "string"},
    361: typeBlock{name: "EncodedAllocText", dtype: "string"},
    362: typeBlock{name: "EncodedUnderlyingIssuerLen", dtype: "string"},
    363: typeBlock{name: "EncodedUnderlyingIssuer", dtype: "string"},
    364: typeBlock{name: "EncodedUnderlyingSecurityDescLen", dtype: "string"},
    365: typeBlock{name: "EncodedUnderlyingSecurityDesc", dtype: "string"},
    366: typeBlock{name: "AllocPrice", dtype: "string"},
    367: typeBlock{name: "QuoteSetValidUntilTime", dtype: "string"},
    368: typeBlock{name: "QuoteEntryRejectReason", dtype: "string"},
    369: typeBlock{name: "LastMsgSeqNumProcessed", dtype: "string"},
    370: typeBlock{name: "OnBehalfOfSendingTime", dtype: "string"},
    371: typeBlock{name: "RefTagID", dtype: "string"},
    372: typeBlock{name: "RefMsgType", dtype: "string"},
    373: typeBlock{name: "SessionRejectReason", dtype: "string"},
    374: typeBlock{name: "BidRequestTransType", dtype: "string"},
    375: typeBlock{name: "ContraBroker", dtype: "string"},
    376: typeBlock{name: "ComplianceID", dtype: "string"},
    377: typeBlock{name: "SolicitedFlag", dtype: "string"},
    378: typeBlock{name: "ExecRestatementReason", dtype: "string"},
    379: typeBlock{name: "BusinessRejectRefID", dtype: "string"},
    380: typeBlock{name: "BusinessRejectReason", dtype: "string"},
    381: typeBlock{name: "GrossTradeAmt", dtype: "string"},
    382: typeBlock{name: "NoContraBrokers", dtype: "string"},
    383: typeBlock{name: "MaxMessageSize", dtype: "string"},
    384: typeBlock{name: "NoMsgTypes", dtype: "string"},
    385: typeBlock{name: "MsgDirection", dtype: "string"},
    386: typeBlock{name: "NoTradingSessions", dtype: "string"},
    387: typeBlock{name: "TotalVolumeTraded", dtype: "string"},
    388: typeBlock{name: "DiscretionInst", dtype: "string"},
    389: typeBlock{name: "DiscretionOffset", dtype: "string"},
    390: typeBlock{name: "BidID", dtype: "string"},
    391: typeBlock{name: "ClientBidID", dtype: "string"},
    392: typeBlock{name: "ListName", dtype: "string"},
    393: typeBlock{name: "TotalNumSecurities", dtype: "string"},
    394: typeBlock{name: "BidType", dtype: "string"},
    395: typeBlock{name: "NumTickets", dtype: "string"},
    396: typeBlock{name: "SideValue1", dtype: "string"},
    397: typeBlock{name: "SideValue2", dtype: "string"},
    398: typeBlock{name: "NoBidDescriptors", dtype: "string"},
    399: typeBlock{name: "BidDescriptorType", dtype: "string"},
    400: typeBlock{name: "BidDescriptor", dtype: "string"},
    401: typeBlock{name: "SideValueInd", dtype: "string"},
    402: typeBlock{name: "LiquidityPctLow", dtype: "string"},
    403: typeBlock{name: "LiquidityPctHigh", dtype: "string"},
    404: typeBlock{name: "LiquidityValue", dtype: "string"},
    405: typeBlock{name: "EFPTrackingError", dtype: "string"},
    406: typeBlock{name: "FairValue", dtype: "string"},
    407: typeBlock{name: "OutsideIndexPct", dtype: "string"},
    408: typeBlock{name: "ValueOfFutures", dtype: "string"},
    409: typeBlock{name: "LiquidityIndType", dtype: "string"},
    410: typeBlock{name: "WtAverageLiquidity", dtype: "string"},
    411: typeBlock{name: "ExchangeForPhysical", dtype: "string"},
    412: typeBlock{name: "OutMainCntryUIndex", dtype: "string"},
    413: typeBlock{name: "CrossPercent", dtype: "string"},
    414: typeBlock{name: "ProgRptReqs", dtype: "string"},
    415: typeBlock{name: "ProgPeriodInterval", dtype: "string"},
    416: typeBlock{name: "IncTaxInd", dtype: "string"},
    417: typeBlock{name: "NumBidders", dtype: "string"},
    418: typeBlock{name: "TradeType", dtype: "string"},
    419: typeBlock{name: "BasisPxType", dtype: "string"},
    420: typeBlock{name: "NoBidComponents", dtype: "string"},
    421: typeBlock{name: "Country", dtype: "string"},
    422: typeBlock{name: "TotNoStrikes", dtype: "string"},
    423: typeBlock{name: "PriceType", dtype: "string"},
    424: typeBlock{name: "DayOrderQty", dtype: "int"},
    425: typeBlock{name: "DayCumQty", dtype: "int"},
    426: typeBlock{name: "DayAvgPx", dtype: "string"},
    427: typeBlock{name: "GTBookingInst", dtype: "string"},
    428: typeBlock{name: "NoStrikes", dtype: "string"},
    429: typeBlock{name: "ListStatusType", dtype: "string"},
    430: typeBlock{name: "NetGrossInd", dtype: "string"},
    431: typeBlock{name: "ListOrderStatus", dtype: "string"},
    432: typeBlock{name: "ExpireDate", dtype: "string"},
    433: typeBlock{name: "ListExecInstType", dtype: "string"},
    434: typeBlock{name: "CxlRejResponseTo", dtype: "string"},
    435: typeBlock{name: "UnderlyingCouponRate", dtype: "string"},
    436: typeBlock{name: "UnderlyingContractMultiplier", dtype: "string"},
    437: typeBlock{name: "ContraTradeQty", dtype: "string"},
    438: typeBlock{name: "ContraTradeTime", dtype: "string"},
    439: typeBlock{name: "ClearingFirm", dtype: "string"},
    440: typeBlock{name: "ClearingAccount", dtype: "string"},
    441: typeBlock{name: "LiquidityNumSecurities", dtype: "string"},
    442: typeBlock{name: "MultiLegReportingType", dtype: "string"},
    443: typeBlock{name: "StrikeTime", dtype: "string"},
    444: typeBlock{name: "ListStatusText", dtype: "string"},
    445: typeBlock{name: "EncodedListStatusTextLen", dtype: "string"},
    446: typeBlock{name: "EncodedListStatusText", dtype: "string"},
}

var fixMsgTypes map[string]string = map[string]string{
    "0": "Heartbeat",
    "1": "Test Request",
    "2": "Resend Request",
    "3": "Reject",
    "4": "Sequence Reset",
    "5": "Logout",
    "6": "Indication of Interest",
    "7": "Advertisement",
    "8": "Execution Report",
    "9": "Order Cancel Reject",
    "a": "Quote Status Request",
    "A": "Logon",
    "b": "Quote Acknowledgement",
    "B": "News",
    "c": "Security Definition Request",
    "C": "Email",
    "d": "Security Definition",
    "D": "Order - Single",
    "e": "Security Status Request",
    "E": "Order - List",
    "f": "Security Status",
    "F": "Order Cancel Request",
    "g": "Trading Session Status Request",
    "G": "Order Cancel/Replace Request",
    "h": "Trading Session Status",
    "H": "Order Status Request",
    "i": "Mass Quote",
    "j": "Business Message Reject",
    "J": "Allocation",
    "k": "Bid Request",
    "K": "List Cancel Request",
    "l": "Bid Response",
    "L": "List Execute",
    "m": "List Strike Price",
    "M": "List Status Request",
    "N": "List Status",
    "P": "Allocation ACK",
    "Q": "Don't Know Trade",
    "R": "Quote Request",
    "S": "Quote",
    "T": "Settlement Instructions",
    "V": "Market Data Request",
    "W": "Market Data - Snapshot/Full Refresh",
    "X": "Market Data - Incremental Refresh",
    "Y": "Market Data Request Reject",
    "Z": "Quote Cancel",
}

var fixExecTransTypes map[string]string = map[string]string{
    "0": "New",
    "1": "Cancel",
    "2": "Correct",
    "3": "Status",
}

var fixExecTypes map[string]string = map[string]string{
    "0": "New",
    "1": "Partial Fill",
    "2": "Fill",
    "3": "Done for day",
    "4": "Canceled",
    "5": "Replace",
    "6": "Pending Cancel",
    "7": "Stopped",
    "8": "Rejected",
    "9": "Suspended",
    "A": "Pending New",
    "B": "Calculated",
    "C": "Expired",
    "D": "Restated",
    "E": "Pending Replace",
}


