services:
  # This is a proxy used to block beats until all services are healthy.
  # See: https://github.com/docker/compose/issues/4369
  proxy_dep:
    image: busybox
    depends_on:
      elasticsearch: { condition: service_healthy }
      kibana: { condition: service_healthy }

  elasticsearch:
    extends:
      file: ${ES_BEATS}/testing/environments/${TESTING_ENVIRONMENT}.yml
      service: elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -u kibana_system_user:testing -f http://localhost:9200/_cat/health?h=status | grep -q green"]
      retries: 1200
      interval: 5s
      start_period: 60s
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=true"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.authc.realms.file.file1.order=0"
    command: bash -c "bin/elasticsearch-users useradd myelastic -r superuser -p changeme | /usr/local/bin/docker-entrypoint.sh eswrapper"
    ports:
      - 9200:9200

  elasticsearch_setup:
    extends:
      file: ${ES_BEATS}/testing/environments/${TESTING_ENVIRONMENT}.yml
      service: elasticsearch
    entrypoint: ["/bin/bash"]
    command:
      - -ec
      - |
        curl --fail --silent --show-error -u admin:testing \
          -H 'Content-Type: application/json' \
          -X PUT http://elasticsearch:9200/_index_template/beats-integration-workflow-replicas \
          -d '{"index_patterns":[".workflows-*"],"priority":500,"template":{"settings":{"index.number_of_replicas":0}}}'
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    depends_on:
      elasticsearch_setup:
        condition: service_completed_successfully
    extends:
      file: ${ES_BEATS}/testing/environments/${TESTING_ENVIRONMENT}.yml
      service: kibana
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u kibana_system_user:testing -f http://localhost:5601/api/status?v8format=true | grep -q '\"overall\":{\"level\":\"available\"'"]
      retries: 1200
      interval: 5s
      start_period: 60s
    command: /usr/local/bin/kibana-docker
