BEAT_NAME?=libbeat
BEAT_PATH?=github.com/elastic/beats/x-pack/${BEAT_NAME}
ES_BEATS?=../..
LICENSE=Elastic
SYSTEM_TESTS?=true
TEST_ENVIRONMENT?=true

# Path to the libbeat Makefile
include $(ES_BEATS)/libbeat/scripts/Makefile

collect update fields config: ;
