BEAT_NAME?=libbeat
BEAT_FULL_NAME?=x-pack/${BEAT_NAME}
BEAT_PATH?=github.com/elastic/beats/${BEAT_FULL_NAME}
ES_BEATS?=../..
LICENSE=Elastic
SYSTEM_TESTS?=true
TEST_ENVIRONMENT?=true

# Path to the libbeat Makefile
include $(ES_BEATS)/libbeat/scripts/Makefile

collect update fields config: ;
