// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package googlecloud

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "googlecloud", asset.ModuleFieldsPri, AssetGooglecloud); err != nil {
		panic(err)
	}
}

// AssetGooglecloud returns asset data.
// This is the base64 encoded gzipped contents of module/googlecloud.
func AssetGooglecloud() string {
	return "eJy8lE+O8jAMxfc9hXesuEAW34ZPYjdCmgOgkJiORRpHsQNiTj+CUTvlTxkEZbyr9frLS5/dKWxwb6B2qQJQ0oAGJnPmOiDMAhcPi2B1zbmZVAAZA1pBAytUWwF4FJcpKXE08K8CAJjPFtCwLwGPj4eaQrQNGnDcpKI//UteW7pPaKDOXFKve+W0tmYc1VIUELVKouTkALeKHpRBPxAcZ/z/9g6CeUuu72JNGLyYE2DrmaKojSfyYYNDsD5wTRl3NoQLwS3oLXAf7jOnhH652ivK0nGJelXfnhU41ncBk3Ub1IeR3QSk8pJ7F6VAn/YwGTfNeS6rcJ7lGUpsjUul5rrsF1L33Ug2L7lpRjtivEcap1FYu0yK41n7xj3hrQs0DYR5x7sRdcf5VUk6pO2Yy9oRn9zWPlMw6mMOpwN/97/ufwUAAP//mnClUQ=="
}
