[[topbeat-configuration-options]]
== Configuration Options

Before modifying configuration settings, make sure you've read
<<topbeat-configuration>>.

The Topbeat configuration file uses http://yaml.org/[YAML] for its syntax.
The configuration options are described in the following sections:

* <<configuration-input>>
* <<configuration-output>>
* <<configuration-shipper>>
* <<configuration-logging>>
* <<configuration-run-options>>

[[configuration-input]]
=== Input

The `input` section specifies how often Topbeat reads server statistics and which
statistics it captures. Here is an example configuration:

[source,yaml]
------------------------------------------------------------------------------
input:
  # In seconds, defines how often to read server statistics
  period: 10

  # Regular expression to match the processes that are monitored
  # By default, all the processes are monitored
  procs: [".*"]

  # Statistics to collect (all enabled by default)
  stats:
    # per system statistics, by default is true
    system: true

    # per process statistics, by default is true
    process: true

    # file system information, by default is true
    filesystem: true

    # cpu usage per core, by default is false
    cpu_per_core: false


------------------------------------------------------------------------------

==== Options

You can specify the following options in the `input` section:

===== period

How often, in seconds, to read system-wide and per-process statistics from your servers. The default is 10.

===== procs

A list of regular expressions to match all the processes that need to be monitored. By
default, all the running processes are monitored.

===== stats

The statistics to collect. You can specify the following settings:

* `system` to export system-wide statistics, including statistics about
system load, CPU usage, memory usage, and swap usage.
* `process` to export per-process statistics, such as the process name,
parent pid, state, pid, CPU usage, and memory usage.
* `filesystem` to export file system statistics, including details about the
mounted disks, such as the total and used disk space, and details about each
disk, such as the device name and the mounting place.
* `cpu_per_core` to export the cpu usage per core. By default is false and it makes sense only if `system: true`. 
The details are grouped under `cpus`. For each core of the server, few details are exported like:

[source,json]
----------------------------------------------------------------------------------
    "cpus": {
      "cpu0": {
        "user": 373170,
        "user_p": 0,
        "nice": 0,
        "system": 463408,
        "system_p": 0,
        "idle": 2904305,
        "iowait": 0,
        "irq": 0,
        "softirq": 0,
        "steal": 0
      },
      ...
  }
----------------------------------------------------------------------------------

include::../../libbeat/docs/outputconfig.asciidoc[]

include::../../libbeat/docs/shipperconfig.asciidoc[]

include::../../libbeat/docs/loggingconfig.asciidoc[]

include::../../libbeat/docs/runconfig.asciidoc[]

