[[filtering-data]]
=== Filtering the Exported Data

When your use case requires only a subset of the data exported by Topbeat, you can <<topbeat-filtering-overview,use Topbeat config options to filter the data>>, or you can <<generic-filtering-overview-topbeat,use the generic filtering provided by libbeat>>.

[[topbeat-filtering-overview]]
==== Topbeat Config Options for Filtering

You can specify the <<procs-option,`procs`>> option in the `input` section of the config file to specify a list of
regular expressions to match the processes that you want to monitor.

By default, all processes are monitored:

[source,yaml]
-------------------------------------------------------------------------------------
topbeat.procs: [".*"]
-------------------------------------------------------------------------------------

[[generic-filtering-overview-topbeat]]
==== Generic Filtering

include::../../libbeat/docs/filtering.asciidoc[]


For example, the following filters configuration reduces the exported fields to include only `load`, `memory`,
`swap`, and `cpu`:

[source,yaml]
-----------------------------------------------------
filters:
 - include_fields:
     fields: ["load", "mem", "swap", "cpu"]
-----------------------------------------------------

The following filters configuration drops all the cpu information if cpu.user_p is lower than 50%.

[source,yaml]
-----------------------------------------------------
filters:
 - drop_fields:
     range:
       lt:
         cpu.user_p: 0.5
     fields: ["cpu"]
-----------------------------------------------------

You can drop the core information details if it's coming from a certain host:

[source,yaml]
---------
filters:
 - drop_fields:
     equals:
       host.hostname: "test"
     fields["core"]
---------

To reduce the volume of `process` type documents, you can filter to export only those that have `proc.cpu.total_p >
70%`:

[source,yaml]
--------
filters:
 - drop_event:
     range:
       gt:
         proc.cpu.total_p: 0.7
--------

See <<configuration-filter,filter configuration options>> for more information.
