// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package traefik

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "traefik", asset.ModuleFieldsPri, AssetTraefik); err != nil {
		panic(err)
	}
}

// AssetTraefik returns asset data.
// This is the base64 encoded zlib format compressed contents of module/traefik.
func AssetTraefik() string {
	return "eJy0kcGK2zAQhu9+ih9fCqWb3n0o7LGHllLaUylBkcaOurJGaMahefuitRPsoKZLYfGcZvD8n755wBOdO2g21PunBlCvgTq03+ZO2wCOxGaf1HPs8KEBgGWKTCfKQkiZf5/xHoGNw8EEEy1ljKTZW2mATIGMUIfBNICQqo+DdPjRioT2Hdqjamp/NkDvKTjpnlMeEM1Ia7ry6TmVRZmntHQqgP8DCWzj1whHMkGP13aN4g5JqU+zDPBBjY/k0GceL4xvZEnA45ePoOgS+6ir/7cCgTrtmnhK6kfaCdnN+EIeOA43gzvwpb4/LwT3V7E+ihaJ8BFClqOTKkomSRyFblbWFb6A5Ouy7+Z296yscSxPG7f/FPMCpFKfp/FAuQi6PFj+ymBOw77o3E3yCiSPJ8pmoCsHSlS50uht5tqp1myiRifZW3Yku7eVgBmPD7/I1jzOg/0r6ESivODBsqPmzwDnIEJs"
}
