// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package azure

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "azure", asset.ModuleFieldsPri, AssetAzure); err != nil {
		panic(err)
	}
}

// AssetAzure returns asset data.
// This is the base64 encoded zlib format compressed contents of module/azure.
func AssetAzure() string {
	return "eJzkmcGO27YTxu9+isGe/v8A8QPsocCmzSGHtEHbnIkxOdaykUiGHDpxn74gJdqyLMt2VuvuothLIonf9xvy00ii38IX2t4D/h09LQBYc033cPeQ/n+3AFAUpNeOtTX38NMCANprobEq1mmIp5ow0D1UuABYa6pVuM8XvgWDDe3F0x9vXbrU2+i6I/0R/VGsG6o8arM7U0Z/oe0361Xv+Ahl+fvzkSBXAw2x13JEtzh6CjZ6SUeGfdwL7IoOBEdSrzX1UYflHpS8dX3zqYrPYBSUNBzsGriHNWqdAOa1TooXWQ9ndwbv4ne0cntXxios3wxGt7Z29RdJHpxqD4opsN4lokHntKm66+/e3F1XRJvYXRkZdjEsIRUSHB5M6ym+Cb+yWFkKAtUkmdSRW4irnYTQ6umefUH48Mu04SCfc1geSBZTdK7WEmcrsqc3VqPSDZmgrTnM4okcnsngpfmbQD7olD24I/D2krB8czX3urbI81J/bGHAE0dvSB3jonNCm6CrRw5n2/vuibYixssI+ss84jPV9AOjZ6GQ+/new42cmODYBT2JHo8tnmTU3I5k1Gm/8bRMJOZsaq5JzvkKUgEd42LInqITGPn8a8ETczM0+a+HxtPXSIGDkDYaXobYDDROJ+OM9e+tMmThae816prUc5i3yhMMMZAvxUejv0aaC+FzID9hHCjkR9KzeP/Rip+tGyM/kuHUVEnNzPDQ1279JnhW3n4L5AXrRpsqCEP8zfovQkWfG/4SN9VcZO9aL+i8oPOC4nURYMh36g3oktF1aJ4k6Q2JG8B1VtfxOW9lCqipbjKBe7vrMNky1jchzE7TcPRdUtZ7hk79vmhP3J89/26enpEAkMtqQE0bqs8hBfKbZydqTSaAHPm19Q0aSe0ipUdLQ431W4Eb1DWuahKrLVOYM02f9rZQbKG1hZ0tZNvLsbubRjivN8i3ou5coXP9UWjponDkJRnGikS+vW7GLl2EvTlk86eW8C/BX42tbV6xNPkikLRG3Yz8w29tWhIftN6LIfpK17U21XN8Y3TSgEZBDGnhFTHq+tIPVBm9JyO3o3N1vAtxwWy964h+7pSXo77OE+N3IW3guZYpfedhk5KRdiaTMqxobT0B4/dximg0p1YjaS6Iz0YzfEqKoEPemc3y5VswdUS2sLVxCf/b2ujh/QNYD5Yf81u7YY+SUx+S9P9x5q8RDWvezkX8kTCkfaHEWrTBRS8fMZBKcNKaEBtSy8EUpxENMfn0lq3Se0RKYjpaUunIa6vG61Dk0HNDhof7f08MYILcix/uBPYBnLcqSp7P+FMrmB1hbX1e/jJ5+TGekmD9bnbHJybfxiJvAsz4NZ5Vz+0C5IsEGTW78eRmQBcX0cZF6HH7Hw7DYRpBnwgkytzcZ07jr71fSkprfGidpjG0mr8nd8agVfr6Xmvypxg4Yj1/d86ycCRbbFOzlhh4duMifNq6Tf5Iwp8e/YOxxU/axkUmsWkG+6a7d4AKF2d3Uid3US/dQZ0oZE85UYAIEmsKxK+jkh3u7vxIbYZRG/LpZwVOb5wvu7SOFgrtREGeKh3Yb19HQYV2oqDusfo66ulgj8pRyLjCQKJr/i+5msJaHlRHxTTWaLb+8q+dCi9zPhYeftkc/6NABbYeqxd9H3eIJ+e1O/8aMjIs5Z8BAI191+g="
}
