// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package azure

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "azure", asset.ModuleFieldsPri, AssetAzure); err != nil {
		panic(err)
	}
}

// AssetAzure returns asset data.
// This is the base64 encoded gzipped contents of module/azure.
func AssetAzure() string {
	return "eJzslcFu2zAMhu95CiLHAO0D5DCgwC477La7QcuMx9WWDJHu4D394NpW5Mi107WHBJgPASLRP79fpMwHeKbuCPin9bQDUNaKjrB/6v/vdwAFifHcKDt7hC87ABhioXZFW/WveKoIhY5Q4g7gxFQVcnwNfACLNZ3F+0e7pg/1rm3GlYUMc5lYSrmm0iPbsDNJPlP32/kiWl8UHp4fPwmeBhukns2C7pTRk7jWG0oSxh6uSDfpgDRk+MQUo17anVnuGpptvO14A2NC6V8HdwKNsBZTX1r8hNzhGFLtYBhLeTwspnX5LzJ6sTUsZmtgUUhWY9OwLcf4/WH/PhND2wQbr7BJ0/S/0uBC17y7TYMUCFVkNOqbKZu0eZDIuPh4zlgQvn1NEhZckxV2dl6nN2q0UZ9ra7PCPLvKEVwCnnNVsS0373L4puWkeB1D7Syr81de6oFVHg//3OinyuFKwEfb/PsACJ609ZaK81kmh2pc3bRK2Ut9YWc+GTYMrpr7hB45U64YyMRgRUJ6H04C7lpxrCJb8hlbUbSGbtvaSAsT7YohTyWL+u4+DE20K4aE/AvfS4FG2HQ2oGKOQhka41p70zdpYoWRNTGTftQ35kX5f1psTAtR57G86SYfEUNX/A0AAP//+O6EXg=="
}
