// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package azure

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "azure", asset.ModuleFieldsPri, AssetAzure); err != nil {
		panic(err)
	}
}

// AssetAzure returns asset data.
// This is the base64 encoded gzipped contents of module/azure.
func AssetAzure() string {
	return "eJzUlb9u2zAQxnc/xcFjgPgBPBQI0KVDt+7CmTor10gkwTulcJ++kPUnlCVTSuPB1mDAIvl9v093JJ/hjU57wL91oA2Aspa0h+1L83+7AchJTGCv7Owevm0AoJ0LlcvrslkSqCQU2kOBG4AjU5nL/jzxGSxW9CHePHryzdTgat+9mXEYy8RSyhUVAdkOI73kG53+uJBH72eF2+fXK8FLG4M0sJnR7R0DiauDoYlhnGGFXa8D4snwkSlGvYw7inzyNBq4nngBo0dploM7gkZYs9aXEW/gPXyGqfYQGAvZPc3ausNvMnox1L7MUmDRlKxC79kW3fzt0/ZzIdq2GWKcYSdN0/yKx5mu+XSbDlIgVJLRqG96N6kPg0TG+dc9Y0H48X1imHNFVtjZcZ2u1GihPmtrk2AebeUIbgKO3mdshYtXlcUNPRxsB1JcB4Lel2zw/N1mfFLbPFo6rmGqjgs4fT1jrKicsb0oBs1y1PmzZmZghe9ZdLq29ySb39qRbH7dr20Q2T399+lyLB0mJnzxbGkCdIyTzjWu8rVS9l5d4I+v34VAyTA32IgflIkAmRgsSUgfI8mAO4zPZLOKbCk0h4uiNXTf0Tpa6GkTgQIVLBpOjxGop00EEgrv/CgF6mCnFzAqHlAoQ2Ncbe96J/Ws0LFOwlTOsrqw/j4uVt7GU+HUBXzvtwP8bAEhkNbBUr67fiCJuoDFXTd5hzh0xb8AAAD///4f3bg="
}
