////
This file is generated! See scripts/docs_collector.py
////

[id="{beatname_lc}-module-audit"]
== Audit Module

The `audit` module reports security-relevant information based on data captured
from the operating system (OS) or services running on the OS. Although this
feature doesn’t provide additional security to your system, it does make it
easier for you to discover and track security policy violations.

[float]
=== Index Management

The data produced by this metricset may contain sensitive information and may
have different access and retention requirements than other data produced by
{beatname_uc}. For these reasons you may wish to store the data in a separate
index. Below is an example configuration demonstrating how to store the data
from the `audit` module in its own index.

[source,yaml]
----
auditbeat.modules:
- module: audit
  metricsets: ["kernel"]

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  indices:
  - index: "auditbeat-%{[beat.version]}-audit-%{+yyyy.MM.dd}"
    when.equals.metricset.module: "audit"
----

The default index template applied by {beatname_uc} will also apply to this
index because the pattern in the template matches the
`auditbeat-%{[beat.version]}` prefix.


[float]
=== Example configuration

The Audit module supports the common configuration options that are
described under <<configuration-{beatname_lc},configuring {beatname_uc}>>. Here
is an example configuration:

[source,yaml]
----
auditbeat.modules:
- module: audit
  metricsets: [kernel]
  kernel.audit_rules: |
    # Define audit rules here.
    # Create file watches (-w) or syscall audits (-a or -A). For example:
    #-w /etc/passwd -p wa -k identity
    #-a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

- module: audit
  metricsets: [file]
  file.paths:
    binaries:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    conf:
    - /etc
  
----

[float]
=== Metricsets

The following metricsets are available:

* <<{beatname_lc}-metricset-audit-kernel,kernel>>

include::audit/kernel.asciidoc[]

