// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package redis

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("packetbeat", "redis", asset.ModuleFieldsPri, AssetRedis); err != nil {
		panic(err)
	}
}

// AssetRedis returns asset data.
// This is the base64 encoded zlib format compressed contents of protos/redis.
func AssetRedis() string {
	return "eJyMkL1uwzAMhHc9xSFzkwfw0L1r0b1grHMs1JIMkg7gty/8kzZBMxRcJJHf3YlHfHFuoIzJAuDJBzY4vC/3QwAirdU0eqqlwWsAgLV3tJFt6lILXlkcXeIQ7RSwn5p19Igimb/yS/k8ssFF6zTuL/fEI+WTls+rDBN/mk8j3eqj505hpVA7eM8tMtqas5SIVCDopywFSolyHoiuahY/hT8hqFr1f+5vz8x6MShtGpybc9kkX+B9sm1baGtxScUW/kFyHUWmmVxuX2PEeb5zMuqVegrhewDBP4pi"
}
