// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package dns

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("packetbeat", "dns", asset.ModuleFieldsPri, AssetDns); err != nil {
		panic(err)
	}
}

// AssetDns returns asset data.
// This is the base64 encoded zlib format compressed contents of protos/dns.
func AssetDns() string {
	return "eJzMl0uP2zYQx+/+FANfmqBdpSnQiw8F0u4WCFAsgmzaQy8ORY4sdimOwiG9q3z6YijJlh9y0kce2MMaEjn8/efF0RXcY7cC43kBEG10uILl9e3dcgFgkHWwbbTkV3B9e3fFLWpbWQ24RR+hsugMFwsYfq0WAABX4FWDo0n5i12LK9gESu3wZLp+uqdyasOFSrGmYKOKdou7NaOdksih8pPnB5w/TV4AvBDubBZ6+M76DcRaRYg1QkBuyRt5xhi2GMAyKA8jQQcVhQODsstQo6zPMiExGrA+W3uXkMVZxWJGWECdAlvya7VV1qnSfRJ5DzXGGgMMx20R3iUMHXBqWwoxaxzPH9gPrGZhvT8+QopBtgHNpxCyi5N2VhLO2IA6cn40xCsStClwQlAHBnvFOw+4roDX8+6g7F3lZuVKQqCPVq+NiuqTat0xjympybM1GHiSsjxNHIAd3qwAXaO+t36zNpYl7p8pXvmsacAOrLDdeBVTQNgqZ42SIABVYzGFblZODMlrFdGsz/jj/9VD3nWZqLKBI/z4/Acou4g8ggZsXQcPGA5DEjCm4NGckbDrExidWbcu8Zo8zoG+qRGwqlBLN4RI7ZXDLbqxCz3BN79dPwWxAuQRGgoITpXoiolFgF8pAD6qpnX4XZYj+759Lg0OlhVRUapQbMgpvykobIql1MVy+uDQnmBJLWQDBiOGxvq+aHvboKlBhipQIy0VmxKNQQOa2m7w3YHB3pisrmNsV8+etal0VnOqKvuYCSbLByUrUI16T77QVKT7M65Wnh8w8FpT8nGyv08RR34z5/bD/BC1PjUlBkEPyJSCRumwFAyDJh+V9fur4K3xXAyHv+2vx2JxBm+4ZyzyCRyVf6GOH4f3woMKQXUjiMRBgbFatKiQrzFApevJzcaSUeR7lx8Ho0cvLhJ/IafuAXaOPTY6sxAa1QGF/M9ThBLBeu2SZKXBFvtBgE4vRE2+spsUdg3qldL3GEtU8bKLCgnznDPeHI0SkeChtrqGWFs+dge0GCSyfLYKhh+FpuYDQJJbl4DkvaR4rsajCJxSnYW5vbuMoJ1ivsSQFwiEzAT/AeTl7RkQY6yoVe6zVdzuxH9bcnvkL1Rye4APlNzJws9VcvuDv5KSmwB9qZKbIHwtJVfE6OYwThM12kY6dMSwVU4wGDV5w+OcecqU061E0ErXByMuQImVTEY2AteUnJHubyxrFQyaAv7EQDKFJmRoUPn9LJu90e85MDikc39Ucb4mL/ri6EviA86Q1YPDynHMGtUXeYVgy5s8W1ked0iRTWMPQ7nl3gHKm33wpzZ3UT7RQG0stpi/Y+fwBedGUmlYdzZXlt8vT5NFjBv6p8P8ywoYYz/XxqA8q77RJkaWyf7u5pcZIfgY10GTma3Qm8eIXtrV+KEBsvq0De5l/fzi+o+b13cz4pJp12zf4/mEmYF4jfmbgcI3DL9fv4JWdY6UATEET6yHsovIT4vF4u8BACsvXY8="
}
