// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package mssql

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "mssql", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzMjz1SwzAQRnud4pv0uYAKOk7BUIjoC6OJ/lgpEN+eiZwBxTY0LuLtvGu9N2+PEweNUMqHV0B11VNj1753CrAsB3G5uhQ1nhQA8JIpLjBW419eVdu1/xGSPXsq4OjobdHttEc0gb+K69QhU+Nd0jnfNguee0yPsm8/qyXWn7zbqX89VfQaXkzIraef0Xfi8JXETm7/WK/zPAJH6awqlTVVd683VJUpxyTBxAPX5C1jNtRZKJ+UNYkzwgPrvgMAAP//+RYFSw=="
}
