# Todo delete before merge to elastic/beats
FROM golang
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN apt-get update
RUN apt-get install -y ca-certificates
EXPOSE 40000
EXPOSE 8080
COPY ./cloudbeat /cloudbeat
COPY ./cloudbeat.yml /cloudbeat.yml
ENTRYPOINT ["/go/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--wd=/", "exec", "/cloudbeat"]
CMD ["--", "-e", "-d", "'*'"]
