{{- $beatHome := printf "%s/%s" "/usr/share" .BeatName }}
{{- $beatBinary := printf "%s/%s" $beatHome .BeatName }}

FROM {{ .From }}

LABEL \
  org.label-schema.schema-version="1.0" \
  org.label-schema.vendor="{{ .BeatVendor }}" \
  org.label-schema.name="{{ .BeatName }}" \
  org.label-schema.version="{{ .Version }}" \
  org.label-schema.url="https://www.elastic.co/products/beats/{{ .BeatName }}" \
  org.label-schema.vcs-url="{{ .BeatURL }}" \
  license="{{ .BeatLicense }}" \
  description="{{ .BeatDescription }}"

ENV ELASTIC_CONTAINER "true"
ENV PATH={{ $beatHome }}:$PATH
{{- range $key, $value := .Env }}
ENV {{ $key }} {{ $value }}
{{- end }}

COPY beat {{ $beatHome }}
COPY docker-entrypoint /usr/local/bin/docker-entrypoint
RUN chmod a+x /usr/local/bin/docker-entrypoint

{{- if .LinuxCapabilities }}
RUN setcap {{ .LinuxCapabilities }} {{ $beatBinary }}
{{- end }}

RUN groupadd --gid 1000 {{ .BeatName }}

WORKDIR {{ $beatHome }}
RUN mkdir data logs && \
    chown -R root:{{ .BeatName }} . && \
    find {{ $beatHome }} -type d -exec chmod 0750 {} \; && \
    find {{ $beatHome }} -type f -exec chmod 0640 {} \; && \
    chmod 0750 {{ $beatBinary }} && \
    chmod 0770 data logs
{{- range $i, $modulesd := .ModulesDirs }}
RUN chmod 0770 {{ $modulesd }}
{{- end }}

{{- if .User }}
RUN useradd -M --uid 1000 --gid 1000 --home {{ $beatHome }} {{ .User }}
USER {{ .User }}
{{- end }}

ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
CMD ["-e"]