// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package kibana

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "kibana", asset.ModuleFieldsPri, AssetKibana); err != nil {
		panic(err)
	}
}

// AssetKibana returns asset data.
// This is the base64 encoded zlib format compressed contents of module/kibana.
func AssetKibana() string {
	return "eJy8l01v4zYTgO/7Kwa5ZF/A0mtnHSfxYYFiuwXaYrtFu+ilKOwRObK4oUgtOXLif1+Qkh0p/ojtptVNImfmmeF8UAnc02oK9ypDg28AWLGmKfy8fnekCT1NYRHeJHnhVMXKmim8fwMArSR8srLW9AYgV6Sln8a1BAyWNAVPbqkEpcZKSp3V5OMyAK8qmgaCB+tkT2QD9LRt4WxdtV92gISnoYDcOqjQeWUWrSeg7cKn7b4uYh/Te2XNTMnN0jNLXwqCH78HmwMXBLUntxYC9N4KhUwSHhQXwIXyQEsynMJHFEUgUAaQmcqKwZGvNXsIn6A26ltNG1VKph0AesSyCmdyMbp6R+PryU1Ct3dZMrqS7xIcX0+S8dVkMhqPbsbD4fCiI7kd3Z63FQo64OtFcFbJtbNx+yEvL3YyS8qx1nwCFi5Jzmz2lQSnYetBvrBhQxgkoZE8AxR9kVl08kzU4wP5jzAnV3fXmZTDZIhDSkYjuklur67zZHIzvhUSb+Tt9e2ZHoRPB30IG17Hi3KVRAVJo+B4YJRyxnYWk9EfhPXEgbVJWyU9cIEM2Ad/QA++QEcS2O5h/fOyzeHLAVyW6O6JlVlc/nU8tCRNTLPc2fJVyR2VNnwKiv89eJXnaW5diXyYWhRU4u70YHYqq5misvCKooghfzlTvnprZhWyKGb0yGQknVCgkd1WfkugAev6szJYKjGFHLXfWwXvOwsAP/3++Rf4NaCBrchh2ONbgSyMnv2B8CAKNAuSkK06MRgAlYpjGRVk+rJN6GqpwgFCkDCYaZJhgjQzLu3RxZmz4YISV6CM0LUkmC9R1zQHNBLmVss/mteHwnpqvIptdYlOkQ+ETwf41rNTZjEAU5cZuQFk1mpCMwB0DlcDsK4F/l8f50tU3kxeQEfg2bqGfj7ztnaC5pDVDMYylFhVJOHtvH8sc7CmiVZrAryFUj2GVFpVIahogrjA2lNUEkIlrMm1Euz7QJ/aZS6oBPQwb3TOmw42b6O7sax8JPN1niuhyPAUPmr0rIQndKIAz0prcBSUhL2m7W0Qg+3B16IIdpoAdmCeJ2tqq4OF9nSmFblQmCFHTEy2zTntKSZHlUZBpxdQWiEXe6l+++EDTO6Go7YirDJMrqlu2iT6S2z/jzfPE9GM/XxUdfdwv3uqwsqRJ8MhC7eKdZ2MOyu148Q20JnRQtMptNjzQ5M/BqEXx461E+ZqzQUZViJm1qxydqkkuYOJ2JeBtczWbQDbq+8h6gy9EqOzeV+8J+5jjY3ubOCzeR2hLg8C95vLM/wo3lzHHgolCshrnSsdpsEx7AZZLU8oNW3tfV2dDN2ItbD/Dedia2/3p3ELuj/Pn/4UQStDvXnx/Jexa5Zx4XsL+zhfJOhTLOJ4wsWzwbW5uzMyvZ7dD7VzoRVGteEat+tSsbZdEuNO01utNzzNx9luuL36U0ff0oJQktsd3lyHn2lD8pAKf6SKvwMAAP//LPYZYw=="
}
