This is the https://www.oracle.com[Oracle] module for Metricbeat. It is an alpha release and under active development with feedback from the community. A single Metricset for Tablespace monitoring is added so the community can start gathering metrics from their nodes and contributing to the module.

[float]
== Compatibility
The nature of Oracle makes it a bit tricky when it comes to testing and we want to ensure that the module is 100% stable. Currently, we are testing with version 12c R2 by using the store/oracle/database-enterprise:12.2.0.1 Docker image downloaded directly from the https://hub.docker.com/_/oracle-database-enterprise-edition[Oracle Docker Hub repository]
which is based on 5.0.13-arch1-1-ARCH Arch Linux. This is important, module has only been tested with the mentioned image in Linux environments.

[float]
== Metricsets

The following Metricset is included in the module:

=== `tablespaces`

Includes information about data files and temp files, grouped by Tablespace with free space available, used space, status of the data files, status of the Tablespace, etc.
