// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package file_integrity

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("auditbeat", "file_integrity", asset.ModuleFieldsPri, AssetFileIntegrity); err != nil {
		panic(err)
	}
}

// AssetFileIntegrity returns asset data.
// This is the base64 encoded zlib format compressed contents of module/file_integrity.
func AssetFileIntegrity() string {
	return "eJyUkcFu6jAQRff5ivsD8BRDIpTFk3jSq6jaXbtghxw8xBYmQbZpyd9XTNMCElLsZUY3x2fmTrCnvsLOWNqYNlDjTOgzIJhgqcKTsYTnm7kiv3XmGEzXVnjX5AnSEYIm7AxZ5dFQS04GUqj7YX7LxqFTJ0vTDMMPVQZM0MoDVdDS6wwAQn+kCo3rTkf+vnv2L4+AlfSaPLrd7zPTi9JlI89W0jadM0EfGO8hW8XRD2lPxJGBdBlqOoPabadIQZmGfBhy04xTV9urb23lnkS9EUX5Q2LxPfWfnVPD7E7+3+vy5b+oJ6Ioed07/ewhfbaYp9Jni3ksvchFKr3IxRjdaylEtPbbainEqLHXcrZJo3I+jhtf4Td3vD/mJpTH3IjmmJtQG3PjOitykXjhIhd/4m7M7KQrM3v8zuezLqOV1+vykexXAAAA//+VAnyT"
}
