// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package file_integrity

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("auditbeat", "file_integrity", asset.ModuleFieldsPri, AssetFileIntegrity); err != nil {
		panic(err)
	}
}

// AssetFileIntegrity returns asset data.
// This is the base64 encoded zlib format compressed contents of module/file_integrity.
func AssetFileIntegrity() string {
	return "eJykk0GP2jAQhe/5Fe8PQBXvJlrlUImqrajanrYHbsjBQ2zhxMh2gPz7Km5KQEKKwx4zmnzved7MAgfqCuyVpq1qPFVW+S4BvPKaCnxXmvDjpi7I7aw6emWaAn8kOQK3BC8Je0VaOFTUkOWeBMpuqN+yURvRalomGH4oEmCBhtdUQHInEwDw3ZEKVNa0x/B9J/s5lIA1d5IczP4qs+wt9S9ywRXXlbHKyzrgHXgjQuuJ65ZCy0Dqi5IuoGZnBAkIVZHzQ98yCV2j29FvqfmBWLllWf6fFIwfqDsbK4banfkvv1Y/v7FywbI8PPfOfvKQ/vL2Opf+8vYaS89SNpeepWyKXotsIJgT2bNVngp421Ks1u+v2ZSGkzz9mMj7epVGqDAWHcD7esXY5Ox75nVlnvcesUNO8nF9nleK2KdeaTtvUqE/jht/YP+4cZOZc1qBGzuHGUcVuBEX5SQfqc8nGa00M8ssZZ/i0gzsWXkG9nSil4vMoy1vNvkjs38DAAD//xoUE8I="
}
