Filebeat supports a `logs` Builder for modules:

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
filebeat.autodiscover:
  providers:
    - type: kubernetes
      builders:
        - type: logs
-------------------------------------------------------------------------------------

This configuration enables the `logs` Builder. The `logs` builder looks for hints
in the form of Kubernetes annotations or Docker labels which have the prefix `co.elastic.logs`.

[float]
==== Kubernetes
Kubernetes pods can annotate themselves with hints for the `logs` builder to be able to spin up
Filebeat inputs:

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
annotations:
  co.elastic.logs/multiline.pattern: '^\['
  co.elastic.logs/multiline.negate: 'true'
  co.elastic.logs/multiline.match: after
  co.elastic.logs.sidecar/exlude_lines: '^DBG'
-------------------------------------------------------------------------------------

The above annotations are used to add additional information to the input that is generated. The hints
generated convey the multiline configuration to use and the lines to exclude in the container which is
named `sidecar`. Hints can also be provided for the following input configuration:
parameters:

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
include_lines
-------------------------------------------------------------------------------------

[float]
==== Docker
Docker allows providing hints through Docker labels. When containers are spun up the Builder understands
labels that convey hints to convey additional configuration to the input.

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
  co.elastic.logs/multiline.pattern: '^\['
  co.elastic.logs/multiline.negate: 'true'
  co.elastic.logs/multiline.match: after
-------------------------------------------------------------------------------------

The above labels would allow Filebeat to add a multiline pattern to the input that would be
generated for the logs of the running container.
