[[filebeat-configuration]]
=== Configure the {beatname_uc} input manually

//TODO::Move this information to the config topic about inputs.

This guide describes how to configure {beatname_uc} manually. When possible,
use <<filebeat-modules-overview,Filebeat modules>> for the fastest getting
started experience.

include::{libbeat-dir}/shared/configuring-intro.asciidoc[]

Here is a sample of the `filebeat` section of the `filebeat.yml` file. Filebeat uses predefined
default values for most configuration options.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    #- c:\programdata\elasticsearch\logs\*
-------------------------------------------------------------------------------------

To configure Filebeat:

. Define the path (or paths) to your log files.
+
For the most basic Filebeat configuration, you can define a single input with a single path. For example:
+
[source,yaml]
-------------------------------------------------------------------------------------
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
-------------------------------------------------------------------------------------
+
The input in this example harvests all files in the path `/var/log/*.log`, which means
that Filebeat will harvest all files in the directory `/var/log/` that end with `.log`. All patterns supported
by https://golang.org/pkg/path/filepath/#Glob[Go Glob] are also supported here.
+
To fetch all files from a predefined level of subdirectories, the following pattern can be used:
`/var/log/*/*.log`. This fetches all `.log` files from the subfolders of `/var/log`. It does not
fetch log files from the `/var/log` folder itself. Currently it is not possible to recursively
fetch all files in all subdirectories of a directory.

