// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package kibana

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "kibana", asset.ModuleFieldsPri, AssetKibana); err != nil {
		panic(err)
	}
}

// AssetKibana returns asset data.
// This is the base64 encoded gzipped contents of module/kibana.
func AssetKibana() string {
	return "eJzMWE2O4zYT3fsUBW9m060DeDHAh28CJAi6J5hMI4sgMMpi2WKaIhVWyd3O6QNSki3LlC1nbEy0Mijx1atXf6Qf4ZV2C3jVK7Q4AxAthhYw/zkuzGcAijj3uhLt7AI+zgAAmpdQOlUbmgFw4bwsc2fXerOANRoOq54MIdMCNgGYSUTbDS/g9zmzmT/AvBCp5n/MANaajOJFxH4EiyX1GIVHdlXA8a6u2pUjVl8/f/rcrveh+nAsKJzVjBvKwsr+gw4cjUburVYoRcci6+/WVtF7Gv8EtM/4hPXH3ou9phEH0CrwtX0UXRKUJF7nnPU+P5a2e4a+9/lF7kdvxjiOIfXRjjUYIr7S7s15lXg/FrUB11oPN6djBPs4Mfmtzik72VjqjcfGnvh6qMCZeMAhJtqyoM0JXl5++pRkPMioS1JcafYE/VwYvsHuM5YEbt3a/8CgrZC3aBKGOgqFYxkW1I3dDyZGJRCPlqvQflApTzxMj6mJk959i+wJFsh/4L0fsboD5aRDW/KsnZ3sxjQSadRjCdLfnJNg3/wsVlw4SZJeOWcIh7AXaP9WkBTkQQrqXFjV2ijQDLi316ylKQlKnU6GWyRlCCehkSJlqOOQO5vX3pONs9FSHsDTnIyzmyuLtS5X5EO55kaTFeiZgBIVgbgoX5N/GTw7IZACBVbevTF5hhwtMFkFZW1EV4aAdfiJllzNR4jiwNNfNbH0Po7IgMwUZpaAszk9xPSWgnYR3tNjzQTEgiujuSDVh82SulXe5WOVnJpWF5T6pYHr5uikUddRoW2InnGuWioyuMvK4f6OGOdoSC3XxuGwDi4yBPgh2IFgB6Id0BZKbYxmyp1VQ6MdvZJK53dZQTjU5JxeE/h0mgXkEeEunxLECZpstRM63Xsm8SO08yXKAsY2X3QA4Guw3jiAxrgchVRI4za7gsJp9MORidR3Y/9j4B0YwGo3nTLrv2lpdKnluxF/wvcMnFHAFeYUGR3r/+wUZX9y59TDhEBU4RycKr0L7kyg+xKxQxvtiTxaeR2jthXeqkMBfGl7a+5qK1d1qgMppbltrfcQ6jBvWue5GSZv5Klnmk6P/Uft4A7MmkK3J/xGIseVs0zLEPZbxe9LCwoB9LpBc2CG2819Uvx/W/K4ob3rkeWFAdMbMfh+H1pP+K7LupxIa/Rcd/VF+9eI0Ibjm+7U97/1pc9H/9n7cSCWptzeLbKmSu9zuWlbQHavS07Mm8yFajIm/iV0++i36NHYSPTT3eVf966nBu60HmBCz5p0w4EbNIv/N1Z6BsevEXA6qMcppc/Hkzh1MzvESrMM/qLrnjEJYfLkhkv6TeQLiVnZH9znFYUJk/yeTI/I/RMAAP//oUjITA=="
}
