// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package kibana

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "kibana", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzEl82O2zYQx+9+isFecsnqAXwoULQBWhRZFGkXPRSFMSbHFrsUqXJGXrtPX1AftixTttzIiA5BVpL/85tv8Rne6LCEN7NGhwsAMWJpCU+/1DeeFgCaWAVTivFuCd8tAACah1B4XVlaAHDug6yUdxuzXcIGLce7gSwh0xLWJFGaScS4LS/hzydm+/TXAmBjyGpe1qrP4LCgHku85FDSErbBV2V7J8FzrtPXYkHh492U3Khkc7Wu1jqATkOo3LOYgqAgCUZx1nt96HF3Den6hFVl9NmDDvKNDu8+DJ9dQe3hGseCThG8vv78Y9Js/DdpVmgvX2fzQrqzaZym/Xy+vmBB4Det/Q8MxgkFhzZhqEPIPQ+9mzHaUX3UewnouIyNgloHYp6dgynsKHzgI0ddsNFkEmhHgY13s2OkdI/96LDk3KdzsPbeEg6Bbhj9IyfJKYDk1AGsK2M1GAY82mvupZEEpZo/GV1RxHQQWslThjoGZSsWCqt5h0Fs/tggMTSfLLIYxYRB5Z09EA/vuVF5B628c6TkbKj1KL1TVQjk6lkfXzTepSNnvdve2c1VsaYQcZU15AR6JqBATRE2etJUeQYvXggkR4F18O9MgUGhAyanoaismNISsIn/RUe+4jNF8RDon4pY4stG6pdrZUBmisNewDtFH+smkpwOtXyg54oJiAXX1nBOui+bjlsZvBrr9+EqmhCpXxu5bgENnqd2TQ/lor6uZOwmyYnlVGiD8h/hoF2sIut9udJk8ZAVQz86LlZoSa821uNwakzg+xTtQLQDtR0wDgpjrWFS3umh0Q6voMKHQ5YTDnNzLW93xCsqjyRwLIW9TeIFbbY+CF3+9mo6ATY+FChLGPvxTQcAfo/WGwfQWq9QSMd2aqs8RjitfvziYdLfjP6nyB0JYH2YjszmX1pZUxj5ZuCfcZ+Btxq4REU10Xn8X7ym7G/unPo4IRFl/JBNtd4NdybgvtbacSj0gjzaeR1RO5LnmpQAX9oZr3zl5K6JeYLShru9+IBAnfZe6zw3S+2dAvVM0+XcPhsHDyBrGt1d8I1kjkvvmFYx7XPl70srClH0voV3IsPd9jEl/v2OAm7p6HpNeWPB9FYM7h+D9Rn3pqiKiVijX8F3n5R/qxXadHzloXj0dDrLMS2qp7/UHnsYj+ppu+2RKWua7VEnsraX0whNAWQ+FrW1Wfxz/hS06rWxkRSkm/x/j5DPjdxlWcKE0THpwAMz9OwPjZWewfFTBVzuy3Gk9GfqJKZudcZcmfrseMkxHkKYvEDhVvwm8kJiZfX35/WIwoSF+kjSM7j/AgAA//9sJ4H2"
}
