[[processor-translate-guid]]
=== Translate GUID

++++
<titleabbrev>translate_guid</titleabbrev>
++++

The `translate_guid` processor translates an LDAP Global Unique Identifier (GUID)
into its common name.

Every object on an Active Directory is issued a GUID. Internal processes
refer to their GUID's rather than the object's name and these values
sometimes appear in logs.

If the GUID is invalid (malformed) or does not map to any object on the domain
then this will result in the processor returning an error unless `ignore_failure`
is set.

[source,yaml]
----
processors:
  - translate_guid:
      field: winlog.event_data.ObjectGuid
      ldap_address: "ldap://"
      ldap_base_dn: "dc=example,dc=com"
      ignore_missing: true
      ignore_failure: true
----

The `translate_guid` processor has the following configuration settings:

.Translate GUID options
[options="header"]
|======
| Name                     | Required    | Default    | Description
| `field`                  | yes      |            | Source field containing a GUID.
| `target_field`           | no       |            | Target field for the common name. If not set it will be replaced in place.
| `ldap_address`           | yes      |            | LDAP server address. eg: `ldap://ds.example.com:389`
| `ldap_base_dn`           | yes      |            | LDAP base DN. eg: `dc=example,dc=com`
| `ldap_user`              | no       |            | LDAP user.
| `ldap_password`          | no       |            | LDAP password.
| `ldap_search_time_limit` | no       | 30         | LDAP search time limit in seconds.
| `ldap_ssl`*              | no       | 30         | LDAP TLS/SSL connection settings.
| `ignore_missing`         | no       | false      | Ignore errors when the source field is missing.
| `ignore_failure`         | no       | false      | Ignore all errors produced by the processor.
|======

&#42; Also see <<configuration-ssl>> for a full description of the `ldap_ssl` options.

If the searches are slow or you expect a high amount of GUID's to be found, consider using a cache processor to speed processing:


[source,yaml]
-------------------------------------------------------------------------------
processors:
  - cache:
      backend:
        memory:
          id: ldapguids
      get:
        key_field: guid.cn
        target_field: winlog.common_name
      ignore_missing: true
  - if:
      not:
        - has_fields: winlog.common_name
    then:
      - translate_guid:
          field: winlog.event_data.ObjectGuid
          target_field: winlog.common_name
          ldap_address: "ldap://"
          ldap_base_dn: "dc=example,dc=com"
      - cache:
          backend:
            memory:
              id: ldapguids
            capacity: 10000
          put:
            key_field: guid.cn
            value_field: winlog.common_name
-------------------------------------------------------------------------------