////
This file is generated! See scripts/docs_collector.py
////

:edit_url: https://github.com/elastic/beats/edit/main/x-pack/filebeat/module/windows/_meta/docs.asciidoc

[[filebeat-module-windows]]
[role="xpack"]

:modulename: windows
:has-dashboards: true

== Windows module

include::{libbeat-dir}/shared/integration-link.asciidoc[]

The Windows module allows you to monitor the Windows OS, services, applications, and more.

Use the Windows module to collect events from your machine.
Then visualize that data in Kibana, create alerts to notify you if something goes wrong, and reference data when troubleshooting an issue.

include::../include/gs-link.asciidoc[]

[float]
=== Compatibility

[float]
==== Windows Event ID clause limit

If you specify more than 22 query conditions (event IDs or event ID ranges), some
versions of Windows will prevent the integration from reading the event log due to
limits in the query system. If this occurs, a similar warning as shown below:

```
The specified query is invalid.
```

In some cases, the limit may be lower than 22 conditions. For instance, using a
mixture of ranges and single event IDs, along with an additional parameter such
as `ignore older`, results in a limit of 21 conditions.

If you have more than 22 conditions, you can work around this Windows limitation
by using a drop_event processor to do the filtering after filebeat has received
the events from Windows. The filter shown below is equivalent to
`event_id: 903, 1024, 2000-2004, 4624` but can be expanded beyond 22 event IDs.

["source","yaml",subs="attributes"]
-----
- drop_event.when.not.or:
  - equals.winlog.event_id: "903"
  - equals.winlog.event_id: "1024"
  - equals.winlog.event_id: "4624"
  - range:
      winlog.event_id.gte: 2000
      winlog.event_id.lte: 2004
-----

include::../include/config-option-intro.asciidoc[]

[float]
==== `powershell` fileset settings

Example config:

["source","yaml",subs="attributes"]
-----
- module: windows
  powershell:
    enabled: false
    var:
      id: windows-module-powershell
      name: Windows PowerShell
      event_id: 400, 403, 600, 800
  powershell_operational:
    enabled: false
    var:
      id: windows-module-powershell-operational
      name: Microsoft-Windows-PowerShell/Operational
      event_id: 4103, 4104, 4105, 4106
-----

include::../include/timezone-support.asciidoc[]

:has-dashboards!:

:fileset_ex!:

:modulename!:


[float]
=== Fields

For a description of each field in the module, see the
<<exported-fields-windows,exported fields>> section.

:edit_url!: