Metricbeat supports a autodiscover based on hints from the provider. The `hints` system looks for
hints in Kubernetes annotations or Docker labels which have the prefix `co.elastic.metrics`. Hints tell
Metricbeat how to get metrics for the given container. This is the full list of supported hints:

[float]
===== `co.elastic.metrics.module`

Metricbeat module to use to fetch metrics.

[float]
===== `co.elastic.metrics.hosts`

Hosts setting, as documented by the configured module. Hosts can include `${data.host}` and `${data.port}`
values from the autodiscover event, ie: `${data.host}:80`.

[float]
===== `co.elastic.metrics.metricsets`

List of metricsets to use, comma separated. If no metricsets are provided, default metricsets for the module
will be used.

[float]
===== `co.elastic.metrics.period`

The time interval for metrics retrieval, ie: 10s

[float]
===== `co.elastic.metrics.timeout`

Metrics retrieval timeout, default: 3s

[float]
===== `co.elastic.metrics.ssl.*`

SSL parameters, as seen in <<configuration-ssl>>.



[float]
=== Kubernetes

Docker autodiscover provider supports hints in labels, to enable it just set `hints.enabled`:

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
metricbeat.autodiscover:
  providers:
    - type: kubernetes
      hints.enabled: true
-------------------------------------------------------------------------------------

This configuration enables the `hints` autodiscover for Kubernetes. The `hints` system looks for
hints in Kubernetes annotations or Docker labels which have the prefix `co.elastic.metrics`.

You can annotate Kubernetes Pods with useful info to spin up Metricbeat modules:

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
annotations:
  co.elastic.metrics/module: prometheus
  co.elastic.metrics/metricsets: collector
  co.elastic.metrics/hosts: '${data.host}:9090'
  co.elastic.metrics/period: 1m
-------------------------------------------------------------------------------------

The above annotations are used to spin up a Prometheus collector metricset and it polls the
parent container on port `9090` at a 1 minute interval.

[float]
===== Multiple containers

When a Pod has multiple containers, these settings are shared. To set hints specific to a container in
the pod you can put the container name in the hint.

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
annotations:
  co.elastic.metrics/module: apache
  co.elastic.metrics/hosts: '${data.host}:80'
  co.elastic.metrics.sidecar/hosts: '${data.host}:8080'
-------------------------------------------------------------------------------------

For example, these hints configure a common behavior for all containers in the Pod, and sets a specific
`hosts` hint for the container called `sidecar`.

[float]
=== Docker

Docker autodiscover provider supports hints in labels, to enable it just set `hints.enabled`:

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
-------------------------------------------------------------------------------------

You can label Docker containers with useful info to spin up Metricbeat modules, for example:

["source","yaml",subs="attributes"]
-------------------------------------------------------------------------------------
  co.elastic.metrics/module: nginx
  co.elastic.metrics/metricsets: stubstatus
  co.elastic.metrics/hosts: '${data.host}:80'
  co.elastic.metrics/period: 10s
-------------------------------------------------------------------------------------

The above labels would allow Metricbeat to configure a Prometheus collector to poll port `9090`
of the Docker container every 1 minute.
