[[configuration-metricbeat]]
== Specify which modules to run

To enable specific modules and metricsets, you add entries to the `modules` list in of the +{beatname_lc}.yml+ config file. Each entry in the list begins with a dash (-) and is followed by settings for that <<metricbeat-modules,module>>.

//REVIWERS: Using "list" here instead of "array" to match the terminology we use in the Platform Ref to describe the config file

The following example shows a basic configuration for the Apache module:

[source,yaml]
----
metricbeat:
  modules:
    - module: apache
      metricsets: ["status"]
      hosts: ["http://127.0.0.1/"]
      period: 10s
      enabled: true
      fields:
        dc: west
      tags: ["tag"]
      processors:
        ....
----


The following example shows a configuration where the Apache and MySQL modules are enabled:

[source,yaml]
------------------------------------------------------------------------------
metricbeat.modules:

#---------------------------- Apache Status Module ---------------------------
- module: apache
  metricsets: ["status"]
  enabled: true
  period: 1s
  hosts: ["http://127.0.0.1/"]

#---------------------------- MySQL Status Module ----------------------------
- module: mysql
  metricsets: ["status"]
  enabled: true
  period: 2s
  hosts: ["root@tcp(127.0.0.1:3306)/"]
------------------------------------------------------------------------------

[float]
== Configuration combinations

You can specify a configuration that uses different combinations of modules, metricsets, periods, and hosts. In the following example, the Redis host is crawled for `stats` information every second because this is critical data, but the full list of Apache metricsets is only fetched every 30 seconds because the metrics are less critical.

[source,yaml]
----
metricbeat:
  modules:
    - module: redis
      metricsets: ["info"]
      hosts: ["host1"]
      period: 1s
      enabled: true
    - module: apache
      metricsets: ["info"]
      hosts: ["host1"]
      period: 30s
      enabled: true
----

For a module with multiple metricsets defined, it's possible to define the module twice and specify
a different period to use for each metricset. For the following example, the `set1` metricset will be fetched every
10 seconds, while the `set2` metricset will be fetched every 2 minutes:

[source,yaml]
----
metricbeat:
  modules:
    - module: example
      metricsets: ["set1"]
      hosts: ["host1"]
      period: 10s
    - module: example
      metricsets: ["set2"]
      hosts: ["host1"]
      period: 2m
----


[float]
=== Standard config options

You can specify the following options for any Metricbeat module. Some modules
require additional configuration settings. See the <<metricbeat-modules>> section for more information.

[float]
==== `module`

The name of the module to run. For documentation about each module, see the <<metricbeat-modules>> section.

[float]
==== `metricsets`

A list of metricsets to execute. Make sure that you only list metricsets
that are available in the module. It is not possible to reference metricsets from other modules. For a list of available metricsets, see the documentation for the module.

[float]
==== `enabled`

A Boolean value that specifies whether the module is enabled. If you use the default config file, `metricbeat.yml`,
the System module is enabled (set to `enabled: true`) by default. If the `enabled` option is missing from the
configuration block, the module is enabled by default.

[float]
[[metricset-period]]
==== `period`

How often the metricsets are executed. If a system is not reachable, Metricbeat returns an error for each period. This setting is required.

[float]
==== `hosts`

A list of hosts to fetch information from. For some metricsets, such as the System module, this setting is optional.

[float]
==== `fields`

A dictionary of fields that will be sent with the metricset event. This setting is optional.

[float]
==== `tags`

A list of tags that will be sent with the metricset event. This setting is optional.

[float]
==== `processors`

A list of processors to apply to the data generated by the metricset.

See <<filtering-and-enhancing-data>> for information about specifying
processors in your config.

