[[filtering-and-enhancing-data]]
== Filtering and Enhancing the Exported Data

Your use case might require only a subset of the data exported by Metricbeat, or
you might need to enhance the exported data (for example, by adding metadata).
Metricbeat provides a couple of options for filtering and enhancing exported
data. You can:

* <<metricbeat-filtering-overview,Define filters at the module level>> to
configure each module to include or exclude specific events or fields.
* <<defining-processors,Define processors>> to configure global processing
across all data exported by Metricbeat.

[float]
[[metricbeat-filtering-overview]]
=== Filtering at the Metricbeat Module Level

Each module accepts a list of filters in its configuration. These filters are
applied to the data generated by the module. These filters are applied to the
module data prior to the addition of the common Beat fields like `beat.hostname`
and `type` so they can only be used to filter fields from the module.

The following example reduces the exported fields of the Redis module to
include only the `redis.info.memory` fields.

[source,yaml]
----
metricbeat.modules:
- module: redis
  metricsets: ["info"]
  period: 1s
  hosts: ["127.0.0.1:6379"]
  enabled: true
  filters:
    - include_fields:
       fields: ['memory']
----

[float]
[[defining-processors]]
=== Defining Processors

include::../../libbeat/docs/processors.asciidoc[]

For example, the following configuration reduces the exported fields by
dropping the `beat.name` and `beat.hostname` fields under `beat` from all documents.

[source, yaml]
----
processors:
 - drop_fields:
    fields: ['beat']
----

See <<configuration-processors>> for more information.
