[[metricbeat-overview]]
== Overview

Metricbeat is a lightweight shipper that you can install on your servers to
periodically collect metrics from the operating system and from services running
on the server. Metricbeat takes the metrics and statistics that it collects and
ships them to the output that you specify, such as Elasticsearch or Logstash.

Metricbeat helps you monitor your servers by collecting metrics from the system
and the following services:

  * {metricbeat}/metricbeat-module-apache.html[Apache]
  * {metricbeat}/metricbeat-module-haproxy.html[HAProxy]
  * {metricbeat}/metricbeat-module-mongodb.html[MongoDB]
  * {metricbeat}/metricbeat-module-mysql.html[MySQL]
  * {metricbeat}/metricbeat-module-nginx.html[Nginx]
  * {metricbeat}/metricbeat-module-postgresql.html[PostgreSQL]
  * {metricbeat}/metricbeat-module-redis.html[Redis]
  * {metricbeat}/metricbeat-module-system.html[System]
  * {metricbeat}/metricbeat-module-zookeeper.html[Zookeeper]

Metricbeat can insert the collected metrics directly into Elasticsearch
or send them to Logstash, Redis, or Kafka.
