[[configuration-metricbeat]]
=== Metricbeat

The `metricbeat.modules` section contains an array with the enabled modules.
Please see the <<metricbeat-modules>> section for details about the available
modules and their configuration options.


[source,yaml]
------------------------------------------------------------------------------
metricbeat.modules:

#---------------------------- Apache Status Module ---------------------------
- module: apache
  metricsets: ["status"]
  enabled: true
  period: 1s
  filters:

  # Apache hosts
  hosts: ["http://127.0.0.1/"]

#---------------------------- MySQL Status Module ----------------------------
- module: mysql
  metricsets: ["status"]
  enabled: true
  period: 2s

  # Host DSN should be defined as "tcp(127.0.0.1:3306)/"
  # The username and password can either be set in the DSN or for all hosts in username and password config option
  hosts: ["root@tcp(127.0.0.1:3306)/"]
------------------------------------------------------------------------------


==== Metricbeat Options

You can specify the following options in the `metricbeat` section. These options
are the same for all modules. Each module can have its specific additional configurations.
For more details check the docs of each module.

===== module

The name of module that should be enabled.

===== metricset

A list of metricsets that should be enabled for the module. Make sure to only list metricsets
which are available in the module. It is not possible to reference metricsets from other modules.

===== hosts

A list of hosts to fetch information from. For some metricsets this is optional.

===== enabled

Boolean value if a the configuration block is enabled. If the configuration option is missing, it
is enabled by default.

===== period

Period on how often the metricsets should be called. This is required.



===== filters

Each module configuration can have its own filters. More details on how to configure filters can be found here:
<<configuration-filter>>.

===== tags

List of tags

===== fields

Dict of fields



include::../../../../libbeat/docs/outputconfig.asciidoc[]

include::../../../../libbeat/docs/shipperconfig.asciidoc[]

include::../../../../libbeat/docs/shared-path-config.asciidoc[]

include::../../../../libbeat/docs/loggingconfig.asciidoc[]

include::../../../../libbeat/docs/runconfig.asciidoc[]

include::../../../../libbeat/docs/filteringconfig.asciidoc[]
