[[append]]
=== Append Processor

++++
<titleabbrev>append_processor</titleabbrev>
++++

The `append_processor` processor appends static values and values from the listed fields to target field.

`target_field`:: The field in which you want to append the data.
`fields`:: () List of fields from which you want to copy data from. If the value is of a concrete type it will be appended directly to the target. 
However, if the value is an array, all the elements of the array are pushed individually to the target field.
`values`:: (Optional) List of static values you want to append to target field.
`ignore_empty_values`:: (Optional) If set to `true`, all the `""` and `nil` are omitted from being appended to the target field.  
`fail_on_error`:: (Optional) If set to `true` and an error occurs, the changes are reverted and the original is returned. If set to `false`,
processing continues if an error occurs. Default is `true`.
`ignore_missing`:: (Optional) Indicates whether to ignore events that lack the source
                   field. The default is `false`, which will fail processing of
                   an event if a field is missing.

note: If you want to use `fields` parameter with fields under `message`, make sure you use `decode_json_fields` first with `target: ""`.

For example, this configuration:

[source,yaml]
------------------------------------------------------------------------------
processors:
  - decode_json_fields:
      fields: message
      target: ""
  - append_processor:
      target_field: my-target-field
      fields: 
        - concrete.field
        - array.one
      values: 
        - static-value
        - ""
      ignore_missing: true
      fail_on_error: true
      ignore_empty_values: true
------------------------------------------------------------------------------

Copies the values of `concrete.field`, `array.one` from response field to `my-target-field`:

[source,json]
-------------------------------------------------------------------------------
{
  "message": "my-interesting-message",
  "event": {
      "original": "my-interesting-message"
  }
}
-------------------------------------------------------------------------------
