[[lowercase]]
=== Lowercase fields in events

++++
<titleabbrev>lowercase</titleabbrev>
++++

The `lowercase` processor specifies a list of fields that should be converted to lowercase. This transformation applies to keys that match the specified fields. Matching is performed case-insensitively. 


==== Examples: 

1. Default scenario 

[source,yaml]
----
processors:
  - rename:
      fields:
        - "ab.cd"
      ignore_missing: false
      fail_on_error: true
      full_path: true
----
[source,json]
----
// Input
{
  "AB": {"CD":"data"},
  "CD": {"ef":"data"} 
}


// output
{
  "ab": {"cd":"data"},  // abcd is lowercased
  "CD": {"ef":"data"}  
}
----

[start=2]
2. When `full_path` is false

[source,yaml]
----
processors:
  - rename:
      fields:
        - "ab.cd"
      ignore_missing: false
      fail_on_error: true
      alter_full_field: false
----

[source,json]
----
// Input
{
  "AB": {"CD":"data"},
  "CD": {"ef":"data"} 
}


// output
{
  "AB": {"cd":"data"},  // only cd is lowercased
  "CD": {"ef":"data"}  
}
----

[start=2]
2. In case of non unique path to the key

[source,yaml]
----
processors:
  - rename:
      fields:
        - "ab"
      ignore_missing: false
      fail_on_error: true
      alter_full_field: true
----

[source,json]
----
// Input
{
  "ab": "first",
  "aB": "second"
}

// Output
{
  "ab": "first",
  "aB": "second",
  "err": "... Error: key collision"
}
----

==== Configuration:

The `lowercase` processor has the following configuration settings:

`fields`:: The field names to lowercase. The match is case-insensitive, e.g. `a.b.c.d` would match `A.b.C.d` or `A.B.C.D`.
`ignore_missing`:: (Optional) Indicates whether to ignore events that lack the source field.
                    The default is `false`, which will fail processing of an event if a field is missing.
`fail_on_error`:: (Optional) If set to `true` and an error occurs, the changes are reverted and the original event is returned.
                    If set to `false`, processing continues if an error occurs. Default is `true`.
`alter_full_path`:: (Optional) If set to `true`, the entire key path is lowercased. If set to `false` only the final part of the key path is lowercased. Default is true    

                                  

See <<conditions>> for a list of supported conditions.
