// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package zookeeper

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "zookeeper", asset.ModuleFieldsPri, AssetZookeeper); err != nil {
		panic(err)
	}
}

// AssetZookeeper returns asset data.
// This is the base64 encoded gzipped contents of module/zookeeper.
func AssetZookeeper() string {
	return "eJyslEFvGjEQhe/8iidOiZSQO4dIUY5tpahJL71Uw/oBI4y99dhB5NdX3rJkCVRRpfUJzezM9+YZzy023M/xFuOGbJkmQNbsOcf0Z4xfuth0AiR6inGOBbNMAEdrkrZZY5jjfgIAx+/xLbriOQGWSu9s3qVvEWTLU1Q9ed9yjlWKpT1EhlXDSmN6ZZqpO2Y+6PgR9Hch1DFkXSoT4hJ5zb5yUPeXuuF+F5M7I0lxms++Hmo8Y98PEkMvHmor+LiyIf6jnf35OPrp+GYaw0nuX4N8KrCeR68Mue8LdRexbyE6jgd9krzur+W89Qn0V8WMR37Zt6zkrjc0oBHrAk2i1CLElqn7dVGTNH48Mc85aVghsU00hnwQ0Kt7ePwKrxuicWknV51C3sDRM/MmUdwNdklrTNxWw/UML2s1qNW/2ooOMfg9ljHBmB8a/8lsiVZ8Hm+8712//p6P7BmeopkuPPEqvtAgibiy0jQ0u1uK+pJ4p+E1buiuZ32f6SEyrQMWoztMVl/1c47tOwELNlKMsBp+t2PBZUwEg5XO+LyWfGgAaXIR7/ddTUs3u2hRsePKGsGgx7jdCoytJMl08GqdXZVi2K1j54yYxUYlEzvNawiakyd7trd8XI2ztf53X/0JAAD//5lPxIs="
}
