[[monitor-icmp-options]]
=== ICMP options

Also see <<monitor-options>>.

The options described here configure {beatname_uc} to use ICMP (v4 and v6) Echo
Requests to check the configured hosts. Please note that on most platforms you
must execute Heartbeat with elevated permissions to perform ICMP pings.

On Linux, regular users may perform pings if the right file capabilities are set. Run
`sudo setcap cap_net_raw+eip /path/to/heartbeat` to  grant {beatname_uc} ping capabilities on Linux.

The binary has the correct capabilities already set on the container image, however your container runtime
must allow the use of these privileges for them to be used. On docker this can be achieved with `--cap-add=NET_RAW`.

Other platforms may require {beatname_uc} to run as root or administrator to execute pings.

Example configuration:

[source,yaml]
----
- type: icmp
  id: ping-myhost
  name: My Host Ping
  hosts: ["myhost"]
  schedule: '*/5 * * * * * *'
----

[float]
[[monitor-icmp-hosts]]
==== `hosts`

A list of hosts to ping.

[float]
[[monitor-icmp-wait]]
==== `wait`

The duration to wait before emitting another ICMP Echo Request if no response is received. The default is 1
second (1s).
