This is the storage metricset of the module azure.

This metricset allows users to retrieve all metrics from specified storage accounts.

include::../../_meta/shared-azure.asciidoc[]

[float]
==== Config options to identify resources

`resource_id`:: (_[]string_) The fully qualified ID's of the resource, including the resource name and resource type. Has the format /subscriptions/{guid}/resourceGroups/{resource-group-name}/providers/{resource-provider-namespace}/{resource-type}/{resource-name}.
  Should return a list of resources.

`resource_group`:: (_[]string_) This option will return all storage accounts inside the resource group.

`service_type`:: (_[]string_) This configuration key can be used with any of the 2 options above, for example:

----
resources:
    - resource_id: ""
      service_type: ["blob", "table"]
    - resource_group: ""
      service_type: ["queue", "file"]

----

it will filter the metric values to be returned by specific metric namespaces. The supported metrics and namespaces can be found here https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccounts.
The service type values allowed are `blob`, `table`, `queue`, `file` based on the namespaces  `Microsoft.Storage/storageAccounts/blobServices`,`Microsoft.Storage/storageAccounts/tableServices`,`Microsoft.Storage/storageAccounts/fileServices`,`Microsoft.Storage/storageAccounts/queueServices`.
If no service_type is specified all values are applied.

Also, if the `resources` option is not specified, then all the storage accounts from the entire subscription will be selected.
The primary aggregation value will be retrieved for all the metrics contained in the namespaces. The aggregation options are `avg`, `sum`, `min`, `max`, `total`, `count`.

The default time grain is 5 minutes (`PT5M`), so configure a `period` of 300s or a multiple of it unless you change `default_timegrain`.

`default_timegrain`:: (_string_) Sets the default time grain to use when collecting storage account metrics. Defaults to PT5M. Available since 8.19.5.

To collect storage account metrics with a PT1M time grain, we recommend using one of the following configurations:

["source","yaml"]
----
# (1) With `period: 60s` and `default_timegrain: "PT1M"`, the metricset
# collects 1 data point every 60s.
- module: azure
  metricsets:
  - storage
  enabled: true
  period: 60s
  client_id: '${AZURE_CLIENT_ID:""}'
  client_secret: '${AZURE_CLIENT_SECRET:""}'
  tenant_id: '${AZURE_TENANT_ID:""}'
  subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'
  refresh_list_interval: 3600s # 1h
  enable_batch_api: true
  default_timegrain: "PT1M"
----

["source","yaml"]
----
# (2) With `period: 300s` and `default_timegrain: "PT1M"`, the metricset
# collects 5 data points every 300s (5 minutes), one for each minute,
# but all data points arrive after 5 minutes.
- module: azure
  metricsets:
  - storage
  enabled: true
  period: 300s
  client_id: '${AZURE_CLIENT_ID:""}'
  client_secret: '${AZURE_CLIENT_SECRET:""}'
  tenant_id: '${AZURE_TENANT_ID:""}'
  subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'
  refresh_list_interval: 3600s # 1h
  enable_batch_api: true
  default_timegrain: "PT1M"
----

These two configurations trade off scalability and freshness. Configuration (1) prioritizes freshness over scalability, while configuration (2) prioritizes scalability over freshness.

Suggested changes:

* `enable_batch_api: true`: Retrieves metric values for multiple Azure resources in one API call, supporting more storage accounts.
* `refresh_list_interval: 3600s`: Looks for new storage accounts every 60 minutes instead of the 600s used in the default module configuration, helping to avoid or reduce gaps when monitoring many storage accounts.

NOTE: By setting the collection `period: 1m`, the metricset only has 60s to collect all metric values instead of 300s, so it can handle fewer storage accounts. Keep in mind that the storage accounts metricset collects metrics for five different namespaces (storage account, blob, file, queue, and table).


