This is the storage metricset of the module azure.

This metricset allows users to retrieve all metrics from specified storage accounts.

include::../../_meta/shared-azure.asciidoc[]

[float]
==== Config options to identify resources

`resource_id`:: (_[]string_) The fully qualified ID's of the resource, including the resource name and resource type. Has the format /subscriptions/{guid}/resourceGroups/{resource-group-name}/providers/{resource-provider-namespace}/{resource-type}/{resource-name}.
  Should return a list of resources.

`resource_group`:: (_[]string_) This option should return a list of storage accounts we want to apply our metric configuration options on.

`service_type`:: (_[]string_) This configuration key can be used with any of the 2 options above, for example:

----
resources:
    - resource_id: ""
      service_type: ["blob", "table"]
    - resource_group: ""
      service_type: ["queue", "file"]

----

it will filter the metric values to be returned by specific metric namespaces. The supported metrics and namespaces can be found here https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccounts.
The service type values allowed are `blob`, `table`, `queue`, `file` based on the namespaces  `Microsoft.Storage/storageAccounts/blobServices`,`Microsoft.Storage/storageAccounts/tableServices`,`Microsoft.Storage/storageAccounts/fileServices`,`Microsoft.Storage/storageAccounts/queueServices`.
If no service_type is specified all values are applied.

Also, if the `resources` option is not specified, then all the storage accounts from the entire subscription will be selected.
The primary aggregation value will be retrieved for all the metrics contained in the namespaces. The aggregation options are `avg`, `sum`, `min`, `max`, `total`, `count`.

A default non configurable timegrain of 5 min is set so users are advised to configure an interval of 300s or  a multiply of it.


