// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package couchdb

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "couchdb", asset.ModuleFieldsPri, AssetCouchdb); err != nil {
		panic(err)
	}
}

// AssetCouchdb returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/couchdb.
func AssetCouchdb() string {
	return "eJyUkE1SxSAcw/ecIvP27wIs3HkKxwWvRGUKhQGq7e0dS6v9wOrLMgy/JP8rWo4Sje+bN30TQDbZUuIyOxcBaKYmmpCN7yQeBABwCIzGscvKPj2LyZt/wHndWwrgxdDqJKfHKzrluA76Uh4DJV6j78PsVLK2oALblV5UKb+oCi46FF8UaakSJW7MauXv+/w+8LvYYeg/etWGl5DE+M4o/uKfsA+Es00clAuby/xkthw/fNT3rAIeC7CEis8AAAD//z9Fpjk="
}
