#!/usr/bin/env bash

set -euo pipefail

source .buildkite/filebeat/scripts/pre-common.sh

if [[ "$BUILDKITE_PIPELINE_SLUG" == "filebeat" ]]; then
  changeset="^filebeat/
    ^go.mod
    ^pytest.ini
    ^dev-tools/
    ^libbeat/
    ^testing/
    ^\.buildkite/filebeat/"

  check_filebeat_changes "$changeset"
  echo ":: FILEBEAT_CHANGESET=$FILEBEAT_CHANGESET ::"
fi
