#!/usr/bin/env bash

set -euo pipefail

unset_secrets () {
  for var in $(printenv | sed 's;=.*;;' | sort); do
    if [[ "$var" == *_SECRET || "$var" == *_TOKEN ]]; then
      unset "$var"
    fi
  done
}

cleanup() {
  if [[ "$BUILDKITE_COMMAND" != *"buildkite-agent pipeline upload"* ]]; then
  echo "Deleting temporary files..."
    if [[ -n "${BIN:-}" ]]; then
      rm -rf "${BIN}"
    fi
  echo "Done."
  fi
}

unset_secrets
cleanup
