#!/usr/bin/env bash

set -euo pipefail

source .buildkite/env-scripts/util.sh

unset_secrets

if [[ "$BUILDKITE_PIPELINE_SLUG" == "auditbeat" && "$BUILDKITE_STEP_KEY" == package* ]]; then
     docker logout "${DOCKER_REGISTRY}"
fi

# Ensure that any temporal files created during any step are removed
cleanup
