#!/bin/bash

set -euo pipefail

echo "Golang version:"
version=$(cat .go-version)
export GO_VERSION="${version}"
echo "${GO_VERSION}"

# TODO remove in final
if [[ "$BUILDKITE_PIPELINE_SLUG" == "beats-metricbeat" ]] &&  \
    [[ "$BUILDKITE_STEP_KEY" == "test-"* ]]; then
    echo "--- prepare env"

    source .buildkite/scripts/pre-install.sh
    with_go ${GO_VERSION} ${SETUP_GVM_VERSION}
    with_mage
fi
