// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package vsphere

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "vsphere", asset.ModuleFieldsPri, AssetVsphere); err != nil {
		panic(err)
	}
}

// AssetVsphere returns asset data.
// This is the base64 encoded zlib format compressed contents of module/vsphere.
func AssetVsphere() string {
	return "eJzUmktv27gTwO/5FIPe695z+ANF/thNgU1TrNNeA0YaW1zzIZAjG+6nXwz1sCxLjh+k2/WhKGxl5sfhPEl9hBVu72HtywId3gGQJIX38GE9D998uAPI0WdOliStuYf/3QEANL+Ctnml+M8cKhQe72Ep7gAWElXu78OjH8EIjX0V/KFtyQ87W5XNNyNa9gX1heWChCfbiRsXOSm2+WlEyP462s8Qo4+SiVJkkrazhUOcvW0J/d5zLZiyZjn44Qgbf/5wiBAEgl0AFbgjng0eXlinBd3DofoDTLIkVFTOF5YYH7TymEfl/O4xT4RZZjQK6TOhMH9dKCuGD7wD+w1dhobEEhm2A+30QtA7gV3WfzwKvvCMNkq7wu3GuvxML5UK/dYT6iBlNqq0sJ5mma3MuJnO38uvlX5Dx6Zh0f6IVv7vuAddtNy/pCdWK5QKLsQ6groJBmnLWP47J+vYH758eoYHa8hZBWK5dLgUhDl8MWVFn54rKiuC5xKdYEGePQnmmFmTjxPyv/Hs8//OU1nuuEaHIm5k/y0ohAkLlmYZwgUWzuprozyQKkFosjZz6ljQn9cYtlNojouQkqRGhgIRFINtN3FkLSANaKmU9GFrJ7zPk6AqovfPg7x30mdX8XWikP/xNLHctU4d7j+ejgX7xkmK2wO0ns2SO88me61f16C/wrGD5gs9+6AN5OR7TQf4yMlbmtpeHU3b3KJZS2eNRkOz61rEsqrbBF38jNnLPHz7zsZ6evw57o6st9nbaIrrZu8UzaEfjqc4dMPv6d2FROI8kO+VuYl0sKNJkwc7+R6s6bqRCRbpV7Ne0yqWcRPVS9EPeN+0Kl23mlXOoSG1hTfkPJZZ4ysd+nGwrsVHQ0x3djoLi8txLTNsc5qok1DyrCYJSKzQc1LOrC4VEoIwMH+Yf+EvtDB5nVbKYutlJhTUoKcV8LCyRHn6US4L9ASNeFgLVSGIzFnvg6Ozch8GDd6mrts9HTx6o9dugulioJ7nQru0KyXSrwBFVoAf6XtPdqj41XwKnzURmq6wx+GPP+nPKx3yDvMFk7Nz1xXdCV5ID5rdJOg+n16jti7VgcpTEH49XapzlFh8aY5PrqaLO20+ttP3xGiLtLFu9Rq5Gfhaiz1W+hvNqdsQczpJmhakkX5CA9JyvAmTb2ROxYycMF5z5ktTJDglgSDYFDIr6slpIzz01EJeOe5GmFwaQrcWagYvheSKUjr0aMiHXzvqdvZtl3N+ABzYwWGGcn1bI7Q6fw8LJKtUbXz095xrVrf8umy16WzUGhevrxTZCsnv+XmaKGw09Zd5PAhbtM710nJ1ak6CQuesu6XZNpIKqLWeb8KG9kaW7KNeZtUQajEh67bFHEM9jVBXimQmPN1g6ztdl8fODjfx3h+ynrfzPbsm3/wD1tMQc2fLEvMbbHy/ErTmbLWfhZp407sKdRXk7aL9KF7sa4iXAsFyg6MUFCgUFY2K0Bt3pxRcxt85zN0xViXJidHkstOwYPtG7D5Xc3ASMuS5mL/6iiPZpc5aOqqEAi2yQpqpI80Oo366efhuCHLGHcCkpPPP+QOqHJr/2vFWTgRV0Mb/xB+pWWLb5h+Z6KLq/dHs/1O9EUemehvR+Ydam3tzs4R5/U7DNEbqW53il93qHNMc+Vbn81pIJd4Uvqu8f6y1rNBTssMtu4A/WUGkM7gQQAlZm0vMKMeZ8Q27d6gZz7LBDePT9k+II8BmlSerX+uaMYpo3/7Bg3fH6i9fr0hrD0FxU6x+t7PRsfcuYbJ0w0TRhUElGq7hvXWcsJawHhZ98MILCO9tJsN7V+HSRvpBIzF0lp5TjLRPcMxnTyUduxc+k3PgHP+5DeqOo3/r/bmUMtU49bw/SgmT741Tg878RuPTbnBqhpLd4DTyRtDdvwEAAP//8HhtJQ=="
}
