// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package auditd

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
<<<<<<< HEAD
	if err := asset.SetFields("filebeat", "auditd", asset.ModuleFieldsPri, AssetAuditd); err != nil {
=======
	if err := asset.SetFields("filebeat", "Auditd", asset.ModuleFieldsPri, AssetAuditd); err != nil {
>>>>>>> Introduce local fields generation
		panic(err)
	}
}

// AssetAuditd returns asset data.
// This is the base64 encoded gzipped contents of module/auditd.
func AssetAuditd() string {
<<<<<<< HEAD
	return "eJzsWk2P2zYQve+vGKSX9hA1px5coECBIkCANAXa9NDTgiZHMrEURyGH9qq/viAl+VOyLdpBerAPAVYW5703fCRn6LyFF2wXIILSrJ4AWLPBBbz5NT148wSg0EunG9ZkF/DLEwDA76SCQSjJQSOc17bqA4ChyhdPAH5Fjp8l2VJXC2AX8Amg1GiUXzylGG/BihoXEDy69ACA2wYXUDkKTf/kYMT+KEZXayvM9oth9Au2G3Jq7/kI/+HzuY8C5IC5BYVrLRHIwmal5Qp4hYkfaA8NupLi61V6TEuPbo0KhGS91twWpyRTTk4Y7uvb17hPbIig1cHjaZEXhMbPHxajzjoY1o1BCFZ/CQhaoWVdanQeqNxKLkb5xH9nMMJXUTfRTsIs0fE8vn9FCyXESNtQpe0hwVGGKbvFPfP293Geku8jjYQV3RL/8K1nrH9sjODok/H8dexmZvECv/j5lLJU7liNuBHLEqNX8eHIr+XIMYIPQ04ZstQGO5IPRz4c+X9wJG3sthiBhxkfZvyWZvRijephxocZv5UZD9oYNdmjTSC8T8aE0lGdIh81iDDi3QHQUHXR92d0HSN/1Da8dvgxdAGfiEEY0+ODcAiKZKjRMipYoUNYohTBHyaaV9h2L7dW1FqCsArWwrWwbPvwuEbLiXFx5Rolo55FOLHchWl7v/V0QvTAK+1jl5paU6N6Oh9+i2ZXW8+lXrZxOv5JJ0FTjBR1Yvni5t5ULW62VAv4PNgkEpfCwhI7/mNknZAIZeDgcBuZdirjI9DJ1Nr1649bkCthK/TwvdEvx8sI4qxT6vAdEf8wnoU4YR79nefLo/ea7FeYsftyjRO241rABz6aKGCNIE6CJh1MRxO2bPeDjUrw+CWgleNbniFbzRO3s1i3VIfwYEO9nDoWNGM9M4kRpwsZd9YUALQF0Sd1Gmc+TBzVbTGgrdJSMPr+/ip9RYGH3Z2JhTnmVYxE1X54S3v4Fx29XQqP6mcQsBYmpOPiHdQorAfNgzlK7TynoOP6mNtZJ1eprZ5U/vkfCP193f41nQvWxhXcOKqcqD3QxNoQ7+anuhMoXJXOimG/6Q5vkMKYCSil3Khw3czS/CfWxJjCoY8pF3ygXZK1KDnKj4ffOBnX0EktdWY1XcGnSZXWmfVj7pWAjySjf5E35F6GPExg3k9mhzqqcny6pRxHFkaL432kEbzqLsHHKrtaV050vPo79FO4ZqJenUZrHMmYuNORV+HdAJiH6E6OsEuA3SZLgSVl5dShJKeeI0wWspARIAO4QjpZE+MFMEwUlvvRJFnWFi0/j3jrvJqdIk/BSSwqpOJivHMSD4kFy6591p6eJam7ULsY8VpyhqQYmb4MUmciXUvGYaXJ3mn+zge7evI0t/cy1JlQMzN0PytdDjhF7eDV74ZGdImGNrCJbaUl7g4bjMUa/FS8wjJw951nbQwsMVUv1AQjGNVEQeHkaua+tCLPRRynGWWswXM2p9kbfzrXJm5VrkE87TavQszCEpnyUjtxi8iRnnoGcBZk6TPF7n6zuUVx6TMl78FnAWOm7O1vp7eoxkzRO/As2NypTvfPt+jNneQOOAuSMrWmH35u0UqZWjvgLEhJ9fFtwbV1eGanga9zq+EBEF9RBhZLkwM78n99rs7vxNhrYGt/3CZeQqzRe1HlSPROzsTq65W+B86AVH5uk6rQs7Yp7pW4/wUAAP//yO3oSA=="
=======
	return "eJy8VsGO2zYQvfsrHnJKD2vk7AIFimxTGGibou3docmxNFiao5LDddWvL0jZXkWWNzWyG95Eke+9eTMc8g4P1K9gsmN1C0BZPa3w5sc68WYBOEo2cqcsYYUfFgDwq7jsCTuJ6ExMHJojALw0abkAUitRN1bCjpsVNGZaADsm79KqQtwhmD2NiMvQvqMVmii5O87MkJfxoSJhF2UPbWnKXsaYbEzopTnPzTE+wzrH/AuH/M/AX6CX+E0UxvsjP0wkOLF5T0HJoaVI2JI1OdFnuNpSPyzug9mzhQkOjyb22PZHeHqkoFXxcrR1Guc41khWotuULZ/9fzbCMv46eXqF9IlCvNuYzO42/A8Si1scBvwEbTmBU7VUvDuSr++RE7laaOVPThTRRS6fcgFaMSrqvNRAh5eWGuhwlrocuba+hzUBWxr0z4mNxhJ2WXOkM7I8RVmmwLsywRHsKChrD9ua0FDCW88P05yiFJbsy2mMIvrd9YQlSi+cr0QpsYRXyNjLai0Je9K6xFoniYIywVyA1jhUJgnb9mOw2RAS/Z0p2Gmuhr7jJTRfdzBP8Ah5v6U4r8FYq7fT1JCNtZKDViCYlMSyKX3swNpWQ6uMedru1qNWWNf3kFr16KJYSukK9muCs9L+xqIr6EMKCkMFAAeY8JxBZdntNGXX0PXBwbE1SgmHlm07/JKspyhV1PipruUMKqfTKk74l6LcbU0i9z0MHo3PVDa/w55MSGA9HaYdx6QV9Erdvbs9ugHTxKbemKeWmPpUQrPG+3mqeGuXKFyRUvZns0YceJuyLfUBidgZ9jnSlXbakHA3e7inj4r/Ieq9BDUcEn4mWf8ODjuJe1NWozFa3g4ONTGQUDV/Gh4+y/LyMM7FTxeQtVCW+Bh8jy5SKqYO18qR5CdvkrJNZKJt0flcOicnmEfD3mw9lZfIXD9000Kae4mMrbISlAMF3ZTvi2Un3x6oP0i8pPyiezidw9Krjkk9c15W/VkWa/8tFbH218VEaljCN5QzED7jTmn/sd9wko0V90qq3g8sWP/5EYXluh4vth6Iqzoakk0nHKY33g3+lGuZNbta+vBG68cXk/a6Fv1RSUYO/RcAAP//EHqm1w=="
>>>>>>> Introduce local fields generation
}
