// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package auditd

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "auditd", asset.ModuleFieldsPri, AssetAuditd); err != nil {
		panic(err)
	}
}

// AssetAuditd returns asset data.
// This is the base64 encoded gzipped contents of module/auditd.
func AssetAuditd() string {
	return "eJy0l8+O4zYMxu95CmJ7aHtYY089pECBAosCC7Q9tedAlmibWFl0RXoy7tMXsvNvHDmZuNncIls/fp9ISfRH+IrDFkzvSN0GQEk9buHDr+PAhw2AQ7GROiUOW/hlAwDwB7veI1QcoTNRKNQHAHiupdgASMNRd5ZDRfUWNPa4AagIvZPtiPgIwbS4hV4wFnXkvtsV5MZHADp0uE3C9hyPYxkZ6fe3YPxeYCTAl8/F5g39ZOtMHd+8zfxt1AlV5Ba0wbm39Lu0chnQc30ay0W8ETUX+XcK/esUP6EL+JMVjPeH+GAigmPbtxgUHTQYEUq0phd8w9UGh+nlIZiWLJjg4MXEAcrhgMcXDDoqLi6mzn1eemXvdqY/Je0d9kaLHJMVClNEAW1IgGT0y94d5Hz5nErDjTWWnqQ6gS5S+stX0JExUous1ID7Z0sNuD9JLeCvY5kk4dYEKHHSnxMbjUWoeu0jnsh8dpmGgKo0QBHIYVDSAWxjQo0CP3j6ilfQEi23aSNGZv0xvwopYYLy5HwJihCHb5Cx52pNCTtrLeCLzhIFSgjmCjr6UJ4lrBwuYVkLgv/0GOw8V9Oh4DnUj5k7l9i0VY94CH1bYsxrIMX2wUVMcSYkcDUBgAKYw6Iux3k8TJo1HTFAwZE1igL7hmwzPeJek4aUPWU1fq6ryFBJjm+RwL8Y+WNpBN3PYODF+B7T5E/QogkCpMfiqCiKjtC8P/PpcXcT08R6PJ6PW1wGSdas8f4cKh/TWs3WjvFk5kntjDaH2zTNzgK7qwPwHq+LbFGkmM88Ef8HcokZr3b9PeRUl9yr5QXnES1Ht0ugVWxjU6Kz6BqZuix0fu/Dwn16SbMclAIG3V1l8Z7es2bhPlosauTiDu8ctg8ahx0J7yy7pwS+Qzx3TNZcLe6qkIukcxXUxOFJK3sLdlpW0uFZiVxEzdw9L4VLwDdzvzv2rCV63sM+daCBFRxWFDCd6/BT8Qplr9MzUfIeSkytSsdd742iWzhzo20e3K0NixYsRZpKijbd2Pld+/C5lf1QeQu9bjDfBV2gmZUaxx5hUrqIXql0Qi9AK1kpuCKP0614W3UlK2VfBFhA40rpWFVolV7wtnJcKfyMXwCvXXIxL+hua1672BN6Acor9fI+HHffInql3gm9ALXcztva9/Y3i10Yvj7agxyR+Iq2V1P6PFgxthSMX0nPTj+xdfgW2FbmH0H3sC2KmDq/ABLtg7TDbWeciyiSPyudi8+nOnm0tXcoSmFscE7k/wIAAP//DhghkQ=="
}
