// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package greenplum

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "greenplum", asset.ModuleFieldsPri, AssetGreenplum); err != nil {
		panic(err)
	}
}

// AssetGreenplum returns asset data.
// This is the base64 encoded gzipped contents of module/greenplum.
func AssetGreenplum() string {
	return "eJzMlE1ugzAQhfecYpR9LsCiN6jUGyALv7hW/CePacPtK6IkGOJKYWPCgsVj/OZjfnykM8aWVARcMINtiJJOBi0dHtqhIZLgPuqQtHctfTRENJ+hTy8Hg4bopGEkt9fPR3LCYmk9PWkMV9UP4aYUvJdWuZ3x6qGtjn4ZCAYJKXM9i8ZF2DD9WxZ507KoZ8ASz0yUtAUnYfPorWSvst1zhuh7MHdaVkh6L8kZ46+PslSC7wgh34YmCsein/zrIhnvVIFHhY6hLFyqyLKe39IEZyUbw9JkO97rgP93cAZa9W0fnMedgx+YtxhtTiKh673E/mNtwSxUTZCESyqA9ENkH7vgWT8l2KUyJ21qlmXbqk/v6ru16ly2WtrVp7m27S8AAP//N9uDpw=="
}
