[[console-output]]
=== Configure the Console output

++++
<titleabbrev>Console</titleabbrev>
++++

The Console output writes events in JSON format to stdout.

To use this output, edit the {beatname_uc} configuration file to disable the {es}
output by commenting it out, and enable the console output by adding `output.console`.

Example configuration:

[source,yaml]
------------------------------------------------------------------------------
output.console:
  pretty: true
------------------------------------------------------------------------------

==== Configuration options

You can specify the following `output.console` options in the +{beatname_lc}.yml+ config file:

===== `enabled`

The enabled config is a boolean setting to enable or disable the output. If set
to false, the output is disabled.

The default value is `true`.

===== `pretty`

If `pretty` is set to true, events written to stdout will be nicely formatted. The default is false.

===== `codec`

Output codec configuration. If the `codec` section is missing, events will be json encoded using the `pretty` option.

See <<configuration-output-codec>> for more information.

===== `bulk_max_size`

The maximum number of events to buffer internally during publishing. The default is 2048.

Specifying a larger batch size may add some latency and buffering during publishing. However, for Console output, this
setting does not affect how events are published.

Setting `bulk_max_size` to values less than or equal to 0 disables the
splitting of batches. When splitting is disabled, the queue decides on the
number of events to be contained in a batch.
