// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package iis

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "iis", asset.ModuleFieldsPri, AssetIis); err != nil {
		panic(err)
	}
}

// AssetIis returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/iis.
func AssetIis() string {
	return "eJzMksFuszAQhO9+ihFHpOQBfPhfBRnYRPtjWGvtNOLtK5dAgNIoUi/dA4fZ0cy3wAkdjRbM0QCJkyeLgjkWBmgpNsohsQwW/wyA7EMv7c2TAZQ8uUgWNSVnDHBh8m20X84TBtfTnJwnjYEsriq38FAOCrYh6yAXgufGZXMVRPxiOErOs8V76oet07zo2GOt0fJzs5iROhrvou1u9wJgB4EM8T1+7r2LdqRVUGkoRtGK91W/wJjCsYRjFb4AUB1JP0jP5bl849VPOFL/pyat5Emopu3Fi/thWfUuBB6uD2dRFu991gVzUQ8v4UR//QpOzz/BfAYAAP//6u79+A=="
}
