[[winlogbeat-getting-started]]
== Getting Started

To get started with your own Winlogbeat setup, install and configure these related products:

 * Elasticsearch for storage and indexing the data. {libbeat}/getting-started.html#elasticsearch-installation[More details]
 * Kibana for the UI. {libbeat}/getting-started.html#kibana-installation[More details]
 * Optionally Logstash for inserting data into Elasticsearch. {libbeat}/getting-started.html#logstash-installation[More details]

After you have installed these products, you can start <<winlogbeat-installation>>.

[[winlogbeat-installation]]
=== Installing Winlogbeat

. Download the Winlogbeat zip file.
. Extract the contents into `C:\Program Files`.
. Rename the `winlogbeat-<version>` directory to `Winlogbeat`.
. Open a PowerShell prompt as an Administrator (right-click on the PowerShell
icon and select Run As Administrator).
. Run the following commands to install the service.

["source","sh",subs="attributes,callouts"]
------------------------------------------------
PS C:\Users\Administrator> cd 'C:\Program Files\Winlogbeat'
PS C:\Program Files\Winlogbeat> .\install-service-winlogbeat.ps1

Security warning
Run only scripts that you trust. While scripts from the internet can be useful,
this script can potentially harm your computer. If you trust this script, use
the Unblock-File cmdlet to allow the script to run without this warning message.
Do you want to run C:\Program Files\Winlogbeat\install-service-winlogbeat.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R

Status   Name               DisplayName
------   ----               -----------
Stopped  winlogbeat         winlogbeat
------------------------------------------------

NOTE: If script execution is disabled on your system, you need to set the execution policy for the current session to allow the script to run. For example: `PowerShell.exe -ExecutionPolicy RemoteSigned -File .\install-service-winlogbeat.ps1`. 

Before starting Winlogbeat, you should look at the configuration options in the
configuration file, for example `C:\Program Files\Winlogbeat\winlogbeat.yml`.
For more information about these options, see <<winlogbeat-configuration-details>>.

[[winlogbeat-configuration]]
=== Configuring Winlogbeat

To configure Winlogbeat, you edit the _winlogbeat.yml_ file. Here is a sample of
the _winlogbeat.yml_ file:

[source,yaml]
--------------------------------------------------------------------------------
winlogbeat:
  registry_file: C:/ProgramData/winlogbeat/.winlogbeat.yaml

  event_logs:
    - name: Application
    - name: Security
    - name: System

output:
  elasticsearch:
    hosts:
      - localhost:9200

logging:
  to_files: true
  files:
    path: C:/ProgramData/winlogbeat/Logs
  level: info
--------------------------------------------------------------------------------

After you save your configuration file, test it with the following command.

[source,shell]
----------------------------------------------------------------------
PS C:\Program Files\Winlogbeat> .\winlogbeat.exe -c .\winlogbeat.yml -configtest
----------------------------------------------------------------------

=== Configuring Winlogbeat to Use Logstash

include::../../libbeat/docs/shared-logstash-config.asciidoc[]

[[winlogbeat-template]]
=== Loading the Index Template in Elasticsearch

Before starting Winlogbeat, you need to load the
http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html[index
template], which lets Elasticsearch know which fields should be analyzed
in which way.

The recommended template file is installed by the Winlogbeat packages. Load it
with the following command:

[source,shell]
----------------------------------------------------------------------
PS C:\Program Files\Winlogbeat> Invoke-WebRequest -Method Put -InFile winlogbeat.template.json -Uri http://localhost:9200/_template/winlogbeat?pretty
----------------------------------------------------------------------

where `localhost:9200` is the IP and port where Elasticsearch is listening.

=== Running Winlogbeat

Start the Winlogbeat service with the following command:

[source,shell]
----------------------------------------------------------------------
PS C:\Program Files\Winlogbeat> Start-Service winlogbeat
----------------------------------------------------------------------

Winlogbeat should now be running. If you used the configuration described here,
then you can view the log file at `C:\ProgramData\winlogbeat\Logs\winlogbeat`.

You can view the status of the service and control it from the Services
management console in Windows. To launch the management console, run
this command:

[source,shell]
----------------------------------------------------------------------
PS C:\Program Files\Winlogbeat> services.msc
----------------------------------------------------------------------

=== Stopping Winlogbeat

Stop the Winlogbeat service with the following command:

[source,shell]
----------------------------------------------------------------------
PS C:\Program Files\Winlogbeat> Stop-Service winlogbeat
----------------------------------------------------------------------

Enjoy!
