[[configuring-howto-heartbeat]]
= Configuring Heartbeat

[partintro]
--
After following the <<heartbeat-configuration,configuration steps>> in the
Getting Started, you might want to fine tune the behavior of Heartbeat.
This section describes some common use cases for changing configuration options.

To configure Heartbeat, you edit the configuration file. For rpm and deb,
you’ll find the default configuration file at
+/etc/heartbeat/heartbeat.yml+. There's also a full example
configuration file at +/etc/heartbeat/heartbeat.full.yml+ that shows
all non-deprecated options. For mac and win, look in the archive that you
extracted.

See the
{libbeat}/config-file-format.html[Config File Format] section of the
_Beats Platform Reference_ for more about the structure of the config file.

The following topics describe how to configure Heartbeat:

* <<heartbeat-configuration-details>>
* <<configuration-processors>>
* <<filtering-and-enhancing-data>>
* <<configuring-ingest-node>>
* <<config-heartbeat-logstash>>
* <<using-environ-vars>>
* <<yaml-tips>>
* <<regexp-support>>

--

include::reference/configuration.asciidoc[]
