// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package zeek

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "zeek", asset.ModuleFieldsPri, AssetZeek); err != nil {
		panic(err)
	}
}

// AssetZeek returns asset data.
// This is the base64 encoded gzipped contents of module/zeek.
func AssetZeek() string {
	return "eJycmMFy4zYMhu9+Cr7AutOd2R5y6My2nZ7aSyenXji0CElsKIILUE6Up++Q0tpxJEfgHm39HwGCAAHpk3qC6UG9AjwdlEoueXhQ/86/LHBDLiaH4UH9elBKqb/Rjh5Ui6R6E6x3oVMeO1aR0I4NWHWaCv7Tb4QHpVoH3vLDQalPKpgBLpaUSlOEB9URjrH83rCm1J+FVy3hcFl2NmjaBKQC0mC8ezUZK8zV4tUmA7PDoJ1dlp1tP8H0jGQPN9oGQ4AmL3f02BivkVx3g50QPZiwgxFwrMIGxwxWn6YEfAN6DN1dipNJULWr3nFCmqqYHAPtP2tjLe2Deety9dmbsK9yIQBpmdYGPiYygd8fuAsJOqC1mlK6EVocTx7Wum8jSCJXpI03vHeQV6HOfwhXzs8lC+eHFetSg1aybtFVrPv1634dZN3j7zLdP38IdUK7JvAzEMs28/j4F4tSheA/aBLYTR/yP+uUxWS83vLmbt7OCEH0DoQIm2e9TuO7wcnyvL5A3qcUl7qzEFO/6c9q54XKt9jIeuBu8xS2IRda1Kuc/dhQYe6ZWctb50GW6PPmTSdIoyJtTEwjgdXRMF82uR/fSPjiQNDHippM6EATfBuBk9BC4x2EpHswFqiUuXRPDHQG+hGy9Jd2dLYKGNwAOivrzCxnKoVKN6vxrQDVvs1mKn27huF+xX3koJDKbvExx2Dfr1mbXnSP71LOxS0liZXXKU4QngXBkRpQUvk6HO87IF+kjubZSLq2CcZPr6I+MwOXDJIC8stq1teMtzPhuEpuRzKrEG31y+/nC0E0/i4pVnqfXJ/naxe6CgLPQK3H5xqn3AAWR8FdO+ujoXzZ1pTWYL+I0783P1doP3/5RaqGl0RmNd5IAN2MCdtWGqArx+51bzpdkJAI47Sbdcz+eAZiURFnceNiD4I3mqId6SyoxCxd2qasdDNAwONwZ7JciQO8JB0JEzboZesDJ3PyjnupjQYo6aY3ThrIi17aWAs1DybVxt5jNTYd8yg+8tlQDXI23tlyR+p5BBZmzHjKLxdVblUx3nDSxgMJ9AGTa+B4/Vog+syyUK4ZYo0+V/ixVr9csrXYPDxUuibtkDeGpI3vLSRvf98pUY95Y0JXTCALFlDyMWoRi17DFi2PJ7kTsnhEEF+6b4nymfIGSfCSNvWmlIOgphc9DMZ5fUI7aYYN9q6hGbTgzaQTPkGFTWchJNc6yY11OYsYCZh1i7TbZBfGEsb4UTs5HA7/BwAA//9bGsLO"
}
