// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package coredns

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "coredns", asset.ModuleFieldsPri, AssetCoredns); err != nil {
		panic(err)
	}
}

// AssetCoredns returns asset data.
// This is the base64 encoded zlib format compressed contents of module/coredns.
func AssetCoredns() string {
	return "eJzElk9P20oUxff5FEdZwRP46T1VLCK1m7Aoi1IE7MvEc5NMseeauWNQ+PTV+E/+2EPSUFcIL9Ad+5zfHN+58TkeaTVByo60lRHgjc9ogvG0roxHgCZJnSm8YTvBlxGA9n58Y11mNAIcZaSEJlioETA3lGmZVLeew6qcti3Cn18V4WbHZdFUIi7hemiee0DK1itjBeKVN+JNKvBL5fFCjuBIacwd55XR5fVdo7CNso0TRFqYONAeqHBNIziOMuVJwzP8kloSCLlnk9LW47txAXHWbd5CWZMmKZfW76y35BnbRWdhD3x13bNXGWyZz8iB57WFRN21lcTRU0ni/wbDU0luhb5wzF6XToVWTKwkszJ9JJ/809GtE+HZT0q7oHXxx7t5b+sQ0FJgacTzwqkcNYzAWFhlWShlq+Wo/UiZ/26wc3a58pM1yPv2IevnzyBlHrqgLfzRRgbtkQjrpmkb98N4Yl4pma08fWTb3JlX6rfMMexHtMgBqDeYugYHeIZ8028Q9S1iTJqHnUzX6xYL08lQ82OzVM9UDffL75gZD6HDaCGPYeEwDWq7eAU5vLIlKKsr5ShXb6GleKTVCzt9HMhXznQIhpoRHqQCU6g0u49S1OlIwVYocSnrYfPZSqd16eRTeUbR+isDJVQJb8KpsaIIc5WbbDUcw/2SoLR2JNJotxjeKSsFO4+T//AZVzc4ubrBMzkxbPHp9Az/V+WLnfrF6WmUe+etfui8xW2DcfzE7eMPOXLjVPtnbp9oyLPyFlPfo6UKn7Pkhm3PWrM9FmaWEebsDs6RcJ6HBQmKYZsohXSX4d/2ZURhCseeh6XZnM/O3MDJuNTFGOww9mkx3hzI/j/bjKGjUpUuKVkaP2wjTYMsgmz9Jb8Or/JDkZULYw9A5UZk4P6usWrhfWC/BgCjRRIG"
}
