[[load-ingest-pipelines]]
== Load ingest pipelines

The ingest pipelines used to parse log lines are set up automatically the first
time you run {beatname_uc}, assuming the {es} output is enabled. If you're sending
events to {ls} you need to load the ingest pipelines manually. To do this, run the
`setup` command with the `--pipelines` option specified. If you used the
<<modules-command,`modules`>> command to enable modules in the `modules.d`
directory, also specify the `--modules` flag. For example, the following command
loads the ingest pipelines used by all filesets enabled in the system, nginx,
and mysql modules:

//TODO: Replace with the platform tab widget.

*deb and rpm:*

["source","sh",subs="attributes"]
----
{beatname_lc} setup --pipelines --modules system,nginx,mysql
----

*mac:*

["source","sh",subs="attributes"]
----
./{beatname_lc} setup --pipelines --modules system,nginx,mysql
----

*linux:*

["source","sh",subs="attributes"]
----
./{beatname_lc} setup --pipelines --modules system,nginx,mysql
----

*win:*

["source","sh",subs="attributes"]
----
PS > .{backslash}{beatname_lc}.exe setup --pipelines --modules system,nginx,mysql
----

TIP: If you're loading ingest pipelines manually because you want to send events
to {ls}, also see
{logstash-ref}/filebeat-modules.html[Working with {beatname_uc} modules].
