// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package etw

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "etw", asset.ModuleFieldsPri, AssetEtw); err != nil {
		panic(err)
	}
}

// AssetEtw returns asset data.
// This is the base64 encoded zlib format compressed contents of input/etw.
func AssetEtw() string {
	return "eJzUV8Fu3DYQvfsrBrk0PqwRF3AOeyhQBAlaoEUP3SJHY0SOpKkpUiEpbffviyGpXcmSgQbxFu3eTJEz7828eaR38ESnPRzZGtfcAESOhvbw5jNb7Y4BPh4+v7kB0BSU5z6ys3v44QYA4BOT0QFq7zqILclOYNsPEd5+HMlGOHhUbBuonYcS7vbuBqBOB/c3KcoOLHY0AyC/eOppD413Q19WNvLL70djSjgIPSmuWUF0Cc6ZwAILegJNNVvS0JKnuxJqgWmOC1XkkePpkfX52wTwiU5H5+frnr4M7EnvoUYTaPblBQKJBDTGVWjMCQbLXwYC1mQj10weYovx8ndI1NTgvZCasN3BoaVFSBLSIR8Wyv1QGQ4taThybCG2HOZJ0hb0EVydEgTslvHOmdYFUi1aS2ZVnNA6H7+1NH8E0tJQslgZyj1Gk+lB752iENg2d/Aho4ARzUABKjLuCPfvEzNPgfxIOglxCATVCX5l5V1wddyIHj1h7CRDdTor2w82ckerTJLDasDKjQRHNgYqAm6s86Q3zsPbFF1YlToDhqmG8O42BVNoJUrDI1kB7HeTZAN1aCOrsNGIVJRHjRFXvXDVn6TmzcgLj68q40NLGcPuPIoCJokTlLNRKpoExqEAAF7M7VJy9iQdHlmLQK3OsV/kvTGeLysw+uFrSc3GJTNK/X9GIDfVDV7RNEovoa4NNuE6Q/NJQufZLwUEtrXzHcpukeoQL9ggDKoVEcqKoBDkQebKWeAIRwxgXNPkQZRG8IxZaiyyDUB/RbKadG76mnBR2ZqzcbZ5De1NCdLMD8U42GpWGAnQZsDfBeioq8iHlntgCwiBki4LH4zUOM+0NWKGxms53S8SOpd+JJ9MPS8Vn3kHsfVuaFp4WFxicy97duT9+cj9w8IIn+27v2z8/uFhcp9Zgku3p4Hcqo1rajZ0rUvycJksSZOfHceWVTtddsIwC/UOfrPmBDgim+TsYvzWWfCEZpdsuAh8q8muV06vebxKl4VFjn+uL9uZT8ABw1MasrJLSMVTzyo/D7KqFyGLL+UuGafykJeo2PeGy1KpGEnEc0OPGBbRSgHXVSmX7ZbPso3UkP/W2vy8fOSUhNnHGrLkz9fmS546qfOxGf5Dr7XzJZY+5gIvIv4jSnb5JLvWbM1vLcEKnpTzGt4+V5PzIGbCihKvDRGlQPn47QazMoHX4vTB2ZqbwadHU77MohMjOKLX6UVWbCONxVTmIJuUs2HoyG+Zw+TO14L909Ch3XlCnYzLrG6FNaSI4el6biXR/29eFVsp4L9nVTnf1ziV3EEhYtevEGqM9Araz2+yBE6uuwTtUkmn0r+QW7UbyW+O5asI6vf0VM7tL4lE3AgdWq4pxF2FIptStr8DAAD//2Iu8Dk="
}
