//go:build integration

package integration

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/brianvoe/gofakeit"
)

// GenerateLogFile writes count lines to path
// Each line contains the current time (RFC3339) and a counter
// Prefix is added instead of current time if it exists
func GenerateLogFile(t *testing.T, path string, count int, append bool, prefix ...string) {
	var file *os.File
	var err error
	if !append {
		file, err = os.Create(path)
		if err != nil {
			t.Fatalf("could not create file '%s': %s", path, err)
		}
	} else {
		file, err = os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0666)
		if err != nil {
			t.Fatalf("could not open or create file: '%s': %s", path, err)
		}
	}

	defer func() {
		if err := file.Close(); err != nil {
			t.Fatalf("could not close file: %s", err)
		}
	}()
	defer func() {
		if err := file.Sync(); err != nil {
			t.Fatalf("could not sync file: %s", err)
		}
	}()

	var now string
	if len(prefix) == 0 {
		// If the length is different, e.g when there is no offset from UTC.
		// add some padding so the length is predictable
		now = time.Now().Format(time.RFC3339)
		if len(now) != len(time.RFC3339) {
			paddingNeeded := len(time.RFC3339) - len(now)
			for range paddingNeeded {
				now += "-"
			}
		}
	} else {
		now = strings.Join(prefix, "")
	}

	for i := range count {
		if _, err := fmt.Fprintf(file, "%s           %13d\n", now, i); err != nil {
			t.Fatalf("could not write line %d to file: %s", count+1, err)
		}
	}
}

// GenerateNLogFiles generates nFiles with nLines in each. The lines are a
// random phrase generated by Gofakeit. Files are generated directly into
// tempDir and the names follow the format "%06d.log".
func GenerateNLogFiles(t *testing.T, tempDir string, nFiles, nLines int) string {
	basePath := filepath.Join(tempDir, "logs")
	if err := os.MkdirAll(basePath, 0777); err != nil {
		t.Fatalf("cannot create folder to store logs: %s", err)
	}

	for fCount := range nFiles {
		path := filepath.Join(basePath, fmt.Sprintf("%06d.log", fCount))
		f, err := os.Create(path)
		if err != nil {
			t.Errorf("cannot create file: %s", err)
		}
		for range nLines {
			_, _ = f.WriteString(gofakeit.HackerPhrase() + "\n")
		}
		if err := f.Sync(); err != nil {
			t.Errorf("cannot sync %q: %s", path, err)
		}
		if err := f.Close(); err != nil {
			t.Errorf("cannot close %q: %s", path, err)
		}
	}

	return basePath
}
