// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package logstash

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "logstash", asset.ModuleFieldsPri, AssetLogstash); err != nil {
		panic(err)
	}
}

// AssetLogstash returns asset data.
// This is the base64 encoded gzipped contents of module/logstash.
func AssetLogstash() string {
	return "eJy0lc2umzAQhfc8xRHrXh6ARVe3VVO1ShfV3VRVhWBC3BgbeYZUefsKEhIwJv/XiyxsfOabmZPxCza0S6FtyZLxOgJEiaYU8bfDVhwBBXHuVC3KmhQfIwDoj1HZotEUAY40ZUwpyiwCmESUKTnFr5hZxx8Qr0Xq+HcErBTpgtNO5wUmq2hE0C7Z1a2Ss0192AkwjJWGarluWMglqjge9Zob2v2zbrgfVN6vn8vX5US8R/3DkglNAgyhQ4xDqVrVpJWhMehJK9MqY++kzmR9gkiMLSjpSJI5tUm09anQT4k30uujtR9eLM6Z2nv3x/a6prhjyGC+Ps6c5FB20iqc8dYVefZr5DU/aKBj7xX2GNKy3GiS9krS/rQK3heVKl22BxHX+KcXQL9YFkxEe9ItOVbW3AjL5LYqpyR8+yHc43B8C2j31H+31dWevBDv69t3LMzK3ujkcOZ4jq9CqWM0jOb/R6Gm4di42tmcmJOwwvnGXQn/Yx8Ci9fgWOvmHz863Lr3g1GROJVz8tCsoy0Z8Ut2t58+dWrws5yDGIKoeTtpa8r72rEwua2UKQ9pIreNaZ/3WQrb+KPrGRjLRkp7C8ZKaSFH80a/n+XzQXrC8j8AAP//2xdhDw=="
}
