[role="xpack"]
[[securing-beats]]
== Configure {beatname_uc} to use {security}

[subs="attributes"]
++++
<titleabbrev>Use {security}</titleabbrev>
++++

// REVIEWERS: I don't want to duplicate the content in the security docs like we
// have in the past. By the time users are configuring security in Beats, they
// should know their security strategy and how to set up users in the Management
// UI. In the Beats docs, I just want to cover beats-specific requirements. Let
// me know if I'm missing anything.

If you want {beatname_uc} to connect to a cluster that has
{stack-ov}/elasticsearch-security.html[{security}] enabled, there are extra
configuration steps:

. <<feature-roles>>.
+
You can use role-based access control to grant {beatname_uc} users access to
secured resources. 

. <<beats-basic-auth>>.
+
To interact with a secured cluster, {beatname_uc} must either provide basic
authentication credentials or present a client certificate.

. <<beats-tls>>.
+
If encryption is enabled on the cluster, you need to enable HTTPS in the
{beatname_uc} configuration.

. <<beats-system-user>>.
+
{beatname_uc} uses the +{beat_monitoring_user}+ user to send monitoring data to {es}. If
you plan to monitor {beatname_uc} in {kib} and have not yet set up the
password, set it up now.

For more information about {security}, see
{xpack-ref}/elasticsearch-security.html[Securing the {stack}].

include::users.asciidoc[]

include::basic-auth.asciidoc[]

include::tls.asciidoc[]

include::beats-system.asciidoc[]
