[role="xpack"]
[[feature-roles]]
=== Grant users access to secured resources

You can use role-based access control to grant users access to secured
resources. The roles that you set up depend on your organization's security
requirements and the minimum privileges required to use specific features.

Typically you need the following separate roles:

* <<privileges-to-setup-beats,setup role>> for setting up index templates and
other dependencies
* <<privileges-to-publish-monitoring,monitoring role>> for sending monitoring
information
* <<privileges-to-publish-events,writer role>>  for publishing events collected
by {beatname_uc}
* <<kibana-user-privileges,reader role>> for {kib} users who need to view and
create visualizations that access {beatname_uc} data


{security} also provides built-in roles that grant a subset of the privileges
needed by {beatname_uc} users. When possible, use the built-in roles to minimize
the affect of future changes on your security strategy.


[[privileges-to-setup-beats]]
==== Setup role

IMPORTANT: Setting up {beatname_uc} is an admin-level task that requires extra
privileges. As a best practice, grant this role to administrators only, and use
a less restrictive role for event publishing.  

Administrators who set up {beatname_uc} typically need to load mappings,
dashboards, and other objects used to index data into {es} and visualize it in
{kib}.

NOTE: These instructions assume that you are using the default name for
{beatname_uc} indices. If you are using a custom name, modify the privileges to
match your index naming pattern.

[options="header"]
|====
|Privileges and roles | Why needed?

|`monitor` privilege
|Send monitoring data to the cluster

ifndef::no_ilm[]
|`manage_ilm`  privilege
|Set up and manage index lifecycle management (ILM) policy
endif::no_ilm[]

ifdef::has_ml_jobs[]
|`manage_ml` privilege
|Set up machine learning job configurations
endif::has_ml_jobs[]

|`manage` privilege on +{beat_default_index_prefix}-*+ indices
|Set up aliases used by ILM
 
ifdef::has_ml_jobs[]
|`read` privilege on +{beat_default_index_prefix}-*+ indices
|Read {beatname_uc} indices in order to set up machine learning jobs
endif::has_ml_jobs[]

|`kibana_user` role
|Load dependencies, such as example dashboards, if available, into {kib}

|`ingest_admin` role
|Set up index templates and, if available, ingest pipelines

ifdef::apm-server[]
|`ingest_admin` role
|Set up ingest pipelines
endif::apm-server[]

ifdef::has_central_config[]
|`beats_admin` role
|Enroll and manage configurations in Beats central management
endif::has_central_config[]
|====

[[privileges-to-publish-monitoring]]
==== Monitoring role

{security} provides the +{beat_default_index_prefix}_system+
{stack-ov}/built-in-users.html[built-in user] and
+{beat_default_index_prefix}_system+ {stack-ov}/built-in-roles.html[built-in
role] for sending monitoring information. You can use the built-in user, or
create a user who has the privileges needed to send monitoring information.
If you use the +{beat_default_index_prefix}_system+ user, make sure you
<<beats-system-user,set the password>>.

[options="header"]
|====
|Privileges and roles | Why needed?

|`monitor` privilege
|Send monitoring info

|`kibana_user` role
|Use {kib}

|`monitoring_user` role
|Use *Stack Monitoring* in {kib} to monitor {beatname_uc}
|====


[[privileges-to-publish-events]]
==== Writer role

Users who publish events to {es} need to create and read from {beatname_uc}
indices. To minimize the privileges required by the writer role, use the
<<privileges-to-setup-beats,setup role>> to load dependencies. Then, in the
configuration file used by the writer role, turn off setup options. For
example:

ifndef::no_ilm[]
[source,yaml]
----
setup.template.enabled: false
setup.ilm.check_exists: false
setup.ilm.overwrite: false <1>
----
<1> Omit `ilm.check_exists` and `ilm.overwrite` if ILM is disabled.
endif::no_ilm[]

ifdef::no_ilm[]
[source,yaml]
----
setup.template.enabled: false
----
endif::no_ilm[]

With setup options turned off, the writer role requires:

[options="header"]
|====
|Privileges and roles | Why needed?

ifndef::apm-server[]
|`monitor` privilege
|Send monitoring info
endif::apm-server[]

ifndef::no_ilm[]
|`read_ilm` privilege
|Read the ILM policy when connecting to clusters that support ILM
endif::no_ilm[]

ifeval::["{beatname_lc}"=="filebeat"]
|`manage_pipeline` privilege
|Load ingest pipelines used by modules
endif::[]

ifndef::no_ilm[]
|`view_index_metadata` privilege on +{beat_default_index_prefix}-*+ indices
|Check for alias when connecting to clusters that support ILM
endif::no_ilm[]

|`index` privilege on +{beat_default_index_prefix}-*+ indices
|Index events into {es}

|`create_index` privilege on +{beat_default_index_prefix}-*+ indices
|Create daily indices when connecting to clusters that do not support ILM {es}
|====

// TODO: Find out if beats_admin is really required to read configs from central config. If so,
// need to add:
//ifdef::has_central_config[]
//|`beats_admin` role |Read configurations from Beats central management
//endif::has_central_config[]

[[kibana-user-privileges]]
==== Reader role

{kib} users typically need to view dashboards and visualizations that contain
{beatname_uc} data. These users might also need to create and edit dashboards
and visualizations.
ifdef::has_central_config[]
If you're using Beats central management, they need to create and manage
configurations.
endif::has_central_config[]

[options="header"]
|====
|Privileges and roles | Why needed?

ifndef::apm-server[]
|`read` privilege on +{beat_default_index_prefix}-*+ indices
|Read data indexed by {beatname_uc} 

|`kibana_user` role
|Use {kib}. To grant read-only access to dashboards, assign the
`kibana_dashboard_only_user` role instead.
endif::apm-server[]

ifdef::apm-server[]
|`kibana_user` and `apm_user` roles
|Use the APM UI
endif::apm-server[]

ifdef::has_central_config[]
|`beats_admin` role
|Create and manage configurations in Beats central management
endif::[]
|====


[[learn-more-security]]
==== Learn more about users and roles

Want to learn more about creating users and roles? See
{stack-ov}/elasticsearch-security.html[Securing the {stack}]. Also see:

* {stack-ov}/security-privileges.html[Security privileges] for a description of
available privileges
* {stack-ov}/built-in-roles.html[Built-in roles] for a description of roles that
you can assign to users
