[role="xpack"]
[[feature-roles]]
=== Grant users access to secured resources


You can use role-based access control to grant users access to secured
resources. The roles that you set up depend on your organization's security
requirements and the minimum privileges required to use specific features. 

{beatname_uc} users typically perform these main roles: they do the initial
setup, publish monitoring information, and publish events. If they're using
{kib}, they view and sometimes create visualizations that access {beatname_uc}
indices.

{security} provides pre-built roles that grant _some_ of the privileges needed
by {beatname_uc} users. When possible, use the built-in roles to minimize the
affect of future changes on your security strategy.

For privileges not granted by existing roles, create new roles. At a minimum,
create a role for setting up {beatname_uc}, a role for publishing events, and a
role for reading {beatname_uc} indices. Assign these new roles, along with the
pre-built roles, to grant the full set of privileges required by {beatname_uc}
users.

The following sections describe the privileges and roles required to perform
specific job roles. 

[[privileges-to-setup-beats]]
==== Privileges needed for initial setup

Users who set up {beatname_uc} typically need to load mappings, dashboards, and
other objects used to index data into {es} and visualize it in {kib}. The
privileges required depend on the setup tasks users need to perform.

NOTE: These instructions assume that you are using the default name for
{beatname_uc} indices. If you are using a custom name, modify the privileges to
match your index naming pattern.

[options="header"]
|====
|Task | Required privileges and roles

.3+|Set up index templates
|`manage_index_templates` and `monitor` on cluster
|`manage_ilm` on cluster (if cluster supports index lifecycle management)
|`manage` on +{beat_default_index_prefix}-*+ indices (if cluster supports index lifecycle management)

ifndef::no_dashboards[]
|Set up example dashboards
|`kibana_user` role
endif::no_dashboards[]

ifdef::has_ml_jobs[]
.3+|Set up machine learning job configurations 
|`manage_ml` and `monitor` on cluster
|`read` on +{beat_default_index_prefix}-*+ indices
|`kibana_user` role
endif::has_ml_jobs[]

ifeval::["{beatname_lc}"=="filebeat"]
.2+|Set up ingest pipelines
|`monitor` on cluster
|`ingest_admin` role
endif::[]

.2+|Set up index lifecycle policies
|`manage_ilm`, `manage_index_templates`, and `monitor` on cluster
|`manage` on +{beat_default_index_prefix}-*+ indices

ifdef::has_central_config[]
|Enroll and manage configurations in Beats central management
|`beats_admin` and `kibana_user` roles
endif::has_central_config[]
|====

[[privileges-to-publish-monitoring]]
==== Privileges needed to publish and view monitoring information

{security} provides built-in users and roles for monitoring. The privileges and
roles needed depend on the method used to collect monitoring data.

===== Internal collection

For <<monitoring-internal-collection,internal collection>>, {security}
provides the +{beat_default_index_prefix}_system+
{stack-ov}/built-in-users.html[built-in user] and
+{beat_default_index_prefix}_system+ {stack-ov}/built-in-roles.html[built-in
role] for sending monitoring information. You can use the built-in user, or
create a user who has the privileges needed to send monitoring information.
If you use the +{beat_default_index_prefix}_system+ user, make sure you
<<beats-system-user,set the password>>.

[options="header"]
|====
|Task | Required privileges and roles

|Send monitoring info
|`monitor` on cluster

|Use *Stack Monitoring* in {kib} to monitor {beatname_uc}
|`monitoring_user` and `kibana_user` roles
|====

ifndef::serverless[]
===== {metricbeat} collection

For <<monitoring-metricbeat-collection,{metricbeat} collection>>, {security}
provides the `remote_monitoring_user` {stack-ov}/built-in-users.html[built-in
user], and the `remote_monitoring_collector` and `remote_monitoring_agent`
{stack-ov}/built-in-roles.html[built-in roles] for collecting and sending
monitoring information. You can use the built-in user, or
create a user who has the privileges needed to collect and send monitoring
information.

If you use the `remote_monitoring_user` user, make sure you
<<beats-system-user,set the password>>.

If you don't use the `remote_monitoring_user` user:

. Create a user on the production cluster who will collect and send monitoring
information.

. Assign the following roles to the user: 
+
[options="header"]
|====
|Role | Why needed?
|`remote_monitoring_collector`
|Collect monitoring metrics from {beatname_uc}
|`remote_monitoring_agent`
|Send monitoring data to the monitoring cluster
|====

. Assign the following role to users who will view the monitoring data in
{kib}:

[options="header"]
|====
|Role | Why needed?
|`monitoring_user`
|Use *Stack Monitoring* in {kib} to monitor {beatname_uc}
|====
endif::serverless[]

[[privileges-to-publish-events]]
==== Privileges needed to publish events

Users who publish events to {es} need to create and read from {beatname_uc}
indices. The privileges required for this role depend on the tasks users
need to perform:

[options="header"]
|====
|Task | Required privileges and roles

.3+|Send data to a secured cluster without index lifecycle management
|`monitor` on cluster
ifeval::["{beatname_lc}"=="filebeat"]
(and `manage_pipeline` if {beatname_uc} modules are used)
endif::[]
|`create_index` and `index` on +{beat_default_index_prefix}-*+ indices
|also requires privileges to <<privileges-to-setup-beats,set up index templates>>
unless you've disabled automatic template loading

.2+|Send data to a secured cluster that supports index lifecycle management
|`manage_index_templates`,`manage_ilm` footnote:[Use `read_ilm` instead of
`manage_ilm` if you pre-loaded the lifecycle policy], and `monitor`
on cluster
ifeval::["{beatname_lc}"=="filebeat"]
(and `manage_pipeline` if {beatname_uc} modules are used)
endif::[]
| `index` and `manage` on +{beat_default_index_prefix}-*+ indices

ifdef::has_central_config[]
.2+|Read configurations from Beats central management
| `monitor` on cluster
|`beats_admin` role
endif::has_central_config[]
|====

// REVIEWERS: Do users need `index` and `manage` on `shrink-beatname-*`, too?
// Are there other privileges that might be required as indices move through the
// lifecycle stages?

[[kibana-user-privileges]]
==== Privileges needed by {kib} users

{kib} users typically need to view dashboards and visualizations that contain
{beatname_uc} data. These users might also need to create and edit dashboards
and visualizations.
ifdef::has_central_config[]
If you're using Beats central management, they need to create and manage
configurations.
endif::has_central_config[]

The privileges required for {kib} users depend on the tasks they need to
perform: 

[options="header"]
|====
|Task | Required privileges and roles

.2+|View {beatname_uc} dashboards
|`read` on +{beat_default_index_prefix}-*+ indices
|`kibana_dashboard_only_user` role

.2+|View and edit {beatname_uc} dashboards
|`read` on +{beat_default_index_prefix}-*+ indices
|`kibana_user` role

ifdef::has_central_config[]
.2+|Create and manage configurations in Beats central management
|`beats_admin` role
|`kibana_user` role
endif::[]
|====

[[learn-more-security]]
==== Learn more about users and roles

Want to learn more about creating users and roles? See
{stack-ov}/elasticsearch-security.html[Securing the {stack}]. Also see:

* {stack-ov}/security-privileges.html[Security privileges] for a description of
available privileges
* {stack-ov}/built-in-roles.html[Built-in roles] for a description of roles that
you can assign to users
