FROM golang:1.21.10 as builder

ENV PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/go/bin:/usr/local/go/bin

ENV CGO_ENABLED=0

RUN go install github.com/go-delve/delve/cmd/dlv@v1.9.0

COPY build/heartbeat-debugger /usr/share/heartbeat/heartbeat-debugger

FROM alpine:3.16

ENV PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/go/bin

WORKDIR /usr/share/heartbeat

COPY --from=builder /go/bin/dlv /go/bin/dlv
COPY --from=builder /usr/share/heartbeat/heartbeat-debugger /usr/share/heartbeat/heartbeat-debugger

ENTRYPOINT ["dlv", "--headless", "--listen=:56268", "--api-version=2", "--log",  "--log-output", "debugger", "exec", "/usr/share/heartbeat/heartbeat-debugger", "--"]
CMD [ "-e" ]
