== Command Line Options

The following command line options are available for Packetbeat. 

[source,shell]
------------------------------------------------------------------------
$ ./packetbeat -h
Usage of ./packetbeat:
  -I string
    	file
  -N	Disable actual publishing for testing
  -O	Read packets one at a time (press Enter)
  -c string
    	Configuration file (default "/etc/packetbeat/packetbeat.yml")
  -cpuprofile string
    	Write cpu profile to file
  -d string
    	Enable certain debug selectors
  -devices
    	Print the list of devices and exit
  -dump string
    	Write all captured packets to this libpcap file
  -e	Output to stdout and disable syslog/file output
  -l int
    	Loop file. 0 - loop forever (default 1)
  -memprofile string
    	Write memory profile to this file
  -t	Read packets as fast as possible, without sleeping
  -test
    	Test configuration and exit.
  -v	Log at INFO level
  -version
    	Print version and exit
  -waitstop int
    	Additional seconds to wait before shutting down
----------------------------------------------------------------------------

=== Packetbeat-Specific Options 

These command line options are specific to Packetbeat. For other options, see {libbeat}/command-line-options.html[Beats Command Line Options].

*-I <file>*::
Pass a `PCAP` file as input to Packetbeat instead of reading packets from the network. 
This option is useful only for testing Packetbeat. Example: `-I ~/pcaps/network_traffic.pcap`.

*-O*::
Read packets one by one by pressing _Enter_ after each. This option is useful only for testing Packetbeat.

*-devices*::
Print the list of devices that are available for sniffing.

*-dump <file>*::
Write all captured packets to a file. This option is useful for troubleshooting Packetbeat.

*-l <n>*::
Read the pcap file n number of times. Use this option in combination with _pcap file input (-I)_. 
For an infinite loop, use _0_. This option is useful only for testing Packetbeat.

*-t*::
Read the packets from the pcap file as fast as possible without sleeping. Use this option 
in combination with _pcap file input (-I)_. This option is useful only for testing Packetbeat.

*-waitstop <n>*::
Wait an additional n seconds before exiting.



