[[command-line-options]]
== Command Line Options

All Beats share some common command line options, but each Beat can also have
its own tailored command line options.

=== Common Options for all Beats

==== -N
Disable publishing of events to the defined output. This option is useful only
for testing the Beat.

==== -c [file]
Pass the location of a configuration file for the Beat.

==== -cpuprofile [output file]
Write CPU profile data to the specified file. This option is useful for
troubleshooting the Beat.

==== -d [selectors]
Enable debugging for the specified selectors. The selectors are a
comma-separated list of components for which to enable debug. Use `-d "*"` to
enable debug for all components, or specifically list the component from which
you want debug. For example, `-d "publish"` displays all the "publish" related
messages.

==== -e
Output the error messages to stdout and disable syslog output.

==== -memprofile [output file]
Write memory profile data to the specified file. This option is useful for
troubleshooting the Beat.

==== -test
Test only the configuration file and exit. This option is useful for
troubleshooting the configuration of a Beat.

==== -v
Enable verbose output showing INFO level messages.

==== -version
Display the Beat version and exit.
