[[command-line-options]]
== Command Line Options


The command line for starting the Beats share couple of common options, but
each Beat can have specific command line options that are detailed in the Beat
documentation.

=== Common Options for all Beats

==== -N
Disable publishing the events to the defined output. This option is useful only for testing the Beat.

==== -c
Pass the configuration file of your Beat.

==== -cpuprofile
Write CPU profile to a given file. This option is useful for troubleshooting
the Beat.

==== -d [selectors]
Enable debugging for the specified selectors. The selectors are a comma-separated
list of components for which to enable debug. Use `*` to enable debug for all
components. For example, `-d publish` displays all the "publish" related messages.

==== -e
Output the error messages to stdout and disable syslog output.

==== -memprofile
Write memory profile to a give file. This option is useful for troubleshooting
the Beat.

==== -test
Test only the configuration file and exit. This option is useful for
troubleshooting the Beat.

==== -v
Enable verbose, showing INFO level messages.

==== -version
Display the Beat version and exit.
