
[[filebeat-configuration-details]]
== Configuration

The configuration file of Filebeat uses http://yaml.org/[YAML] as any other Beat. 
To start with the configuration it is best to have a look at the default configuration. It is described in detail
what each configuration option is for and how it can be used. Remove the items that are not needed for your setup.

The _etc/filebeat.yml_ consists of the following sections:

* {libbeat}/configuration.html#configuration-shipper[Shipper]
* {libbeat}/configuration.html#configuration-output[Output]
* <<configuration-filebeat-options>>
* {libbeat}/configuration.html#configuration-logging[Logging (optional)]
* {libbeat}/configuration.html#configuration-run-options[Run options (optional)]

[[configuration-filebeat-options]]
=== Filebeat

==== Prospectors

Contains a list of prospector items. Each prospector item is described below.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  prospectors: 1024
-------------------------------------------------------------------------------------

Every prospector item starts with a -. Inside are the prospector specific configs defined
and a list of paths is added that should be crawled. The config fields itself are described
in the config below.

[source,yaml]
-------------------------------------------------------------------------------------
############################# Filbeat ######################################
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      # Paths that should be crawled and fetched. Glob based paths.
      # For each file found under this path, a harvester is started.
      paths:
        - /var/log/*.log
      # - c:\programdata\elasticsearch\logs\*

      # Type of the files. Based on this the way the file is read is decided.
      # The different types cannot be mixed in one prospector
      #
      # Possible options are:
      # * log: Reads every line of the log file (default)
      # * stdin: Reads the standard in
      type: log

      # Optional additional fields. These field can be freely picked
      # to add additional information to the crawled log files for filtering
      #fields:
      #  level: debug
      #  review: 1

      # Ignore files which were modified more then the defined timespan in the past
      # Time strings like 2h (2 hours), 5m (5 minutes) can be used.
      #ignore_older:

      # Scan frequency in seconds.
      # How often these files should be checked for changes. In case it is set
      # to 0s, it is done as often as possible. Default: 10s
      #scan_frequency: 10s

      # Defines the buffer size every harvester uses when fetching the file
      #harvester_buffer_size: 16384

      # Always tail on log rotation. Disabled by default
      # Note: This may skip entries
      #tail_on_rotate: false

      # Configure the file encoding for reading file with international characters
      # supported encodings:
      #   plain, utf-8, utf-16be-bom, utf-16be, utf-16le, big5, gb18030, gbk, hzgb2312,
      #   euckr, eucjp, iso2022jp, shiftjis, iso8859-63, iso8859-6i, iso8859-8e,
      #   iso8859-8i
      #encoding: plain
-------------------------------------------------------------------------------------

===== paths

A list of glob based paths that should be crawled and fetched. For each file found under this path, a harvester is
started. Each path is defined one per line.

===== type

It has two options:

    * log:  Reads every line of the log file (default)
    * stdin: Reads the standard in


===== fields

Add optionally couple of fields to be included to the exported fields by the currently configured 
Filebeat instance. These fields can be freely picked to add additional information to the crawled 
log files for filtering.

[source,yaml]
-------------------------------------------------------------------------------------
fields:
    level: debug
    review: 1

-------------------------------------------------------------------------------------

===== ignore_older

If set, ignores the files which were modified more then the defined timespan in the past
Time strings like 2h (2 hours), 5m (5 minutes) can be used.

===== scan_frequency

In seconds, specifies how often these files should be checked for changes. In case it is set
to 0s, it is done as often as possible. Default: 10s


===== harvester_buffer_size

Defines the buffer size every harvester uses when fetching the file. By default is 16384.


===== tail_on_rotate

If true, tail on log rotation. By default, it is disabled. 
Note:: If enabled, it may skip entries.

===== spool_size

Event count spool threshold - forces network flush if exceeded.

-------------------------------------------------------------------------------------
filebeat:
  spool_size: 1024
-------------------------------------------------------------------------------------


===== idle_timeout

Defines how often the spooler is flushed. After idle_timeout the spooler is
Flush even though spool_size is not reached. The value must be given as duration string.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  idle_timeout: 5s
-------------------------------------------------------------------------------------



===== registry_file

Name of the registry file. Per default it is put in the current working
directory. In case the working directory is changed after when running
filebeat again, indexing starts from the beginning again.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  registry_file: .filebeat
-------------------------------------------------------------------------------------


===== config_dir

Full Path to directory with additional prospector configuration files. Each file must end with .yml
These config files must have the full filbeat config hierarchy inside, but only
the prospector part is processed. All global options like spool_size are ignored.
The config_dir MUST point to a different directory then where the main filebeat config file is in.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  config_dir: path/to/configs
-------------------------------------------------------------------------------------

===== encoding

Configures the file encoding for reading file with international characters. The 
supported encodings are:

    * plain, utf-8, utf-16be-bom, utf-16be, utf-16le, big5, gb18030, gbk, hzgb2312,
    * euckr, eucjp, iso2022jp, shiftjis, iso8859-63, iso8859-6i, iso8859-8e,
    * iso8859-8i

