
[[filebeat-configuration-details]]
== Configuration

Filebeat uses for most configuration a predefined default value. The most basic filebeat configuration
looks as following. Please note that this excludes the libbeat configuration part.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  prospectors:
    -
      paths:
        - /var/log/*.log
-------------------------------------------------------------------------------------

The above defines one prospector which is harvesting the path `/var/log/*.log`. Filebeat will
harvest all files in the directory `/var/log/` which end with `.log`. All patterns supported
by https://golang.org/pkg/path/filepath/#Glob[Golang Glob] can be used here.

Every config file can contain multiple prospectors and multiple paths per prospector
as shown below.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  prospectors:
    -
      paths:
        - /var/log/system.log
        - /var/log/wifi.log
    -
      paths:
        - /var/log/apache/*
-------------------------------------------------------------------------------------

The config file above will start to prospectors. The first prospector will have two harvesters,
one harvesting the system.log file, the other wifi.log. The second prospector will start a harvester
for each file in the apache directory.

=== Config Options

All existing config options are listed and described in the default config file under `etc/filebeat.yml`. Below is a list
of all supported configuration options. Part of the configuration are also the libbeat related parts which can be found
{libbeat}/configuration.html[here].

The start with the configuration it is best to have a look at the default configuration. It is described in detail
what each config is for and how it can be used. Remove the items that are needed for your setup.


==== Prospectors
Contains a list of prospector items. Each prospector item is described below

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  prospectors: 1024
-------------------------------------------------------------------------------------

==== Prospector
Every prospector item stats with a -. Inside are the prospector specific configs defined
and a list of paths is added that should be crawled. The config fields itself are described
in the config below.

[source,yaml]
-------------------------------------------------------------------------------------
############################# Filbeat ######################################
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      # Paths that should be crawled and fetched. Glob based paths.
      # For each file found under this path, a harvester is started.
      paths:
        - /var/log/*.log
      # - c:\programdata\elasticsearch\logs\*

      # Type of the files. Based on this the way the file is read is decided.
      # The different types cannot be mixed in one prospector
      #
      # Possible options are:
      # * log: Reads every line of the log file (default)
      # * stdin: Reads the standard in
      type: log

      # Optional additional fields. These field can be freely picked
      # to add additional information to the crawled log files for filtering
      #fields:
      #  level: debug
      #  review: 1

      # Ignore files which were modified more then the defined timespan in the past
      # Time strings like 2h (2 hours), 5m (5 minutes) can be used.
      #ignore_older:

      # Scan frequency in seconds.
      # How often these files should be checked for changes. In case it is set
      # to 0s, it is done as often as possible. Default: 10s
      #scan_frequency: 10s

      # Defines the buffer size every harvester uses when fetching the file
      #harvester_buffer_size: 16384

      # Always tail on log rotation. Disabled by default
      # Note: This may skip entries
      #tail_on_rotate: false
-------------------------------------------------------------------------------------


==== spool_size

Event count spool threshold - forces network flush if exceeded.

-------------------------------------------------------------------------------------
filebeat:
  spool_size: 1024
-------------------------------------------------------------------------------------


==== idle_timeout

Defines how often the spooler is flushed. After idle_timeout the spooler is
Flush even though spool_size is not reached. The value must be given as duration string.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  idle_timeout: 5s
-------------------------------------------------------------------------------------



==== registry_file

Name of the registry file. Per default it is put in the current working
directory. In case the working directory is changed after when running
filebeat again, indexing starts from the beginning again.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  registry_file: .filebeat
-------------------------------------------------------------------------------------


==== config_dir

Full Path to directory with additional prospector configuration files. Each file must end with .yml
These config files must have the full filbeat config hierarchy inside, but only
the prospector part is processed. All global options like spool_size are ignored.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  config_dir: path/to/configs
-------------------------------------------------------------------------------------

