
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported fields

This document describes the fields that are exported by the
Packetbeat shipper for each transaction. They are grouped in the
following categories:

* <<exported-fields-system>>
* <<exported-fields-env>>
* <<exported-fields-proc>>
* <<exported-fields-filesystem>>

[[exported-fields-system]]
=== System wide statistics fields

Contains system wide statistics. Details that you can get by running the *top* command on Unix systems.



=== load fields

System load average. The load average is the average number  of jobs in the run queue.



==== load1

type: float

Load average over 1 minute. 


==== load5

type: float

Load average over 5 minutes.


==== load15

type: float

Load average over 15 minutes. 


=== cpu fields

CPU specific statistics


==== user

type: int

CPU time spent in user space 


==== user_p

type: float

CPU time spent in user space, in percentage


==== nice

type: int

CPU time spent on low priority processes


==== system

type: int

CPU time spent in kernel space


==== system_p

type: float

CPU time spent in kernel space, in percentage


==== idle

type: int

CPU time spent idle


==== iowait

type: int

CPU time spent in wait (on disk)


==== irq

type: int

CPU time spent servicing/handling hardware interrupts


==== softirq

type: int

CPU time spent servicing/handling software interrupts

==== steal

type: int

CPU time in involuntary wait by virtual cpu while hypervisor is servicing another processor CPU time stolen from a virtual machine. Available only on Unix.

=== mem fields

Memory specific statistics


==== total

type: int

Total memory


==== used

type: int

Used memory


==== free

type: int

Available memory


==== used_p

type: float

Used memory, in percentage


==== actual_used

type: int

Actual used memory. Available only on Unix.


==== actual_free

type: int

Actual available memory. Available only on Unix.


=== swap fields

Memory specific statistics


==== total

type: int

Total swap memory


==== used

type: int

Used swap memory


==== free

type: int

Available swap memory


==== used_p

type: float

Used swap memory, in percentage


==== actual_used

type: int

Actual used swap memory. Available only on Unix.


==== actual_free

type: int

Actual available swap memory. Available only on Unix.


[[exported-fields-env]]
=== Common fields fields

Contains common fields available in all event types.



==== timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Set to "system" to specify that are system wide statistics.


==== count

type: int

required: True

For how many transactions is this event representative. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== shipper

type: string

Name of the shipper sending the statistics


[[exported-fields-proc]]
=== Per process statistics fields

Contains per process statistics. Details that you can get by running the *top* command  or by *ps" command on Unix systems.



==== proc.name

type: string

Process name.


==== proc.state

type: string

Process state. Example: "running"


==== proc.pid

type: int

Process pid.


==== proc.ppid

type: int

Process parent pid.


=== proc.cpu fields

CPU specific statistics per process.


==== user

type: int

CPU time spent in user space by the process.


==== user_p

type: float

CPU time spent in user space by the process, in percentage.


==== system

type: int

CPU time spent in kernel space by the process.


==== total

type: int

Total CPU time spent by the process.


==== start_time

type: string

Time when the process was started. Example: "17:45".


=== proc.mem fields

Memory specific statistics per process.


==== size

type: int

Virtual memory the process has in total.


==== rss

type: int

Resident Set Size. Memory occupied by the process in main memory(RAM).


==== rss_p

type: float

Memory occupied by the process in main memory(RAM), in percentage.


==== share

type: int

Shared memory the process uses.


[[exported-fields-filesystem]]
=== File system statistics fields

Contains file system related statistics.



=== fs fields

The fields from this group define information about the disk usage. It contains  details that you can easily get by using the command *df* on Unix systems.



==== avail

type: int

Available disk space in bytes.


==== device_name

type: string

Disk name. Example: /dev/disk1


==== mount_point

type: string

Mounting point. Example: /


==== files

type: int

Total file nodes in the file system. 


==== free_files

type: int

Free file nodes in the file system.


==== total

type: int

Total disk space in bytes.


==== used

type: int

Used disk space in bytes.


==== used_p

type: float

Used disk space in percentage


