
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by Filebeat. They are
grouped in the following categories:

* <<exported-fields-env>>
* <<exported-fields-log>>

[[exported-fields-env]]
=== Common Fields

Contains common fields available in all event types.



==== beat.name

Name of the Beat sending the log messages. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


==== beat.version

The version of the Beat.


==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the log line was read. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Name of the log event. Set to the prospectors document_type configuration option.


==== input_type

required: True

Prospector input type event was generated from. Set to prospectors type configuration option.


[[exported-fields-log]]
=== Log File Content Fields

Contains log file lines.



==== source

type: string

required: True

File the line was read from.


==== offset

type: int

required: False

File offset the reported line starts at.


==== line

type: int

required: True

The line number the published line starts at.


==== message

type: string

required: True

Content of line read from log file given by source.


==== fields Fields

Contains user configurable fields.


==== fileinfo Fields

Operating System specific file information use to identify the source file. For example on linux an inode might be reported.


