[[filebeat-getting-started]]
== Getting Started

To get started with your own Filebeat setup, install and configure these related products:

 * Elasticsearch for storage and indexing the data. {libbeat}/getting-started.html#elasticsearch-installation[More details]
 * Kibana for the UI. {libbeat}/getting-started.html#kibana-installation[More details]
 * Logstash for inserting data into Elasticsearch. {libbeat}/getting-started.html#logstash-installation[More details]

After you have installed these products, you can start <<filebeat-installation>>.

[[filebeat-installation]]
=== Installing Filebeat

To download and install Filebeat, run the following commands. Use the commands that 
work with your system (deb for Debian/Ubuntu, rpm for Redhat/Centos/Fedora, mac for OS X).

deb:

["source","sh",subs="attributes,callouts"]
------------------------------------------------
curl -L -O https://download.elastic.co/beats/filebeat/filebeat_{version}_amd64.deb
sudo dpkg -i filebeat_{version}_amd64.deb
------------------------------------------------



rpm:

["source","sh",subs="attributes,callouts"]
------------------------------------------------
curl -L -O https://download.elastic.co/beats/filebeat/filebeat-{version}-x86_64.rpm
sudo rpm -vi filebeat-{version}-x86_64.rpm
------------------------------------------------


mac:

["source","sh",subs="attributes,callouts"]
------------------------------------------------
curl -L -O https://download.elastic.co/beats/filebeat/filebeat-{version}-darwin.tgz
tar xzvf filebeat-{version}-darwin.tgz
------------------------------------------------

NOTE: We also provide 32-bit images that you can get from our
https://www.elastic.co/downloads/beats/filebeat[download page].

Before starting filebeat, you should look at the configuration options in the configuration 
file, for example `/etc/filebeat/filebeat.yml`. For more information about these options, 
see <<filebeat-configuration-details,Configuration>>.

[[filebeat-configuration]]
=== Configuring Filebeat

Before configuring Filebeat, you need to set up Logstash to work with the Beat. For detailed 
steps, see {libbeat}/getting-started.html#logstash-setup[Setting Up Logstash].

To configure Filebeat, you edit the _filebeat.yml_ file. Here is a sample of 
the _filebeat.yml_ file:

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      # Paths that should be crawled and fetched. Glob based paths.
      # For each file found under this path, a harvester is started.
      paths:
        - /var/log/*.log
      # - c:\programdata\elasticsearch\logs\*

      # Type of the files. Based on this the way the file is read is decided.
      # The different types cannot be mixed in one prospector
      #
      # Possible options are:
      # * log: Reads every line of the log file (default)
      # * stdin: Reads the standard in
      type: log
-------------------------------------------------------------------------------------

Filebeat uses predefined default values for most configuration options. For the most basic 
Filebeat configuration, you can define a single prospector with a single path. For example:  

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  prospectors:
    -
      paths:
        - /var/log/*.log
-------------------------------------------------------------------------------------

The prospector in this example harvests all files in the path `/var/log/*.log`, which means 
that Filebeat will harvest all files in the directory `/var/log/` that end with `.log`. All patterns supported
by https://golang.org/pkg/path/filepath/#Glob[Golang Glob] are also supported here.

To fetch all files from a predefined level of subdirectories, the following pattern can be used:
`/var/log/*/*.log`. This fetches all `.log` files from the subfolders of `/var/log`. It does not
fetch log files from the `/var/log` folder itself. Currently it is not possible to recursively
fetch all files in all subdirectories of a directory.

A config file can contain multiple prospectors and multiple paths per prospector
as shown in the following example.

NOTE: Make sure a file is not defined more than once across all prospectors because this can lead
to unexpected behaviour.

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  prospectors:
    -
      paths:
        - /var/log/system.log
        - /var/log/wifi.log
    -
      paths:
        - /var/log/apache/*
-------------------------------------------------------------------------------------

The config file in the example starts two prospectors. The first prospector has two harvesters,
one harvesting the `system.log` file, and the other harvesting `wifi.log`. The second prospector 
starts a harvester for each file in the apache directory.


See <<filebeat-configuration-details,Configuration>> for more details about each configuration option.

[[filebeat-template]]
=== Loading the Index Template in Elasticsearch

Before starting Filebeat, you need to load the
http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html[index
template], which lets Elasticsearch know which fields should be analyzed
in which way.

The recommended template file is installed by the Filebeat packages. Load it with the
following command:

deb or rpm:

[source,shell]
----------------------------------------------------------------------
curl -XPUT 'http://localhost:9200/_template/filebeat?pretty' -d@/etc/filebeat/filebeat.template.json
----------------------------------------------------------------------

mac:

["source","sh",subs="attributes,callouts"]
----------------------------------------------------------------------
cd filebeat-{version}-darwin
curl -XPUT 'http://localhost:9200/_template/filebeat?pretty' -d@filebeat.template.json
----------------------------------------------------------------------

where `localhost:9200` is the IP and port where Elasticsearch is listening.


=== Running Filebeat

Run the binary by issuing the following command:

deb:

[source,shell]
----------------------------------------------------------------------
sudo /etc/init.d/filebeat start
----------------------------------------------------------------------

rpm:

[source,shell]
----------------------------------------------------------------------
sudo /etc/init.d/filebeat start
----------------------------------------------------------------------

mac:

[source,shell]
----------------------------------------------------------------------
sudo ./filebeat -e -c filebeat.yml -d "publish"
----------------------------------------------------------------------

Filebeat is now ready to send log files to your defined output.

Enjoy!
