[[packetbeat-getting-started]]
== Getting started

The best way to understand the value of an network packet analytics system like
Packetbeat is to try it on your own traffic. 

Follow the steps to get started with your own Packetbeat setup:

 * Install the Packetbeat shippers on your servers so that they capture the network traffic. <<packetbeat-installation>>
 * Install Elasticsearch for storage and indexing the data. TODO[More details]
 * Install Kibana for the UI. TODO[More details]
 * Install optionally Logstash. TODO[More details]
 * Load sample Kibana dashboards to get it started. <<sample-dashboards>>


[[packetbeat-installation]]
=== Packetbeat installation

Now that you have Elasticsearch running, I'm sure you are eager to put some
data in it. For this, install the Packetbeat shippers on your application
servers:

deb:

[source,shell]
----------------------------------------------------------------------
sudo apt-get install libpcap0.8
curl -L -O https://download.elasticsearch.org/beats/packetbeat/packetbeat_$PB_VERSION_amd64.deb
sudo dpkg -i packetbeat_$PB_VERSION_amd64.deb
----------------------------------------------------------------------

rpm:

[source,shell]
----------------------------------------------------------------------
sudo yum install libpcap
curl -L -O https://download.elasticsearch.org/beats/packetbeat/packetbeat-$PB_VERSION-x86_64.rpm
sudo rpm -vi packetbeat-$PB_VERSION-x86_64.rpm
----------------------------------------------------------------------


mac:

[source,shell]
----------------------------------------------------------------------
curl -L -O https://download.elasticsearch.org/beats/packetbeat/packetbeat-$PB_VERSION-darwin.tgz
tar xzvf packetbeat-$PB_VERSION-darwin.tgz
----------------------------------------------------------------------

NOTE: We also provide 32bits images. You can get them from our
https://www.elastic.co/downloads/beats/packetbeat[download page].

Before starting the shipper, edit the configuration file. For rpm and deb the
configuration file is `/etc/packetbeat/packetbeat.yml`. For mac the
configuration file is found in the archive you just downloaded.

First, select the network interface from which to capture the traffic. On
Linux, Packetbeat supports capturing all messages sent or received by the
server on which it is installed. For this, use `any` as the device:

[source,yaml]
----------------------------------------------------------------------
interfaces:
  # Select on which network interfaces to sniff. You can use the "any"
  # keyword to sniff on all connected interfaces.
  device: any
----------------------------------------------------------------------

Note that on OS X, capturing from the `any` device doesn't work. You would
typically use either `lo0` or `en0` depending on which traffic you want to
capture.

In the next section, configure the ports on which Packetbeat can find each
protocol. If you use any non-standard ports, add them here. Otherwise, the
default values should do just fine.

[source,yaml]
----------------------------------------------------------------------
protocols:
  # Configure which protocols to monitor and on which ports are they
  # running. You can disable a given protocol by commenting out its
  # configuration.
  http:
    ports: [80, 8080, 8081, 5000, 8002]

  memcache:
    ports: [11211]

  mysql:
    ports: [3306]

  redis:
    ports: [6379]

  pgsql:
    ports: [5432]

  thrift:
    ports: [9090]
----------------------------------------------------------------------

Set the IP address and port where the shipper can find the Elasticsearch
installation:

[source,yaml]
----------------------------------------------------------------------
output:

  elasticsearch:
    # Uncomment out this option if you want to output to Elasticsearch. The
    # default is false.
    enabled: true

    # Set the host and port where to find Elasticsearch.
    host: 192.168.1.42
    port: 9200

    # Comment this option if you don't want to store the topology in
    # Elasticsearch. The default is false.
    save_topology: true
----------------------------------------------------------------------

Before starting the shipper, you need to load the `packetbeat.template.json` template
as described TODO[here].

More details about getting started with your Beat are TODO[here].


Enjoy!
