== Logtash-Forwarder to Filebeat Migration

The following guide should help you to upgrade from the
https://github.com/elastic/logstash-forwarder[Logstash-Forwarder] to Filebeat.

Filebeat brings the following major changes:

* The config file was restructured and converted from JSON to YAML.
* The registry file which stores the state of the currently read files was
  changed.
* Command line options were removed and moved to the configuration file.
* Configuration options for outputs are inherited from libbeat. Details can be found https://www.elastic.co/guide/en/beats/libbeat/current/index.html[here]
* A new input plugin must be used in Logstash.


=== Migration strategy

==== Logstash side

Filebeat requires a new input plugin in Logstash, called
https://github.com/logstash-plugins/logstash-input-beats[logstash-input-beats].
In both 1.5.x and 2.x versions of Logstash, this plugin can be loaded in
parallel with the
https://github.com/logstash-plugins/logstash-input-lumberjack[logstash-input-lumberjack]
plugin used by the Logstash-Forwarder.

If you have a large number of servers that you want to migrate from the
Forwarder to Filebeat, we recommend keeping the Lumberjack plugin and load the
Beats plugin on the same Logstash instances but set it to a different port. After you migrated
all the machines to Filebeat, you can remove the Lumberjack plugin.

====  Registry file

The registry file stores the state and location from which Filbeat was reading
last. Under Logstash-Forwarder it was called `.logstash-fowarder`. For Filebeat
it was renamed to `.filebeat` or `/usr/lib/filebeat/registry` if you install
from packages or `C:\ProgramData\filebeat\registry` if you run as a Windows
service.

For enhancement reasons, especially for Windows,
the structure of the registry file has been changed. This makes a migration
complex and leads to potential errors.

Instead of a migration of the registry file we recommend to start Filebeat on
the same host and send the log files to a different index.  This will start
indexing from scratch. In case it is preferred to start at the end of all
files, the option `tail_on_rotate` can be set to true.

The above will allow to keep the old Logstash-Forwarder running and it can be
slowly migrated over to Filebeat.

=== Migrate your configuration

Logstash-Forwarder uses JSON + comments for its configuration file while
Filebeat uses YAML for consistency with the other Beats. Like the
Logstash-Forwarder, Filebeat also accepts reading multiple configuration files
from a `conf.d` directory with similar restrictions. For Filebeat the additional
config files must be in a different directory then the main config file. The 
conversion can be done in most cases 1 to 1 on a per file basis.

We recommend to first read the <<filebeat-configuration-details>> section which
documents the Filebeat options.


NOTE:: Logstash-Forwarder has the option of auto-completing environment variables in
the configuration file. This option currently doesn't exist in Filebeat.

==== The "files" section

The "files" section from the Logstash-Forwarder configuration is transformed in
a "prospectors" section in the Filebeat config. For example, assuming you start
with this configuration:

[source,json]
-------------------------------------------------------------------------------------
  # The list of files configurations
  "files": [
    # An array of hashes. Each hash tells what paths to watch and
    # what fields to annotate on events from those paths.
    {
      "paths": [
        "/var/log/messages",
        "/var/log/*.log"
      ],

      # A dictionary of fields to annotate on each event.
      "fields": { "type": "syslog" }
    }, {
      # A path of "-" means stdin.
      "paths": [ "-" ],
      "fields": { "type": "stdin" }
    }, {
      "paths": [
        "/var/log/apache/httpd-*.log"
      ],
      "fields": { "type": "apache" }
    }
  ]
-------------------------------------------------------------------------------------

The equivalent "prospectors" section would look like this:

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      paths:
        - /var/log/messages
        - /var/log/*.log
    -
      paths:
        - "-"
      type: stdin <1>
      fields:
        type: stdin
    -
      paths:
        - /var/log/apache/httpd-*.log
      fields:
        type: apache
-------------------------------------------------------------------------------------

<1> The explicit type field was introduced to separate between normal files and
    stdin. In the future, more types might be supported.

As you can see, apart from the new optional `type` field which was introduced,
the rest of the options can be migrated mechanically. In case no type is defined
the default is to to `log`.

The Filebeat configuration allows some of the options that are global in the
Logstash-Forwarder to be configured per prospector. See
<<filebeat-configuration-details>>.

==== The "network" section

Like Logstash-Forwarder, Filebeat can communicate directly with Logstash.
In addition, Filebeat can also insert log entries directly
into Elasticsearch. This leads to a little bit more complex "output"
as can be seen in the example below. The Logstash part of it,
however, can be easily translated from the equivalent Logstash-Forwarder
configuration.

Assuming you start from the following "network" section:

[source,json]
-------------------------------------------------------------------------------------
  # The network section covers network configuration :)
  "network": {
    # A list of downstream servers listening for our messages.
    # logstash-forwarder will pick one at random and only switch if
    # the selected one appears to be dead or unresponsive
    "servers": [ "localhost:5043" ],

    # The path to your client ssl certificate (optional)
    "ssl certificate": "./logstash-forwarder.crt",
    # The path to your client ssl key (optional)
    "ssl key": "./logstash-forwarder.key",

    # The path to your trusted ssl CA file. This is used
    # to authenticate your downstream server.
    "ssl ca": "./logstash-forwarder.crt",

    # Network timeout in seconds. This is most important for
    # logstash-forwarder determining whether to stop waiting for an
    # acknowledgement from the downstream server. If an timeout is reached,
    # logstash-forwarder will assume the connection or server is bad and
    # will connect to a server chosen at random from the servers list.
    "timeout": 15
  }
-------------------------------------------------------------------------------------

The equivalent in Filebeat would look like this:


[source,yaml]
-------------------------------------------------------------------------------------
output:
  logstash:
    enabled: true

    # The list of downstream Logstash servers. <1>
    hosts:
      - localhost:5043

    tls: <2>
      # The path to your client ssl certificate
      certificate: ./logstash-forwarder.crt
      # The path to your client ssl key
      certificate-ssl: ./logstash-forwarder.key

      # The path to your trusted ssl CA file. This is used
      # to authenticate your downstream server.
      certificate-authorities:
        - ./logstash-forwarder.crt

      # Network timeout in seconds.
      timeout: 15
-------------------------------------------------------------------------------------

<1> When multiple hosts are defined, the default behavior in Filebeat is to
    pick a random one for new connections, similar to the Logstash-Forwarder
    behavior. Filebeat can optionally also to load balancing, see
    {libbeat}/configuration.html#loadbalance[the configuration option].
<2> Note that if the `tls` section is missing the encryption is disabled. It is
   automatically enabled when adding the `tls` section. More TLS options are
   documented {libbeat}/configuration.html#configuration-output-tls[here].


[[changed-configuration-options]]
==== Changed configuration file options

With the refactoring of the configuration file, some options were also removed or renamed.
Below is a list with the changed entries:

[cols="2*", options="header"]
|===
|Config Option
|Action

|`deadTime`
|`deadTime` was renamed to `ignoreOlder`. In case a file is not changed for `ignoreOlder`, the file handler will be closed. If the file is changed again after ignoreOlder has passed, it is be reopened.

|`netTimeout`
|`netTimeout` was removed as it is replaced by the Timeout option in libbeat.

|`log-to-syslog` and `syslog`
|Both options were removed as logging is part of the libbeat config.

|===


==== A complete example

Let's see a simple but complete example of a logstash-forwarder configuration
and its equivalent for Filebeat.

Logstash-Forwarder configuration:

[source,json]
-------------------------------------------------------------------------------------
{
  "files": [
    {
      "paths": [
        "/var/log/*.log"
      ],
      "fields": { "type": "syslog" }
    }
  ],
  "network": {
    "servers": [ "localhost:5043" ],
  }
}
-------------------------------------------------------------------------------------

Filebeat configuration:

[source,yaml]
-------------------------------------------------------------------------------------
filebeat:
  prospectors:
    -
      paths:
        - /var/log/*.log
      fields:
        type: syslog
output:
  elasticsearch:
    enabled: true
    hosts: ["http://localhost:5043"]
-------------------------------------------------------------------------------------

=== Command Line Options

Most command line options from logstash-forwarder have been removed and
migrated to config file options. The only mandatory option for filebeat is `-c`
with the path to the config file to be loaded. In case you used command line
options with Logstash-Forwarder, make sure to add your options to the
configuration file. For the naming changes, check the list below.

The general concept for the config options is that all options are available as
part of the config file and only some special options are also available as
command line option.

==== Renamed options

The renamed command line options are listed below. Also check
<<changed-configuration-options>> for configuration file options that were
either completely removed or moved to libbeat.

[cols="3*", options="header"]
|===
|Command Line Option
|Config File Option
|Description

|`-config`
|`-c`
|The config options was split up in two part. The base and required config is linked with -c. Additional config files can be linked as part of the config file. Note: Additional config files must be in a different directory than the main config file.

|`-config`
|`config_dir`
|Path to directory with additional configuration files

|`-idle-timeout`
|`idle_timeout`
|`idle_timeout` was moved to the config file and removed as flag.

|`-spool-size`
|`spool_size`
|`spool_size` was moved to the config file and removed as flag.

|`-harvester-buff-size`
|`harvester_buffer_size`
|`harvester_buffer_size` was moved to the config file and removed as flag. It can now be configured specific for each harvester.

|`-tail`
|`tail_on_rotate`
|`tail_on_rotate` was moved to the config file and removed as flag. It can now be configured specific for each harvester.

|`-cpuProfileFile`
|
|`cpuProfileFile` option was removed. The profiling options of libbeat can be used instead. For more details on profiling see https://github.com/elastic/libbeat/issues/122

|`-quiet`
|
|The `quiet` option was removed. Libbeat is used for logging and the libbeat configuration options have to be used.


|===


=== Other changes

The following is a list of implementation changes that we don't expect to
affect your experience migrating from Logstash-Forwarder but that you should be
aware of. Please post a GitHub issues if you notice any regression from
Logstash-Forwarder.

==== Packaging

The packaging process for Filebeat uses the Beats infrastructure, so some
things like the init scripts are different from those that the
Logstash-Forwarder provided. Please post GitHub issues if you hit any issues
with the new packages.

One notable change is the name of the registry file depending on the package
type:

 * `.filebeat` for `.tar.gz` and `.tgz` archives
 * `/usr/lib/filebeat/registry` for DEB and RPM pacakges
 * `c:\ProgramData\filebeat\registry` for the Windows zip file

==== Publisher improvements

Behind the scenes, Filebeat uses a sightly improved protocol for communicating
with Logstash.

==== TLS is off by default

If you follow the section on migrating the configuration you will have TLS
enabled, but you must be aware that if the tls section is missing from the
configuration Filebeat uses an unencrypted connection to talk to Logstash.

==== Logging

Filebeat uses libbeat logging and can also log to rotating files instead of syslog.
