== Overview

Topbeat together with Elasticsearch and Kibana offers a complete open source 
server monitoring solution. Topbeat is a lightweight shipper that installed on
your servers, reads periodically system wide and per process CPU and memory statistics 
and indexes them in Elasticsearch.

Topbeat collects the following metrics:

 * System load: in the last second, in the last 5 seconds and in the last 15 seconds
 * System wide CPU usage: user (and percentage), system, idle, IOWait, etc
 * System wide Memory usage: total, used (and percentage), free, etc
 * System wide Swap usage: total, used (and percentage), free, etc
 * Process name
 * Process parent pid
 * Process state
 * Process pid
 * Process CPU usage: user (and percentage), system, total, start time
 * Process Memory usage: virtual memory, resident memory (and percentage), shared memory


The shippers can insert the collected metrics directly into Elasticsearch
or via a central queue created with Redis and Logstash.

In the near future, a direct integration between Topbeat and Logstash will
be implemented, so the Redis instance will no longer be needed.
