[[setup-repositories]]
== Repositories

We have repositories available for APT and YUM based distributions. Note that we
provide binary packages, but no source packages.

We use the PGP key https://pgp.mit.edu/pks/lookup?op=vindex&search=0xD27D666CD88E42B4[D88E42B4],
Elasticsearch Signing Key, with fingerprint

    4609 5ACC 8548 582C 1A26 99A9 D27D 666C D88E 42B4

to sign all our packages. It is available from https://pgp.mit.edu.

[float]
=== APT

Download and install the Public Signing Key:

[source,sh]
--------------------------------------------------
curl https://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
--------------------------------------------------

Save the repository definition to  +/etc/apt/sources.list.d/beats.list+:

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://packages.elastic.co/beats/apt stable main" |  sudo tee -a /etc/apt/sources.list.d/beats.list

--------------------------------------------------

[WARNING]
==================================================
Use the `echo` method described above to add the Beats repository.  Do not use `add-apt-repository`
as it will add a `deb-src` entry as well, but we do not provide a source package.
If you have added the `deb-src` entry, you will see an error like
the following:

    Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

Just delete the `deb-src` entry from the `/etc/apt/sources.list` file and the installation should work as expected.
==================================================

Run apt-get update and the repository is ready for use. For example, you can
install Filebeat with:

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install filebeat
--------------------------------------------------

To configure the beat to automatically start during boot, run:

[source,sh]
--------------------------------------------------
sudo update-rc.d filebeat defaults 95 10
--------------------------------------------------

[float]
=== YUM

Download and install the public signing key:

[source,sh]
--------------------------------------------------
sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
--------------------------------------------------

Add the following in your `/etc/yum.repos.d/` directory
in a file with a `.repo` suffix, for example `beats.repo`

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[beats]
name=Elastic Beats Repository
baseurl=https://packages.elastic.co/beats/yum/el/$basearch
enabled=1
gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
gpgcheck=1
--------------------------------------------------

And your repository is ready for use. For example, you can install Filebeat with:

[source,sh]
--------------------------------------------------
sudo yum install filebeat
--------------------------------------------------

To configure the beat to automatically start during boot, run:

[source,sh]
--------------------------------------------------
sudo chkconfig --add filebeat
--------------------------------------------------
