
== Windows support

This page walks you through the steps required for running Packetbeat on
Windows. It assumes your Windows system has Powershell installed.

Start by downloading and installing WinPcap from this
http://www.winpcap.org/install/default.htm[page]. WinPcap is a library that uses
a driver to enable packet capturing.

Then download the Packetbeat Windows zip file from the
https://www.elastic.co/downloads/beats/packetbeat[downloads page] and unzip
it on your computer. The location where it is extracted is not important, but
remember that you shouldn't delete this repository after the installation is
finished. The exe file and the configuration file will continue to live there.

Then start an Administrator Powershell session (right click the Powershell icon
and select *Run as Administrator*), and navigate to where you uncompressed the
zip file.

Use the following command to list the available network interfaces:

[source,shell]
----------------------------------------------------------------------
PS > .\packetbeat.exe -devices

0: \Device\NPF_{113535AD-934A-452E-8D5F-3004797DE286} (Intel(R) PRO/1000 MT Desktop Adapter)
----------------------------------------------------------------------

In this example, there is only one network card installed on the system. If
there are more of them, remember the index of the device you want to use for
capturing the traffic.

Then edit the `packetbeat.yml` file and modify the `device` line to point to the
index that you just found:

[source,yml]
----------------------------------------------------------------------
interfaces:
  device: 0
----------------------------------------------------------------------

You might want to change other settings in the `packetbeat.yml` file, see the
 <<configuration>> documentation for details.

Then you can install Packetbeat as a Windows service by using the following
Powershell script:

[source,shell]
----------------------------------------------------------------------
PS > .\install-service-packetbeat.ps1
----------------------------------------------------------------------

And then start it with:

[source,shell]
----------------------------------------------------------------------
PS > Start-Service packetbeat
----------------------------------------------------------------------

By default the log files can be found under `C:\ProgramData\packetbeat\Logs`.
