// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package kafka

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "kafka", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy8WEFz2ywQvftX7OTkHKLv9PXgQ2fapNPxtNN20vbswWJlM0agAnbqf98BWbaEJIRkJzrFRHrvsQtvFx5gh8cF7Ei2IzMAwwzHBdx9sb/vZgAUdapYYZgUC3g/AwBw/4Nc0j3HGYDeSmVWqRQZ2ywgI1zbUYUcicYFbCxsxpBTvXCfP4AgOV4o7WOOhX1VyX1xGungbcLUodZK7lCdh7vwejHL56NDgEcp9D5HBZ/tp7AUmVQ5sR/AlhwQ1ogCFBIKmZI5zE+fbYmgnIlNA9JsEdIKz0m5T2ov+HOpz4fRxnA1Hy49iuCUatNidNbJQyhVqHUn2Q6PL1L5QuL4CD2gMkwjPVO0cmZkwdLE/t3KW5s6QPvL4jjMPg5USqoklbTN5EV0kMZBgYVK2mwFUYbZb5NG/sYy/ahggNEgi5vdqoMrHL8G2W/B/uwRGAWZuRVbXNiFGyhjOKyj3INvIweIoO5XSZq0xFX7zneA0b7QB9S0t+oJ7emWR/XrKTUVClNikC7gXfL/pG14SzeDYUfriwCEnA1C7hYxVWi4XDXSy9/teDDgeuN0+BxjLD7Cdf2sPoWJ3IYZxRW98GrWG5Rw3sTxVS1aw8UthwIhs0yjmVRYz4u+xAAmjKxZ0xqZ2LiNFFaQoyGd/Ab/+sKa/HttZH6RYYGAEkNAG1XfqZ20nfUvfvLtte46t7Oa/y6BqJfHoKSUMxTdueg2w6CeD1qzjUB6gnWZsBnBAwqjS3PrW4NXGFakVzyWopZPMC8Dp9EYK69UmzB6P+xbW6n9cE0V0oDqJcwxX/vlfBIrEwaVINyrHCeC+q4N2cXowt0FMr5oBzxjyjo9EMbJmuMJV1ddzoYdUNQ6qpFrVOALBpbH9ML6zQFXrue3ZL7MWtg4fR1B3x3wsKAJZWhCPi+1x3rxW7RCobIYIRhax4tqtFclR0JbbWuE0kEdXx2wbfXnZWvc6iUvIhQWnKV+7byFiucSuVtGf+qEPop0NSRrLSVH4i+3SGVLQZnNtQaWVQEApoGJlO8p0upAxMSDFVO9YtDWF5gvfz5HzUSvBjL8KpOwwj3eXom97QvcIP+fzh1L2SZkaNKtLc6xphK4Ygjqu+p8Z1qXEf3SvBsWuF3739YVeyA4HdvHXHNdfxr22DwtU67CrtfUe1Sc/QsAAP//o1ZfwA=="
}
