// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/x-pack/osquerybeat/ext/osquery-extension/pkg/jumplists/parsers/application_id_generate.go - DO NOT EDIT.

//go:build windows

package tools

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/elastic/beats/v7/x-pack/osquerybeat/ext/osquery-extension/pkg/logger"
)

// isHexString is a compiled regex to check for valid hex strings.
var isHexString = regexp.MustCompile(`^[0-9a-fA-F]+$`)

// downloadPage performs a GET request with a custom User-Agent.
// It's the Go equivalent of the first part of download_webpage_as_soup.
func downloadPage(url string, log *logger.Logger) (*http.Response, error) {
	client := &http.Client{}
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}

	// Set the User-Agent, just like in the Python script
	req.Header.Set("User-Agent", "Mozilla/5.0")

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}

	// Check for non-2xx status codes (like Python's raise_for_status())
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		resp.Body.Close() // Make sure to close the body on error
		return nil, fmt.Errorf("bad status: %s", resp.Status)
	}

	return resp, nil
}

// scrapeJumpListAppIDs replicates the second Python scraping function.
func scrapeJumpListAppIDs(log *logger.Logger) (map[string]string, error) {
	appIDs := make(map[string]string)
	valueRegex := regexp.MustCompile(`.*"(.*)"`)
	url := "https://raw.githubusercontent.com/EricZimmerman/JumpList/refs/heads/master/JumpList/Resources/AppIDs.txt"

	resp, err := downloadPage(url, log)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	// This is a plain text file, so we read the body directly.
	// No need for an HTML parser here.
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	bodyString := string(bodyBytes)

	// for line in ... .splitlines()
	lines := strings.Split(bodyString, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue // Skip empty lines
		}

		// app_id_raw, app_name_raw = line.strip().split('|')
		parts := strings.Split(line, "|")
		if len(parts) != 2 {
			log.Infof("invalid line in response: %s", line)
			continue
		}
		appIDRaw := parts[0]
		appNameRaw := parts[1]

		appIDMatches := valueRegex.FindStringSubmatch(appIDRaw)
		appNameMatches := valueRegex.FindStringSubmatch(appNameRaw)

		if len(appIDMatches) < 2 || len(appNameMatches) < 2 {
			log.Infof("failed to parse quoted values from response: %s", line)
			continue
		}

		appID := appIDMatches[1]
		appName := appNameMatches[1]

		if isHexString.MatchString(appID) {
			appIDs[strings.ToLower(appID)] = appName
		} else {
			log.Infof("Invalid app id in response: %s", line)
		}
	}

	return appIDs, nil
}

func main() {
	log := logger.New(os.Stdout, true)
	appIDs, err := scrapeJumpListAppIDs(log)
	if err != nil {
		log.Fatalf("failed to scrape jump list app ids: %v", err)
	}

	// Build the Go map literal string
	// Using strings.Builder is more efficient than repeated string concatenation
	var sb strings.Builder
	sb.WriteString("// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one\n")
	sb.WriteString("// or more contributor license agreements. Licensed under the Elastic License;\n")
	sb.WriteString("// you may not use this file except in compliance with the Elastic License.\n\n")
	sb.WriteString("// Code generated by beats/x-pack/osquerybeat/ext/osquery-extension/pkg/jumplists/parsers/application_id_generate.go - DO NOT EDIT.\n\n")
	sb.WriteString("//go:build windows\n\n")
	sb.WriteString("package jumplists\n\n")

	sb.WriteString("// jumpListAppIds is a lookup table for known windows AppIDs.\n")
	sb.WriteString("// Source: https://github.com/EricZimmerman/JumpList/blob/master/JumpList/Resources/AppIDs.txt\n")
	sb.WriteString("var jumpListAppIds = map[string]string{\n")

	// Sort keys for consistent output
	keys := make([]string, 0, len(appIDs))
	for k := range appIDs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, appID := range keys {
		appName := appIDs[appID]
		sb.WriteString(fmt.Sprintf("\t%-20s: %q,\n", fmt.Sprintf("\"%s\"", appID), appName))
	}
	sb.WriteString("}\n")

	outputFile := "../parsers/lnk/application_id_generated.go"

	err = os.WriteFile(outputFile, []byte(sb.String()), 0644)
	if err != nil {
		log.Fatalf("failed to write output file: %v", err)
	}

	log.Infof("Generated %s successfully", outputFile)
}
