// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("heartbeat", "Module", asset.BeatFieldsPri, AssetModule); err != nil {
		panic(err)
	}
}

// AssetModule returns asset data.
// This is the base64 encoded gzipped contents of ./build/fields/module.yml.
func AssetModule() string {
	return "eJzsWEFv6zYMvudXEO+yy5rbu/SwS1dgxd7eijb3QLbomIgs+Ul0Uw/78YMUO5EtJ03aFMuA+ZTYFknx+/iJ9A2ssb0FZ/K1+zoDYGKFt/Dl+c+735+/Qm3Na/tlBiDR5ZZqJqNvZwAFoZLO/wK4AS0qjGz4i9sab2FlTVN3d2IL8Et3EyB2BBaVYJQD8zD6t3domXf3pjwe8eqvxbdnUKJFC9Y0WgJbqoGpQjeP3hs7jwPIjdaY8+DZoUDeCCYERBWCxR8NWZTABtCxyBS5EkTvi4yGFxJ92vxLWtaG9DgKgEw4lGA0iBdBSmQKYyNsBqmfj5ZPbTveeuOSR/3OldGriYeDzf/aWBHCIA0V5dY4zI2WbjabdYxk5SI6eqxQ57YN67ewnUjLraFpYA4AEjFjQMj5G4TM0TIVlAvGpTa8fBGK5DLDwlhMmCoF4yGi3gurCB0HOoJg2JSUl8BlDOFPLnboQFiE4HF+YmCiYLRnxfXNO7pYVP96/ZZCS1eKNX5aBRekffn6UHfOosJUFoVsowLVyBtj14nhfX6vplC7Oi2Z66hQf1ssHqEymticWqCdhenEH0h4cHNecTZWJWxjfOXTyPaM9oVy9Fag8fBlbb/NGJGqUUzLFJMd5cVmlgKxxnZjrJwdRGHMtEWJ4I5EBIuSHJADAdroG6GFav/qMwVcCvYPG4dFo8Z8MhbEamVxFXB3Fy/bAN3H6jboyVCmDoeShPN3wvkdyTPkDaKGgqxjyFpGMEVPth+N174MSa9gY4kZNQgtE2sWXW20w+7V2pocXQdQF7mHaO90JAeJwUQeBnKQvP7dMN4CFXtnHmxtGLx5H1JmZAvGgtGqBQG1xYJefwYuaUos/KWbKkML0uDWUtEo5du12qJDzeEMYMNCbc8GjSgxzUwHkwmBhDU+kqtRtClnPdWWPtKL883EIMXnRkiQ0HLnP2SrZ1ba6oU0/s8E+EQm+JLHZScD72LCUR441AGRbTdV1QoZB8ozoRipUhxqKK6xgZhy1jN8WaKQg+b0A2kedmW9xscJdywsj1HwyZ8Q9+0x4GszOiUKa6oerYH6ezz2yB2Z0f7ryOVGM2qeJ04POjwDsyAUbAlfUPbzhve2Cw262ObTwQVBurh6x+F1p/yOOMBWaCe2uMGz55eDDXGZmPMrSBOTULC4e4xndMGMVc1zuNdyuxrCzLbX88SaJAl5ifl6cGBc89lwLazu5hnKq3ieebj74/HEOaZbCefMMQ+PUPtcnzbCdOLjkvabNONqIJdHGvDvW5SoAL85uM9L89QZDvoXkeXdLf/OMjxFgvmEtefDsOs/sed/n668CTfnMdq+/s76tpSfjbh30Uv7e74x1camWJyFfz/KektdyV4C8tHHmbuPDnkX/rg6qdrxB9aR9p4xlT08gpDSonPXomWfMDUfyeh+ivH/HGO9zx6+kmOvcMP0Xkui/gkAAP//xWXgnQ=="
}
