/*
Package defaults imports all Monitor packages so that they
register with the global monitor registry. This package can be imported in the
main package to automatically register all of the standard supported Heartbeat
modules.
*/
package defaults

import (
	// This list is automatically generated by `make imports`
	_ "github.com/elastic/beats/heartbeat/monitors/active/http"
	_ "github.com/elastic/beats/heartbeat/monitors/active/icmp"
	_ "github.com/elastic/beats/heartbeat/monitors/active/tcp"
)
