version: "2"
run:
  build-tags:
    - integration
# Find the whole list here https://golangci-lint.run/usage/linters/
linters:
  default: none
  enable:
    - asciicheck # simple linter to check that your code does not contain non-ASCII identifiers
    - bodyclose # checks whether HTTP response body is closed successfully
    - depguard # checks if package imports are in a list of acceptable packages
    - durationcheck # check for two durations multiplied together
    - errcheck # checking for unchecked errors in go programs
    - errorlint # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
    - forbidigo # forbids identifiers matched by reg exps
    - gomodguard_v2 # check for blocked dependencies
    - gosec # inspects source code for security problems
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - importas # enforces consistent import aliases
    - ineffassign # detects when assignments to existing variables are not used
    - misspell # finds commonly misspelled English words in comments
    - nakedret # finds naked returns in functions greater than a specified function length
    - nilerr # finds the code that returns nil even if it checks that the error is not nil.
    - noctx # noctx finds sending http request without context.Context
    - nolintlint # reports ill-formed or insufficient nolint directives
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - testifylint # checks usage of github.com/stretchr/testify
    - unconvert # Remove unnecessary type conversions
    - unused # checks Go code for unused constants, variables, functions and types
    - wastedassign # wastedassign finds wasted assignment statements.

  # all available settings of specific linters
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: math/rand$
              desc: superseded by math/rand/v2
            - pkg: golang.org/x/exp/maps$
              desc: superseded by maps
            - pkg: golang.org/x/exp/slices$
              desc: superseded by slices
    errcheck:
      # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
      check-type-assertions: true
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      check-blank: false
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - (github.com/elastic/elastic-agent-libs/mapstr.M).Delete # Only returns ErrKeyNotFound, can safely be ignored.
        - (github.com/elastic/elastic-agent-libs/mapstr.M).Put # Can only fail on type conversions, usually safe to ignore.
        - github.com/elastic/elastic-agent-libs/logp.TestingSetup
        - github.com/elastic/elastic-agent-libs/logp.DevelopmentSetup
    errorlint:
      # Check whether fmt.Errorf uses the %w verb for formatting errors. See the readme for caveats
      errorf: true
      # Check for plain type assertions and type switches
      asserts: true
      # Check for plain error comparisons
      comparison: true
    forbidigo:
      # Forbid the following identifiers
      forbid:
        - pattern: fmt.Print.* # too much log noise
        - pattern: ^logp\.NewLogger$
          msg: "accept a *logp.Logger as a parameter instead of creating one with logp.NewLogger"
        - pattern: ^logp\.L$
          msg: "accept a *logp.Logger as a parameter instead of using the global logp.L()"
    gomodguard_v2:
     blocked:
        - module: github.com/pkg/errors
          recommendations:
            - errors
            - fmt
          reason: This package is deprecated, use `fmt.Errorf` with `%w` instead
        - module: go.uber.org/multierr
          recommendations:
            - errors
          reason: This package is deprecated, use `errors.Join` instead
        - module: gotest.tools/v3
          recommendations:
            - github.com/stretchr/testify
          reason: Use one assertion library consistently across the codebase
        - module: github.com/google/uuid
          recommendations:
            - github.com/gofrs/uuid/v5
          reason: Use one uuid library consistently across the codebase
        - module: github.com/elastic/beats/v7
          reason: There must be no Beats dependency
    gosec:
      excludes:
        - G306 # Expect WriteFile permissions to be 0600 or less
        - G404 # Use of weak random number generator
        - G401 # Detect the usage of DES, RC4, MD5 or SHA1: Used in non-crypto contexts.
        - G501 # Import blocklist: crypto/md5: Used in non-crypto contexts.
        - G505 # Import blocklist: crypto/sha1: Used in non-crypto contexts.
    nolintlint:
      # Enable to require an explanation of nonzero length after each nolint directive. Default is false.
      require-explanation: true
      # Enable to require nolint directives to mention the specific linter being suppressed. Default is false.
      require-specific: false
      # Enable to ensure that nolint directives are all used. Default is true.
      allow-unused: false
    staticcheck:
      checks:
        - -ST1005
        - all
    testifylint:
      disable:
        - go-require # Disabled: too many false positives, can be used to exit a goroutine
        - require-error # Disabled: using assert for error checks lets the test continue, maximizing context on failure
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - forbidigo
        path: (.*magefile.go|.*dev-tools/mage/.*)
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 50
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 3
formatters:
  enable:
    - goimports # Goimports does everything that gofmt does. Additionally it checks unused imports
  settings:
    goimports:
      local-prefixes:
        - github.com/elastic
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
