// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Package cursor implements cursor-based incremental data fetching for the
// SQL metricbeat module. It enables the sql/query MetricSet to track the last
// fetched row and retrieve only new data on subsequent collection cycles.
//
// # Problem
//
// Without cursor support, the SQL Input module executes the same query every
// collection cycle, fetching all rows repeatedly. This causes duplicate data
// ingestion, unnecessary database load, and wasted resources.
//
// # Solution
//
// The cursor package provides state management that persists the value of a
// designated cursor column (for example, an auto-increment ID or timestamp) across
// collection cycles. On each run, the persisted value is substituted into a
// parameterized query via the :cursor placeholder, so only rows beyond the
// last checkpoint are fetched.
//
// # Architecture
//
// The package is organized into the following components:
//
//   - [Config]: User-facing configuration (column, type, default) with validation
//   - [Value]: Type-safe cursor value with serialization and comparison support
//   - [Store]: Persistence layer backed by libbeat/statestore with memlog backend
//   - [Manager]: Lifecycle coordinator that ties configuration, storage, and query execution together
//   - Placeholder translation: Converts the :cursor placeholder to driver-specific syntax ($1, ?, :cursor_val, @p1)
//
// # Cursor Types
//
// Five cursor types are supported:
//
//   - "integer": For auto-increment IDs, sequence numbers. Stored as int64.
//   - "timestamp": For TIMESTAMP/DATETIME columns. Stored as Unix nanoseconds (int64) in UTC.
//   - "date": For DATE columns. Stored as YYYY-MM-DD string.
//   - "float": For FLOAT/DOUBLE/REAL columns. Stored as float64. Subject to IEEE 754
//     precision limits -- boundary rows may be duplicated or skipped at the 15th+
//     significant digit. Best for columns where slight imprecision is acceptable.
//   - "decimal": For DECIMAL/NUMERIC columns. Uses shopspring/decimal for exact
//     arbitrary-precision arithmetic. No data loss at boundaries. Best for financial
//     data and exact numeric columns.
//
// # Scan Direction
//
// By default, the cursor tracks the maximum value from each batch (ascending scan).
// For descending scans (ORDER BY col DESC with WHERE col < :cursor), set
// cursor.direction to "desc" to track the minimum value instead.
//
// # Database Support
//
// The placeholder translation layer supports:
//
//   - PostgreSQL / CockroachDB: $1
//   - MySQL: ?
//   - Oracle (godror): :cursor_val
//   - MSSQL (sqlserver): @p1
//
// The cursor value is always passed as a parameterized query argument,
// making it safe against SQL injection.
//
// # State Persistence
//
// Cursor state is persisted using libbeat/statestore with a memlog backend
// (the same proven backend used by Filebeat). State is stored at
// {data.path}/sql-cursor/ and survives process restarts and crashes.
//
// Each cursor gets a unique state key generated by [GenerateStateKey], which
// hashes the following components via xxhash (no secrets appear in the key):
//
//   - Input type ("sql") — fixed namespace, never changes
//   - Full database URI/DSN — not normalized; includes host, port, database
//     name, credentials, and connection parameters
//   - Full query string — not normalized; exact byte match, so whitespace
//     or capitalization changes produce a different key
//   - Cursor column name
//   - Cursor direction ("asc" or "desc")
//
// Any change to these components produces a different key, which resets the
// cursor to its configured default value. Examples of changes that reset:
//
//   - Changing the database password or username in the DSN
//   - Adding connection parameters (e.g., ?sslmode=require)
//   - Reformatting the SQL query (whitespace, capitalization)
//   - Renaming the cursor column
//   - Switching direction from "asc" to "desc"
//
// Examples of changes that do NOT reset the cursor:
//
//   - Changing cursor.default (only used on first run)
//   - Changing period or timeout (runtime settings, not part of the key)
//
// The full URI is used (rather than just host:port) so that two databases
// on the same server produce distinct state keys. This is essential for
// multi-host configurations (hosts: [host1, host2]) where each host gets
// its own MetricSet, and for cross-database isolation (prod_db vs test_db).
//
// Known tradeoff: including the full DSN means that password rotation,
// username changes, or adding connection parameters will reset the cursor.
// This is a safe failure mode — it causes re-ingestion (duplicates), never
// data loss. There is currently no built-in way to avoid cursor resets on
// credential changes. Because the state key is a hash of the full DSN,
// simply backing up and restoring the state directory does not help — the
// new DSN produces a different hash, so the restored state is never looked up.
//
// # Error Philosophy
//
// The cursor follows an "at-least-once" delivery model:
//
//   - Events are emitted BEFORE the cursor is updated
//   - If cursor persistence fails, the next cycle re-fetches the same rows
//   - Duplicates are preferred over data loss
//   - NULL cursor values, missing columns, and parse errors are logged and skipped per-row
//   - "Column not found" and "all values NULL" are reported with distinct error messages
//   - The cursor value is only updated if at least one valid value was found
//   - Float cursors reject NaN and Inf values at both config validation and DB result parsing
//
// # Concurrency and Query Timeout
//
// The [Manager] is safe for concurrent use. All cursor reads and writes are
// protected by a mutex. The MetricSet uses a separate fetchMutex with TryLock
// to prevent overlapping collection cycles when a query takes longer than the
// configured period.
//
// Each cursor-based fetch is wrapped with context.WithTimeout using the
// module's configured timeout (which defaults to period). This prevents hung
// queries (e.g., table locks, network partitions) from blocking the goroutine
// indefinitely and causing all subsequent collection cycles to be skipped
// via fetchMutex.TryLock(). When a query exceeds the timeout, the context is
// cancelled, the database driver aborts the query, and the cursor remains
// unchanged (no data loss).
//
// The timeout is applied only to the cursor path. The non-cursor path does
// not enforce a timeout for backward compatibility with existing users whose
// queries may legitimately take longer than their configured period.
//
// # Resource Cleanup
//
// The MetricSet implements mb.Closer. When the module stops, [Manager.Close]
// is called, which closes the [Store], releasing file handles held by the
// memlog backend and flushing any pending writes. Close is idempotent.
//
// # Usage
//
// Users configure the cursor in metricbeat.yml:
//
//	metricbeat.modules:
//	  - module: sql
//	    metricsets: ["query"]
//	    period: 60s
//	    hosts: ["postgres://user:pass@localhost:5432/mydb"]
//	    driver: postgres
//	    sql_query: >
//	      SELECT id, data FROM events
//	      WHERE id > :cursor ORDER BY id ASC LIMIT 1000
//	    sql_response_format: table
//	    cursor:
//	      enabled: true
//	      column: id
//	      type: integer
//	      default: "0"
//
// The :cursor placeholder is replaced at startup with the driver-specific
// syntax. At each collection cycle:
//
//  1. The current cursor value is loaded (from store or default).
//  2. The query executes with the cursor value as a parameterized argument.
//  3. All returned rows are emitted as events.
//  4. The maximum cursor column value from the batch is persisted.
//
// # Boundary Behavior: > vs >=
//
// When the cursor column has unique values (auto-increment IDs), use the >
// operator: WHERE id > :cursor. When the cursor column may have duplicates
// (timestamps, scores), use >= to avoid missing late-arriving rows that share
// the same value as the cursor. The >= operator causes the boundary row to be
// re-fetched (a duplicate), but prevents data loss. Configure Elasticsearch
// document IDs or deduplication pipelines when using >=.
//
// # Driver-specific Notes
//
//   - MySQL: include parseTime=true in the DSN for timestamp cursors so the
//     driver correctly handles time.Time query parameters.
//   - Oracle: set session timezone to UTC for timestamp cursors via the godror
//     alterSession DSN parameter, or timestamp comparisons may silently fail.
//   - Decimal: ToDriverArg returns string. Most drivers implicitly cast to
//     DECIMAL, but if not, the user can add CAST(:cursor AS DECIMAL) in SQL.
//
// # Limitations
//
//   - Single query only (not sql_queries with multiple queries)
//   - Single cursor column (no composite cursors)
//   - String, UUID, and ULID columns are not supported as cursor types (Phase 3)
//   - :cursor in SQL string literals will be incorrectly replaced
//   - ORDER BY must match the cursor column and the configured direction
//   - The cursor column must be included in the SELECT clause
//   - All matching rows are loaded into memory; use LIMIT (500-5000 recommended)
//   - Float cursors have IEEE 754 precision limits; use decimal for exact comparisons
//   - Float cursors reject NaN and Inf (both as default values and from DB results)
//
// # Testing
//
// Unit tests cover configuration validation, type parsing (including edge
// cases like overflow, NULL, timezone conversion), placeholder translation,
// state persistence, and the full manager lifecycle.
//
// Integration tests verify end-to-end cursor operation against PostgreSQL,
// MySQL, Oracle, and MSSQL with all five cursor types (integer, timestamp,
// date, float, decimal), both scan directions, compound WHERE clauses,
// NULL handling, state persistence, and state isolation.
package cursor
