// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package openmetrics

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "openmetrics", asset.ModuleFieldsPri, AssetOpenmetrics); err != nil {
		panic(err)
	}
}

// AssetOpenmetrics returns asset data.
// This is the base64 encoded zlib format compressed contents of module/openmetrics.
func AssetOpenmetrics() string {
	return "eJzElD1u3DAQhXud4kEpDBhrH4BFihTpAh8gCGyuNFpNzD8MZ7HR7QP9wdQqLrIJEpDViPPeN4+EHvBKg0FMFDypcJMrQFkdGdw9vVXvKkDIkc1kcCS1FdBSboSTcgwGHysAKDrgY3t2VAGZVDmcssHXuldN9QF1zq7+VgEdk2uzmZofEKyna5hx6ZDI4CTxnJbKNQvwS55xvxR6L2hiUMshY6mgk+hBoU2Rg2ZobxVWCF10Ll44nDZDdVG81cdFvKQf1wc8SUsCzmCfoqgNip6EDnD2SC7jws7BW216dCxZD9CeIJRn0zaej1NmQJlIT24d/C2OVxouUdqi/k4A4/4kTF2ZEGI3WX+ZBvtsPbth5zsa/ZnvLL8VWtXPgfWvqG+EVvU58Mf7omGkMIjH79SUxnPh+Qb/zXOfJ51tdzTLqd/GuXoQm6/P3qbE4bQcre/rW6l3uPSDfHJW/l18q2N+n+U/3ejqv7/a7U/o5wBYN4d0"
}
