// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package mongodb

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("packetbeat", "mongodb", asset.ModuleFieldsPri, AssetMongodb); err != nil {
		panic(err)
	}
}

// AssetMongodb returns asset data.
// This is the base64 encoded zlib format compressed contents of protos/mongodb.
func AssetMongodb() string {
	return "eJysVk1v4zYQvftXDBY+7AK2gV59KNBtG2CL7iZIUhQ9NZQ4soglOcrMKI7/fUHqy6ocwEUKnUTNvHnz+DjUFr7jaQ+B4oFssQJQpx738OFrWvml+LACsCglu0YdxT38uAIA6L5+3kqDpatcCfiCUaFy6K3s4LFGwf4NgmMmhtKToD/ldK3HrxVxfu0R4egYoWFSKslnJKjdoUYGjy/o+7SM8jHl4qsJjccNPD23yKcnMNHCE6NQyyU+fQLTNP4ESmOFTFXACBzR+90Kesx9Bt1CNAHPFUmPnhrcw4GpbfqV85zzPEzNjqsXxRueL9Wsc8bnFkWhNgKM0npFCy6CiR3oBrR20pGFkqIaFyUhzEBzKAQUMQcERm05ooXilCJBkF+QdwvWVev9z+Q9lmmXv5mA17WQtiflQjkmZ/12V0WBy/xTM6VRjCYVB+pksUZNYQQzHhyd1n3sDGIzK9SKiwcwYEnh4+7TaK5ZgTm3m3MPDfFj7YooG+pflQuTd+PtriqiXWEuCB3bUCA/0sN3Nzhp8peneLhO9wfUTroOL2lmqWxDdrYSUHAKWxA1rEmSiink+Mqx6Bib7JVWO7ulwNS5oMJ2Vu5YY+y9lIKmlGGz8tl7u9v7nPqOfpOD+vOBFoJ5daENbzVfTL5/i9J9//2dlC4RGCVt/GlZftiRG6ZwXZ0/a2QcUMuWJXvUpRmRBpuTEXNZLW/LdWV+gt8ebr+NfYDWRlMJRul0Xe7yoEKuAkeXj0IeS0ARgRgCMQJ6zMpswHiftDrWrqwhtKIQjJZ1PqZmLD3D77bTxdK3Fu3cryCoczZ3JOIKP9UcMmGdSW5gTWyRi9MG1rWLuoE1vjbeuLjJ53wt0TRSky615GyZmzR95QHTgSd+h7TeBadyfhOOvfUje4iXeY+PNV7kMl0Jl8VHU9aT+v3kTTZJi6a/VjI1qan19vwYzafsMBBdVDwgw4vxLcIPS8nkP8r0eSlT/4OBZwbMdumgh2E05RC0jTWaBbDoUXFJq4v430j1BTunNsgVcUC7vGVcTF/6Oy72IKfUQocgGxDEDPlHXoDbBjnHy0ggv07jfPh3+Gpia/yy1W5efLHXNfs4TRhnMWoSnkcTDAa9vfv7/te73/9KP2dOunNcdLw7J2SNjkamzJGvNWoKI7hb/TMAaSQ/9Q=="
}
