---
name: bump-osquery

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
          cache: false

      - uses: elastic/oblt-actions/updatecli/run-and-notify@v1
        with:
          command: --experimental apply --config .github/workflows/updatecli.d/bump-osquery.yml --values .github/workflows/updatecli.d/values.d/scm.yml
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: "#ingest-notifications"
          slack-message: ":traffic_cone: updatecli failed for `${{ github.repository }}@${{ github.ref_name }}`, please look what's going on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>"
          slack-send-when: "failure"
          version-file: .updatecli-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
