name: golangci-lint
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  pull_request:
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.go-version'
      - '.golangci.yml'
      - '.github/workflows/golangci-lint.yml'

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.12.2
          args: --timeout=30m --whole-files
          only-new-issues: true
